### ISSUE TITLE
[BUG] GpuSequence blows up when nulls exist in any of the inputs (start, stop, step).

### ISSUE THREAD

**Issue by firestarman** [rapidsai/cudf#10013]
**Describe the bug**
GpuSequence blows up when nulls exist in any of the inputs (start, stop, step), 
```
Caused by: ai.rapids.cudf.CudfException: cuDF failure at: ../src/lists/sequences.cu:148: steps input column must not have nulls.
  at ai.rapids.cudf.ColumnVector.sequences(Native Method)
  at ai.rapids.cudf.ColumnVector.sequence(ColumnVector.java:533)

```
but Spark just returns nulls. 
```
+---+---+----------------------+
| _1| _2|sequence(_1, _2, NULL)|
+---+---+----------------------+
|  1|  2|                  null|
|  3|  4|                  null|
+---+---+----------------------+

```

**Steps/Code to reproduce bug**
Launch a Spark shell with GPU support, and run
`Seq((1, 2), (3, 4)).toDF.repartition(1).selectExpr("*", "sequence(_1, _2, null)").show`

**Expected behavior**
We should keep align with what Spark does for null cases.

**Comment by firestarman** [comment]
Filed an FEA issue https://github.com/rapidsai/cudf/issues/10012 to cudf for this

**Comment by firestarman** [comment]
Close due to wrong project. Here is the right one https://github.com/NVIDIA/spark-rapids/issues/4499
