### ISSUE TITLE
[QST]Signature mismatch: 7 argument types given, but function takes 5 arguments

### ISSUE THREAD

**Issue by anamariaUIC** [rapidsai/cudf#10021]
**What is your question?**
Hello,

I am running [this code](https://github.com/beckernick/nersc-rapids-workshop/blob/master/cudf/02-Intro_to_cuDF_UDFs.ipynb)
using rapids-21.12.

Executing this portion of the code throws error:

>>> outdf = df.apply_chunks(haversine_distance_kernel,
                        incols=['lat1', 'lon1', 'lat2', 'lon2'],
                        outcols=dict(out=np.float64),
                        kwargs=dict(),
                        chunks=16,
                        tpb=8)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anamaria/.conda/envs/rapids-21.12/lib/python3.7/site-packages/cudf/core/dataframe.py", line 4210, in apply_chunks
    tpb=tpb,
  File "/home/anamaria/.conda/envs/rapids-21.12/lib/python3.7/site-packages/cudf/utils/applyutils.py", line 103, in apply_chunks
    return applychunks.run(df, chunks=chunks, tpb=tpb)
  File "/home/anamaria/.conda/envs/rapids-21.12/lib/python3.7/site-packages/cudf/utils/applyutils.py", line 163, in run
    self.launch_kernel(df, bound.args, **launch_params)
  File "/home/anamaria/.conda/envs/rapids-21.12/lib/python3.7/site-packages/cudf/utils/applyutils.py", line 209, in launch_kernel
    self.kernel[blkct, tpb](len(df), chunks, *args)
  File "/software/linux-el7-x86_64/compilers/python-3.7.3/lib/python3.7/site-packages/numba/cuda/compiler.py", line 770, in __call__
    self.stream, self.sharedmem)
  File "/software/linux-el7-x86_64/compilers/python-3.7.3/lib/python3.7/site-packages/numba/cuda/compiler.py", line 861, in call
    kernel = self.compile(argtypes)
  File "/software/linux-el7-x86_64/compilers/python-3.7.3/lib/python3.7/site-packages/numba/cuda/compiler.py", line 932, in compile
    **self.targetoptions)
  File "/software/linux-el7-x86_64/compilers/python-3.7.3/lib/python3.7/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/software/linux-el7-x86_64/compilers/python-3.7.3/lib/python3.7/site-packages/numba/cuda/compiler.py", line 57, in compile_kernel
    cres = compile_cuda(pyfunc, types.void, args, debug=debug, inline=inline)
  File "/software/linux-el7-x86_64/compilers/python-3.7.3/lib/python3.7/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/software/linux-el7-x86_64/compilers/python-3.7.3/lib/python3.7/site-packages/numba/cuda/compiler.py", line 46, in compile_cuda
    locals={})
  File "/software/linux-el7-x86_64/compilers/python-3.7.3/lib/python3.7/site-packages/numba/core/compiler.py", line 627, in compile_extra
    return pipeline.compile_extra(func)
  File "/software/linux-el7-x86_64/compilers/python-3.7.3/lib/python3.7/site-packages/numba/core/compiler.py", line 363, in compile_extra
    return self._compile_bytecode()
  File "/software/linux-el7-x86_64/compilers/python-3.7.3/lib/python3.7/site-packages/numba/core/compiler.py", line 425, in _compile_bytecode
    return self._compile_core()
  File "/software/linux-el7-x86_64/compilers/python-3.7.3/lib/python3.7/site-packages/numba/core/compiler.py", line 405, in _compile_core
    raise e
  File "/software/linux-el7-x86_64/compilers/python-3.7.3/lib/python3.7/site-packages/numba/core/compiler.py", line 396, in _compile_core
    pm.run(self.state)
  File "/software/linux-el7-x86_64/compilers/python-3.7.3/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 341, in run
    raise patched_exception
  File "/software/linux-el7-x86_64/compilers/python-3.7.3/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 332, in run
    self._runPass(idx, pass_inst, state)
  File "/software/linux-el7-x86_64/compilers/python-3.7.3/lib/python3.7/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/software/linux-el7-x86_64/compilers/python-3.7.3/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/software/linux-el7-x86_64/compilers/python-3.7.3/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "/software/linux-el7-x86_64/compilers/python-3.7.3/lib/python3.7/site-packages/numba/core/untyped_passes.py", line 107, in run_pass
    % (len(state['args']), state['nargs']))
TypeError: Failed in nopython mode pipeline (step: fix up args)
Signature mismatch: 7 argument types given, but function takes 5 arguments

Can you please advise on how to resolve this?

Thanks
Ana

**Comment by beckernick** [comment]
The linked code is about 21 months old. Do you get similar errors following the documentation for [apply_rows](https://docs.rapids.ai/api/cudf/nightly/api_docs/api/cudf.DataFrame.apply_rows.html)?

Separately, where appropriate, we recommend using the new `df.apply` interface for UDFs. The [documentation](https://docs.rapids.ai/api/cudf/nightly/api_docs/api/cudf.DataFrame.apply.html?highlight=apply#cudf.DataFrame.apply) contains several examples we hope will be useful.

**Comment by anamariaUIC** [comment]
@beckernick @shwina My issue is not with apply_rows it is with apply_chunks (please see my post above). I'm getting error (above) when I run:

outdf = df.apply_chunks(haversine_distance_kernel,
incols=['lat1', 'lon1', 'lat2', 'lon2'],
outcols=dict(out=np.float64),
kwargs=dict(),
chunks=16,
tpb=8)

How this code should be written for rapids-21.12 so that I don't have that error.

**Comment by beckernick** [comment]
I am unable to reproduce your error with the following code:

```python
(rapids-21.12) nicholasb@rl-dgx-r13-u36-rapids-dgx114:/raid/nicholasb$ ipython
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.0 -- An enhanced Interactive Python. Type '?' for help.
...
from math import cos, sin, asin, sqrt, pi, atan2
​
import time
import cudf
import numpy as np
from numba import cuda
​
np.random.seed(12)
data_length = 1000
​
df = cudf.DataFrame()
df['lat1'] = np.random.normal(10, 1, data_length)
df['lon1'] = np.random.normal(10, 1, data_length)
df['lat2'] = np.random.normal(10, 1, data_length)
df['lon2'] = np.random.normal(10, 1, data_length)
​
​
def haversine_distance_kernel(lat1, lon1, lat2, lon2, out):
    """Haversine distance formula taken from Michael Dunn's StackOverflow post:
    https://stackoverflow.com/questions/4913349/haversine-formula-in-python-bearing-and-distance-between-two-gps-points
    """
    for i, (x_1, y_1, x_2, y_2) in enumerate(zip(lat1, lon1, lat2, lon2)):
        # print('thread_id:', cuda.threadIdx.x, 'bid:', cuda.blockIdx.x,
              # 'array size:', lat1.size, 'block threads:', cuda.blockDim.x)
​
        x_1 = pi/180 * x_1
        y_1 = pi/180 * y_1
        x_2 = pi/180 * x_2
        y_2 = pi/180 * y_2
        
        dlon = y_2 - y_1
        dlat = x_2 - x_1
        a = sin(dlat/2)**2 + cos(x_1) * cos(x_2) * sin(dlon/2)**2
        
        c = 2 * asin(sqrt(a)) 
        r = 6371 # Radius of earth in kilometers
        
        out[i] = c * r
        
df = df.apply_chunks(
    haversine_distance_kernel,
    incols=['lat1', 'lon1', 'lat2', 'lon2'],
    outcols=dict(out=np.float64),
    kwargs=dict(),
    chunks=16,
    tpb=8
)
​
print(df.head(3))
        lat1       lon1       lat2       lon2         out
0  10.472986  11.889149  10.173869   9.557545  257.224127
1   9.318574  11.733839  10.237408  10.941703  134.063596
2  10.242439   9.969706   8.158692   8.084421  310.650417
````
