### ISSUE TITLE
[BUG] `fused_concatenate_kernel` can cause illegal memory access

### ISSUE THREAD

**Issue by abellina** [rapidsai/cudf#10333]
When concatenating via the `fused_concatenate_kernel` we see an issue where its strided loop can overflow, even if the output number of rows is < 2B. Here is a small scala repro case:

```
import ai.rapids.cudf.{ColumnVector, Cuda, Scalar, Table}
val s = Scalar.fromByte(1.toByte)
val tbls = (0 until 5).map { _ => new Table(ColumnVector.fromScalar(s, 250 * 1000 * 1000)) }
Table.concatenate(tbls:_*)
Cuda.DEFAULT_STREAM.sync
```

Will produce:
```
ai.rapids.cudf.CudaException: an illegal memory access was encountered
  at ai.rapids.cudf.Cuda.streamSynchronize(Native Method)
  at ai.rapids.cudf.Cuda$Stream.sync(Cuda.java:111)
  ... 47 elided
```

After adding printfs, the grid size is very large and the stride update: https://github.com/rapidsai/cudf/blob/branch-22.04/cpp/src/copying/concatenate.cu#L200 can cause the `size_type` index to become negative.

It seems the simplest fix is to change `output_index` to be `std::size_t` (https://github.com/rapidsai/cudf/blob/branch-22.04/cpp/src/copying/concatenate.cu#L200). 

Thanks to @nvdbaranec and @jlowe  for debugging this with me.

**Comment by abellina** [comment]
I'll have this up for review today. I added a test that reproduces it and building cuDF with the solution.

**Comment by abellina** [comment]
I put up the PR https://github.com/rapidsai/cudf/pull/10344, to address the `fused_concatenate_kernel` specifically. 

I've seen the same bug in other kernels. I am looking for input on how that should be handled. Does it seem we want 1 PR that handles the issue as a whole? 

For example: 
- `fused_concatenate_string_offset_kernel`, `fused_concatenate_string_chars_kernel`
- `get_json_object_kernel`
