### ISSUE TITLE
[QST] Is it compatible with cuda115?

### ISSUE THREAD

**Issue by jiapei100** [rapidsai/cudf#10391]
How can I install **cudf** via **pip**?
I tried  `pip install cudf`, but failed with the following **ERROR** message:

```console
➜  ~ pip install cudf -U --user
Collecting cudf
  Using cached cudf-0.6.1.post1.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: cudf
  Building wheel for cudf (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      running bdist_wheel
      running build
      ~/.local/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      installing to build/bdist.linux-x86_64/wheel
      running install
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-i24lgimr/cudf_04558c93b982460f9971340486c18a8e/setup.py", line 18, in <module>
          setup(name=pkg,
        File "~/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "~/.local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "~/.local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "~/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "~/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "~/.local/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 335, in run
          self.run_command('install')
        File "~/.local/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "~/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-i24lgimr/cudf_04558c93b982460f9971340486c18a8e/setup.py", line 15, in run
          raise Exception(long_description)
      Exception: Please install cudf via the rapidsai conda channel. See https://rapids.ai/start.html for instructions.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cudf
  Running setup.py clean for cudf
Failed to build cudf
Installing collected packages: cudf
  Running setup.py install for cudf ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for cudf did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      running install
      ~/.local/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-i24lgimr/cudf_04558c93b982460f9971340486c18a8e/setup.py", line 18, in <module>
          setup(name=pkg,
        File "~/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "~/.local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "~/.local/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "~/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "~/.local/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-i24lgimr/cudf_04558c93b982460f9971340486c18a8e/setup.py", line 15, in run
          raise Exception(long_description)
      Exception: Please install cudf via the rapidsai conda channel. See https://rapids.ai/start.html for instructions.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> cudf

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

Since I'm using **cuda115**, I tried `pip install cudf-cuda115', but still failed:
```console
➜  ~ pip install cudf-cuda115 -U --user
ERROR: Could not find a version that satisfies the requirement cudf-cuda115 (from versions: none)
ERROR: No matching distribution found for cudf-cuda115
```

Any suggestions?

Cheers

**Comment by shwina** [comment]
Hi @jiapei100 - as David mentioned, we no longer support `pip`. Please use `conda` instead. The conda package supports CUDA 11.5.

**Comment by beckernick** [comment]
I'm going to close this issue as answered. Please feel free to re-open to continue the discussion.
