### ISSUE TITLE
[BUG] Can't import dask_cudf with latest nightly + dask mainline

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#10441]
Using the latest cudf/dask-cudf packages from the rapidsai-nightly channel:
```
conda list | grep dask                                                                    │···
dask                      2022.2.1+34.ga7e57ba9          pypi_0    pypi                                                                                           │···
dask-cuda                 22.04.00a220315         py39_23    rapidsai-nightly                                                                                     │···
dask-cudf                 22.04.00a220314 cuda_11_py39_g61772d8d8e_256    rapidsai-nightly   
```

And having built and installed dask & distributed from their respective main branches, I can't import dask_cudf:
```
>>> import dask_cudf                                                                                                                                              │···
Traceback (most recent call last):                                                                                                                                │···
  File "<stdin>", line 1, in <module>                                                                                                                             │···
  File "/home/rgelhausen/conda/envs/dsql-3-15/lib/python3.9/site-packages/dask_cudf/__init__.py", line 6, in <module>                                             │···
    from . import backends                                                                                                                                        │···
  File "/home/rgelhausen/conda/envs/dsql-3-15/lib/python3.9/site-packages/dask_cudf/backends.py", line 21, in <module>                                            │···
    from dask.dataframe.utils import (                                                                                                                            │···
ImportError: cannot import name 'is_arraylike' from 'dask.dataframe.utils' (/home/rgelhausen/conda/envs/dsql-3-15/lib/python3.9/site-packages/dask-2022.2.1+34.ga7│···
e57ba9-py3.9.egg/dask/dataframe/utils.py)  
```

**Comment by randerzander** [comment]
Fixed by #10442
