### ISSUE TITLE
[BUG] device_buffer.pxd not found from source installation

### ISSUE THREAD

**Issue by MikeChenfu** [rapidsai/cudf#10834]
**Describe the bug**
Hello, I am trying to install cudf from source but get the below error. Appreciate it if anyone has an idea for this problem.
```
(base) root@1b0a4e80eba3:~/json_c/cudf/python/cudf# python setup.py build_ext --inplace
/conda/lib/python3.9/site-packages/setuptools/dist.py:461: UserWarning: Normalizing '22.06.00a+246.g2b204d0433.dirty' to '22.6.0a0+246.g2b204d0433.dirty'
  warnings.warn(tmpl.format(**locals()))
running build_ext
Compiling cudf/_lib/avro.pyx because it changed.
Compiling cudf/_lib/binaryop.pyx because it changed.
Compiling cudf/_lib/column.pyx because it changed.
Compiling cudf/_lib/concat.pyx because it changed.
Compiling cudf/_lib/copying.pyx because it changed.
Compiling cudf/_lib/csv.pyx because it changed.
Compiling cudf/_lib/datetime.pyx because it changed.
Compiling cudf/_lib/expressions.pyx because it changed.
Compiling cudf/_lib/filling.pyx because it changed.
Compiling cudf/_lib/gpuarrow.pyx because it changed.
Compiling cudf/_lib/groupby.pyx because it changed.
Compiling cudf/_lib/hash.pyx because it changed.
Compiling cudf/_lib/interop.pyx because it changed.
Compiling cudf/_lib/io/datasource.pyx because it changed.
Compiling cudf/_lib/io/utils.pyx because it changed.
Compiling cudf/_lib/join.pyx because it changed.
Compiling cudf/_lib/json.pyx because it changed.
Compiling cudf/_lib/labeling.pyx because it changed.
Compiling cudf/_lib/lists.pyx because it changed.
Compiling cudf/_lib/merge.pyx because it changed.
Compiling cudf/_lib/null_mask.pyx because it changed.
Compiling cudf/_lib/nvtext/edit_distance.pyx because it changed.
Compiling cudf/_lib/nvtext/generate_ngrams.pyx because it changed.
Compiling cudf/_lib/nvtext/ngrams_tokenize.pyx because it changed.
Compiling cudf/_lib/nvtext/normalize.pyx because it changed.
Compiling cudf/_lib/nvtext/replace.pyx because it changed.
Compiling cudf/_lib/nvtext/stemmer.pyx because it changed.
Compiling cudf/_lib/nvtext/subword_tokenize.pyx because it changed.
Compiling cudf/_lib/nvtext/tokenize.pyx because it changed.
Compiling cudf/_lib/orc.pyx because it changed.
Compiling cudf/_lib/parquet.pyx because it changed.
Compiling cudf/_lib/partitioning.pyx because it changed.
Compiling cudf/_lib/quantiles.pyx because it changed.
Compiling cudf/_lib/reduce.pyx because it changed.
Compiling cudf/_lib/replace.pyx because it changed.
Compiling cudf/_lib/reshape.pyx because it changed.
Compiling cudf/_lib/rolling.pyx because it changed.
Compiling cudf/_lib/round.pyx because it changed.
Compiling cudf/_lib/scalar.pyx because it changed.
Compiling cudf/_lib/search.pyx because it changed.
Compiling cudf/_lib/sort.pyx because it changed.
Compiling cudf/_lib/stream_compaction.pyx because it changed.
Compiling cudf/_lib/string_casting.pyx because it changed.
Compiling cudf/_lib/strings/attributes.pyx because it changed.
Compiling cudf/_lib/strings/capitalize.pyx because it changed.
Compiling cudf/_lib/strings/case.pyx because it changed.
Compiling cudf/_lib/strings/char_types.pyx because it changed.
Compiling cudf/_lib/strings/combine.pyx because it changed.
Compiling cudf/_lib/strings/contains.pyx because it changed.
Compiling cudf/_lib/strings/convert/convert_fixed_point.pyx because it changed.
Compiling cudf/_lib/strings/convert/convert_floats.pyx because it changed.
Compiling cudf/_lib/strings/convert/convert_integers.pyx because it changed.
Compiling cudf/_lib/strings/convert/convert_lists.pyx because it changed.
Compiling cudf/_lib/strings/convert/convert_urls.pyx because it changed.
Compiling cudf/_lib/strings/extract.pyx because it changed.
Compiling cudf/_lib/strings/find.pyx because it changed.
Compiling cudf/_lib/strings/find_multiple.pyx because it changed.
Compiling cudf/_lib/strings/findall.pyx because it changed.
Compiling cudf/_lib/strings/json.pyx because it changed.
Compiling cudf/_lib/strings/padding.pyx because it changed.
Compiling cudf/_lib/strings/repeat.pyx because it changed.
Compiling cudf/_lib/strings/replace.pyx because it changed.
Compiling cudf/_lib/strings/replace_re.pyx because it changed.
Compiling cudf/_lib/strings/split/partition.pyx because it changed.
Compiling cudf/_lib/strings/split/split.pyx because it changed.
Compiling cudf/_lib/strings/strip.pyx because it changed.
Compiling cudf/_lib/strings/substring.pyx because it changed.
Compiling cudf/_lib/strings/translate.pyx because it changed.
Compiling cudf/_lib/strings/wrap.pyx because it changed.
Compiling cudf/_lib/text.pyx because it changed.
Compiling cudf/_lib/transform.pyx because it changed.
Compiling cudf/_lib/transpose.pyx because it changed.
Compiling cudf/_lib/types.pyx because it changed.
Compiling cudf/_lib/unary.pyx because it changed.
Compiling cudf/_lib/utils.pyx because it changed.
[ 1/75] Cythonizing cudf/_lib/avro.pyx
warning: cudf/_lib/cpp/types.pxd:51:8: 'UNEQUAL' redeclared 

Error compiling Cython file:
------------------------------------------------------------
...

from libcpp cimport bool
from libcpp.memory cimport unique_ptr
from libcpp.vector cimport vector

from rmm._lib.device_buffer cimport device_buffer
^
------------------------------------------------------------

cudf/_lib/cpp/column/column.pxd:7:0: 'rmm/_lib/device_buffer.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...

from libcpp cimport bool
from libcpp.memory cimport unique_ptr
from libcpp.vector cimport vector

from rmm._lib.device_buffer cimport device_buffer
^
------------------------------------------------------------

cudf/_lib/cpp/column/column.pxd:7:0: 'rmm/_lib/device_buffer/device_buffer.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from cudf._lib.cpp.types cimport data_type, size_type


cdef extern from "cudf/column/column.hpp" namespace "cudf" nogil:
    cdef cppclass column_contents "cudf::column::contents":
        unique_ptr[device_buffer] data
                               ^
------------------------------------------------------------

cudf/_lib/cpp/column/column.pxd:15:32: unknown type in template argument

Error compiling Cython file:
------------------------------------------------------------
...


cdef extern from "cudf/column/column.hpp" namespace "cudf" nogil:
    cdef cppclass column_contents "cudf::column::contents":
        unique_ptr[device_buffer] data
        unique_ptr[device_buffer] null_mask
                               ^
------------------------------------------------------------

cudf/_lib/cpp/column/column.pxd:16:32: unknown type in template argument

Error compiling Cython file:
------------------------------------------------------------
...
        column(const column& other) except +

        column(
            data_type dtype,
            size_type size,
            device_buffer&& data
           ^
------------------------------------------------------------

cudf/_lib/cpp/column/column.pxd:26:12: 'device_buffer' is not a type identifier
Traceback (most recent call last):
  File "/root/json_c/cudf/python/cudf/setup.py", line 236, in <module>
    setup(
  File "/conda/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/conda/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/conda/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/conda/lib/python3.9/distutils/dist.py", line 984, in run_command
    cmd_obj.ensure_finalized()
  File "/conda/lib/python3.9/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/root/json_c/cudf/python/cudf/setup.py", line 148, in finalize_options
    self.distribution.ext_modules = cythonize(
  File "/root/json_c/cudf/python/cudf/.eggs/Cython-0.29.28-py3.9-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1127, in cythonize
    cythonize_one(*args)
  File "/root/json_c/cudf/python/cudf/.eggs/Cython-0.29.28-py3.9-linux-x86_64.egg/Cython/Build/Dependencies.py", line 1250, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: cudf/_lib/avro.pyx


```

**Comment by shwina** [comment]
This could actually be an issue with RMM rather than cuDF, where the `rmm` package may not be correctly shipped with `.pxd` files. That being said, you won't be able to reproduce the issue by grabbing the RMM source (they will have the `.pxd` files...), so I think it's fine to keep the discussion here.

**Comment by shwina** [comment]
@MikeChenfu do you have `rmm` installled already? That's a dependency of cuDF. If you aren't doing so already, I'd highly recommend following the instructions in our [CONTRIBUTING](https://github.com/rapidsai/cudf/blob/branch-22.06/CONTRIBUTING.md) document to set up a development environment with the required dependencies.

In particular, you should do:

```
# create the conda environment (assuming in base `cudf` directory)
# note: RAPIDS currently doesn't support `channel_priority: strict`;
# use `channel_priority: flexible` instead
conda env create --name cudf_dev --file conda/environments/cudf_dev_cuda11.5.yml
# activate the environment
conda activate cudf_dev
```

**Comment by MikeChenfu** [comment]
The environment and cudf are built well and I'll close this issue. Thanks @shwina for the kind help.

**Comment by fecet** [comment]
As document suggest that it's possible to build without Conda, are there other solutions?

**Comment by vyasr** [comment]
The issue above was specifically an issue when building against the conda package. If you have installed rmm in a different way, the problem should not be present. If you are still seeing it, please open a separate issue describing how you build/install rmm so that we can help you determine why your rmm installation isn't working for cudf builds.
