### ISSUE TITLE
[FEA] Support casting to date (datetime64[D]) type

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#11048]
I have string encoded date columns I'd like to cast to plain dates:
```
>>> import cudf
>>> test_df = cudf.DataFrame({"dt": ["2022-06-02"]})
>>> test_df = cudf.DataFrame({"dt_str": ["2022-06-02"]})

# works
>>> test_df["dt"] = test_df["dt_str"].astype("datetime64[ns]")

# fails
>>> test_df["dt"] = test_df["dt_str"].astype("datetime64[D]")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/dsql/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/dsql/lib/python3.9/site-packages/cudf/core/series.py", line 1636, in astype
    return super().astype(dtype, copy, errors, **kwargs)
  File "/opt/conda/envs/dsql/lib/python3.9/site-packages/cudf/core/indexed_frame.py", line 2460, in astype
    raise e
  File "/opt/conda/envs/dsql/lib/python3.9/site-packages/cudf/core/indexed_frame.py", line 2457, in astype
    data = super().astype(dtype, copy, **kwargs)
  File "/opt/conda/envs/dsql/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/dsql/lib/python3.9/site-packages/cudf/core/frame.py", line 354, in astype
    result[col_name] = col.astype(dt, copy=copy, **kwargs)
  File "/opt/conda/envs/dsql/lib/python3.9/site-packages/cudf/core/column/column.py", line 868, in astype
    elif cudf.dtype(dtype).type in {
  File "/opt/conda/envs/dsql/lib/python3.9/site-packages/cudf/core/dtypes.py", line 47, in dtype
    raise TypeError(f"Unsupported type {np_dtype}")
TypeError: Unsupported type datetime64[D]

# this is supported by Pandas
>>> test_df.to_pandas()["dt_str"].astype("datetime64[D]")
0   2022-06-02
Name: dt_str, dtype: datetime64[ns]
```

**Comment by galipremsagar** [comment]
@randerzander So the expectation here is to cast to `datetime64[ns]` but not to raise an error for `datetime64[D]`? If yes, in addition having a warning while this op happens would be meaningful because we/pandas don't support true `datetime64[D]` dtype.

**Comment by randerzander** [comment]
Ah, I see Pandas doesn't actually store it as a "date" type. It does, however, perform the truncation to date only values before storing the result into a `datetime64[ns]`:

```
>>> test_df = cudf.DataFrame({"dt_str": ["2022-06-02 12:00:00"]})
>>> test_df.to_pandas()['dt_str'].astype('datetime64[D]')
0   2022-06-02
Name: dt_str, dtype: datetime64[ns]
```

So, the expectation I'd have for cudf is to perform the same truncation down to the "date only" (2022-06-02) part of the datetime.

**Comment by vyasr** [comment]
AFAICT the above behavior is also no longer observed in pandas, so I think we can close this request. Please reopen if needed, though.
```
>>> cudf.DataFrame({"dt_str": ["2022-06-02 12:00:00"]}).to_pandas()['dt_str'].astype('datetime64[D]')
...
ValueError: Unexpected value for 'dtype': 'datetime64[D]'. Must be 'datetime64[s]', 'datetime64[ms]', 'datetime64[us]', 'datetime64[ns]' or DatetimeTZDtype'.
```
