### ISSUE TITLE
[BUG] Loading a missing column from a Parquet file results in ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#11278]
**Describe the bug**
Attempting to load a non-existent column from a Parquet file throws ArrayIndexOutOfBoundsException instead of a more specific error.

**Steps/Code to reproduce bug**
Try to load a single column name that does not exist from a Parquet file.  For example:
```
Table.readParquet(ParquetOptions.builder().includeColumn("doesnotexist").build(), new java.io.File("data.parquet"))
```
throws the following exception:
```
java.lang.ArrayIndexOutOfBoundsException: 0
  at ai.rapids.cudf.Table.<init>(Table.java:96)
  at ai.rapids.cudf.Table.readParquet(Table.java:974)
  ... 49 elided
```

**Expected behavior**
A more useful error exception/message should be used than an array index error.

**Comment by GregoryKimball** [comment]
This issue does not appear to impact cuDF-python and may only impact the Java bindings.
