### ISSUE TITLE
[BUG]Decimal128 OverflowError BUG?

### ISSUE THREAD

**Issue by pengyizeng** [rapidsai/cudf#11337]
BUG EXAMPlE:

```
>>> a = Decimal('0.0009384233522166997927180531650178250')
>>> b =cudf.Series([a])
>>> b
0    0.0009384233522166997927180531650178250
dtype: decimal128
>>> b*b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zen/anaconda3/envs/rapids-22.06/lib/python3.9/site-packages/cudf/core/mixins/mixin_factory.py", line 11, in wrapper
    return method(self, *args1, *args2, **kwargs1, **kwargs2)
  File "/home/zen/anaconda3/envs/rapids-22.06/lib/python3.9/site-packages/cudf/core/indexed_frame.py", line 2188, in _binaryop
    ColumnAccessor(type(self)._colwise_binop(operands, op)),
  File "/home/zen/anaconda3/envs/rapids-22.06/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/zen/anaconda3/envs/rapids-22.06/lib/python3.9/site-packages/cudf/core/frame.py", line 2436, in _colwise_binop
    else getattr(operator, fn)(left_column, right_column)
  File "/home/zen/anaconda3/envs/rapids-22.06/lib/python3.9/site-packages/cudf/core/mixins/mixin_factory.py", line 11, in wrapper
    return method(self, *args1, *args2, **kwargs1, **kwargs2)
  File "/home/zen/anaconda3/envs/rapids-22.06/lib/python3.9/site-packages/cudf/core/column/decimal.py", line 84, in _binaryop
    output_type = _get_decimal_type(self.dtype, other.dtype, op)
  File "/home/zen/anaconda3/envs/rapids-22.06/lib/python3.9/site-packages/cudf/core/column/decimal.py", line 402, in _get_decimal_type
    raise OverflowError("Maximum supported decimal type is Decimal128")
OverflowError: Maximum supported decimal type is Decimal128
```

Is there any solution to avoid the OverflowError when doing math operations like this above?

**Comment by shwina** [comment]
It looks like the result type is too large to fit in Decimal128. Would silently overflowing in this situation would be preferable over raising an OverflowError? For all other data types, we (and Pandas) do silently overflow.

**Comment by pengyizeng** [comment]
I think silently overflowing in Decimal128 type will be preferable over raising an Error. Hope to make the improvement in the Decimal128 type.
