### ISSUE TITLE
[BUG] Failed to dlopen libcuda.so

### ISSUE THREAD

**Issue by wbo4958** [rapidsai/cudf#11366]
**Describe the bug**
I read https://github.com/rapidsai/cudf/issues/11028 and  https://github.com/rapidsai/cudf/issues/10308, but both of them didn't help

I installed the rapids-22.06 stable version by 

``` bash
conda create -n xgboost -c rapidsai -c nvidia -c conda-forge rapids=22.06 python=3.9 cudatoolkit=11.5
```

``` bash
conda activate xgboost

(xgboost) ssh xxx@xxxxxx:~$ python -m cudf
Traceback (most recent call last):
  File "cuda/_cuda/ccuda.pyx", line 3671, in cuda._cuda.ccuda._cuInit
  File "cuda/_cuda/ccuda.pyx", line 435, in cuda._cuda.ccuda.cuPythonInit
RuntimeError: Failed to dlopen libcuda.so
Exception ignored in: 'cuda._lib.ccudart.utils.cudaPythonGlobal.lazyInitGlobal'
Traceback (most recent call last):
  File "cuda/_cuda/ccuda.pyx", line 3671, in cuda._cuda.ccuda._cuInit
  File "cuda/_cuda/ccuda.pyx", line 435, in cuda._cuda.ccuda.cuPythonInit
RuntimeError: Failed to dlopen libcuda.so
Segmentation fault (core dumped)
```

## env

``` console
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
```

## nvidia-smi

``` console
nvidia-smi 
Wed Jul 27 18:54:43 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.48.07    Driver Version: 515.48.07    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN RTX    On   | 00000000:01:00.0 Off |                  N/A |
| 41%   36C    P8    19W / 280W |      1MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA TITAN RTX    On   | 00000000:02:00.0 Off |                  N/A |
| 41%   30C    P8    14W / 280W |      1MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

## nvcc

``` console
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
```

## locate libcuda.so

``` console
locate libcuda.so
/usr/lib/i386-linux-gnu/libcuda.so
/usr/lib/i386-linux-gnu/libcuda.so.1
/usr/lib/i386-linux-gnu/libcuda.so.515.48.07
/usr/lib/x86_64-linux-gnu/libcuda.so.1
/usr/lib/x86_64-linux-gnu/libcuda.so.515.48.07
/usr/lib/x86_64-linux-gnu/stubs/libcuda.so
/usr/local/cuda-11.4/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.5/lib64/stubs/libcuda.so
/usr/local/cuda-11.5/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.6/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/share/man/man7/libcuda.so.7.gz
```

I tried 
``` bash
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu &&  python -m cudf
```
but it didn't help.

**Comment by wbo4958** [comment]
@shwina 

``` bash
~/anaconda3/envs$ conda list |  grep cuda
arrow-cpp                 7.0.0           py39h0f417f0_8_cuda    conda-forge
arrow-cpp-proc            3.0.0                      cuda    conda-forge
cucim                     22.06.00        cuda_11_py39_g575240a_0    rapidsai
cuda-python               11.7.0           py39h3fd9d12_0    nvidia
cudatoolkit               11.5.1               hcf5317a_9    nvidia
cudf                      22.06.01        cuda_11_py39_g0dab0f8305_0    rapidsai
cugraph                   22.06.01        cuda11_py39_gde8036b5_0    rapidsai
cuml                      22.06.01        cuda11_py39_ge38b5bdd5_0    rapidsai
dask-cuda                 22.06.00                 py39_0    rapidsai
dask-cudf                 22.06.01        cuda_11_py39_g0dab0f8305_0    rapidsai
faiss-proc                1.0.0                      cuda    rapidsai
libcucim                  22.06.00        cuda11_g575240a_0    rapidsai
libcudf                   22.06.01        cuda11_g0dab0f8305_0    rapidsai
libcugraph                22.06.01        cuda11_gde8036b5_0    rapidsai
libcugraph_etl            22.06.01        cuda11_gde8036b5_0    rapidsai
libcugraphops             22.06.00        cuda11_gb4e1cbb_0    nvidia
libcuml                   22.06.01        cuda11_ge38b5bdd5_0    rapidsai
libcumlprims              22.06.00        cuda11_g8c6e2c0_0    nvidia
libcuspatial              22.06.00        cuda11_g96613ba_0    rapidsai
libfaiss                  1.7.0           cuda112h5bea7ad_8_cuda    conda-forge
libraft-distance          22.06.00        cuda11_ged2c529_0    rapidsai
libraft-headers           22.06.00        cuda11_ged2c529_0    rapidsai
libraft-nn                22.06.00        cuda11_ged2c529_0    rapidsai
librmm                    22.06.01        cuda11_g1c7ff61a_0    rapidsai
libxgboost                1.6.0dev.rapidsai22.06       cuda_11_0    rapidsai
py-xgboost                1.6.0dev.rapidsai22.06  cuda_11_py39_0    rapidsai
pyarrow                   7.0.0           py39h1ed2e5d_8_cuda    conda-forge
pylibcugraph              22.06.01        cuda11_py39_gde8036b5_0    rapidsai
pyraft                    22.06.00        cuda11_py39_ged2c529_0    rapidsai
rapids                    22.06.00        cuda11_py39_ged167d1_108    rapidsai
rapids-xgboost            22.06.00        cuda11_py39_ged167d1_108    rapidsai
rmm                       22.06.01        cuda11_py39_g1c7ff61a_0    rapidsai
xgboost                   1.6.0dev.rapidsai22.06  cuda_11_py39_0    rapidsai
```

BTW, I tried 22.08 nightly, still got the same exception

**Comment by wbo4958** [comment]
after uninstall gpu driver/cuda, it worked. feel free to close it.
