### ISSUE TITLE
[BUG] cudf.Series.fillna fails for numpy.datetime64 columns

### ISSUE THREAD

**Issue by trstovall** [rapidsai/cudf#1140]
**Describe the bug**
cudf.Series.fillna fails for numpy.datetime64 columns

**Steps/Code to reproduce bug**
```
>>> import cudf
>>> from datetime import date

>>> s = cudf.Series([None, date.today()])
>>> print(s)
0                          
1   2019-03-07T00:00:00.000
dtype: datetime64[ms]

>>> nat = s.dtype.type(None)
>>> s.fillna(nat)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/lib/python3.7/site-packages/cudf-0.6.0.dev0+803.gde773d4-py3.7-linux-x86_64.egg/cudf/dataframe/series.py", line 558, in fillna
    data = self._column.fillna(value)
  File "/conda/lib/python3.7/site-packages/cudf-0.6.0.dev0+803.gde773d4-py3.7-linux-x86_64.egg/cudf/dataframe/column.py", line 443, in fillna
    value=value)
  File "/conda/lib/python3.7/site-packages/cudf-0.6.0.dev0+803.gde773d4-py3.7-linux-x86_64.egg/cudf/utils/cudautils.py", line 444, in fillna
    configured(value, mask, out)
  File "/conda/lib/python3.7/site-packages/numba/cuda/compiler.py", line 226, in __call__
    kernel = self.kernel.specialize(*args)
  File "/conda/lib/python3.7/site-packages/numba/cuda/compiler.py", line 776, in specialize
    kernel = self.compile(argtypes)
  File "/conda/lib/python3.7/site-packages/numba/cuda/compiler.py", line 792, in compile
    **self.targetoptions)
  File "/conda/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/conda/lib/python3.7/site-packages/numba/cuda/compiler.py", line 62, in compile_kernel
    cres = compile_cuda(pyfunc, types.void, args, debug=debug, inline=inline)
  File "/conda/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/conda/lib/python3.7/site-packages/numba/cuda/compiler.py", line 51, in compile_cuda
    locals={})
  File "/conda/lib/python3.7/site-packages/numba/compiler.py", line 926, in compile_extra
    return pipeline.compile_extra(func)
  File "/conda/lib/python3.7/site-packages/numba/compiler.py", line 374, in compile_extra
    return self._compile_bytecode()
  File "/conda/lib/python3.7/site-packages/numba/compiler.py", line 857, in _compile_bytecode
    return self._compile_core()
  File "/conda/lib/python3.7/site-packages/numba/compiler.py", line 844, in _compile_core
    res = pm.run(self.status)
  File "/conda/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/conda/lib/python3.7/site-packages/numba/compiler.py", line 255, in run
    raise patched_exception
  File "/conda/lib/python3.7/site-packages/numba/compiler.py", line 246, in run
    stage()
  File "/conda/lib/python3.7/site-packages/numba/compiler.py", line 485, in stage_nopython_frontend
    self.locals)
  File "/conda/lib/python3.7/site-packages/numba/compiler.py", line 1029, in type_inference_stage
    infer.propagate()
  File "/conda/lib/python3.7/site-packages/numba/typeinfer.py", line 860, in propagate
    raise errors[0]
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot resolve setitem: array(datetime64[ms], 1d, A)[int32] = datetime64[]

File "../conda/lib/python3.7/site-packages/cudf-0.6.0.dev0+803.gde773d4-py3.7-linux-x86_64.egg/cudf/utils/cudautils.py", line 436:
def gpu_fill_masked(value, validity, out):
    <source elided>
        if not valid:
            out[tid] = value
            ^

[1] During: typing of setitem at /conda/lib/python3.7/site-packages/cudf-0.6.0.dev0+803.gde773d4-py3.7-linux-x86_64.egg/cudf/utils/cudautils.py (436)

File "../conda/lib/python3.7/site-packages/cudf-0.6.0.dev0+803.gde773d4-py3.7-linux-x86_64.egg/cudf/utils/cudautils.py", line 436:
def gpu_fill_masked(value, validity, out):
    <source elided>
        if not valid:
            out[tid] = value
            ^
```

**Expected behavior**
no stack trace

**Environment details (please complete the following information):**
```
root@3ba3ff913a03:/cudf# ./print_env.sh 
**git***
commit de773d4350096a70080ca08c1e583ef02a81559c (HEAD -> branch-0.6, origin/branch-0.6, origin/HEAD)
Merge: d5de9f8 b2dd6fe
Author: Keith Kraus <keith.j.kraus@gmail.com>
Date:   Wed Feb 27 16:45:14 2019 -0800

    Merge pull request #1054 from jrhemstad/fix-ext-trie-default-ctor
    
    [REVIEW] Added default constructor for SerialTrieNode to solve Thrust bug on CentOS7

***OS Information***
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
Linux 3ba3ff913a03 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

***GPU Information***
Thu Mar  7 20:23:40 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-SXM2...  Off  | 00000000:05:00.0 Off |                    0 |
| N/A   36C    P0    43W / 300W |    861MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-SXM2...  Off  | 00000000:06:00.0 Off |                    0 |
| N/A   31C    P0    34W / 300W |     10MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P100-SXM2...  Off  | 00000000:84:00.0 Off |                    0 |
| N/A   28C    P0    34W / 300W |     10MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P100-SXM2...  Off  | 00000000:85:00.0 Off |                    0 |
| N/A   33C    P0    34W / 300W |     10MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

***CPU***
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                56
On-line CPU(s) list:   0-55
Thread(s) per core:    2
Core(s) per socket:    14
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2650L v4 @ 1.70GHz
Stepping:              1
CPU MHz:               2000.222
CPU max MHz:           2500.0000
CPU min MHz:           1200.0000
BogoMIPS:              3401.36
Virtualization:        VT-x
Hypervisor vendor:     vertical
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              35840K
NUMA node0 CPU(s):     0-13,28-41
NUMA node1 CPU(s):     14-27,42-55
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts flush_l1d

***CMake***
/conda/bin/cmake
cmake version 3.13.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).

***g++***
/usr/bin/g++
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


***nvcc***
/usr/local/cuda/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

***Python***
/conda/bin/python
Python 3.7.1

***Environment Variables***
PATH                            : /conda/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LD_LIBRARY_PATH                 : :/usr/local/cuda/lib64:/usr/local/lib:/usr/local/cuda/lib64:/usr/local/lib
NUMBAPRO_NVVM                   : /usr/local/cuda/nvvm/lib64/libnvvm.so
NUMBAPRO_LIBDEVICE              : /usr/local/cuda/nvvm/libdevice/
CONDA_PREFIX                    : 
PYTHON_PATH                     : 

***conda packages***
/conda/bin/conda
# packages in environment at /conda:
#
# Name                    Version                   Build  Channel
arrow-cpp                 0.12.1           py37h0e61e49_0    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     18.2.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                         mkl  
bleach                    3.1.0                      py_0    conda-forge
boost                     1.68.0          py37h8619c78_1001    conda-forge
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py37_1000    conda-forge
cffi                      1.12.2           py37h9745a5d_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                      pypi_0    pypi
cloudpickle               0.8.0                      py_0    conda-forge
cmake                     3.13.4               h8d4ced6_0    conda-forge
conda                     4.6.7                    py37_0    conda-forge
conda-env                 2.6.0                         1  
cryptography              2.5              py37hb7f436b_1    conda-forge
cudf                      0.6.0.dev0+803.gde773d4          pypi_0    pypi
cuml                      0.5.1+309.gfc47196          pypi_0    pypi
curl                      7.64.0               h646f8bb_0    conda-forge
cython                    0.29.6           py37hf484d3e_0    conda-forge
cytoolz                   0.9.0.1         py37h14c3975_1001    conda-forge
dask-core                 1.1.2                      py_0    conda-forge
dask-cudf                 0.0.1+253.g06ec3a1          pypi_0    pypi
decorator                 4.3.2                      py_0    conda-forge
distributed               1.26.0                   py37_1    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
heapdict                  1.0.0                 py37_1000    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
intel-openmp              2019.1                      144  
ipykernel                 5.1.0           py37h24bf2e0_1002    conda-forge
ipython                   7.3.0            py37h24bf2e0_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.13.3                   py37_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jsonschema                3.0.1                    py37_0    conda-forge
jupyter_client            5.2.4                      py_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
krb5                      1.16.3            hc83ff2d_1000    conda-forge
libcurl                   7.64.0               h01ee5af_0    conda-forge
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgdf-cffi               0.6.0                    pypi_0    pypi
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libprotobuf               3.6.1             hdbcaa40_1001    conda-forge
librmm-cffi               0.5.0                    pypi_0    pypi
libsodium                 1.0.16            h14c3975_1001    conda-forge
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
libuv                     1.26.0               h14c3975_0    conda-forge
llvmlite                  0.27.0           py37hf484d3e_0    numba
markupsafe                1.1.1            py37h14c3975_0    conda-forge
mistune                   0.8.4           py37h14c3975_1000    conda-forge
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py37h14c3975_1    conda-forge
mkl_random                1.0.2            py37h637b7d7_2    conda-forge
more-itertools            4.3.0                 py37_1000    conda-forge
msgpack-python            0.6.1            py37h6bb024c_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  he6710b0_1  
notebook                  5.7.4                 py37_1000    conda-forge
numba                     0.42.0          np115py37hf484d3e_0    numba
numpy                     1.15.4           py37h7e9f1db_0  
numpy-base                1.15.4           py37hde5b4d6_0  
nvstrings                 0.2.0            cuda9.2_py37_0    nvidia
openssl                   1.0.2r               h14c3975_0    conda-forge
pandas                    0.23.4          py37h637b7d7_1000    conda-forge
pandoc                    2.6                           1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parquet-cpp               1.5.1                         4    conda-forge
parso                     0.3.4                      py_0    conda-forge
pexpect                   4.6.0                 py37_1000    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pip                       19.0.3                   py37_0    conda-forge
pluggy                    0.9.0                      py_0    conda-forge
prometheus_client         0.6.0                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
psutil                    5.5.1            py37h14c3975_0    conda-forge
ptyprocess                0.6.0                 py37_1000    conda-forge
py                        1.8.0                      py_0    conda-forge
pyarrow                   0.12.0           py37hbbcf98d_2    conda-forge
pycosat                   0.6.3           py37h14c3975_1001    conda-forge
pycparser                 2.19                       py_0    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyrsistent                0.14.11          py37h14c3975_0    conda-forge
pysocks                   1.6.8                 py37_1002    conda-forge
pytest                    4.3.0                    py37_0    conda-forge
python                    3.7.1             hd21baee_1001    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
pyyaml                    3.13            py37h14c3975_1001    conda-forge
pyzmq                     18.0.0           py37h0e1adb2_0    conda-forge
readline                  7.0                  h7b6447c_5  
requests                  2.21.0                py37_1000    conda-forge
rhash                     1.3.6             h14c3975_1001    conda-forge
ruamel_yaml               0.15.71         py37h14c3975_1000    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.8.0                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.26.0               h7b6447c_0  
tblib                     1.3.2                    pypi_0    pypi
terminado                 0.8.1                 py37_1001    conda-forge
testpath                  0.4.2                 py37_1000    conda-forge
thrift-cpp                0.12.0            h23e226f_1001    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
toolz                     0.9.0                    pypi_0    pypi
tornado                   5.1.1           py37h14c3975_1000    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
urllib3                   1.24.1                py37_1000    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.1                   py37_0    conda-forge
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zeromq                    4.2.5             hf484d3e_1006    conda-forge
zict                      0.1.3                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
```

**Comment by kkraus14** [comment]
cc @shwina another one to tackle in the fillna rework?

**Comment by kkraus14** [comment]
@trstovall could you try with `nat = s.dtype.type(None).astype(s.dtype)` I've seen numpy behavior really weirdly when it comes to typing scalars like this.

**Comment by shwina** [comment]
@trstovall Could you please confirm if this works with the latest cudf (branch-0.6)?

You should also just be able to do:

```
s.fillna('nat')
```

**Comment by trstovall** [comment]
`nat = s.dtype.type(None).astype(s.dtype); s.fillna(nat)` works, `s.fillna('nat')` does not.

**Comment by shwina** [comment]
Thanks, @trstovall. I'm having trouble reproducing this with current branch-0.6. Both `s.dtype.type(None)` and `'nat'` seem to be working:

```python
In [1]: import cudf                                                               
                                                                               
In [2]: from datetime import date                                                                                                                                                 
                                                                                                                                                                                 
In [3]:  s = cudf.Series([None, date.today()])                                                                                                                                    
/home/atrikut/projects/cudf/python/cudf/dataframe/columnops.py:301: UserWarning: Date32 values are not yet supported so this will be typecast to a Date64 value
  "be typecast to a Date64 value", UserWarning)                                
                                                                               
In [4]: print(s)                                                               
0                                                                              
1   2019-03-11T00:00:00.000                                                    
dtype: datetime64[ms]                                                          
                                                                               
In [5]: print(s.fillna('nat'))                                                                                                                                                    
0                       NaT                                                                                                                                                       
1   2019-03-11T00:00:00.000                                                                                                                                                       
dtype: datetime64[ms]                                                          
                                                                                                                                                                                  
In [6]: print(s.fillna(s.dtype.type(None)))                                                                                                                                       
0                       NaT                                                     
1   2019-03-11T00:00:00.000                                                       
dtype: datetime64[ms]   
```

Note that `fillna()` was updated recently, so this will work only with a relatively recent build of cudf. Could you please post the results of `./print_env.sh ` after updating cudf?

**Comment by trstovall** [comment]
@kkraus14 Interestingly, `s.dtype.type(None) == s.dtype.type(None).astype(s.dtype)`.

**Comment by trstovall** [comment]
@shwina I tried again with last night's build of 0.6 and both `s.dtype.type(None)` and `nat` solutions work.
