### ISSUE TITLE
[QST] cudf.core.subword_tokenizer on multiple GPUs

### ISSUE THREAD

**Issue by maxbalrog** [rapidsai/cudf#11531]
I was reading the following blog post https://developer.nvidia.com/blog/run-state-of-the-art-nlp-workloads-at-scale-with-rapids-huggingface-and-dask/ but the link at the end of the post to the workflow code is no longer available (Check out the [workflow code here](https://github.com/rapidsai/tpcx-bb/blob/main/tpcx_bb/queries/q27/tpcx_bb_query_hf_27.py).)

In my project I am trying to rewrite some NLP preprocessing workflow (e.g., tokenization, tf-idf transformer) from CPU to GPU and multiple GPUs mode. I am doing this with `cudf`, `dask_cudf` and `cuML` libraries. In particular, I am using `cudf.core.subword_tokenizer` to transform string data to numerical representation (as an analog of tokenization + stemming). On one GPU everything works fine, but my realization of multiple-GPU version (`dask_cudf.DataFrame` with `map_partitions()` call to the function doing `cudf.core.subword_tokenizer` call) fails to work. It breaks down with the following error `TypeError: no default __reduce__ due to non-trivial __cinit__`.

I would really appreciate if someone could share some thoughts or experience on how `cudf.core.subword_tokenizer` could be realized for multiple GPUs with `dask_cudf`. Or why my realization fails to work.

**Comment by quasiben** [comment]
Here's a link to the query:
https://github.com/rapidsai/gpu-bdb/blob/main/gpu_bdb/queries/q27/gpu_bdb_query_hf_27.py

@VibhuJawa maybe you can update the blogpost ?

@maxbalrog can you build a small reproducer for the error you are seeing ?

**Comment by maxbalrog** [comment]
@quasiben I managed to locate and correct the issue but still it is unclear for me why it behaves in such way. I would appreciate if you could give some comments why it happens.

Here is code to reproduce the error. I have an abstract class `SubwordClass` with `transform` method which uses auxiliary methods (`_concat_columns` and `_subword_tokenize`). In the main part of the code an artificial dataframe is constructed, vocabulary and hashed vocabulary are created and the dataframe is transformed with the help of `SubwordClass.transform()`.

Error happens in _mgpu_ mode (I run it on one node with 2 V100 GPUs) when keyword `error=True`. It happens when I have an additional instance of `SubwordTokenizer(self.vocab_path)` initialized in the `_init_` method (initially that was the case in my code). If that instance is removed, then everything works fine.

```python
class SubwordClass:
    def __init__(self, vocab_path, device, error=False):
        self.vocab_path = vocab_path
        self.device = device
        self.max_length = 5
        self._fname_prefix = 'subword_gpu'
        if error:
            self.subword = SubwordTokenizer(self.vocab_path)

    def _concat_columns(self, df, col_name):
        outputs = df[df.columns[0]].fillna("").astype(str)
        for col in df.columns[1:]:
            outputs = outputs + " " + df[col].fillna("").astype(str)
        new_df = cudf.DataFrame({col_name: outputs})
        return new_df

    def _subword_tokenize(self, df):
        outputs = []
        subword_gpu = SubwordTokenizer(self.vocab_path)
        for col in df.columns:
            pred = subword_gpu(df[col].fillna("").astype(str),
                               max_length=self.max_length,
                               max_num_rows=len(df[col]),
                               padding='max_length',
                               return_tensors='cp',
                               truncation=True)
            col_name = self._fname_prefix + "__" + col
            pred = self._concat_columns(cudf.DataFrame(pred['input_ids']).astype(str), col_name)
            outputs.append(pred)
        new_df = cudf.DataFrame(cudf.concat(outputs, axis=1))
        return new_df

    def transform(self, df):
        if self.device == 'gpu':
            output = self._subword_tokenize(df)
        elif self.device == 'mgpu':
            new_cols = [self._fname_prefix + "__" + col for col in df.columns]
            output = df.map_partitions(self._subword_tokenize, meta=cudf.DataFrame(columns=new_cols)).persist()
        return output

# device = 'gpu'
device = 'mgpu'
N = 100
error = True

if __name__ == "__main__":
    import numpy as np
    import pandas as pd
    import torch

    if device == 'mgpu':
        from dask.distributed import Client
        from dask_cuda import LocalCUDACluster

        cluster = LocalCUDACluster(rmm_managed_memory=True, CUDA_VISIBLE_DEVICES="0,1",
                                   protocol="ucx", enable_nvlink=True,
                                   memory_limit="30GB")
        client = Client(cluster)

    import cudf
    import dask_cudf
    from cudf.utils.hash_vocab_utils import hash_vocab
    from cudf.core.subword_tokenizer import SubwordTokenizer

    # Create dataframe
    df = pd.DataFrame({'reviews_1': ["it is good", "not bad", "i am not really sure", "what is this"]*N,
                       'reviews_2': ["it is good", "not bad", "i am not really sure", "what is this"]*N})
    df_cudf = cudf.DataFrame(df)
    print(df_cudf.head())

    # Manually define vocabulary and produce hash version of it
    vocab = [' ', '[UNK]', '[CLS]', '[SEP]', 'it', 'is', 'good', 'not', 'bad',
             'i', 'am', 'not', 'really', 'sure', 'what', 'this']
    vocab_path = 'vocab.txt'
    with open(vocab_path, 'w') as f:
        for word in vocab:
            f.write(f"{word}\n")
    vocab_hash_path = 'vocab_hash.txt'
    hash_vocab(vocab_path, vocab_hash_path)

    if device == 'gpu':
        cls = SubwordClass(vocab_hash_path, device)
        output = cls.transform(df_cudf)
        print(type(output))
    elif device == 'mgpu':
        # Create dask df
        n_gpu = torch.cuda.device_count()
        print(f"n_gpu: {n_gpu}")
        df_daskcudf = dask_cudf.from_cudf(df_cudf, npartitions=n_gpu).persist()

        cls = SubwordClass(vocab_hash_path, device, error=error)
        output = cls.transform(df_daskcudf)
        print(type(output.compute()))

        client.close()
        cluster.close()
```

Here I add error message which I'm seeing
```
Traceback (most recent call last):
  File "/trinity/home/m.valialshchikov/.conda/envs/lama_venv/lib/python3.8/site-packages/distributed/worker.py", line 3824, in dumps_function
    result = cache_dumps[func]
  File "/trinity/home/m.valialshchikov/.conda/envs/lama_venv/lib/python3.8/site-packages/distributed/utils.py", line 1366, in __getitem__
    value = super().__getitem__(key)
  File "/trinity/home/m.valialshchikov/.conda/envs/lama_venv/lib/python3.8/collections/__init__.py", line 1010, in __getitem__
    raise KeyError(key)
KeyError: subgraph_callable-40df7b45-39c4-4c4b-9340-11d1f45cd0cb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/trinity/home/m.valialshchikov/.conda/envs/lama_venv/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 49, in dumps
    result = pickle.dumps(x, **dump_kwargs)
  File "stringsource", line 2, in cudf._lib.nvtext.subword_tokenize.Hashed_Vocabulary.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/test_subword_tokenize.py", line 124, in <module>
    output = cls.transform(df_daskcudf)
  File "tests/test_subword_tokenize.py", line 70, in transform
    output = df.map_partitions(self._subword_tokenize, meta=cudf.DataFrame(columns=new_cols)).persist()
  File "/trinity/home/m.valialshchikov/.conda/envs/lama_venv/lib/python3.8/site-packages/dask/base.py", line 261, in persist
    (result,) = persist(self, traverse=False, **kwargs)
  File "/trinity/home/m.valialshchikov/.conda/envs/lama_venv/lib/python3.8/site-packages/dask/base.py", line 765, in persist
    results = client.persist(
  File "/trinity/home/m.valialshchikov/.conda/envs/lama_venv/lib/python3.8/site-packages/distributed/client.py", line 2978, in persist
    futures = self._graph_to_futures(
  File "/trinity/home/m.valialshchikov/.conda/envs/lama_venv/lib/python3.8/site-packages/distributed/client.py", line 2594, in _graph_to_futures
    dsk = dsk.__dask_distributed_pack__(self, keyset, annotations)
  File "/trinity/home/m.valialshchikov/.conda/envs/lama_venv/lib/python3.8/site-packages/dask/highlevelgraph.py", line 1063, in __dask_distributed_pack__
    "state": layer.__dask_distributed_pack__(
  File "/trinity/home/m.valialshchikov/.conda/envs/lama_venv/lib/python3.8/site-packages/dask/blockwise.py", line 555, in __dask_distributed_pack__
    else dumps_function(dsk[0])
  File "/trinity/home/m.valialshchikov/.conda/envs/lama_venv/lib/python3.8/site-packages/distributed/worker.py", line 3826, in dumps_function
    result = pickle.dumps(func, protocol=4)
  File "/trinity/home/m.valialshchikov/.conda/envs/lama_venv/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 60, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
  File "/trinity/home/m.valialshchikov/.conda/envs/lama_venv/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/trinity/home/m.valialshchikov/.conda/envs/lama_venv/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 602, in dump
    return Pickler.dump(self, obj)
  File "stringsource", line 2, in cudf._lib.nvtext.subword_tokenize.Hashed_Vocabulary.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__

```

**Comment by VibhuJawa** [comment]
> Here is code to reproduce the error. I have an abstract class `SubwordClass` with `transform` method which uses auxiliary methods (`_concat_columns` and `_subword_tokenize`). In the main part of the code an artificial dataframe is constructed, vocabulary and hashed vocabulary are created and the dataframe is transformed with the help of `SubwordClass.transform()`.
> 

Thanks for the reproducer. I was able to reproduce this. What is happening is that SubwordTokenizer is not serializable and we are getting the  no default __reduce__ due to non-trivial __cinit__


Suggested Work Around is to set a worker attribute to dask and use that .  The function can look something like below: 


```python
def tokenize_strings(s, max_length=8):
    
    worker = get_worker() 
    
    ### doing it like this because SubwordTokenizer is not  
    ### serializable
    if hasattr(worker, "cudf_tokenizer"):
        tokenizer = worker.cudf_tokenizer
    else:
        tokenizer = SubwordTokenizer('voc_hash.txt',
                                   do_lower_case=True)
        
        worker.cudf_tokenizer = tokenizer
        
    max_num_rows = len(s)*2
    d = tokenizer(s, max_length=max_length, max_num_rows=max_num_rows, truncation=True, return_tensors='cp')
    return cudf.DataFrame({"input_ids":d['input_ids'].flatten(),
                           "attention_mask":d['attention_mask'].flatten()})
   ```` 



**Function in use on with a full blown MRE**:

```python
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
from dask.distributed import wait, get_worker

cluster = LocalCUDACluster(local_directory='/raid/vjawa/dask-workers')
client = Client(cluster)

#from cudf.utils.hash_vocab_utils import hash_vocab
#!wget https://huggingface.co/bert-base-cased/raw/main/vocab.txt
#hash_vocab('vocab.txt', 'voc_hash.txt')
from cudf.core.subword_tokenizer import SubwordTokenizer
import cudf
import dask_cudf
import cupy as cp


def tokenize_strings(s, max_length=8):
    
    worker = get_worker() 
    
    ### doing it like this because SubwordTokenizer is not  
    ### serializable
    if hasattr(worker, "cudf_tokenizer"):
        tokenizer = worker.cudf_tokenizer
    else:
        tokenizer = SubwordTokenizer('voc_hash.txt',
                                   do_lower_case=True)
        
        worker.cudf_tokenizer = tokenizer
        
    max_num_rows = len(s)*2
    d = tokenizer(s, max_length=max_length, max_num_rows=max_num_rows, truncation=True, return_tensors='cp')
    return cudf.DataFrame({"input_ids":d['input_ids'].flatten(),
                           "attention_mask":d['attention_mask'].flatten()})


max_length = 8

cudf_ser = cudf.Series(["This is a series", "This is also a series"])
meta_df = cudf.DataFrame({'input_ids':cp.zeros([1,2,3],dtype=cp.uint32),
                          'attention_mask':cp.zeros([1,2,3],dtype=cp.uint32),
                         })

dask_ser = dask_cudf.from_cudf(cudf_ser,2)
output = dask_ser.map_partitions(tokenize_strings, max_length=max_length, meta=meta_df)

input_ids = output['input_ids'].values
input_ids = input_ids.compute_chunk_sizes()
input_ids = input_ids.reshape(-1,max_length)
input_ids.compute()
```

```python
array([[ 101, 1142, 1110,  170, 1326,  102,    0,    0],
       [ 101, 1142, 1110, 1145,  170, 1326,  102,    0]], dtype=uint32)

```

**Comment by maxbalrog** [comment]
@VibhuJawa thanks for such a detailed answer! It is much more clear now.
