### ISSUE TITLE
[QST]

### ISSUE THREAD

**Issue by Ankitkurani1997** [rapidsai/cudf#11676]
I want to read a csv file which has size greater then that of single GPU on my local system. It give out of memory error, every time I try to read the file in cudf dataframe.

Is there a way to spill the memory to host memory or manage this, or is it not possible to read file greater than single GPU memory in cudf dataframe?

I have only one GPU.

I tried dask_cudf, but it also internally calls cudf.read_csv, so while performing .compute(), it again gives Out of memory error or illegal address.

**Comment by shwina** [comment]
>  so while performing .compute(), it again gives Out of memory error or illegal address.

Are you calling `compute()` immediately after  the call to `read_csv()`? Ideally, you should only call `.compute()` on the _end result_ of your workflow, which is typically much smaller than the initial data.

**Comment by madsbk** [comment]
Try to use a local CUDA cluster with spilling enabled:
```python
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
import dask_cudf

# Must run dask cluster within a "__main__" guard
if __name__ == "__main__":

    # Setup local CUDA cluster with spilling
    with LocalCUDACluster(jit_unspill=True) as cluster:
        with Client(cluster) as client:
            # Load from a CSV file
            ddf = dask_cudf.read_csv("myfile.csv")
            print(ddf)
            # Do your computations
            # ...
            # Get result
            print(ddf.head())
```

**Comment by Ankitkurani1997** [comment]
> > so while performing .compute(), it again gives Out of memory error or illegal address.
> 
> Are you calling `compute()` immediately after the call to `read_csv()`? Ideally, you should only call `.compute()` on the _end result_ of your workflow, which is typically much smaller than the initial data.

Got it

**Comment by Ankitkurani1997** [comment]
> 

@madsbk 

Getting following error when trying to construct a graph using cugraph

Traceback (most recent call last):
  File "new_approach.py", line 33, in <module>
    G.from_dask_cudf_edgelist(ddf, source='src', destination='dst')
  File "/home/ankit/miniconda3/envs/rapids-22.08/lib/python3.8/site-packages/cugraph/structure/graph_classes.py", line 284, in from_dask_cudf_edgelist
    self._Impl._simpleDistributedGraphImpl__from_edgelist(
  File "/home/ankit/miniconda3/envs/rapids-22.08/lib/python3.8/site-packages/cugraph/structure/graph_implementation/simpleDistributedGraph.py", line 143, in __from_edgelist
    source_col, dest_col = symmetrize(
  File "/home/ankit/miniconda3/envs/rapids-22.08/lib/python3.8/site-packages/cugraph/structure/symmetrize.py", line 242, in symmetrize
    output_df = symmetrize_ddf(input_df, source_col_name, dest_col_name,
  File "/home/ankit/miniconda3/envs/rapids-22.08/lib/python3.8/site-packages/cugraph/structure/symmetrize.py", line 162, in symmetrize_ddf
    num_partitions = len(worker_list)
TypeError: object of type 'NoneType' has no len()

Code snippet :

import dask
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
import dask_cudf
import cugraph
import cugraph.dask as dask_cugraph

if __name__ == "__main__":
    with dask.config.set(jit_unspill=True):
        with LocalCUDACluster(n_workers=1, device_memory_limit="1GB") as cluster:
            with Client(cluster) as client:
                ddf = dask_cudf.read_csv("twitter-2010.csv", delimiter=' ', names=['src', 'dst'], dtype=['int32', 'int32'])
                G = cugraph.Graph(directed=True)
                G.from_dask_cudf_edgelist(ddf, source='src', destination='dst')
                print(ddf.head())

**Comment by quasiben** [comment]
cc @eriknw @VibhuJawa for cugraph usage

**Comment by Ankitkurani1997** [comment]
@beckernick @eriknw @VibhuJawa can you please suggest some fix around the above error or point to some different approach if I want to use dask_cudf along with cugraph?

**Comment by Ankitkurani1997** [comment]
@madsbk 
I want to try to read 26GB data on a singl gpu having memory 24GB available.
Wanted to know how memory over subscription is handled
I am using cudf.read_csv

and have imported rmm
and rmm.reinitialize(managed_memory=True) for allocating all memory as managed memory (cudaMallocManaged underlying allocator)
as suggested in article https://medium.com/rapids-ai/tackling-large-graphs-with-rapids-cugraph-and-unified-virtual-memory-b5b69a065d4

Giving copy_if failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered

Have also tried rmm.mr.set_current_device_resource(rmm.mr.ManagedMemoryResource())

Does cudf.read_csv does not handle memory over subscription ?

If possible how to enable the setting?

**Comment by beckernick** [comment]
Dask cuDF will spill from GPU to CPU memory during dataframe operations by default. The threshold for spilling can be configured by using the `device_memory_limit` parameter as you're doing. Dask likely cannot spill cuGraph operations with the default configuration.

It sounds like you are trying to use Dask with cuDF and cuGraph and running into issues related to processing large graphs with cuGraph. As a result, I'm going to transfer this issue to the cuGraph repository.

If possible, please provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). This will make it much easier for folks to understand what you're trying to do and provide guidance.

**Comment by rlratzel** [comment]
@Ankitkurani1997 , I was able to reproduce your problem using your code snippet.  I made a few minor changes to it and was able to get it to work, see below:

```python
import dask
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
import dask_cudf
import cugraph
import cugraph.dask as dask_cugraph
from cugraph.dask.common.mg_utils import get_visible_devices
from cugraph.dask.comms import comms as Comms

csv_file_name = "twitter-2010.csv"

if __name__ == "__main__":
    with dask.config.set(jit_unspill=True):
        with LocalCUDACluster(n_workers=1, device_memory_limit="1GB") as cluster:
            with Client(cluster) as client:
                client.wait_for_workers(len(get_visible_devices()))
                Comms.initialize(p2p=True)
                ddf = dask_cudf.read_csv(csv_file_name, delimiter=' ', names=['src', 'dst'], dtype=['int32', 'int32'])
                G = cugraph.Graph(directed=True)
                G.from_dask_cudf_edgelist(ddf, source='src', destination='dst')
                print(ddf.head())
```

The extra code needed was the `wait_for_workers()` call and the `Comms.initialize(p2p=True)` call.  Unfortunately, I don't think the `Comms` object will get cleaned up upon exit of the context manager (this would a nice enhancement for us to make), so you'll have to call
```
Comms.destroy()
```
separately after exiting the context.

> My question is can I directly use dask_cudf dataframe to perform operations directly on the algorithms provided by cugraph or...

The Graph you created and populated with `from_dask_cudf_edgelist()` is all you should need for calling our `cugraph.dask` algos - you simply pass it as the first arg to those algos in the `cugraph.dask` package. The results returned will be `dask_cudf` DataFrames instead of `cudf` DataFrames, but otherwise our single-GPU and multi-GPU algos are intended to be pretty close in their usage.
