### ISSUE TITLE
[BUG] semantic mismatch for Int64 and int64

### ISSUE THREAD

**Issue by mattf** [rapidsai/cudf#11976]
**Describe the bug**
rewriting code from pandas to cudf, using `import cudf as pd`

**Steps/Code to reproduce bug**

```
$ python
Python 3.9.13 (main, May 18 2022, 00:00:00) 
[GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas, cudf

>>> pandas.__version__
'1.5.1'

>>> cudf.__version__
'22.10.00a+392.g1558403753'

>>> pandas.Series([1, None], dtype="Int64")
0       1
1    <NA>
dtype: Int64

>>> pandas.Series([1, None], dtype="int64")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.9/site-packages/pandas/core/series.py", line 470, in __init__
    data = sanitize_array(data, index, dtype, copy)
  File ".../python3.9/site-packages/pandas/core/construction.py", line 622, in sanitize_array
    subarr = _try_cast(data, dtype, copy, raise_cast_failure)
  File ".../python3.9/site-packages/pandas/core/construction.py", line 835, in _try_cast
    subarr = maybe_cast_to_integer_array(arr, dtype)
  File ".../python3.9/site-packages/pandas/core/dtypes/cast.py", line 1834, in maybe_cast_to_integer_array
    casted = np.array(arr, dtype=dtype, copy=copy)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

>>> cudf.Series([1, None], dtype="Int64")
Traceback (most recent call last):
  File ".../python3.9/site-packages/cudf/core/column/column.py", line 2038, in as_column
    memoryview(arbitrary), dtype=dtype, nan_as_null=nan_as_null
TypeError: memoryview: a bytes-like object is required, not 'list'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File ".../python3.9/site-packages/cudf/core/column/column.py", line 2127, in as_column
    np_type = np.dtype(dtype).type
TypeError: data type 'Int64' not understood
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File ".../python3.9/site-packages/cudf/core/column/column.py", line 2199, in _construct_array
    arbitrary = cupy.asarray(arbitrary, dtype=dtype)
  File ".../python3.9/site-packages/cupy/_creation/from_data.py", line 76, in asarray
    return _core.array(a, dtype, False, order)
  File "cupy/_core/core.pyx", line 2266, in cupy._core.core.array
  File "cupy/_core/core.pyx", line 2290, in cupy._core.core.array
  File "cupy/_core/core.pyx", line 2415, in cupy._core.core._array_default
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.9/site-packages/nvtx/nvtx.py", line 101, in inner
    result = func(*args, **kwargs)
  File ".../python3.9/site-packages/cudf/core/series.py", line 536, in __init__
    data = column.as_column(data, nan_as_null=nan_as_null, dtype=dtype)
  File ".../python3.9/site-packages/cudf/core/column/column.py", line 2184, in as_column
    _construct_array(arbitrary, dtype),
  File ".../python3.9/site-packages/cudf/core/column/column.py", line 2212, in _construct_array
    arbitrary = np.asarray(
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

>>> cudf.Series([1, None], dtype="int64")
0       1
1    <NA>
dtype: int64

```

**Expected behavior**
matching behavior for `Int64` and `int64`

ref https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html and https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes

**Comment by vyasr** [comment]
This is fixed on the latest versions of cudf:
```
❯ python
Python 3.13.5 | packaged by conda-forge | (main, Jun 16 2025, 08:27:50) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf
>>> cudf.Series([1, None], dtype="Int64")
0       1
1    <NA>
dtype: int64
>>> cudf.Series([1, None], dtype="int64")
0       1
1    <NA>
dtype: int64
>>> cudf.__version__
'25.10.00'
```
