### ISSUE TITLE
[BUG] instructions on pypi.org direct users to the incorrect package

### ISSUE THREAD

**Issue by mattf** [rapidsai/cudf#12071]
**Steps/Code to reproduce bug**
```
$ pip --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

$ pip install nvidia-cudf-cu11
Collecting nvidia-cudf-cu11
  Downloading nvidia-cudf-cu11-0.0.1.dev5.tar.gz (8.2 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dk2q347e/nvidia-cudf-cu11/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dk2q347e/nvidia-cudf-cu11/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-dk2q347e/nvidia-cudf-cu11/pip-egg-info
         cwd: /tmp/pip-install-dk2q347e/nvidia-cudf-cu11/
    Complete output (16 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dk2q347e/nvidia-cudf-cu11/setup.py", line 152, in <module>
        raise RuntimeError(open("ERROR.txt", "r").read())
    RuntimeError:  ###########################################################################################
    The package you are trying to install is only a placeholder project on PyPI.org repository.
    This package is hosted on NVIDIA Python Package Index.
    This package can be installed as:
    ```
    $ pip install nvidia-pyindex
    $ pip install nvidia-cudf-cu11
    ```
###########################################################################################
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

$ pip install nvidia-pyindex  
Collecting nvidia-pyindex
  Downloading nvidia-pyindex-1.0.9.tar.gz (10 kB)
Building wheels for collected packages: nvidia-pyindex
  Building wheel for nvidia-pyindex (setup.py) ... done
  Created wheel for nvidia-pyindex: filename=nvidia_pyindex-1.0.9-py3-none-any.whl size=8398 sha256=eb8351cd5e0707cae221507f3c89a29aeeaf456c4f4e97e7ab086760c69d2b67
  Stored in directory: /root/.cache/pip/wheels/e0/c2/fb/5cf4e1cfaf28007238362cb746fb38fc2dd76348331a748d54
Successfully built nvidia-pyindex
Installing collected packages: nvidia-pyindex
Successfully installed nvidia-pyindex-1.0.9

$ pip install nvidia-cudf-cu11
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'pypi.ngc.nvidia.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Collecting nvidia-cudf-cu11
  Downloading nvidia-cudf-cu11-0.0.1.dev5.tar.gz (8.2 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6m3c60ed/nvidia-cudf-cu11/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6m3c60ed/nvidia-cudf-cu11/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-6m3c60ed/nvidia-cudf-cu11/pip-egg-info
         cwd: /tmp/pip-install-6m3c60ed/nvidia-cudf-cu11/
    Complete output (16 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6m3c60ed/nvidia-cudf-cu11/setup.py", line 152, in <module>
        raise RuntimeError(open("ERROR.txt", "r").read())
    RuntimeError:    ###########################################################################################
    The package you are trying to install is only a placeholder project on PyPI.org repository.
    This package is hosted on NVIDIA Python Package Index.
    This package can be installed as:
    ```
    $ pip install nvidia-pyindex
    $ pip install nvidia-cudf-cu11
    ```
###########################################################################################
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Expected behavior**
instructions to indicate `cudf-cu11`, instead of `nvidia-cudf-cu11`
```
$ pip install cudf-cu11
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/connectionpool.py:999: InsecureRequestWarning: Unverified HTTPS request is being made to host 'pypi.ngc.nvidia.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Collecting cudf-cu11
  Downloading https://developer.download.nvidia.com/compute/redist/cudf-cu11/cudf_cu11-22.10.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (435.2 MB)
     |████████████████████████████████| 435.2 MB 61.8 MB/s 
...
Installing collected packages: typing-extensions, pyparsing, packaging, fsspec, cachetools, numpy, cython, cuda-python, zipp, importlib-metadata, llvmlite, numba, rmm-cu11, protobuf, six, python-dateutil, pytz, pandas, cubinlinker-cu11, fastrlock, cupy-cuda115, nvtx, pyarrow, ptxcompiler-cu11, cudf-cu11
Successfully installed cachetools-5.2.0 cubinlinker-cu11-0.3.0 cuda-python-11.7.0 cudf-cu11-22.10.0 cupy-cuda115-10.6.0 cython-0.29.32 fastrlock-0.8.1 fsspec-2022.10.0 importlib-metadata-5.0.0 llvmlite-0.39.1 numba-0.56.4 numpy-1.23.4 nvtx-0.2.5 packaging-21.3 pandas-1.5.1 protobuf-3.20.3 ptxcompiler-cu11-0.7.0 pyarrow-9.0.0 pyparsing-3.0.9 python-dateutil-2.8.2 pytz-2022.6 rmm-cu11-22.10.0 six-1.16.0 typing-extensions-4.4.0 zipp-3.10.0
```

**Comment by mattf** [comment]
cc @jarmak-nv

**Comment by jarmak-nv** [comment]
Hey @mattf - yeah this is a known issue and is on our radar. The pip wheels are still in experimental stages and we haven't finalized the message in the placeholders (those messages are pretty out of date).

We're also not going to push users to install `nvidia-pyindex` any more, so the correct command will be `pip install cudf-cu11 --extra-index-url=https://pypi.ngc.nvidia.com`

[rapids.ai/pip](https://rapids.ai/pip) describes the correct installation method, and we're working on updating the existing placeholders to direct people to the correct method (you'd need to upgrade pip as well based on the above output, as mentioned in the pip install page).

**Comment by bdice** [comment]
I think this is fixed. I get the following output:

```bash
$ pip install cudf-cu11
Collecting cudf-cu11
  Downloading cudf_cu11-23.4.1.tar.gz (6.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ml5zwi9w/cudf-cu11_ba9605605fd34da7a8518bed44b2df6c/setup.py", line 137, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      This package is hosted on NVIDIA Python Package Index.
      
      This package can be installed as:
      ```
      $ pip install --extra-index-url https://pypi.nvidia.com cudf_cu11
      ```
      ###########################################################################################
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
