### ISSUE TITLE
cannot load library libcudf.so due to libNVStrings.so: undefined symbol

### ISSUE THREAD

**Issue by alexqdh** [rapidsai/cudf#1231]
**Describe the bug**
Install cudf from pip, and it failed when I import cudf
Following is the detail：
cudf-cuda100-0.5.1
nvstrings         0.3.0.post1
nvstrings-cuda100 0.3.0.post1
pyarrow-0.12.0
python36
cuda10

**Steps/Code to reproduce bug**
```
>>> import cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/cudf/__init__.py", line 2, in <module>
    from cudf import dataframe
  File "/usr/local/lib/python3.6/site-packages/cudf/dataframe/__init__.py", line 1, in <module>
    from cudf.dataframe import (buffer, dataframe, series,
  File "/usr/local/lib/python3.6/site-packages/cudf/dataframe/dataframe.py", line 21, in <module>
    from cudf import formatting, _gdf
  File "/usr/local/lib/python3.6/site-packages/cudf/_gdf.py", line 13, in <module>
    from libgdf_cffi import ffi, libgdf
  File "/usr/local/lib/python3.6/site-packages/libgdf_cffi/__init__.py", line 35, in <module>
    libgdf_api = ffi.dlopen(_get_lib_name())
OSError: cannot load library '/usr/local/lib/python3.6/site-packages/libcudf.so': /usr/local/lib/python3.6/site-packages/libNVStrings.so: undefined symbol: _ZN3rmm6Logger6recordENS0_10MemEvent_tEiPvNSt6chrono10time_pointINS3_3_V212system_clockENS3_8durationIlSt5ratioILl1ELl1000000000EEEEEESB_mmmP11CUstream_stNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj
```

**Comment by kkraus14** [comment]
This will be resolved in the 0.6 release, it's grabbing too new of a version of NVStrings currently.

**Comment by harrism** [comment]
@kkraus14 is this fixed?

**Comment by kkraus14** [comment]
This is resolved.
