### ISSUE TITLE
[BUG] error using %W in cudf.to_datetime

### ISSUE THREAD

**Issue by mattf** [rapidsai/cudf#12419]
**Is your feature request related to a problem? Please describe.**
rewriting code with `import cudf as pd`

https://docs.rapids.ai/api/cudf/stable/api_docs/api/cudf.to_datetime.html
```
The strftime to parse time, eg “%d/%m/%Y”, note that “%f” will parse all the way up to nanoseconds. See strftime documentation for more information on choices: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior.
```

https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior
```
%W | Week number of the year (Monday as the first day of the week) as a zero-padded decimal number. All days in a new year preceding the first Monday are considered to be in week 0. | 00, 01, …, 53
```

**Describe the solution you'd like**
same result for `cudf.to_datetime` as `pandas.to_datetime`
```
>>> import cudf as pd
>>> pd.__version__
'22.12.01'
>>> df = pd.DataFrame({'a': ['2012015','2012045','2012495','2012525']})
>>> pd.to_datetime(df.a, format=('%Y%W%w'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.8/site-packages/cudf/core/tools/datetimes.py", line 272, in to_datetime
    raise e
  File ".../python3.8/site-packages/cudf/core/tools/datetimes.py", line 248, in to_datetime
    col = _process_col(
  File ".../python3.8/site-packages/cudf/core/tools/datetimes.py", line 358, in _process_col
    col = col.as_datetime_column(
  File ".../python3.8/site-packages/cudf/core/column/string.py", line 5435, in as_datetime_column
    return self._as_datetime_or_timedelta_column(out_dtype, format)
  File ".../python3.8/site-packages/cudf/core/column/string.py", line 5405, in _as_datetime_or_timedelta_column
    result_col = casting_func(self, dtype, format)
  File "string_casting.pyx", line 564, in cudf._lib.string_casting.timestamp2int
RuntimeError: cuDF failure at: /workspace/.conda-bld/work/cpp/src/strings/convert/convert_datetime.cu:152: invalid format specifier: W

>>> import pandas
>>> pandas.__version__
'1.2.2'
>>> pandas.to_datetime(df.to_pandas().a, format=('%Y%W%w'))
0   2012-01-06
1   2012-01-27
2   2012-12-07
3   2012-12-28
Name: a, dtype: datetime64[ns]
```

**Comment by davidwendt** [comment]
For reference, the libcudf `cudf::strings::to_timestamps` function only supports the following format specifiers: https://docs.rapids.ai/api/libcudf/stable/group__strings__convert.html#gafe1551d734ca34da4831fb112f16a06d

**Comment by mattf** [comment]
also running into missing %b

**Comment by davidwendt** [comment]
> also running into missing %b

Recommend opening a separate, single issue for locale-specific format specifiers: `%a, %A, %b, %B, %c, %x, %X`
These will likely not be supported so it would be good to have them called out separate from this issue.
