### ISSUE TITLE
[BUG] cannot append/contact DataFrames with mismatched index

### ISSUE THREAD

**Issue by mattf** [rapidsai/cudf#12420]
**Describe the bug**
writing code with `import cudf as pd`

**Steps/Code to reproduce bug**
```
>>> import cudf as pd
>>> import pandas
>>> pd.__version__
'22.12.01'
>>> pandas.__version__
'1.2.2'

>>> x = pd.DataFrame({'a': range(0,10)})
>>> y = pd.DataFrame({'b': range(10,20)})

>>> x.index = x.index.astype(str)

>>> x.info()
<class 'cudf.core.dataframe.DataFrame'>
StringIndex: 10 entries, 0 to 9
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       10 non-null     int64
dtypes: int64(1)
memory usage: 134.0+ bytes
>>> y.info()
<class 'cudf.core.dataframe.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   b       10 non-null     int64
dtypes: int64(1)
memory usage: 80.0 bytes

>>> x.to_pandas().info()
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 9
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       10 non-null     int64
dtypes: int64(1)
memory usage: 160.0+ bytes
>>> y.to_pandas().info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   b       10 non-null     int64
dtypes: int64(1)
memory usage: 208.0 bytes

>>> pandas.concat([x.to_pandas(),y.to_pandas()])
     a     b
0  0.0   NaN
1  1.0   NaN
2  2.0   NaN
3  3.0   NaN
4  4.0   NaN
...
5  NaN  15.0
6  NaN  16.0
7  NaN  17.0
8  NaN  18.0
9  NaN  19.0

>>> pd.concat([x,y])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.8/site-packages/cudf/core/reshape.py", line 399, in concat
    result = cudf.DataFrame._concat(
  File ".../python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File ".../python3.8/site-packages/cudf/core/dataframe.py", line 1618, in _concat
    categories = _find_common_dtypes_and_categories(non_null_cols, dtypes)
  File ".../python3.8/site-packages/cudf/core/dataframe.py", line 7646, in _find_common_dtypes_and_categories
    raise ValueError("All columns must be the same type")
ValueError: All columns must be the same type
```

**Expected behavior**
same behavior for `cudf` as `pandas`

**Note**: _All **columns**_ in the error makes this a difficult error to track down

**Comment by shwina** [comment]
This is a wontfix, unfortunately. Since we don't have a true `"object"` data type like Pandas, we can't resolve `str` and `int64` to a common data type. The best we can do is throw an error.
