### ISSUE TITLE
[FEA] Allow user to control "not null" constraint on Parquet columns

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#12702]
Related to https://github.com/dask/dask/issues/9920, but with a slightly different (and less helpful) error:
```
RuntimeError: CUDF failure at: /opt/conda/conda-bld/work/cpp/src/io/parquet/reader_impl_helpers.cpp:265: All sources must have the same schema
```

When writing null data separately from non-null data w/ dask-cudf, the Parquet files for non-null data will have `not null` contraints. This means Dask (and other systems) can't read them well.

Reproducer to highlight the problem:
```
>>> import cudf                                                                                                                                                                                      
>>> df = cudf.DataFrame({"id": [0, 1, 2]})                                                        
>>> df.to_parquet("test/no_nulls.parquet")                                                                                                                                                           
>>> df = cudf.DataFrame({"id": [0, 1, None]})
>>> df.to_parquet("test/nulls.parquet")                                                                                                                                                              
>>> import dask.dataframe as dd
>>> ddf = dd.read_parquet("test", split_row_groups=100, aggregate_files=True)

>>> len(ddf)                                                                                                                                                                                 [2/9174]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/dataframe/core.py", line 4592, in __len__
    return len(s)
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/dataframe/core.py", line 720, in __len__
    return self.reduction(
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/base.py", line 314, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/base.py", line 599, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/threaded.py", line 89, in get
    results = get_async(
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/local.py", line 511, in get_async
    raise_exception(exc, tb)
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/local.py", line 319, in reraise
    raise exc
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/core.py", line 113, in _execute_task
    return [_execute_task(a, cache) for a in arg] 
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/core.py", line 113, in <listcomp>
    return [_execute_task(a, cache) for a in arg] 
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/dataframe/io/parquet/core.py", line 97, in __call__
    return read_parquet_part(
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/dataframe/io/parquet/core.py", line 659, in read_parquet_part
    df = engine.read_partition(
  File "/raid/rgelhausen/conda/envs/pynds/lib/python3.9/site-packages/dask/dataframe/io/parquet/arrow.py", line 537, in read_partition
    arrow_table = pa.concat_tables(tables)
  File "pyarrow/table.pxi", line 5139, in pyarrow.lib.concat_tables
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Schema at index 1 was different: 
id: int64 not null
vs
id: int64
```

**Comment by rjzamora** [comment]
Thanks for raising tis @randerzander !  Since using "not null" doesn't seem to trip up pyarrow, I think another possible solution here would be to handle multi-file reads in `cudf.read_parquet` where the schema inconsistency is related to "not null." (It seems like cudf should be able to cast "not null" columns to be nullable when not **all** concatenated row-groups share that property)

**Comment by vuule** [comment]
It seems to me that controlling nullability in parquet writer is a workaround for the inability to concatenate columns of different nullability.
If possible, adding this capability to cudf could be a better solution.
I'm okay with the parquet writer change if it's the only option ATM.

**Comment by GregoryKimball** [comment]
@SrikarVanavasam - we were talking with @nvdbaranec about solving this issue by adding a parquet reader option to treat all columns an nullable. Would you please take a look? Thank you for your help 😊

**Comment by SrikarVanavasam** [comment]
> @SrikarVanavasam - we were talking with @nvdbaranec about solving this issue by adding a parquet reader option to treat all columns an nullable. Would you please take a look? Thank you for your help 😊

Yup, I can certainly work on it!

**Comment by vuule** [comment]
do we want an option to select which column should be read as nullable, or specifically the option to treat ALL columns as nullable?
Maybe we can start with ALL, and add more granular option if/when we have solid schema support in the reader APIs.

**Comment by GregoryKimball** [comment]
We have a writer option to control nullability in https://github.com/rapidsai/cudf/pull/12933, @randerzander should we keep this issue open?

**Comment by GregoryKimball** [comment]
I believe this is solved for now. If we want to consider follow-on reader changes, let's please open a new issue.
