### ISSUE TITLE
[BUG] NA handling inconsistent in DataFrame/Series.replace

### ISSUE THREAD

**Issue by mattf** [rapidsai/cudf#12720]
**Describe the bug**
working with `import cudf as pd`

**Steps/Code to reproduce bug**
```
>>> import cudf, pandas, numpy
>>> cudf.__version__
'23.02.00a+310.g58e0fde346'
>>> pandas.__version__
'1.5.3'

>>> cudf.Series([1, 2, numpy.nan]).replace(numpy.nan, -1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/rapids/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/series.py", line 2180, in replace
    return super().replace(to_replace, value, *args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/indexed_frame.py", line 765, in replace
    copy_data[name] = col.find_and_replace(
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/numerical.py", line 483, in find_and_replace
    to_replace_col = _normalize_find_and_replace_input(
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/numerical.py", line 771, in _normalize_find_and_replace_input
    col_to_normalize_casted = input_column_dtype.type(
ValueError: cannot convert float NaN to integer
>>> pandas.Series([1, 2, numpy.nan]).replace(numpy.nan, -1)
0    1.0
1    2.0
2   -1.0
dtype: float64
```

**Comment by galipremsagar** [comment]
The above issue is now resolved in `cudf.pandas` or using `cudf` directly with `pandas.compatible` option turned on:

```
In [6]: cudf.set_option("mode.pandas_compatible", True)

In [7]: cudf.Series([1, 2, numpy.nan]).replace(numpy.nan, -1)
Out[7]: 
0    1.0
1    2.0
2   -1.0
dtype: float64
```
