### ISSUE TITLE
[BUG] Pip install cudf-cu11 failed on Azure/AWS Databricks cluster

### ISSUE THREAD

**Issue by NvTimLiu** [rapidsai/cudf#12772]
**Describe the bug**

Following : https://rapids.ai/pip.html#install

On Azure Databricks cluster, pip install install cudf-cu11 , got below failures:

```
sudo pip install cudf-cu11 dask-cudf-cu11 --extra-index-url=https://pypi.ngc.nvidia.com

Collecting cudf-cu11
  Downloading cudf_cu11-23.2.0.tar.gz (6.5 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1kkb_653/cudf-cu11_11988a2fcb1740938689629c6c54896d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1kkb_653/cudf-cu11_11988a2fcb1740938689629c6c54896d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-7or11xxq
         cwd: /tmp/pip-install-1kkb_653/cudf-cu11_11988a2fcb1740938689629c6c54896d/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1kkb_653/cudf-cu11_11988a2fcb1740938689629c6c54896d/setup.py", line 137, in <module>
        raise RuntimeError(open("ERROR.txt", "r").read())
    FileNotFoundError: [Errno 2] No such file or directory: 'ERROR.txt'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/58/b2/0a5e5c63e95ff7cf500ec2c6b289e9eb45143699778d1b4b05ae962946c4/cudf_cu11-23.2.0.tar.gz#sha256=b233ed5668f5f643afd30b49a75bfa876b73a912ad1274ed0ff438b900f3bb39 (from https://pypi.org/simple/cudf-cu11/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

......

uccessfully installed MarkupSafe-2.1.2 cachetools-5.3.0 click-8.1.3 cloudpickle-2.2.1 cubinlinker-cu11-0.3.0.post1 cuda-python-11.8.1 cudf-cu11-22.12.0 cupy-cuda11x-11.5.0 cython-0.29.33 dask-2022.11.1 dask-cudf-cu11-22.12.0.post1 distributed-2022.11.1 fastrlock-0.8.1 fsspec-2023.1.0 heapdict-1.0.1 importlib-metadata-6.0.0 jinja2-3.1.2 llvmlite-0.39.1 locket-1.0.0 msgpack-1.0.4 numba-0.56.4 numpy-1.23.5 nvtx-0.2.5 packaging-23.0 pandas-1.5.3 partd-1.3.0 protobuf-3.20.3 psutil-5.9.4 ptxcompiler-cu11-0.7.0.post1 pyarrow-9.0.0 python-dateutil-2.8.2 pytz-2022.7.1 pyyaml-6.0 rmm-cu11-22.12.0 sortedcontainers-2.4.0 tblib-1.7.0 toolz-0.12.0 tornado-6.1 typing-extensions-4.4.0 zict-2.2.0 zipp-3.13.0


```

After pip installing, python import cudf got below errors:

```
$ python -c "import pyspark"   
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pyspark'
ubuntu@0214-081006-br1u8hyd-10-2-128-4:~$ python -c "import cudf"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/cudf/__init__.py", line 5, in <module>
    validate_setup()
  File "/usr/local/lib/python3.8/dist-packages/cudf/utils/gpu_utils.py", line 95, in validate_setup
    cuda_runtime_version = runtimeGetVersion()
  File "/usr/local/lib/python3.8/dist-packages/rmm/_cuda/gpu.py", line 87, in runtimeGetVersion
    major, minor = numba.cuda.runtime.get_version()
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cudadrv/runtime.py", line 111, in get_version
    self.cudaRuntimeGetVersion(ctypes.byref(rtver))
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cudadrv/runtime.py", line 65, in __getattr__
    self._initialize()
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cudadrv/runtime.py", line 51, in _initialize
    self.lib = open_cudalib('cudart')
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cudadrv/libs.py", line 59, in open_cudalib
    path = get_cudalib(lib)
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cudadrv/libs.py", line 51, in get_cudalib
    libdir = get_cuda_paths()['cudalib_dir'].info
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cuda_paths.py", line 159, in get_cuda_paths
    'libdevice': _get_libdevice_paths(),
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cuda_paths.py", line 59, in _get_libdevice_paths
    candidates = find_file(re.compile(pat), libdir)
  File "/databricks/python3/lib/python3.8/site-packages/numba/misc/findlib.py", line 56, in find_file
    entries = os.listdir(ldir)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/cuda/nvvm/libdevice'
ubuntu@0214-081006-br1u8hyd-10-2-128-4:~$

```

**Steps/Code to reproduce bug**
1, create a DB cluster with below config
```
{
    "num_workers": 0,
    "cluster_name": "TEST-AZURE-DB-10.4",
    "spark_version": "10.4.x-gpu-ml-scala2.12",
    "spark_conf": {
        "spark.master": "local[*, 4]",
        "spark.databricks.cluster.profile": "singleNode"
    },
    "azure_attributes": {
        "first_on_demand": 1,
        "availability": "ON_DEMAND_AZURE",
        "spot_bid_max_price": -1
    },
    "node_type_id": "Standard_NC6s_v3",
    "driver_node_type_id": "Standard_NC6s_v3",
    "ssh_public_keys": [],
    "custom_tags": {
        "ResourceClass": "SingleNode"
    },
    "spark_env_vars": {},
    "autotermination_minutes": 120,
    "enable_elastic_disk": true,
    "cluster_source": "UI",
    "init_scripts": [],
    "single_user_name": "timl@nvidia.com",
    "data_security_mode": "LEGACY_SINGLE_USER_STANDARD",
    "runtime_engine": "STANDARD"
}
```
2, pip install cudf-cu11 on the Azure Databricks cluster.
```
pip install cudf-cu11 dask-cudf-cu11 --extra-index-url=https://pypi.ngc.nvidia.com
```

3, After pip installing, run below command
```
$ python -c "import cudf"
--------------------------------below errors reported on Databricks cluster------------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/cudf/__init__.py", line 5, in <module>
    validate_setup()
  File "/usr/local/lib/python3.8/dist-packages/cudf/utils/gpu_utils.py", line 95, in validate_setup
    cuda_runtime_version = runtimeGetVersion()
  File "/usr/local/lib/python3.8/dist-packages/rmm/_cuda/gpu.py", line 87, in runtimeGetVersion
    major, minor = numba.cuda.runtime.get_version()
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cudadrv/runtime.py", line 111, in get_version
    self.cudaRuntimeGetVersion(ctypes.byref(rtver))
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cudadrv/runtime.py", line 65, in __getattr__
    self._initialize()
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cudadrv/runtime.py", line 51, in _initialize
    self.lib = open_cudalib('cudart')
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cudadrv/libs.py", line 59, in open_cudalib
    path = get_cudalib(lib)
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cudadrv/libs.py", line 51, in get_cudalib
    libdir = get_cuda_paths()['cudalib_dir'].info
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cuda_paths.py", line 159, in get_cuda_paths
    'libdevice': _get_libdevice_paths(),
  File "/databricks/python3/lib/python3.8/site-packages/numba/cuda/cuda_paths.py", line 59, in _get_libdevice_paths
    candidates = find_file(re.compile(pat), libdir)
  File "/databricks/python3/lib/python3.8/site-packages/numba/misc/findlib.py", line 56, in find_file
    entries = os.listdir(ldir)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/cuda/nvvm/libdevice'

```

**Expected behavior**
Successfully install cudf-cu11 on Databricks cluster.

**Environment overview (please complete the following information)**
 - Azure/AWS Databricks cluster
 - sudo pip install cudf-cu11 dask-cudf-cu11 --extra-index-url=https://pypi.ngc.nvidia.com
   - none

**Environment details**
```
$ . print_env.sh
<details><summary>Click here to see environment details</summary><pre>

     **git***
     Not inside a git repository

     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=20.04
     DISTRIB_CODENAME=focal
     DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
     NAME="Ubuntu"
     VERSION="20.04.5 LTS (Focal Fossa)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 20.04.5 LTS"
     VERSION_ID="20.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=focal
     UBUNTU_CODENAME=focal
     Linux 0214-093925-4etwry3h-10-2-128-4 5.4.0-1100-azure #106~18.04.1-Ubuntu SMP Mon Dec 12 21:49:35 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

     ***GPU Information***
     Tue Feb 14 10:06:05 2023
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.4     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  Tesla V100-PCIE...  Off  | 00000001:00:00.0 Off |                  Off |
     | N/A   29C    P0    24W / 250W |      0MiB / 16160MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+

     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+

     ***CPU***
     Architecture:                    x86_64
     CPU op-mode(s):                  32-bit, 64-bit
     Byte Order:                      Little Endian
     Address sizes:                   46 bits physical, 48 bits virtual
     CPU(s):                          6
     On-line CPU(s) list:             0-5
     Thread(s) per core:              1
     Core(s) per socket:              6
     Socket(s):                       1
     NUMA node(s):                    1
     Vendor ID:                       GenuineIntel
     CPU family:                      6
     Model:                           79
     Model name:                      Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
     Stepping:                        1
     CPU MHz:                         2593.992
     BogoMIPS:                        5187.98
     Hypervisor vendor:               Microsoft
     Virtualization type:             full
     L1d cache:                       192 KiB
     L1i cache:                       192 KiB
     L2 cache:                        1.5 MiB
     L3 cache:                        35 MiB
     NUMA node0 CPU(s):               0-5
     Vulnerability Itlb multihit:     KVM: Vulnerable
     Vulnerability L1tf:              Mitigation; PTE Inversion
     Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
     Vulnerability Meltdown:          Mitigation; PTI
     Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
     Vulnerability Retbleed:          Not affected
     Vulnerability Spec store bypass: Vulnerable
     Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
     Vulnerability Spectre v2:        Mitigation; Retpolines, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
     Vulnerability Srbds:             Not affected
     Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT Host state unknown
     Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt md_clear

     ***CMake***
     /usr/bin/cmake
     cmake version 3.16.3

     CMake suite maintained and supported by Kitware (kitware.com/cmake).

     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
     Copyright (C) 2019 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


     ***nvcc***

     ***Python***
     /databricks/python3/bin/python
     Python 3.8.10

     ***Environment Variables***
     PATH                            : /databricks/python3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    :
     PYTHON_PATH                     :

     conda not found
     ***pip packages***
     /databricks/python3/bin/pip
     Package                      Version
     ---------------------------- -------------------
     absl-py                      0.11.0
     appdirs                      1.4.4
     argon2-cffi                  20.1.0
     astor                        0.8.1
     astunparse                   1.6.3
     async-generator              1.10
     attrs                        20.3.0
     backcall                     0.2.0
     bcrypt                       3.2.0
     bidict                       0.21.4
     bleach                       3.3.0
     blis                         0.7.4
     boto3                        1.16.7
     botocore                     1.19.7
     cachetools                   4.2.4
     catalogue                    2.0.6
     certifi                      2020.12.5
     cffi                         1.14.5
     chardet                      4.0.0
     click                        7.1.2
     cloudpickle                  1.6.0
     cmdstanpy                    0.9.68
     configparser                 5.0.1
     convertdate                  2.3.2
     cryptography                 3.4.7
     cubinlinker-cu11             0.3.0.post1
     cuda-python                  11.8.1
     cudf-cu11                    22.12.0
     cupy-cuda11x                 11.5.0
     cycler                       0.10.0
     cymem                        2.0.5
     Cython                       0.29.23
     dask                         2022.11.1
     dask-cudf-cu11               22.12.0.post1
     databricks-automl-runtime    0.2.6.4
     databricks-cli               0.16.3
     dbl-tempo                    0.1.2
     dbus-python                  1.2.16
     decorator                    5.0.6
     defusedxml                   0.7.1
     dill                         0.3.2
     diskcache                    5.2.1
     distlib                      0.3.4
     distributed                  2022.11.1
     distro                       1.4.0
     distro-info                  0.23ubuntu1
     entrypoints                  0.3
     ephem                        4.1.3
     facets-overview              1.0.0
     fastrlock                    0.8.1
     fasttext                     0.9.2
     filelock                     3.0.12
     Flask                        1.1.2
     flatbuffers                  2.0
     fsspec                       0.9.0
     future                       0.18.2
     gast                         0.4.0
     gitdb                        4.0.7
     GitPython                    3.1.12
     google-auth                  1.22.1
     google-auth-oauthlib         0.4.2
     google-pasta                 0.2.0
     grpcio                       1.39.0
     gunicorn                     20.0.4
     gviz-api                     1.10.0
     h5py                         3.1.0
     HeapDict                     1.0.1
     hijri-converter              2.2.3
     holidays                     0.12
     horovod                      0.23.0
     htmlmin                      0.1.12
     huggingface-hub              0.1.2
     idna                         2.10
     ImageHash                    4.2.1
     imbalanced-learn             0.8.1
     importlib-metadata           3.10.0
     ipykernel                    5.3.4
     ipython                      7.22.0
     ipython-genutils             0.2.0
     ipywidgets                   7.6.3
     isodate                      0.6.0
     itsdangerous                 1.1.0
     jedi                         0.17.2
     Jinja2                       2.11.3
     jmespath                     0.10.0
     joblib                       1.0.1
     joblibspark                  0.3.0
     jsonschema                   3.2.0
     jupyter-client               6.1.12
     jupyter-core                 4.7.1
     jupyterlab-pygments          0.1.2
     jupyterlab-widgets           1.0.0
     keras                        2.8.0
     Keras-Preprocessing          1.1.2
     kiwisolver                   1.3.1
     koalas                       1.8.2
     korean-lunar-calendar        0.2.1
     langcodes                    3.3.0
     libclang                     13.0.0
     lightgbm                     3.3.2
     llvmlite                     0.38.0
     locket                       1.0.0
     LunarCalendar                0.0.9
     Mako                         1.1.3
     Markdown                     3.3.3
     MarkupSafe                   2.0.1
     matplotlib                   3.4.2
     missingno                    0.5.1
     mistune                      0.8.4
     mleap                        0.18.1
     mlflow-databricks-artifacts  2.0.0
     mlflow-skinny                1.24.0
     msgpack                      1.0.4
     multimethod                  1.7
     murmurhash                   1.0.5
     nbclient                     0.5.3
     nbconvert                    6.0.7
     nbformat                     5.1.3
     nest-asyncio                 1.5.1
     networkx                     2.5
     nltk                         3.6.1
     notebook                     6.3.0
     numba                        0.55.1
     numpy                        1.20.1
     nvtx                         0.2.5
     oauthlib                     3.1.0
     opt-einsum                   3.3.0
     packaging                    21.3
     pandas                       1.2.4
     pandas-profiling             3.1.0
     pandocfilters                1.4.3
     paramiko                     2.7.2
     parso                        0.7.0
     partd                        1.3.0
     pathy                        0.6.0
     patsy                        0.5.1
     petastorm                    0.11.4
     pexpect                      4.8.0
     phik                         0.12.0
     pickleshare                  0.7.5
     Pillow                       8.2.0
     pip                          21.0.1
     plotly                       5.5.0
     pmdarima                     1.8.4
     preshed                      3.0.5
     prompt-toolkit               3.0.17
     prophet                      1.0.1
     protobuf                     3.17.2
     psutil                       5.8.0
     psycopg2                     2.8.5
     ptxcompiler-cu11             0.7.0.post1
     ptyprocess                   0.7.0
     pyarrow                      4.0.0
     pyasn1                       0.4.8
     pyasn1-modules               0.2.8
     pybind11                     2.9.1
     pycparser                    2.20
     pydantic                     1.8.2
     Pygments                     2.8.1
     PyGObject                    3.36.0
     PyMeeus                      0.5.11
     PyNaCl                       1.4.0
     pyodbc                       4.0.30
     pyparsing                    2.4.7
     pyrsistent                   0.17.3
     pystan                       2.19.1.1
     python-apt                   2.0.1
     python-dateutil              2.8.1
     python-editor                1.0.4
     python-engineio              4.3.0
     python-socketio              5.4.1
     pytz                         2020.5
     PyWavelets                   1.1.1
     PyYAML                       5.4.1
     pyzmq                        20.0.0
     regex                        2021.4.4
     requests                     2.25.1
     requests-oauthlib            1.3.0
     requests-unixsocket          0.2.0
     rmm-cu11                     22.12.0
     rsa                          4.7.2
     s3transfer                   0.3.7
     sacremoses                   0.0.46
     scikit-learn                 0.24.1
     scipy                        1.6.2
     seaborn                      0.11.1
     Send2Trash                   1.5.0
     setuptools                   52.0.0
     setuptools-git               1.2
     shap                         0.40.0
     simplejson                   3.17.2
     six                          1.15.0
     slicer                       0.0.7
     smart-open                   5.2.0
     smmap                        3.0.5
     sortedcontainers             2.4.0
     spacy                        3.2.1
     spacy-legacy                 3.0.8
     spacy-loggers                1.0.1
     spark-tensorflow-distributor 1.0.0
     sqlparse                     0.4.1
     srsly                        2.4.1
     ssh-import-id                5.10
     statsmodels                  0.12.2
     tabulate                     0.8.7
     tangled-up-in-unicode        0.1.0
     tblib                        1.7.0
     tenacity                     6.2.0
     tensorboard                  2.8.0
     tensorboard-data-server      0.6.1
     tensorboard-plugin-profile   2.5.0
     tensorboard-plugin-wit       1.8.1
     tensorflow                   2.8.0
     tensorflow-estimator         2.8.0
     tensorflow-io-gcs-filesystem 0.24.0
     termcolor                    1.1.0
     terminado                    0.9.4
     testpath                     0.4.4
     tf-estimator-nightly         2.8.0.dev2021122109
     thinc                        8.0.12
     threadpoolctl                2.1.0
     tokenizers                   0.10.3
     toolz                        0.12.0
     torch                        1.10.2+cu111
     torchvision                  0.11.3+cu111
     tornado                      6.1
     tqdm                         4.59.0
     traitlets                    5.0.5
     transformers                 4.16.2
     typer                        0.3.2
     typing-extensions            3.7.4.3
     ujson                        4.0.2
     unattended-upgrades          0.1
     urllib3                      1.25.11
     virtualenv                   20.4.1
     visions                      0.7.4
     wasabi                       0.8.2
     wcwidth                      0.2.5
     webencodings                 0.5.1
     websocket-client             0.57.0
     Werkzeug                     1.0.1
     wheel                        0.36.2
     widgetsnbextension           3.5.1
     wrapt                        1.12.1
     xgboost                      1.5.2
     zict                         2.2.0
     zipp                         3.4.1
WARNING: You are using pip version 21.0.1; however, version 23.0 is available.
You should consider upgrading via the '/databricks/python3/bin/python -m pip install --upgrade pip' command.

</pre></details>

```

**Additional context**

**Comment by bdice** [comment]
@NvTimLiu Using pip wheels of cudf requires a user-installed CUDA Toolkit. Conda packages can use `cudatoolkit` from conda-forge, but pip wheels require the user to have the CUDA Toolkit installed on their system (we cannot install it for the user as a dependency). I suspect this problem because importing `cudf` fails when Numba tries to access the CUDA installation, resulting in `FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/cuda/nvvm/libdevice'`.

Additionally, the environment information for `nvcc` is blank:
```
***nvcc***

```

Please refer to the pip installation instructions for more details about the system requirements: https://rapids.ai/pip.html#install

Feel free to re-open if you have additional questions.

**Comment by tdembelova** [comment]
Hello! @NvTimLiu Did you manage to install cudf on Databricks cluster? I am also getting the same error. I tried to install cuda myself, but fails anyway...

**Comment by tdembelova** [comment]
The only thing which worked is installing using conda, but then i can not use cudf in the Databricks notebooks...

@NvTimLiu @bdice  I would be grateful if you could reopen this issue!

**Comment by vyasr** [comment]
The compiled parts of cudf in wheels do not directly require the CTK to be installed. However, cudf wheels still wind up with a transitive dependence on CTK installation via dependencies. The traceback shown here is indicating that the one that's currently failing is numba, so the question we need to answer is how to install numba with CUDA support onto Databricks. I will follow up internally to see if anyone has more information about that.

As an aside, @NvTimLiu's original example is a bit out of date, it's trying to install one of our placeholders from PyPI instead of actually pulling the built package from NVIDIA's index. The issue is that as of 23.02 the extra index URL has changed, it should be `--extra-index-url=https://pypi.nvidia.com` (note that there is no `.ngc` subdomain anymore).

**Comment by tdembelova** [comment]
@vyasr Yes, the bug from @NvTimLiu is a bit different then mine, I opened a new bug issue, please look into it: https://github.com/rapidsai/cudf/issues/12893

**Comment by vyasr** [comment]
Yup that looks like the numba issue as I described above. I'm going to close your other issue so that we can centralize discussion here.

**Comment by tdembelova** [comment]
@vyasr I actually did some experiments with installing cudatoolkit of different versions (11.3, 11.8 and 12.0 from https://developer.nvidia.com/cuda-toolkit-archive) and also setting CUDA_HOME, CUDA_PATH and LD_LIBRARY_PATH to the corresponding paths, but the exceptions changed to failures to import cupy with not being able to find `libcublas.so` and `libnvrtc.so`

**Comment by vyasr** [comment]
OK yes that makes sense. Basically cudf is built in such a way that we don't need the CTK available at runtime because we wanted to avoid these problems, but we end up stuck with them anyway because Python packages that we depend on still need the CTK (and in the case of cupy also some of the math libraries, not just the CUDA runtime). Asking around to see if anyone has experience with installing these packages on databricks.

**Comment by tdembelova** [comment]
Great! Looking for updates from your end :)

**Comment by tdembelova** [comment]
we were able to resolve the problem by installing cudatoolkit and packages cudf through pip in the init scripts of the databricks cluster.

**Comment by bdice** [comment]
@tdembelova Awesome! Thanks for the update. cc: @jacobtomlinson may want to know this. I’ll close for now, since it seems resolved, but feel free to ask if you need anything else.

**Comment by vyasr** [comment]
Thanks for letting us know @tdembelova! I haven't yet heard from anyone with this specific experience so I will let them know that this worked.
