### ISSUE TITLE
cudf.read_json returns ValueError when given file is not found

### ISSUE THREAD

**Issue by davidwendt** [rapidsai/cudf#13026]
**Describe the bug**
The `cudf.read_json` reports an incorrect error when given an invalid file path.

**Steps/Code to reproduce bug**
```
>>> import cudf
>>> df = cudf.read_json("nosuchfile.json")
/conda/envs/rapids/lib/python3.10/site-packages/cudf-23.6.0-py3.10-linux-x86_64.egg/cudf/io/json.py:121: UserWarning: Using CPU via Pandas to read JSON dataset, this may be GPU accelerated in the future
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/rapids/lib/python3.10/site-packages/cudf-23.6.0-py3.10-linux-x86_64.egg/cudf/io/json.py", line 143, in read_json
    pd_value = pd.read_json(
  File "/conda/envs/rapids/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/conda/envs/rapids/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/conda/envs/rapids/lib/python3.10/site-packages/pandas/io/json/_json.py", line 757, in read_json
    return json_reader.read()
  File "/conda/envs/rapids/lib/python3.10/site-packages/pandas/io/json/_json.py", line 915, in read
    obj = self._get_object_parser(self.data)
  File "/conda/envs/rapids/lib/python3.10/site-packages/pandas/io/json/_json.py", line 937, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/conda/envs/rapids/lib/python3.10/site-packages/pandas/io/json/_json.py", line 1064, in parse
    self._parse_no_numpy()
  File "/conda/envs/rapids/lib/python3.10/site-packages/pandas/io/json/_json.py", line 1321, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Unexpected character found when decoding 'null'
```
Using `engine="cudf"` gives the following result
```
>>> df = cudf.read_json("nosuchfile.json", engine="cudf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/rapids/lib/python3.10/site-packages/cudf-23.6.0-py3.10-linux-x86_64.egg/cudf/io/json.py", line 111, in read_json
    df = libjson.read_json(
  File "json.pyx", line 50, in cudf._lib.json.read_json
  File "json.pyx", line 138, in cudf._lib.json.read_json
RuntimeError: CUDF failure at: /cudf/cpp/src/io/json/json_column.cu:958: Input needs to be an array of arrays or an array of (nested) objects
```

I spent way too much time trying to debug my json file format until I realized I had a typo in the path name.

**Expected behavior**
The other `cudf.read_*` functions raise `FileNotFoundError` if the file cannot be found

**Comment by wence-** [comment]
This is partly a consequence of pandas api compatibility, for some reason pandas `read_json` is special compared to all other `read_XXX` functions in that the input is allowed to not just name a path or be a file-like object, but also be a "VALID json string" which is treated literally.

There have been a few discussions about this on the pandas side, see https://github.com/pandas-dev/pandas/issues/29102, a rejected PR to fix this https://github.com/pandas-dev/pandas/pull/29104, and a PR that partially fixed it https://github.com/pandas-dev/pandas/pull/46718 (by pattern-matching the input string against some subset of likely extensions that indicate a file).

I think this is a niche use-case (although happy to be corrected) and think we should go ahead and deprecate this functionality (if one wants to load json data directly from a string, it is not so difficult to wrap it in an `io.StringIO`).

I've opened https://github.com/pandas-dev/pandas/issues/52271 to see if a deprecation could be made in pandas too.

**Comment by davidwendt** [comment]
I believe `cudf.read_csv` also accepts a string as input but probably must be wrapped in `StringIO`.
It seems reasonable for us to support `read_json` in the same way.

**Comment by GregoryKimball** [comment]
It's worth pointing out that I used string input extensively in my JSON [blog post](https://developer.nvidia.com/blog/gpu-accelerated-json-data-processing-with-rapids/) and [user guide](https://docs.rapids.ai/api/cudf/stable/user_guide/io/read-json.html). 😱

**Comment by vyasr** [comment]
It looks like pandas has merged the linked PR above, so we can also stop accepting literal JSON here. @mroeschke any objections?

**Comment by mroeschke** [comment]
Agreed. `cudf.read_json` (and all other readers) should stop accepting any literal string data

**Comment by vyasr** [comment]
Cool. This should be easy enough to address, so I've marked it as a good first issue.

**Comment by lithomas1** [comment]
I'm planning on taking this issue.

Just to clarify, there should be no deprecation required, since pandas (and hence the pandas engine) already raises this error, so we can also raise in the cudf reader to align behavior with pandas, right?
