### ISSUE TITLE
[BUG] cudf not installing properly via pip (cupy/cupy-cuda error)

### ISSUE THREAD

**Issue by jared-burleson** [rapidsai/cudf#13055]
**Describe the bug**
I have been trying to install cudf (version 22.08) on a remote server and I have been running issues with it showing that is installed but it is not able to run in a python script. I believe it is the result of an issue with cupy-cuda, but I can't figure out how to fix it (nor can I find information online/past issues on how to resolve).

**Steps/Code to reproduce bug**
I am using an existing code framework to create an environment using micromamba/conda which installs cudf (from gitlab), that uses pip to install cudf=22.08. 

```
micromamba create --name gnn4itk -f gpu_environment.yml
micromamba activate gnn4itk
pip install -e . 
```

where gpu_environment.yml contains
```
dependencies:
    - cudf=22.08
    - cugraph=22.08
    - cudatoolkit=11.6
```

to install cudf and required packages. Upon installation, the following error occurs:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. dask-cudf 22.8.1 requires cupy-cuda115<11.0.0a0,>=9.5.0, which is not installed.
```

I have been told this error is trivial and not important, but given my further issues I am not so sure, so I have included it in case.

When I `import cudf` in python I get the following:

```
(gnn4itk) [15:29] jareddb2-gnncode:/data/jareddb2/commonframework $ python
Python 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:45:29) 
[GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf
Traceback (most recent call last):
  File "/home/jareddb2/micromamba/envs/gnn4itk/lib/python3.9/site-packages/cupy/__init__.py", line 18, in <module>
    from cupy import _core  # NOQA
  File "/home/jareddb2/micromamba/envs/gnn4itk/lib/python3.9/site-packages/cupy/_core/__init__.py", line 1, in <module>
    from cupy._core import core  # NOQA
  File "cupy/_core/core.pyx", line 1, in init cupy._core.core
  File "/home/jareddb2/micromamba/envs/gnn4itk/lib/python3.9/site-packages/cupy/cuda/__init__.py", line 8, in <module>
    from cupy.cuda import compiler  # NOQA
  File "/home/jareddb2/micromamba/envs/gnn4itk/lib/python3.9/site-packages/cupy/cuda/compiler.py", line 13, in <module>
    from cupy.cuda import device
  File "cupy/cuda/device.pyx", line 5, in init cupy.cuda.device
ImportError: cannot import name syncdetect

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jareddb2/micromamba/envs/gnn4itk/lib/python3.9/site-packages/cudf/__init__.py", line 7, in <module>
    import cupy
  File "/home/jareddb2/micromamba/envs/gnn4itk/lib/python3.9/site-packages/cupy/__init__.py", line 20, in <module>
    raise ImportError(f'''
ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: cannot import name syncdetect
================================================================
```

The key here being the `Failed to import CuPy` error message.

I run a quick show diagnostic

```
(gnn4itk) [15:31] ~/home $ pip show cudf
Name: cudf
Version: 22.8.1
Summary: cuDF - GPU Dataframe
Home-page: https://github.com/rapidsai/cudf
Author: NVIDIA Corporation
Author-email: 
License: Apache 2.0
Location: /home/jareddb2/micromamba/envs/gnn4itk/lib/python3.9/site-packages
Requires: cachetools, cuda-python, cupy-cuda115, fsspec, numba, numpy, nvtx, packaging, pandas, protobuf, typing_extensions
Required-by: dask-cudf
(gnn4itk) [15:31] ~/home $ pip show cupy
Name: cupy
Version: 10.6.0
Summary: CuPy: NumPy & SciPy for GPU
Home-page: https://cupy.dev/
Author: Seiya Tokui
Author-email: tokui@preferred.jp
License: MIT License
Location: /home/jareddb2/micromamba/envs/gnn4itk/lib/python3.9/site-packages
Requires: fastrlock, numpy
Required-by: 
(gnn4itk) [15:31] ~/home $ pip show cupy-cuda115
WARNING: Package(s) not found: cupy-cuda115
```

So using pip install for cudf seems to install cupy (version 10.6.0), rather than cupy-cuda115, which pip shows is a required dependency in order to use cudf. So, I am not sure why using pip install for cudf does not install the proper required package.

I have tried to manually uninstall cupy and instead manually install cupy-cuda115 (using pip install cupy-cuda115), but when I try to run `import cudf` in a python script it gives me some attribute errors like `AttributeError: module 'cupy' has no attribute 'int8'` which make me believe this is not the best fix to this issue.

**Expected behavior**
I would expect to be able to use pip to install cudf and be able to use cudf in a python script 

**Environment overview**
 - Environment location: Remote server loaded with a container image, creating a virtual environment using micromamba (conda) inside of the remote server
 - Method of cuDF install: pip install

**Environment details**
```
<details><summary>Click here to see environment details</summary><pre>

     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=20.04
     DISTRIB_CODENAME=focal
     DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
     NAME="Ubuntu"
     VERSION="20.04.4 LTS (Focal Fossa)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 20.04.4 LTS"
     VERSION_ID="20.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=focal
     UBUNTU_CODENAME=focal
     Linux jareddb2-gnncode 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

     ***GPU Information***
     Tue Apr  4 15:41:20 2023
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  NVIDIA A100-SXM...  Off  | 00000000:41:00.0 Off |                    0 |
     | N/A   29C    P0    51W / 400W |      0MiB / 40536MiB |      0%      Default |
     |                               |                      |             Disabled |
     +-------------------------------+----------------------+----------------------+

     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+

     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     Address sizes:       48 bits physical, 48 bits virtual
     CPU(s):              128
     On-line CPU(s) list: 0-127
     Thread(s) per core:  2
     Core(s) per socket:  32
     Socket(s):           2
     NUMA node(s):        8
     Vendor ID:           AuthenticAMD
     CPU family:          25
     Model:               1
     Model name:          AMD EPYC 7543 32-Core Processor
     Stepping:            1
     CPU MHz:             2794.876
     BogoMIPS:            5589.75
     Virtualization:      AMD-V
     L1d cache:           2 MiB
     L1i cache:           2 MiB
     L2 cache:            32 MiB
     L3 cache:            512 MiB
     NUMA node0 CPU(s):   0-7,64-71
     NUMA node1 CPU(s):   8-15,72-79
     NUMA node2 CPU(s):   16-23,80-87
     NUMA node3 CPU(s):   24-31,88-95
     NUMA node4 CPU(s):   32-39,96-103
     NUMA node5 CPU(s):   40-47,104-111
     NUMA node6 CPU(s):   48-55,112-119
     NUMA node7 CPU(s):   56-63,120-127
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb cat_l3 cdp_l3 invpcid_single hw_pstate sme retpoline_amd ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif umip pku ospke vaes vpclmulqdq overflow_recov succor smca

     ***CMake***

     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
     Copyright (C) 2019 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


     ***nvcc***

     ***Python***
     /home/jareddb2/micromamba/envs/gnn4itk/bin/python
     Python 3.9.15

     ***Environment Variables***
     PATH                            : /home/jareddb2/micromamba/envs/gnn4itk/bin:/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/jareddb2/.local/bin:/home/jareddb2/bin
     LD_LIBRARY_PATH                 : /usr/local/nvidia/lib:/usr/local/nvidia/lib64
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/jareddb2/micromamba/envs/gnn4itk
     PYTHON_PATH                     :

     conda not found
     ***pip packages***
     /home/jareddb2/micromamba/envs/gnn4itk/bin/pip
     Package             Version                  Editable project location
     ------------------- ------------------------ ------------------------------
     asttokens           2.2.1
     atlasify            0.8.0
     backcall            0.2.0
     bokeh               2.4.3
     brotlipy            0.7.0
     cachetools          5.3.0
     certifi             2022.12.7
     cffi                1.15.1
     charset-normalizer  3.1.0
     click               8.1.3
     cloudpickle         2.2.1
     colorama            0.4.6
     comm                0.1.3
     contourpy           1.0.7
     cryptography        39.0.0
     cuda-python         11.7.0
     cudf                22.8.1
     cugraph             22.8.0+0.g460692f0.dirty
     cupy                10.6.0
     cycler              0.11.0
     cytoolz             0.12.0
     dask                2022.7.1
     dask-cuda           22.8.0
     dask-cudf           22.8.1
     debugpy             1.6.6
     decorator           5.1.1
     distributed         2022.7.1
     executing           1.2.0
     fastavro            1.7.3
     fastrlock           0.8
     fonttools           4.39.3
     fsspec              2023.3.0
     gnn4itk-cf          0.0.1                    /data/jareddb2/commonframework
     HeapDict            1.0.1
     idna                3.4
     importlib-metadata  6.1.0
     importlib-resources 5.12.0
     ipykernel           6.22.0
     ipython             8.12.0
     jedi                0.18.2
     Jinja2              3.1.2
     joblib              1.2.0
     jupyter_client      8.1.0
     jupyter_core        5.3.0
     kiwisolver          1.4.4
     lightning-utilities 0.8.0
     llvmlite            0.38.1
     locket              1.0.0
     lz4                 4.3.2
     MarkupSafe          2.1.2
     matplotlib          3.7.1
     matplotlib-inline   0.1.6
     msgpack             1.0.5
     munkres             1.1.4
     nest-asyncio        1.5.6
     networkx            3.0
     numba               0.55.2
     numpy               1.22.0
     nvtx                0.2.3
     packaging           23.0
     pandas              1.4.4
     parso               0.8.3
     partd               1.3.0
     pexpect             4.8.0
     pickleshare         0.7.5
     Pillow              9.4.0
     pip                 23.0.1
     platformdirs        3.2.0
     ply                 3.11
     pooch               1.7.0
     prompt-toolkit      3.0.38
     protobuf            3.20.2
     psutil              5.9.4
     ptxcompiler         0.7.0
     ptyprocess          0.7.0
     pure-eval           0.2.2
     pyarrow             8.0.1
     pycparser           2.21
     Pygments            2.14.0
     pylibcugraph        22.8.0+0.g460692f0.dirty
     pynvml              11.5.0
     pyOpenSSL           23.1.1
     pyparsing           3.0.9
     PyQt5               5.15.7
     PyQt5-sip           12.11.0
     PySocks             1.7.1
     python-dateutil     2.8.2
     pytorch-lightning   1.9.2
     pytz                2023.3
     PyYAML              6.0
     pyzmq               25.0.2
     raft                22.8.0
     requests            2.28.2
     rmm                 21.12.0
     scikit-learn        1.2.2
     scipy               1.10.1
     seaborn             0.12.2
     setuptools          67.6.1
     sip                 6.7.7
     six                 1.16.0
     sortedcontainers    2.4.0
     stack-data          0.6.2
     tblib               1.7.0
     threadpoolctl       3.1.0
     toml                0.10.2
     toolz               0.12.0
     torch               1.12.1
     torch-cluster       1.6.0
     torch-geometric     2.2.0
     torch-scatter       2.1.0
     torch-sparse        0.6.16
     torchmetrics        0.11.4
     tornado             6.2
     tqdm                4.65.0
     trackml             3
     traitlets           5.9.0
     typing_extensions   4.5.0
     ucx-py              0.27.0
     unicodedata2        15.0.0
     urllib3             1.26.15
     wcwidth             0.2.6
     wheel               0.40.0
     zict                2.2.0
     zipp                3.15.0

</pre></details>
```

**Additional context**
We have been trying to resolve this issue on our end, but we can't seem to figure out what the issue is related to. This may not be a cudf-specific issue, but if it is, we are unsure how to resolve it currently.

**Comment by jared-burleson** [comment]
Adjusting the cudatoolkit version was sufficient (before I had tried cudatoolkit=11.5, but trying it now with cudatoolkit=11.3 worked).
