### ISSUE TITLE
Can't install CUDF[QST]

### ISSUE THREAD

**Issue by fatemeh9264** [rapidsai/cudf#13065]
Hello, I want to install Cudf, but I have a problem. They are the following features:
Driver Version 460.84
CUDA Version 11.2
python version 3.9.13
please guide me on how to resolve it.

**Comment by fatemeh9264** [comment]
I tried different commands in this page: https://anaconda.org/rapidsai/cudf

**Comment by shwina** [comment]
Thanks. Could you please try using the tool below to generate an install command?

https://docs.rapids.ai/install#selector

Please note that the latest versions of RAPIDS are supported on either Python 3.8, or Python 3.10 (but not 3.9). If you absolutely must use Python 3.9, you will need to use an older version of RAPIDS unfortunately.

Please let us know if this works for you or if you run into any issues!

**Comment by fatemeh9264** [comment]
I have created a virtual environment supporting Python 3.8 but I have the following errors:
Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
   - feature:|@/linux-64::__glibc==2.31=0
  - cudf -> __glibc[version='>=2.17,<3.0.a0']
  - cudf -> cupy[version='>7.1.0,<10.0.0a0'] -> __glibc[version='>=2.17']
Your installed version is: 2.31

**Comment by shwina** [comment]
Thanks - could you please provide the exact commands you used to create the virtual environment, as well as the command you are using to install cudf?

**Comment by fatemeh9264** [comment]
After activating the virtual environment, I have tried the following command:
conda install -c rapidsai cudf

Although it's better for me to use python 3.10

**Comment by shwina** [comment]
I believe you need more than just the `rapidsai` channel. For example to create an environment and install the latest stable version of cudf:

```
conda create -n rapids-23.02 -c rapidsai -c conda-forge -c nvidia cudf=23.02 python=3.8 cudatoolkit=11.8
```

**Comment by fatemeh9264** [comment]
Thank you, I ran your command and the installation was done.
To test it, I imported cudf:
import cudf
**but I received the following warning**
>>> import cudf
/root/anaconda3/envs/rapids-23.02/lib/python3.8/site-packages/cudf/utils/gpu_utils.py:88: UserWarning: A GPU with NVIDIA Pascal\u2122 (Compute Capability 6.0) or newer architecture is required.
Detected GPU 0: Tesla K80                                                                                                                                                                                                
Detected Compute Capability: 3.7
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/rapids-23.02/lib/python3.8/site-packages/cudf/__init__.py", line 20, in <module>
    from cudf.core.algorithms import factorize
  File "/root/anaconda3/envs/rapids-23.02/lib/python3.8/site-packages/cudf/core/algorithms.py", line 9, in <module>
    from cudf.core.indexed_frame import IndexedFrame
  File "/root/anaconda3/envs/rapids-23.02/lib/python3.8/site-packages/cudf/core/indexed_frame.py", line 57, in <module>
    from cudf.core.groupby.groupby import GroupBy
  File "/root/anaconda3/envs/rapids-23.02/lib/python3.8/site-packages/cudf/core/groupby/__init__.py", line 3, in <module>
    from cudf.core.groupby.groupby import GroupBy, Grouper
  File "/root/anaconda3/envs/rapids-23.02/lib/python3.8/site-packages/cudf/core/groupby/groupby.py", line 26, in <module>
    from cudf.core.udf.groupby_utils import jit_groupby_apply
  File "/root/anaconda3/envs/rapids-23.02/lib/python3.8/site-packages/cudf/core/udf/groupby_utils.py", line 32, in <module>
    dev_func_ptx = _get_ptx_file(os.path.dirname(__file__), "function_")
  File "/root/anaconda3/envs/rapids-23.02/lib/python3.8/site-packages/cudf/core/udf/utils.py", line 322, in _get_ptx_file
    raise RuntimeError(
**RuntimeError: This cuDF installation is missing the necessary PTX files that are <=37.**

**Comment by fatemeh9264** [comment]
Thank you, I ran your command and the installation was done.
To test it, I imported cudf:
import cudf
but I received the following Error

import cudf
/root/anaconda3/envs/rapids-23.02/lib/python3.8/site-packages/cudf/utils/gpu_utils.py:88: UserWarning: A GPU with NVIDIA Pascal\u2122 (Compute Capability 6.0) or newer architecture is required.
Detected GPU 0: Tesla K80
Detected Compute Capability: 3.7
warnings.warn(
Traceback (most recent call last):
File "", line 1, in
File "/root/anaconda3/envs/rapids-23.02/lib/python3.8/site-packages/cudf/init.py", line 20, in
from cudf.core.algorithms import factorize
File "/root/anaconda3/envs/rapids-23.02/lib/python3.8/site-packages/cudf/core/algorithms.py", line 9, in
from cudf.core.indexed_frame import IndexedFrame
File "/root/anaconda3/envs/rapids-23.02/lib/python3.8/site-packages/cudf/core/indexed_frame.py", line 57, in
from cudf.core.groupby.groupby import GroupBy
File "/root/anaconda3/envs/rapids-23.02/lib/python3.8/site-packages/cudf/core/groupby/init.py", line 3, in
from cudf.core.groupby.groupby import GroupBy, Grouper
File "/root/anaconda3/envs/rapids-23.02/lib/python3.8/site-packages/cudf/core/groupby/groupby.py", line 26, in
from cudf.core.udf.groupby_utils import jit_groupby_apply
File "/root/anaconda3/envs/rapids-23.02/lib/python3.8/site-packages/cudf/core/udf/groupby_utils.py", line 32, in
dev_func_ptx = get_ptx_file(os.path.dirname(file), "function")
File "/root/anaconda3/envs/rapids-23.02/lib/python3.8/site-packages/cudf/core/udf/utils.py", line 322, in _get_ptx_file
raise RuntimeError(
RuntimeError: This cuDF installation is missing the necessary PTX files that are <=37.

**Comment by fatemeh9264** [comment]
Thanks a lot for reply!
Unfortunately I work on a system that its GPU is Tesla K80.

**Comment by shwina** [comment]
Thanks for letting us know. I'm sorry, but there's no way around this requirement.

Thank you for your patience working through this issue! Please give RAPIDS a try once you have access to a newer GPU.

I'll close this issue out, but please feel free to reopen if you have any other questions!

**Comment by fatemeh9264** [comment]
Thank you
