### ISSUE TITLE
[QST] Is it possible to use RAPIDS via Dask distributed without a local GPU?

### ISSUE THREAD

**Issue by jriesen** [rapidsai/cudf#13481]
**What is your question?**

We have set up a Kubernetes RAPIDS environment with a Dask scheduler and multiple Dask workers.  Many of our developer VMs are GPU-less Ubuntu 22.04 VMs, and they are not able to actually run e.g. `import cudf` or `import dask_cudf` without an error.  I can confirm this with a fresh pyenv installation of 3.10.10, running `pip install cudf-cu11 dask-cudf-cu11 --extra-index-url=https://pypi.nvidia.com` (which installs cudf-cu11 23.4.1, dask-cudf-cu11 23.4.1, and their associated dependencies), and then just running `python` and `import cudf`.

```text
ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
================================================================
```

Sure, this doesn't seem unreasonable, I can see why we might need to compile CUDA locally even if we're pushing them to Dask over the wire?  But after installing `nvidia-cuda-toolkit` (with or without `nvidia-headless-530`) I get:

```text
>>> import cudf # or dask_cudf
/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cudf/utils/gpu_utils.py:148: UserWarning: No NVIDIA GPU detected
  warnings.warn("No NVIDIA GPU detected")
```
and later
```text
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: Call to cuInit results in CUDA_ERROR_NO_DEVICE (100)
```

Well, yeah, I don't have a GPU.  That's why we set up the Dask cluster, so every dev VM didn't need a GPU slice.

I haven't been able to figure out a way around this. Despite the "resolution" of #3661, calling `import cudf` obviously still requires `libcuda.so.1` (as per #11287 it's just done via dlopen in the `jitify2` dependency now), and apparently this will throw exceptions if there is no GPU in the system that can execute CUDA code.  It's kind of funny, because I can actually compile CUDA with `nvcc` on these systems, and can even run them without a crash, although as expected when I try and call a kernel function `cudaGetErrorString()` tells me `no CUDA-capable device is detected`.

To be honest, I'm coming at this from an operations perspective, I only know the bare basics of RAPIDS.  Am I thinking about this the wrong way? Is a GPU really required because operations in cudf must execute on a GPU before ever being sent to a Dask scheduler?  Or is this just an unintentional requirement of how cudf is written (or how its dependencies operate)?  Should we reopen #3661?

**Comment by shwina** [comment]
Thanks for reporting, @jriesen. I think your diagnosis is correct: the error you're seeing is a bug introduced after #11287.

Could you please post the full output you see on `import cudf`?

**Comment by jriesen** [comment]
Can do!

On an Ubuntu 22.04 machine using Python 3.10.10 inside pyenv, after running `pip install cudf-cu11 --extra-index-url=https://pypi.nvidia.com` and installing `cudf-cu11` 23.4.1 and dependencies.  (Looks like it's pulling https://pypi.nvidia.com/cudf-cu11/cudf_cu11-23.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl specifically.)

Here is the system without CUDA toolkit installed at all.
```text
jriesen@jriesen:~$ python
Python 3.10.10 (main, May 31 2023, 19:54:15) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf
/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cudf/utils/gpu_utils.py:148: UserWarning: No NVIDIA GPU detected
  warnings.warn("No NVIDIA GPU detected")
Traceback (most recent call last):
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cupy/__init__.py", line 18, in <module>
    from cupy import _core  # NOQA
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cupy/_core/__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cudf/__init__.py", line 7, in <module>
    import cupy
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cupy/__init__.py", line 20, in <module>
    raise ImportError(f'''
ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
================================================================

>>> 
```

After installing CUDA toolkit via `apt install nvidia-cuda-toolkit` it is able to find libcuda.so.1, but then the following occurs:
```text
jriesen@jriesen:~$ python
Python 3.10.10 (main, May 31 2023, 19:54:15) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf
/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cudf/utils/gpu_utils.py:148: UserWarning: No NVIDIA GPU detected
  warnings.warn("No NVIDIA GPU detected")
Traceback (most recent call last):
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 247, in ensure_initialized
    self.cuInit(0)
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 320, in safe_cuda_api_call
    self._check_ctypes_error(fname, retcode)
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 388, in _check_ctypes_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [100] Call to cuInit results in CUDA_ERROR_NO_DEVICE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cudf/__init__.py", line 21, in <module>
    from cudf.core.algorithms import factorize
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cudf/core/algorithms.py", line 9, in <module>
    from cudf.core.indexed_frame import IndexedFrame
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cudf/core/indexed_frame.py", line 57, in <module>
    from cudf.core.groupby.groupby import GroupBy
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cudf/core/groupby/__init__.py", line 3, in <module>
    from cudf.core.groupby.groupby import GroupBy, Grouper
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cudf/core/groupby/groupby.py", line 28, in <module>
    from cudf.core.udf.groupby_utils import jit_groupby_apply
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cudf/core/udf/groupby_utils.py", line 11, in <module>
    import cudf.core.udf.utils
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cudf/core/udf/utils.py", line 121, in <module>
    _PTX_FILE = _get_ptx_file(os.path.dirname(__file__), "shim_")
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cudf/core/udf/utils.py", line 87, in _get_ptx_file
    dev = cuda.get_current_device()
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/numba/cuda/api.py", line 435, in get_current_device
    return current_context().device
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/numba/cuda/cudadrv/devices.py", line 220, in get_context
    return _runtime.get_or_create_context(devnum)
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/numba/cuda/cudadrv/devices.py", line 138, in get_or_create_context
    return self._get_or_create_context_uncached(devnum)
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/numba/cuda/cudadrv/devices.py", line 153, in _get_or_create_context_uncached
    with driver.get_active_context() as ac:
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 488, in __enter__
    driver.cuCtxGetCurrent(byref(hctx))
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 285, in __getattr__
    self.ensure_initialized()
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 251, in ensure_initialized
    raise CudaSupportError(f"Error at driver init: {description}")
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: Call to cuInit results in CUDA_ERROR_NO_DEVICE (100)
>>> 
```

Now, I can get further if I delay CUDA initialization by running `RAPIDS_NO_INITIALIZE=1 python` (I discovered that environment variable when poking through cudf's source code).  With that, I can `import cudf` but I cannot use it to do anything interesting.
```text
jriesen@jriesen:~$ RAPIDS_NO_INITIALIZE=1 python
Python 3.10.10 (main, May 31 2023, 19:54:15) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf
>>> series = cudf.Series([1, 2, 3])
Traceback (most recent call last):
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cudf/core/column/column.py", line 2196, in as_column
    memoryview(arbitrary), dtype=dtype, nan_as_null=nan_as_null
TypeError: memoryview: a bytes-like object is required, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/nvtx/nvtx.py", line 101, in inner
    result = func(*args, **kwargs)
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cudf/core/series.py", line 570, in __init__
    data = column.as_column(
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cudf/core/column/column.py", line 2308, in as_column
    data = as_column(
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cudf/core/column/column.py", line 1958, in as_column
    col = ColumnBase.from_arrow(arbitrary)
  File "/home/jriesen/.pyenv/versions/3.10.10/lib/python3.10/site-packages/cudf/core/column/column.py", line 368, in from_arrow
    result = libcudf.interop.from_arrow(data)[0]
  File "interop.pyx", line 178, in cudf._lib.interop.from_arrow
RuntimeError: CUDA error at: /project/python/cudf/_skbuild/linux-x86_64-3.10/cmake-build/_deps/rmm-src/include/rmm/cuda_device.hpp:56: cudaErrorNoDevice no CUDA-capable device is detected
>>> 
```

I notice in my first capture there that, after trying to clean out everything and start fresh, it's appears to be missing `libcudart.so.11.0` rather than `libcuda.so.1` but otherwise displays the same error.  (I think I had that previous error in a conda environment, but I can't seem to reproduce it?)  In that regard, I don't think that #11287 is _regressed_ in any way, I do think it satisfies what it set out to do... it just isn't sufficient to satisfy the feature request of #3661, which is to allow (basic, non-executing) use of cudf on machines without GPUs.  Which I fully acknowledge may not even be possible, of course!

**Comment by shwina** [comment]
@jriesen thanks for your response! What exactly are some examples of things you'd like to do after importing cuDF without a GPU? Note that it's impossible to even construct DataFrames without a GPU, since cuDF stores things in GPU memory.

So, what you're seeing with `RAPIDS_NO_INITIALIZE` turned on is about as far as you can get.

**Comment by jriesen** [comment]
That makes sense; I thought those weren't necessarily pushed into GPU memory until actually needed/used, but they're a handle for data already placed in the GPU.

I guess my frustration came from trying to use e.g. dask_cudf to work with our dask+RAPIDS workers... but tutorials (such as the 10 Minutes to cuDF and Dask-cuDF) inevitably do something like:
```python
s = cudf.Series([1, 2, 3, None, 4])
ds = dask_cudf.from_cudf(s, npartitions=2)
```
or
```python
import dask_cudf
from dask.distributed import Client
client = Client('my.dask.cluster:8786')
gdf = dask_cudf.read_csv('test.csv')
```

That is, a typical way to create basic dataframes for processing in Dask is to first load them into a local GPU, then dispatch them for remote processing.  This is okay!  It just revealed some misunderstanding on my part.  I suspect that I could also get around some of this using `client.run` to assemble cudf objects on the Dask workers themselves, but that's a whole different adventure.

Thank you for your prompt response, and thank you for taking the time to clarify matters!

On my end, after some wrangling I was able to set aside a single multiuser development VM with GPU resources dedicated for this purpose, so our data scientists can have individual accounts on this machine and work in normal fashion against the Dask cluster.

**Comment by quasiben** [comment]
@jriesen you may be interested in this post on how you could architect your dask code in a hardware agnostic fashion:
https://medium.com/rapids-ai/easy-cpu-gpu-arrays-and-dataframes-run-your-dask-code-where-youd-like-e349d92351d
