### ISSUE TITLE
[BUG] cudf.read_json() failed to read dataframe in json generated by .to_json()

### ISSUE THREAD

**Issue by yuchenz427** [rapidsai/cudf#13527]
`cudf.read_json()` raises `RuntimeError` when reading json dataframe generated by `to_json()`

Reproduce:
```python
import cudf

df = cudf.DataFrame(
    {
        'col1': [1, 2, 3, 4, 5],
        'col2': [1.1, 2.2, 3.3, 4.4, 5.5],
        'col3': ['a', 'b', 'c', 'd', 'e'],
        'col4': [True, False, True, False, True]
    },
    columns=['col1', 'col2', 'col3', 'col4'])

intermediate = df.to_json()

df2 = cudf.read_json(intermediate, engine="cudf") # this fails
```
Error Message:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nfs/miniconda3/envs/lib/python3.10/site-packages/cudf/io/json.py", line 111, in read_json
    df = libjson.read_json(
  File "json.pyx", line 50, in cudf._lib.json.read_json
  File "json.pyx", line 138, in cudf._lib.json.read_json
RuntimeError: CUDF failure at: /opt/conda/conda-bld/work/cpp/src/io/json/json_column.cu:949: Input needs to be an array of arrays or an array of (nested) objects
```

Using raw string also produces the same error:
```python
new_data = """
{
"col1": [1, 2, 3, 4, 5],
"col2": [1.1, 2.2, 3.3, 4.4, 5.5],
"col3": ['a', 'b', 'c', 'd', 'e'],
"col4": [True, False, True, False, True]
}
"""
df2 = cudf.read_json(new_data, engine="cudf") # This fails
```

I'm using cudf 23.02 in conda environment:
```bash
cudf                      23.02.00        cuda_11_py310_g5ad4a85b9d_0    rapidsai
libcudf                   23.02.00        cuda11_g5ad4a85b9d_0    rapidsai
```

**Comment by yuchenz427** [comment]
It works - thanks @GregoryKimball for clarification
