### ISSUE TITLE
[FEA] Support indicator=True in dask_cudf.DataFrame.merge

### ISSUE THREAD

**Issue by ChrisJar** [rapidsai/cudf#13581]
**Is your feature request related to a problem? Please describe.**
I wish dask_cudf dataframes would support the `indicator=True` option in the merge function

**Describe the solution you'd like**
In dask dataframe the code:
```python
import pandas as pd
import dask.dataframe as dd

dfa = pd.DataFrame({"id":[1,2,2,4], "a":["a","b","c","d"]})
dfb = pd.DataFrame({"id":[2,3,3,4], "b":["e","f","g","h"]})
ddfa = dd.from_pandas(dfa, npartitions=1)
ddfb = dd.from_pandas(dfb, npartitions=1)

ddf = ddfa.merge(ddfb, on="id", how="outer", indicator=True)
print(ddf.compute())
```
returns:
```
   id    a    b      _merge
0   1    a  NaN   left_only
1   2    b    e        both
2   2    c    e        both
3   4    d    h        both
4   3  NaN    f  right_only
5   3  NaN    g  right_only
```

but in dask_cudf:
```python
import cudf
import dask_cudf as dd

dfa = cudf.DataFrame({"id":[1,2,2,4], "a":["a","b","c","d"]})
dfb = cudf.DataFrame({"id":[2,3,3,4], "b":["e","f","g","h"]})
ddfa = dd.from_cudf(dfa, npartitions=1)
ddfb = dd.from_cudf(dfb, npartitions=1)

ddf = ddfa.merge(ddfb, on="id", how="outer", indicator=True)
print(ddf.compute())
```
this throws a `NotImplementedError`:
```
Traceback (most recent call last):                                                                                                                             
  File "/raid/cjarrett/dask-sql/min.py", line 13, in <module>     
    ddf = ddfa.merge(ddfb, on="id", how="outer", indicator=True)
  File "/raid/cjarrett/mambaforge/envs/dsql-6-6/lib/python3.10/site-packages/nvtx/nvtx.py", line 101, in inner
    result = func(*args, **kwargs)
  File "/raid/cjarrett/mambaforge/envs/dsql-6-6/lib/python3.10/site-packages/dask_cudf/core.py", line 121, in merge
    return super().merge(
  File "/raid/cjarrett/mambaforge/envs/dsql-6-6/lib/python3.10/site-packages/dask/dataframe/core.py", line 5644, in merge
    return merge(
  File "/raid/cjarrett/mambaforge/envs/dsql-6-6/lib/python3.10/site-packages/dask/dataframe/multi.py", line 724, in merge
    return hash_join(
  File "/raid/cjarrett/mambaforge/envs/dsql-6-6/lib/python3.10/site-packages/dask/dataframe/multi.py", line 398, in hash_join
    meta = _lhs_meta.merge(_rhs_meta, **kwargs)
  File "/raid/cjarrett/mambaforge/envs/dsql-6-6/lib/python3.10/site-packages/nvtx/nvtx.py", line 101, in inner
    result = func(*args, **kwargs)
  File "/raid/cjarrett/mambaforge/envs/dsql-6-6/lib/python3.10/site-packages/cudf/core/dataframe.py", line 3969, in merge
    raise NotImplementedError(
NotImplementedError: Only indicator=False is currently supported
```

**Comment by wence-** [comment]
This needs to happen in the `cudf` implementation of `merge` (which doesn't support `indicator` either). The implementation is relatively straightforward. You carry around an extra column that is `2^0` for the left frame, `2^1` for the right frame. Then you merge, and sum those columns (treating null as zero). Where this result column is `2^0`, the input only appeared in the left frame, where it is `2^1` it only appeared in the right frame, if it's `3`, it appeared in both. This can be encoded as a categorical column.

Care to try implementing that (relevant code is in `cudf/python/core/join/join.py`).
