### ISSUE TITLE
[BUG] libcudf fails to recognized malformed dictionary during Parquet read

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#13656]
**Describe the bug**
Using libcudf to load a Parquet file with a malformed dictionary does not result in an error. 

**Steps/Code to reproduce bug**
Read the [nation.dict-malformed.parquet file from apache/parquet-testing](https://github.com/apache/parquet-testing/blob/master/data/nation.dict-malformed.parquet)  with libcudf and note that it does not error. 

**Expected behavior**
Loading this from Apache Spark or via the [parquet-cli tool](https://github.com/apache/parquet-mr/tree/master/parquet-cli) results in a decode error as expected:
```
java -cp '/home/jlowe/src/parquet-mr/parquet-cli/target/parquet-cli-1.13.1.jar:/home/jlowe/src/parquet-mr/parquet-cli/target/dependency/*' org.apache.parquet.cli.Main cat parquet-testing/data/nation.dict-malformed.parquet
Unknown error
java.lang.RuntimeException: Failed on record 0
	at org.apache.parquet.cli.commands.CatCommand.run(CatCommand.java:86)
	at org.apache.parquet.cli.Main.run(Main.java:163)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
	at org.apache.parquet.cli.Main.main(Main.java:193)
Caused by: java.lang.RuntimeException: Failed while reading Parquet file: /home/jlowe/src/spark-rapids/thirdparty/parquet-testing/data/nation.dict-malformed.parquet
	at org.apache.parquet.cli.BaseCommand$1$1.advance(BaseCommand.java:367)
	at org.apache.parquet.cli.BaseCommand$1$1.<init>(BaseCommand.java:344)
	at org.apache.parquet.cli.BaseCommand$1.iterator(BaseCommand.java:342)
	at org.apache.parquet.cli.commands.CatCommand.run(CatCommand.java:73)
	... 3 more
Caused by: java.io.EOFException
	at org.apache.parquet.bytes.SingleBufferInputStream.sliceBuffers(SingleBufferInputStream.java:134)
	at org.apache.parquet.hadoop.ParquetFileReader$Chunk.readAsBytesInput(ParquetFileReader.java:1688)
	at org.apache.parquet.hadoop.ParquetFileReader$Chunk.readAllPages(ParquetFileReader.java:1604)
	at org.apache.parquet.hadoop.ParquetFileReader$Chunk.readAllPages(ParquetFileReader.java:1547)
	at org.apache.parquet.hadoop.ParquetFileReader.readChunkPages(ParquetFileReader.java:1157)
	at org.apache.parquet.hadoop.ParquetFileReader.internalReadRowGroup(ParquetFileReader.java:993)
	at org.apache.parquet.hadoop.ParquetFileReader.readNextRowGroup(ParquetFileReader.java:940)
	at org.apache.parquet.hadoop.ParquetFileReader.readNextFilteredRowGroup(ParquetFileReader.java:1082)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.checkRead(InternalParquetRecordReader.java:130)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:230)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:132)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:136)
	at org.apache.parquet.cli.BaseCommand$1$1.advance(BaseCommand.java:363)
	... 6 more
```

**Comment by etseidl** [comment]
It appears that it's not so much that the dictionary is corrupt, but that the file metadata in the footer does not agree with the sizes in the page headers. For the two columns that use a dictionary, the file metadata gives a size for the column chunk that is 15 bytes smaller than the sum of the sizes from the page headers. One place where this could be detected is in `gpuDecodePageHeaders`, where it would be possible to detect incrementing the `bs->cur` pointer beyond `bs->end`. Communicating that back to the host then becomes the challenge.

**Comment by etseidl** [comment]
#14167 will help with this one
