### ISSUE TITLE
unsupported types: TIMESTAMP 64-bits, DATE 32-bits, TIME 32-bits, BOOL

### ISSUE THREAD

**Issue by randyzwitch** [rapidsai/cudf#140]
Related: https://github.com/mapd/pymapd/issues/76#issuecomment-401410409

When taking result of timestamp from MapD through pymapd, NotImplementedError thrown

```
In [12]: df = conn.select_ipc_gpu("select * from flights_2008_7m limit 1000")
Traceback (most recent call last):

  File "<ipython-input-12-a039584d5164>", line 1, in <module>
    df = conn.select_ipc_gpu("select * from flights_2008_7m limit 1000")

  File "/home/rzwitch/miniconda3/envs/py36/lib/python3.6/site-packages/pymapd/connection.py", line 272, in select_ipc_gpu
    return _parse_tdf_gpu(tdf)

  File "/home/rzwitch/miniconda3/envs/py36/lib/python3.6/site-packages/pymapd/_parsers.py", line 190, in _parse_tdf_gpu
    reader = GpuArrowReader(schema_buffer, darr)

  File "/home/rzwitch/miniconda3/envs/py36/lib/python3.6/site-packages/pygdf/gpuarrow.py", line 173, in __init__
    self._open()

  File "/home/rzwitch/miniconda3/envs/py36/lib/python3.6/site-packages/pygdf/gpuarrow.py", line 207, in _open
    dtype=_schema_to_dtype(**layout['dtype']),

  File "/home/rzwitch/miniconda3/envs/py36/lib/python3.6/site-packages/pygdf/gpuarrow.py", line 50, in _schema_to_dtype
    raise NotImplementedError(fmt.format(name, bitwidth))

NotImplementedError: unsupported type TIMESTAMP 64-bits
```

MapD: In [8]: conn._client.get_version()
Out[8]: '4.1.0dev-20180705-81fe840'

```
# packages in environment at /home/rzwitch/miniconda3/envs/py36:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.11                   py36_0  
arrow-cpp                 0.7.1                    py36_2    conda-forge
asn1crypto                0.24.0                   py36_0  
astroid                   1.6.5                    py36_0  
babel                     2.6.0                    py36_0  
backcall                  0.1.0                    py36_0  
bleach                    2.1.3                    py36_0  
ca-certificates           2018.03.07                    0  
certifi                   2018.4.16                py36_0  
cffi                      1.11.5           py36h9745a5d_0  
chardet                   3.0.4            py36h0f667ec_1  
cloudpickle               0.5.3                    py36_0  
cryptography              2.2.2            py36h14c3975_0  
cudatoolkit               9.1                  h85f986d_0    numba
dbus                      1.13.2               h714fa37_1  
decorator                 4.3.0                    py36_0  
docutils                  0.14             py36hb0f60f5_0  
entrypoints               0.2.3            py36h1aec115_2  
expat                     2.2.5                he0dffb1_0  
fontconfig                2.13.0               h9420a91_0  
freeglut                  2.8.1                         0  
freetype                  2.9.1                h8a8886c_0  
glib                      2.56.1               h000015b_0  
gmp                       6.1.2                h6c8ec71_1  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
html5lib                  1.0.1            py36h2f9c1c0_0  
icu                       58.2                 h9c2bf20_1  
idna                      2.7                      py36_0  
imagesize                 1.0.0                    py36_0  
intel-openmp              2018.0.3                      0  
ipykernel                 4.8.2                    py36_0  
ipython                   6.4.0                    py36_0  
ipython_genutils          0.2.0            py36hb52b0d5_0  
isort                     4.3.4                    py36_0  
jedi                      0.12.0                   py36_1  
jinja2                    2.10             py36ha16c418_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                2.6.0            py36h006f8b5_0  
jupyter_client            5.2.3                    py36_0  
jupyter_core              4.4.0            py36h7c827e3_0  
lazy-object-proxy         1.3.1            py36h10fcdad_0  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 7.2.0                hdf63c60_3  
libgdf                    0.1.0a2.dev          cuda9.1_56    gpuopenanalytics/label/dev
libgdf_cffi               0.1.0a2.dev             py36_56    gpuopenanalytics/label/dev
libgfortran-ng            7.2.0                hdf63c60_3  
libopenblas               0.2.20               h9ac9557_7  
libpng                    1.6.34               hb9fc6fc_0  
libsodium                 1.0.16               h1bed415_0  
libstdcxx-ng              7.2.0                hdf63c60_3  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.8                h26e45fe_1  
llvmlite                  0.23.2           py36hdbcaa40_0  
markupsafe                1.0              py36hd9260cd_1  
mccabe                    0.6.1            py36h5ad9710_1  
mistune                   0.8.3            py36h14c3975_1  
mkl                       2018.0.3                      1  
mkl_fft                   1.0.1            py36h3010b51_0  
mkl_random                1.0.1            py36h629b387_0  
nbconvert                 5.3.1            py36hb41ffb7_0  
nbformat                  4.4.0            py36h31c9010_0  
ncurses                   6.1                  hf484d3e_0  
numba                     0.38.1           py36h04863e7_0  
numpy                     1.13.3           py36hdbf6ddf_4  
numpy-base                1.14.3           py36h0ea5e3f_1  
numpydoc                  0.8.0                    py36_0  
openssl                   1.0.2o               h20670df_0  
packaging                 17.1                     py36_0  
pandas                    0.23.2                   py36_0    conda-forge
pandoc                    2.2.1                h629c226_0  
pandocfilters             1.4.2            py36ha6701b7_1  
parquet-cpp               1.3.0.post                    2    conda-forge
parso                     0.2.1                    py36_0  
pcre                      8.42                 h439df22_0  
pexpect                   4.6.0                    py36_0  
pickleshare               0.7.4            py36h63277f8_0  
pip                       10.0.1                   py36_0  
prompt_toolkit            1.0.15           py36h17d85b1_0  
psutil                    5.4.6            py36h14c3975_0  
ptyprocess                0.6.0                    py36_0  
pyarrow                   0.7.1                    py36_1    conda-forge
pycodestyle               2.4.0                    py36_0  
pycparser                 2.18             py36hf9f622e_1  
pyflakes                  2.0.0                    py36_0  
pygdf                     0.1.0a2                py36_128    gpuopenanalytics/label/dev
pygments                  2.2.0            py36h0d3125c_0  
pylint                    1.9.2                    py36_0  
pymapd                    0.4.0                    py36_0    conda-forge
pyopengl                  3.1.1a1             np113py36_0  
pyopenssl                 18.0.0                   py36_0  
pyparsing                 2.2.0            py36hee85983_1  
pyqt                      5.9.2            py36h751905a_0  
pysocks                   1.6.8                    py36_0  
python                    3.6.6                hc3d631a_0  
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
pyzmq                     17.0.0           py36h14c3975_0  
qt                        5.9.6                h52aff34_0  
qtawesome                 0.4.4            py36h609ed8c_0  
qtconsole                 4.3.1            py36h8f73b5b_0  
qtpy                      1.4.2                    py36_0  
readline                  7.0                  ha6073c6_4  
requests                  2.19.1                   py36_0  
rope                      0.10.7           py36h147e2ec_0  
setuptools                39.2.0                   py36_0  
simplegeneric             0.8.1                    py36_2  
sip                       4.19.8           py36hf484d3e_0  
six                       1.11.0                   py36_1    conda-forge
snowballstemmer           1.2.1            py36h6febd40_0  
sphinx                    1.7.5                    py36_0  
sphinxcontrib             1.0              py36h6d0f590_1  
sphinxcontrib-websupport  1.1.0                    py36_1  
spyder                    3.2.8                    py36_0  
sqlalchemy                1.2.9                    py36_0    conda-forge
sqlite                    3.24.0               h84994c4_0  
testpath                  0.3.1            py36h8cadb63_0  
thrift                    0.11.0                   py36_0    conda-forge
tk                        8.6.7                hc745277_3  
tornado                   5.0.2                    py36_0  
traitlets                 4.3.2            py36h674d592_0  
urllib3                   1.23                     py36_0  
wcwidth                   0.1.7            py36hdf4376a_0  
webencodings              0.5.1            py36h800622e_1  
wheel                     0.31.1                   py36_0  
wrapt                     1.10.11          py36h28b7045_0  
xz                        5.2.4                h14c3975_4  
zeromq                    4.2.5                h439df22_0  
zlib                      1.2.11               ha838bed_2  
```

**Comment by kkraus14** [comment]
Timestamp, datetime, and date types are not yet supported but are in the works. There's a pull request that is ready for review for libgdf here: https://github.com/gpuopenanalytics/libgdf/pull/47. Python bindings and relevant operations / conversions should start following shortly!

**Comment by randyzwitch** [comment]
Thanks @kkraus14 , please let me know if there's anything I can do to help. It looks like this won't be ready for a webinar I have on 7/18, but I'm speaking at JupyterCon in late August, would be great to have this straightened out so I can talk about GOAI

**Comment by kkraus14** [comment]
Timestamp support was added in https://github.com/gpuopenanalytics/pygdf/pull/154.

**Comment by kkraus14** [comment]
Reopening this as we only support DATE64, not TIMESTAMP. We should support arbitrary resolutions as well.

**Comment by jrhemstad** [comment]
@kkraus14 what functionality is needed from libcudf here?

**Comment by randyzwitch** [comment]
@jrhemstad I've been playing with this a little today, it might not need any libcudf functionality.

@kkraus14 This might be almost exactly like my fix for #1385, I just need to play around a bit more. I can get a timestamp out of OmniSci by modifying `_schema_to_dtype`, but it looks like cudf wants either ms or ns for the input to datetime. `_schema_to_dtype` only accounts for the bitwidth, but the resolution of the Arrow timestamp. But nevertheless, might finally make some progress here.

**Comment by randyzwitch** [comment]
Ok, I take it back, there are several issues here.

1. Adding types to `_schema_to_dtype`:

I was hoping to just add this to the `_schema_to_dtype` function:

```python
    elif name == 'TIMESTAMP':
        ret = getattr(np, 'datetime{:d}'.format(bitwidth))
```
This will get you past the `NotImplementedError: unsupported type TIMESTAMP 64-bits` error message, so that's good.

2. When writing the test, I get the wrong result:

```python
import cudf
import datetime
import numpy as np
import pyarrow as pa
from librmm_cffi import librmm as rmm
from cudf.comm.gpuarrow import GpuArrowReader

dtarray = np.array([datetime.datetime(2019, 3, 2, 0, 0)])
d_dtarray = pa.array(dtarray)
batch = pa.RecordBatch.from_arrays([d_dtarray], ['dt'])

schema_bytes = batch.schema.serialize().to_pybytes()
recordbatches_bytes = batch.serialize().to_pybytes()

schema = np.ndarray(shape=len(schema_bytes), dtype=np.byte,
                    buffer=bytearray(schema_bytes))

rb_cpu_data = np.ndarray(shape=len(recordbatches_bytes), dtype=np.byte,
                         buffer=bytearray(recordbatches_bytes))

rb_gpu_data = rmm.to_device(rb_cpu_data)
gar = GpuArrowReader(schema, rb_gpu_data)
columns = gar.to_dict()
columns["dt"].to_pandas()

Out[45]: 
0   1970-01-18 22:58:04.800
dtype: datetime64[ns]
```

So for the first part, getting all the dtypes into `_schema_to_dtype`, you could add the timestamp lines above, but somewhere along the line the data doesn't get translated correctly. At this line in the code, we still know what units the data are in (the units are part of the Arrow definition):

https://github.com/rapidsai/cudf/blob/aee62a8bd4e3f0aa6a01106f0d0637f3a43056b1/python/cudf/comm/gpuarrow.py#L210

```python
ipdb> schema
{'schema': {'fields': [{'name': 'dt', 'nullable': True, 'type': {'name': 'timestamp', 'unit': 'MICROSECOND'}, 'children': []}]}, 'batches': []}
```

So at this point I'm stuck. I was hoping to solve for timestamp and bool (both are missing in the `_schema_to_dtype` function), but it feels like there needs to be a step to translate the Arrow data into the format that cudf wants.

**Comment by kkraus14** [comment]
For bools, Arrow uses a single bit per value whereas we use a byte per value. You can use Arrow builtins to cast for now, though we have the functionality to handle this on the GPU just not in a nicely exposed API.

For timestamps, the plumbing from Python to libcudf is severely lacking and only really supports millisecond granularity as of now. We should improve this.

**Comment by randyzwitch** [comment]
Ok. I tried `ret = getattr(np, 'bool_')`, and saw fewer results than expected. So that might have been the issue (I didn't calculate if I got 1/8th of the expected results)

**Comment by randyzwitch** [comment]
@kkraus14 I just changed the title of this issue to include other known types to not work. I wasn't able to figure out `BOOL` or `TIMESTAMP 64-bits`, I'll try and hack on `DATE32` and `TIME32` and see what happens.

**Comment by wamsiv** [comment]
Just ran into `unsupported type DATE32 `. All new date types created in Omniscidb would return date in days. So, arrow serialized date types would not work with cudf until the issue has been resolved. Would be very helpful if @kkraus14 you could please provide an update on when the feature would be/planned to be implemented.

**Comment by kkraus14** [comment]
@wamsiv We're working on revamping datetimes currently, but GDF_DATE32 is problematic on the Python side because there isn't an equivalent Pandas / Numpy dtype for it unless we do something really gross like using `datetime64[D]` which doesn't sound like a good idea due to different sizing underneath.

**Comment by kkraus14** [comment]
cc @trxcllnt since he's current working on this section of the codebase

**Comment by wamsiv** [comment]
Thanks @kkraus14. Valid point. But we should handle new date types, otherwise arrow handling of dates would be unusable. 
One option is from our end we can temporarily revert to date64 at-least on the gpu side, I will circle back after discussion.

**Comment by kkraus14** [comment]
@wamsiv I would love to find an option that leaves everyone satisfied here. One note though is if you're using Arrow as an intermediary for Pandas as well that DATE32 and DATE64 dtypes end up becoming an object dtype column filled with Python datetime.date objects which I imagine is not what you want.

**Comment by kkraus14** [comment]
Connected with @wamsiv offline and came to the agreement that using Arrow timestamp types is the best bet for now for more performant integration with both Pandas and cuDF. We will continue to investigate how we can better support DATE32 in the future from the Python API.

**Comment by wamsiv** [comment]
Hi @kkraus14 , I have made changes in omnscidb to return `DATE64`, however, I get this error:
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-7-e0321810ab8c> in <module>
----> 1 df = con.select_ipc_gpu("select b from vskp;")

~/raidStorage/pymapd/pymapd/connection.py in select_ipc_gpu(self, operation, parameters, device_id, first_n, release_memory)
    304         self._tdf = tdf
    305 
--> 306         df = _parse_tdf_gpu(tdf)
    307 
    308         # Deallocate TDataFrame at OmniSci instance

~/raidStorage/pymapd/pymapd/_parsers.py in _parse_tdf_gpu(tdf)
    201                                           dtype=dtype,
    202                                           gpu_data=dptr)
--> 203     reader = GpuArrowReader(schema_buffer, darr)
    204     df = DataFrame()
    205     df.set_tdf = MethodType(set_tdf, df)

cudf/bindings/gpuarrow.pyx in cudf.bindings.gpuarrow.GpuArrowReader.__init__()

cudf/bindings/gpuarrow.pyx in cudf.bindings.gpuarrow.GpuArrowReader._open()

cudf/bindings/gpuarrow.pyx in cudf.bindings.gpuarrow._schema_to_dtype()

NotImplementedError: unsupported type DATE64 64-bits
```
Looks like DATE32 or DATE64 neither is working.
Please let me know if I am missing something, I am on:
```
cudf                      0.8.0                    py37_0    rapidsai 
libcudf                   0.8.0                cuda10.0_0    rapidsai
```

**Comment by kkraus14** [comment]
@wamsiv We are working on adding DATE64 and TIMESTAMP support to the IPC parser, will update you when it lands.

**Comment by trxcllnt** [comment]
Hi @wamsiv, I'll be working this into https://github.com/rapidsai/cudf/pull/2213

**Comment by wamsiv** [comment]
Thanks @kkraus14 and @trxcllnt!

**Comment by harrism** [comment]
@kkraus14 can we close this now? We have new timestamp types and we support bool columns.
