### ISSUE TITLE
pip install cudf fails on MacOS (M2)

### ISSUE THREAD

**Issue by DavidARivkin** [rapidsai/cudf#14510]
**Describe the bug**

**Steps/Code to reproduce bug**
Simply type 'pip3 install cudf" on a Mac M2 (ARM) based system.

**Expected behavior**
The module should build and install without any issue.

**Environment overview (please complete the following information)**
 - Environment location:  MacBook Pro (2023) M2 hardware 32G RAM with MacOS Sonoma 14.1.1
 - Method of cuDF install: 
     pip3

**Environment details**
Not possible to run the requested script since it was not installed.

**Additional context**
pip3 install cudf
Collecting cudf
  Downloading cudf-0.6.1.post1.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: cudf
  Building wheel for cudf (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      running bdist_wheel
      running build
      /opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      installing to build/bdist.macosx-13-arm64/wheel
      running install
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/3f/85ss3wld1m7316cqb639q8xm0000gn/T/pip-install-08fx9rb3/cudf_e690a7e1e1c94d88bcbd31e5351631f1/setup.py", line 18, in <module>
          setup(name=pkg,
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/opt/homebrew/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 399, in run
          self.run_command("install")
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/opt/homebrew/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/3f/85ss3wld1m7316cqb639q8xm0000gn/T/pip-install-08fx9rb3/cudf_e690a7e1e1c94d88bcbd31e5351631f1/setup.py", line 15, in run
          raise Exception(long_description)
      Exception: Please install cudf via the rapidsai conda channel. See https://rapids.ai/start.html for instructions.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cudf
  Running setup.py clean for cudf
Failed to build cudf
ERROR: Could not build wheels for cudf, which is required to install pyproject.toml-based projects

**Comment by wence-** [comment]
There are two problems here:

**Narrow issue**
Our current wheels are not hosted on the official pypi index, but rather nvidia's index. As per https://docs.rapids.ai/install, to install via pip you would use `pip install --extra-index-url=https://pypi.nvidia.com cudf-cu12`. The error you are getting is that we (many moons ago) had cudf packages on pypi, but those are very out of date and so the most recent one has a setup.py that just raises this exception pointing you at conda instead (which was the preferred mechanism to install at the time cudf-0.6.1 was current).

**Wider problem**
cudf, irrespective of the mechanism you use to download binary packages (or build from source), requires that one can install the CUDA driver and CUDA runtime on the target system. This is not possible on an ARM-based Mac, since NVIDIA does not provide CUDA on these systems.

So, unfortunately, there's no way to install and/or run cudf on MacOS.

**Comment by vyasr** [comment]
I'm going to close this issue answered, but feel free to reopen if new information is available. Unfortunately at this point this request cannot be satisfied at a hardware level.
