### ISSUE TITLE
[BUG] Issue installing with pip

### ISSUE THREAD

**Issue by qsimeon** [rapidsai/cudf#14532]
I want to use the pip install command (because I install most of the packages in my environment with pip and want to avoid conflicts). But I get this error:
```
(worm-graph) qsimeon@node100 /om2/user/qsimeon/worm-graph/setup$ pip install --no-cache-dir --force-reinstall \
>     --extra-index-url=https://pypi.nvidia.com \
>     cudf-cu11 dask-cudf-cu11 cuml-cu11 cugraph-cu11 cuspatial-cu11 \
>     cuproj-cu11 cuxfilter-cu11 cucim pylibraft-cu11 raft-dask-cu11

Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
Collecting cudf-cu11
  Downloading cudf-cu11-23.10.2.tar.gz (6.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-3l8mb_ei/cudf-cu11_88ea668e9bea44d1a0a1d01a7a305d3f/setup.py", line 137, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      This package is hosted on NVIDIA Python Package Index.
      
      This package can be installed as:
      ```
      $ pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com cudf-cu11
      ```
      ###########################################################################################
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by bdice** [comment]
It looks like this fetched the placeholder package on PyPI instead of the actual cudf-cu11 package from the NVIDIA index. This normally indicates that you’re using an unsupported Python version or OS. RAPIDS currently supports Python 3.9 and 3.10 on Linux or WSL2. It looks like you’re on Linux so I am guessing the problem is with your Python version. Can you confirm the Python version you’re using?
