### ISSUE TITLE
[QST] how can I use cudf in colab？

### ISSUE THREAD

**Issue by 1jiangxd** [rapidsai/cudf#14660]
# how can I use cudf in colab？
i tried 2 ways to install, but they all failed

## one way
source（https://docs.rapids.ai/install）:
pip install \
    --extra-index-url=https://pypi.nvidia.com \
    cudf-cu12==23.12.* dask-cudf-cu12==23.12.* cuml-cu12==23.12.* \
    cugraph-cu12==23.12.* cuspatial-cu12==23.12.* cuproj-cu12==23.12.* \
    cuxfilter-cu12==23.12.* cucim-cu12==23.12.* pylibraft-cu12==23.12.* \
    raft-dask-cu12==23.12.*

## another way：
source https://colab.research.google.com/drive/13sspqiEZwso4NYTbsflpPyNFaVAAxUgr

after click run all cell ，it didn't work
i still can't use cudf

**Comment by beckernick** [comment]
Hi @1jiangxd , thanks for filing an issue. It looks like Colab has recently upgraded from CUDA Toolkit 11 to 12, so you'll need to use the CUDA 12 packages when installing via pip.

You can install cuDF in Colab with `!pip install cudf-cu12 --extra-index-url=https://pypi.nvidia.com` in a cell when you're connected to an NVIDIA GPU-enabled runtime.

I'm going to close this issue as resolved, but please feel free to reopen it if you run into any other issues installing cuDF.

We'll investigate whether our existing content and installation guides need to be updated to reflect this (cc @taureandyernv @aravenel @bdice , per offline discussion).

**Comment by 1jiangxd** [comment]
thank you for your answer，after i tried the code 
```!pip install cudf-cu12 --extra-index-url=https://pypi.nvidia.com```
it shows:
```
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com/
Collecting cudf-cu12
  Downloading https://pypi.nvidia.com/cudf-cu12/cudf_cu12-23.12.1-cp310-cp310-manylinux_2_28_x86_64.whl (511.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.6/511.6 MB 2.3 MB/s eta 0:00:00
Requirement already satisfied: cachetools in /usr/local/lib/python3.10/dist-packages (from cudf-cu12) (5.3.2)
Collecting cuda-python<13.0a0,>=12.0 (from cudf-cu12)
  Downloading cuda_python-12.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (23.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.6/23.6 MB 27.4 MB/s eta 0:00:00
Requirement already satisfied: cupy-cuda12x>=12.0.0 in /usr/local/lib/python3.10/dist-packages (from cudf-cu12) (12.2.0)
Requirement already satisfied: fsspec>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from cudf-cu12) (2023.6.0)
Collecting numba<0.58,>=0.57 (from cudf-cu12)
  Downloading numba-0.57.1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 43.6 MB/s eta 0:00:00
Requirement already satisfied: numpy<1.25,>=1.21 in /usr/local/lib/python3.10/dist-packages (from cudf-cu12) (1.23.5)
Collecting nvtx>=0.2.1 (from cudf-cu12)
  Downloading nvtx-0.2.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (582 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 582.4/582.4 kB 33.2 MB/s eta 0:00:00
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from cudf-cu12) (23.2)
Requirement already satisfied: pandas<1.6.0dev0,>=1.3 in /usr/local/lib/python3.10/dist-packages (from cudf-cu12) (1.5.3)
Collecting protobuf<5,>=4.21 (from cudf-cu12)
  Downloading protobuf-4.25.1-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.6/294.6 kB 14.9 MB/s eta 0:00:00
Collecting pyarrow<15.0.0a0,>=14.0.1 (from cudf-cu12)
  Downloading pyarrow-14.0.2-cp310-cp310-manylinux_2_28_x86_64.whl (38.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.0/38.0 MB 8.7 MB/s eta 0:00:00
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from cudf-cu12) (13.7.0)
Collecting rmm-cu12==23.12.* (from cudf-cu12)
  Downloading https://pypi.nvidia.com/rmm-cu12/rmm_cu12-23.12.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 46.8 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from cudf-cu12) (4.5.0)
Requirement already satisfied: fastrlock>=0.5 in /usr/local/lib/python3.10/dist-packages (from cupy-cuda12x>=12.0.0->cudf-cu12) (0.8.2)
Collecting llvmlite<0.41,>=0.40.0dev0 (from numba<0.58,>=0.57->cudf-cu12)
  Downloading llvmlite-0.40.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (42.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.1/42.1 MB 9.4 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas<1.6.0dev0,>=1.3->cudf-cu12) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<1.6.0dev0,>=1.3->cudf-cu12) (2023.3.post1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->cudf-cu12) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->cudf-cu12) (2.16.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->cudf-cu12) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas<1.6.0dev0,>=1.3->cudf-cu12) (1.16.0)
Installing collected packages: nvtx, cuda-python, pyarrow, protobuf, llvmlite, numba, rmm-cu12, cudf-cu12
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 10.0.1
    Uninstalling pyarrow-10.0.1:
      Successfully uninstalled pyarrow-10.0.1
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
      Successfully uninstalled protobuf-3.20.3
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.41.1
    Uninstalling llvmlite-0.41.1:
      Successfully uninstalled llvmlite-0.41.1
  Attempting uninstall: numba
    Found existing installation: numba 0.58.1
    Uninstalling numba-0.58.1:
      Successfully uninstalled numba-0.58.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ibis-framework 6.2.0 requires pyarrow<13,>=2, but you have pyarrow 14.0.2 which is incompatible.
tensorboard 2.15.1 requires protobuf<4.24,>=3.19.6, but you have protobuf 4.25.1 which is incompatible.
tensorflow-metadata 1.14.0 requires protobuf<4.21,>=3.20.3, but you have protobuf 4.25.1 which is incompatible.
Successfully installed cuda-python-12.3.0 cudf-cu12-23.12.1 llvmlite-0.40.1 numba-0.57.1 nvtx-0.2.8 protobuf-4.25.1 pyarrow-14.0.2 rmm-cu12-23.12.0
```
then i ran the cell:
```
 import cudf
 print(cudf.Series([1, 2, 3]))
```
but the colab works as follow:
```
/usr/local/lib/python3.10/dist-packages/cudf/utils/_ptxcompiler.py:61: UserWarning: Error getting driver and runtime versions:

stdout:



stderr:

Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/usr/local/lib/python3.10/dist-packages/numba/cuda/cudadrv/driver.py", line 299, in __getattr__
    raise CudaSupportError("Error at driver init: \n%s:" %
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: 

CUDA driver library cannot be found.
If you are sure that a CUDA driver is installed,
try setting environment variable NUMBA_CUDA_DRIVER
with the file path of the CUDA driver shared library.
:


Not patching Numba
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.10/dist-packages/cudf/utils/gpu_utils.py:62: UserWarning: Failed to dlopen libcuda.so.1
  warnings.warn(str(e))
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/cupy/__init__.py](https://localhost:8080/#) in <module>
     16 try:
---> 17     from cupy import _core  # NOQA
     18 except ImportError as exc:

3 frames
[/usr/local/lib/python3.10/dist-packages/cupy/_core/__init__.py](https://localhost:8080/#) in <module>
      2 
----> 3 from cupy._core import core  # NOQA
      4 from cupy._core import fusion  # NOQA

ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
[<ipython-input-1-a185519d2583>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import cudf
      2 print(cudf.Series([1, 2, 3]))

[/usr/local/lib/python3.10/dist-packages/cudf/__init__.py](https://localhost:8080/#) in <module>
     10 validate_setup()
     11 
---> 12 import cupy
     13 from numba import config as numba_config, cuda
     14 

[/usr/local/lib/python3.10/dist-packages/cupy/__init__.py](https://localhost:8080/#) in <module>
     17     from cupy import _core  # NOQA
     18 except ImportError as exc:
---> 19     raise ImportError(f'''
     20 ================================================================
     21 {_environment._diagnose_import_error()}

ImportError: 
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

Original error:
  ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
================================================================


---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by beckernick** [comment]
Seeing that error on Colab often means you're not using a GPU-enabled runtime? Can you confirm that you've selected a GPU runtime type?

If you start fresh and connect to a GPU-enabled runtime, does this still happen?

**Comment by 1jiangxd** [comment]
> Seeing that error on Colab often means you're not using a GPU-enabled runtime. Can you confirm that you've selected a GPU runtime type?
> 
> If you start fresh and connect to a GPU-enabled runtime, does this still happen?

i'm sure i've selected a GPU runtime type?
but it still didn't work

and i have another question:  how can i install cudf through conda on existing environment(created by anaconda) (not base) in my personal computer ？

thank you for your attention

**Comment by beckernick** [comment]
Can you confirm that the following **doesn't** work for you?

- Create a brand new blank Colab notebook
- Click "Runtime", select "Change runtime type", select "T4 GPU" and then click "Save"
- Execute `!pip install cudf-cu12 --extra-index-url=https://pypi.nvidia.com` in the first cell

If this doesn't work, can you run `!nvidia-smi` in a cell and share the output?

The [RAPIDS quick start guide](https://rapids.ai/#quick-start) has instructions that should hopefully get you up and running with conda, if that's preferred.

**Comment by taureandyernv** [comment]
@1jiangxd , Please try https://colab.research.google.com/drive/13sspqiEZwso4NYTbsflpPyNFaVAAxUgr again.  You should be good to go with that.  I'll explain below:

Colab had updated their system nearly 2 weeks ago, which had previously caused the installation to fail.  We had updated our script last week with this pull request, https://github.com/rapidsai-community/rapidsai-csp-utils/pull/92.  Using the link above, it just installed everything correctly for me 3 minutes ago. 

That link that we share also provides you with the correct GPU instance and a T4.  It also contains a script that properly prepares the instance with the right cupy, which is why you are getting your error above.  If you have further issues with the script, please let us know here AND please make an issue in https://github.com/rapidsai-community/rapidsai-csp-utils and tag me in it.

**Comment by 1jiangxd** [comment]
> @1jiangxd , Please try https://colab.research.google.com/drive/13sspqiEZwso4NYTbsflpPyNFaVAAxUgr again. You should be good to go with that. I'll explain below:
> 
> Colab had updated their system nearly 2 weeks ago, which had previously caused the installation to fail. We had updated our script last week with this pull request, [rapidsai-community/rapidsai-csp-utils#92](https://github.com/rapidsai-community/rapidsai-csp-utils/pull/92). Using the link above, it just installed everything correctly for me 3 minutes ago. I think you happened to have tried in the span of time between their change and our fix.
> 
> That link that we share also provides you with the correct GPU runtime instance, which will have a T4. It also contains a script that properly prepares the instance with the right cupy to run RAPIDS, which is why you are getting your latest error above. If you have further issues with the script, please let us know here AND please make an issue in https://github.com/rapidsai-community/rapidsai-csp-utils and tag me in it.

thank you for your attention and work，I will try your solution

**Comment by bdice** [comment]
I verified that the demonstration Colab notebook is working again: https://colab.research.google.com/drive/13sspqiEZwso4NYTbsflpPyNFaVAAxUgr

I'll close this for now, feel free to reopen if needed.
