### ISSUE TITLE
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: Call to cuInit results in CUDA_ERROR_OUT_OF_MEMORY (2)

### ISSUE THREAD

**Issue by jtromans** [rapidsai/cudf#14699]
**Describe the bug**
in Python 3.10
`import cudf` results in:

```
>>> import cudf
/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/cudf/utils/_ptxcompiler.py:61: UserWarning: Error getting driver and runtime versions:

stdout:



stderr:

Traceback (most recent call last):
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 258, in ensure_initialized
    self.cuInit(0)
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 331, in safe_cuda_api_call
    self._check_ctypes_error(fname, retcode)
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 399, in _check_ctypes_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [2] Call to cuInit results in CUDA_ERROR_OUT_OF_MEMORY

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 296, in __getattr__
    self.ensure_initialized()
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 262, in ensure_initialized
    raise CudaSupportError(f"Error at driver init: {description}")
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: Call to cuInit results in CUDA_ERROR_OUT_OF_MEMORY (2)


Not patching Numba
  warnings.warn(msg, UserWarning)
/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/cudf/utils/gpu_utils.py:148: UserWarning: No NVIDIA GPU detected
  warnings.warn("No NVIDIA GPU detected")
Traceback (most recent call last):
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 258, in ensure_initialized
    self.cuInit(0)
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 331, in safe_cuda_api_call
    self._check_ctypes_error(fname, retcode)
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 399, in _check_ctypes_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [2] Call to cuInit results in CUDA_ERROR_OUT_OF_MEMORY


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/cudf/__init__.py", line 27, in <module>    from cudf.core.algorithms import factorize
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/cudf/core/algorithms.py", line 10, in <module>
    from cudf.core.indexed_frame import IndexedFrame
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/cudf/core/indexed_frame.py", line 59, in <module>
    from cudf.core.groupby.groupby import GroupBy
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/cudf/core/groupby/__init__.py", line 3, in <module>
    from cudf.core.groupby.groupby import GroupBy, Grouper
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/cudf/core/groupby/groupby.py", line 31, in <module>
    from cudf.core.udf.groupby_utils import _can_be_jitted, jit_groupby_apply
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/cudf/core/udf/groupby_utils.py", line 11, in <module>
    import cudf.core.udf.utils
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/cudf/core/udf/utils.py", line 66, in <module>
    _PTX_FILE = _get_ptx_file(os.path.dirname(__file__), "shim_")
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/cudf/utils/_numba.py", line 47, in _get_ptx_file
    dev = cuda.get_current_device()
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/numba/cuda/api.py", line 443, in get_current_device
    return current_context().device
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/numba/cuda/cudadrv/devices.py", line 220, in get_context
    return _runtime.get_or_create_context(devnum)
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/numba/cuda/cudadrv/devices.py", line 138, in get_or_create_context
    return self._get_or_create_context_uncached(devnum)
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/numba/cuda/cudadrv/devices.py", line 153, in _get_or_create_context_uncached
    with driver.get_active_context() as ac:
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 499, in __enter__
    driver.cuCtxGetCurrent(byref(hctx))
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 296, in __getattr__
    self.ensure_initialized()
  File "/home/username/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 262, in ensure_initialized
    raise CudaSupportError(f"Error at driver init: {description}")
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: Call to cuInit results in CUDA_ERROR_OUT_OF_MEMORY (2)
```

**Steps/Code to reproduce bug**
- Host OS Name Microsoft Windows 11 Pro Version 10.0.22621 Build 22621
- Running latest NVIDIA drivers (546.33) on host
- WSL2 with fresh install of Ubuntu 22.04.3 LTS
- Installed Miniconda3-py310_23.11.0-2-Linux-x86_64.sh
- Installed RAPIDS via WSL2 Conda Install (Preferred Method)
- Specific command executed in WSL2 `conda create --solver=libmamba -n rapids-23.12 -c rapidsai -c conda-forge -c nvidia  rapids=23.12 python=3.10 cuda-version=12.0`
- Activated rapids-23.12
- In Python shell, run `import cudf` and obtain the above error stack

nvidia-smi command in host and WSL2 shows this:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.36                 Driver Version: 546.33       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2080 Ti     On  | 00000000:19:00.0 Off |                  N/A |
|  0%   32C    P8              17W / 260W |      0MiB / 11264MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 2080 Ti     On  | 00000000:1A:00.0 Off |                  N/A |
|  0%   32C    P8               4W / 260W |     14MiB / 11264MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce RTX 2080 Ti     On  | 00000000:67:00.0 Off |                  N/A |
|  0%   32C    P8               3W / 260W |      0MiB / 11264MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce RTX 2080 Ti     On  | 00000000:68:00.0  On |                  N/A |
|  0%   33C    P5              36W / 260W |   1047MiB / 11264MiB |      8%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A        32      G   /Xwayland                                 N/A      |
|    1   N/A  N/A        32      G   /Xwayland                                 N/A      |
|    2   N/A  N/A        32      G   /Xwayland                                 N/A      |
|    3   N/A  N/A        32      G   /Xwayland                                 N/A      |
+---------------------------------------------------------------------------------------+
```

Please advise!

**Comment by quasiben** [comment]
I'm sorry, i misread the issue.  This seems like you are running out of memory when initializing a CUDA Context.  What happens when you import cupy ?

**Comment by jtromans** [comment]
import cupy worked successfully without an error.

**Comment by quasiben** [comment]
After you import cupy can you show what nvida-smi returns ?

**Comment by jtromans** [comment]
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.36                 Driver Version: 546.33       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2080 Ti     On  | 00000000:19:00.0 Off |                  N/A |
|  0%   31C    P8              15W / 260W |      0MiB / 11264MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 2080 Ti     On  | 00000000:1A:00.0 Off |                  N/A |
|  0%   31C    P8               3W / 260W |     14MiB / 11264MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce RTX 2080 Ti     On  | 00000000:67:00.0 Off |                  N/A |
|  0%   31C    P8               4W / 260W |      0MiB / 11264MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA GeForce RTX 2080 Ti     On  | 00000000:68:00.0  On |                  N/A |
|  0%   33C    P8              31W / 260W |   1008MiB / 11264MiB |     29%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A        32      G   /Xwayland                                 N/A      |
|    1   N/A  N/A        32      G   /Xwayland                                 N/A      |
|    2   N/A  N/A        32      G   /Xwayland                                 N/A      |
|    3   N/A  N/A        32      G   /Xwayland                                 N/A      |
+---------------------------------------------------------------------------------------+
```

**Comment by quasiben** [comment]
Hmm, can you try using another GPU and seeing what happens.  Can you also tell us what the `/Xwayland` process is ?  The CUDA Context should only take ~300 MBs of GPU memory so you should be fine.  The fact that when creating CuPy arrays is also failing leads me to believe something outside of cuDF/RAPIDS is a problem. 

The following will using GPU DEVICE 2
> CUDA_VISIBLE_DEVICES=2 python

**Comment by jtromans** [comment]
Xwayland is an X server for running X clients under Wayland. Xwayland is installed by default in Ubuntu 22.04.

Remember that I am using WSL so I think only 1 GPU is available to the Linus subsystem. 

When I try `CUDA_VISIBLE_DEVICES=2 python` I get this error when I try to do the cp.array()

```
>>> import cupy as cp
>>> x_gpu = cp.array([1, 2, 3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jtromans/miniconda3/envs/rapids-23.12/lib/python3.10/site-packages/cupy/_creation/from_data.py", line 46, in array
    return _core.array(obj, dtype, copy, order, subok, ndmin)
  File "cupy/_core/core.pyx", line 2376, in cupy._core.core.array
  File "cupy/_core/core.pyx", line 2400, in cupy._core.core.array
  File "cupy/_core/core.pyx", line 2531, in cupy._core.core._array_default
  File "cupy/_core/core.pyx", line 132, in cupy._core.core.ndarray.__new__
  File "cupy/_core/core.pyx", line 220, in cupy._core.core._ndarray_base._init
  File "cupy/cuda/memory.pyx", line 740, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1426, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1447, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1118, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1139, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 1367, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
  File "cupy/cuda/memory.pyx", line 1364, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
  File "cupy/cuda/memory.pyx", line 1089, in cupy.cuda.memory.SingleDeviceMemoryPool._alloc
  File "cupy/cuda/memory.pyx", line 635, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 636, in cupy.cuda.memory._malloc
  File "cupy/cuda/memory.pyx", line 101, in cupy.cuda.memory.Memory.__init__
  File "cupy_backends/cuda/api/runtime.pyx", line 475, in cupy_backends.cuda.api.runtime.malloc
  File "cupy_backends/cuda/api/runtime.pyx", line 144, in cupy_backends.cuda.api.runtime.check_status
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorDevicesUnavailable: CUDA-capable device(s) is/are busy or unavailable
```

**Comment by jtromans** [comment]
Interestingly, when I specifically do `CUDA_VISIBLE_DEVICES=1 python` the `x_gpu = cp.array([1, 2, 3])` runs successfully. I will keep looking in to this and report back. I might be because I have multiple GPUs and that creates an issue.

**Comment by jtromans** [comment]
```
(rapids-23.12) jtromans@DESKTOP-MGL63Q8:~/miniconda$ CUDA_VISIBLE_DEVICES=1 python
Python 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf
>>> print(cudf.Series([1, 2, 3]))
0    1
1    2
2    3
dtype: int64
>>>
```

**Comment by bdice** [comment]
Out of curiosity, is there something peculiar about device 2? It looked like nvidia-smi was reporting that you have four RTX 2080 Ti devices. That is a supported GPU but it’s not clear to me why only three of the four would work.
