### ISSUE TITLE
[BUG] Error when installing cuDF (Windows 11, CUDA 12, Python 3.12)

### ISSUE THREAD

**Issue by masbicudo** [rapidsai/cudf#15413]
**Describe the bug**
I am trying to install cuDF in a Python environment under Windws 11. Is this possible?

**Steps/Code to reproduce bug**
Just install using pip:
```bash
pip install --extra-index-url=https://pypi.nvidia.com --no-cache-dir cudf-cu12
```

**Expected behavior**
Installed cudf

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal, Windows 11, Python 3.12, CUDA 12
 - Method of cuDF install: pip
   - `pip install --extra-index-url=https://pypi.nvidia.com --no-cache-dir cudf-cu12`

**Environment details**
```
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     Not inside a git repository

     ***OS Information***
cat: '/etc/*-release': No such file or directory
     MINGW64_NT-10.0-22631 Note-Avell-MASB 3.4.10-87d57229.x86_64 2024-02-14 20:17 UTC x86_64 Msys

     ***GPU Information***
     Fri Mar 29 12:34:37 2024       
     +-----------------------------------------------------------------------------------------+
     | NVIDIA-SMI 551.76                 Driver Version: 551.76         CUDA Version: 12.4     |
     |-----------------------------------------+------------------------+----------------------+
     | GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
     |                                         |                        |               MIG M. |
     |=========================================+========================+======================|
     |   0  NVIDIA GeForce RTX 3060 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
     | N/A   55C    P8             18W /  120W |    1576MiB /   6144MiB |     16%      Default |
     |                                         |                        |                  N/A |
     +-----------------------------------------+------------------------+----------------------+

     +-----------------------------------------------------------------------------------------+
     | Processes:                                                                              |
     |  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
     |        ID   ID                                                               Usage      |
     |=========================================================================================|
     |    0   N/A  N/A      2952    C+G   C:\Windows\explorer.exe                     N/A      |
     |    0   N/A  N/A      3416    C+G   ...4.0_x64__cv1g1gvanyjgm\WhatsApp.exe      N/A      |
     |    0   N/A  N/A      5404    C+G   ...crosoft\Edge\Application\msedge.exe      N/A      |
     |    0   N/A  N/A      5872    C+G   ...5n1h2txyewy\ShellExperienceHost.exe      N/A      |
     |    0   N/A  N/A      6840    C+G   ...wekyb3d8bbwe\XboxGameBarWidgets.exe      N/A      |
     |    0   N/A  N/A      6904    C+G   ...m Files\SyncTrayzor\SyncTrayzor.exe      N/A      |
     |    0   N/A  N/A      9964    C+G   ....0_x64__8wekyb3d8bbwe\HxOutlook.exe      N/A      |
     |    0   N/A  N/A     16392    C+G   ...__8wekyb3d8bbwe\WindowsTerminal.exe      N/A      |
     |    0   N/A  N/A     16424    C+G   ...werToys\PowerToys.PowerLauncher.exe      N/A      |
     |    0   N/A  N/A     17316    C+G   ...ys\WinUI3Apps\PowerToys.Peek.UI.exe      N/A      |
     |    0   N/A  N/A     18924    C+G   ...ram Files\paint.net\paintdotnet.exe      N/A      |
     |    0   N/A  N/A     18968    C+G   ...GeForce Experience\NVIDIA Share.exe      N/A      |
     |    0   N/A  N/A     19136    C+G   ...GeForce Experience\NVIDIA Share.exe      N/A      |
     |    0   N/A  N/A     19372    C+G   ...nt.CBS_cw5n1h2txyewy\SearchHost.exe      N/A      |
     |    0   N/A  N/A     20572    C+G   ...siveControlPanel\SystemSettings.exe      N/A      |
     |    0   N/A  N/A     21572    C+G   ...2txyewy\StartMenuExperienceHost.exe      N/A      |
     |    0   N/A  N/A     22904    C+G   ...41.0_x64__8wekyb3d8bbwe\GameBar.exe      N/A      |
     |    0   N/A  N/A     24596      C   ...yenv-win\versions\3.10.6\python.exe      N/A      |
     |    0   N/A  N/A     27484    C+G   ...am Files\Microsoft VS Code\Code.exe      N/A      |
     |    0   N/A  N/A     31128    C+G   ...ekyb3d8bbwe\PhoneExperienceHost.exe      N/A      |
     |    0   N/A  N/A     34544    C+G   ...on\122.0.2365.92\msedgewebview2.exe      N/A      |
     |    0   N/A  N/A     38256    C+G   ...e Stream\88.0.0.0\GoogleDriveFS.exe      N/A      |
     |    0   N/A  N/A     40132    C+G   ...les\Microsoft OneDrive\OneDrive.exe      N/A      |
     +-----------------------------------------------------------------------------------------+
     
     ***CPU***
./print_env.sh: line 30: lscpu: command not found

     ***CMake***
which: no cmake in (/c/Users/masbi/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/masbi/bin:/c/Program Files/PowerShell/7:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.4/bin:/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.4/libnvvp:/c/texlive/2024/bin/windows:/c/tools/ruby33/bin:/c/Program Files/Microsoft MPI/Bin:/c/texlive/2023/bin/windows:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/Users/masbi/.pyenv/pyenv-win/bin:/c/Users/masbi/.pyenv/pyenv-win/shims:/c/tools/ruby31/bin:/c/Program Files/Microsoft/jdk-11.0.16.101-hotspot/bin:/c/Windows/system32:/c/tools/Python3x/Scripts:/c/tools/Python3x:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/ProgramData/chocolatey/bin:/c/Program Files/Microsoft VS Code/bin:/c/Program Files/PostgreSQL/14/bin:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/c/Program Files/dotnet:/c/Shortcuts:/c/ProgramData/nvm:/c/Program Files/Microsoft SQL Server/150/Tools/Binn:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files (x86)/GitExtensions:/c/Program Files/PostgreSQL/15/bin:/c/texlive/2022/bin/win32:/c/ProgramData/nvm:/c/Program Files/nodejs:/c/Program Files (x86)/Microsoft SQL Server/160/DTS/Binn:/c/Program Files/Azure Data Studio/bin:/c/Program Files (x86)/Microsoft SQL Server/160/Tools/Binn:/c/Program Files/Microsoft SQL Server/160/Tools/Binn:/c/Program Files/Microsoft SQL Server/160/DTS/Binn:/c/Program Files/PowerShell/7:/c/Program Files/Amazon/AWSCLIV2:/c/Program Files/Amazon/SessionManagerPlugin/bin:/c/Program Files/Docker/Docker/resources/bin:/c/Program Files/GitHub CLI:/cmd:/mingw64/bin:/usr/bin:/c/Program Files/PostgreSQL/16/bin:/c/Program Files/NVIDIA Corporation/Nsight Compute 2024.1.0:/c/Users/masbi/AppData/Local/pnpm:/c/users/masbi/appdata/local/pnpm:/c/tools/ruby31/bin:/c/users/masbi/appdata/local/microsoft/windowsapps:/c/program files/kdiff3:/c/program files/oracle/virtualbox:/c/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin:/c/programdata/nvm:/c/users/masbi/.local/bin:/c/users/masbi/appdata/roaming/python/python310/scripts:/c/users/masbi/appdata/local/programs/oh-my-posh/bin:/c/users/masbi/.dotnet/tools:/c/Users/masbi/.dotnet/tools:/c/ghcup/bin:/c/Users/masbi/appdata/local/microsoft/windowsapps:/c/ProgramData/nvm:/c/Program Files/nodejs:/c/users/masbi/appdata/local/pandoc:/c/users/masbi/appdata/roaming/python/scripts:/c/Program Files/Azure Data Studio/bin:/c/users/masbi/.pyprojectx:/c/Users/masbi/AppData/Roaming/cabal/bin:/c/tools/ghc-9.8.1/bin:/c/ProgramData/mingw64/mingw64/bin:/c/Users/masbi/.pyenv/pyenv-win/bin:/c/Users/masbi/.pyenv/pyenv-win/shims:/c/ProgramData/nvm:/c/Program Files/nodejs:/usr/bin/vendor_perl:/usr/bin/core_perl)

     ***g++***
     /c/ProgramData/mingw64/mingw64/bin/g++
     g++.exe (x86_64-posix-seh-rev0, Built by MinGW-Builds project) 13.2.0
     Copyright (C) 2023 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


     ***nvcc***
     /c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.4/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2024 NVIDIA Corporation
     Built on Tue_Feb_27_16:28:36_Pacific_Standard_Time_2024
     Cuda compilation tools, release 12.4, V12.4.99
     Build cuda_12.4.r12.4/compiler.33961263_0

     ***Python***
     /c/Users/masbi/.pyenv/pyenv-win/shims/python
     Python 3.12.2

     ***Environment Variables***
     PATH                            : /c/Users/masbi/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/masbi/bin:/c/Program
     Files/PowerShell/7:/c/Program   : Files/NVIDIA
     GPU                             : Computing
     Toolkit/CUDA/v12.4/bin:/c/Program: Files/NVIDIA
     GPU                             : Computing
     Toolkit/CUDA/v12.4/libnvvp:/c/texlive/2024/bin/windows:/c/tools/ruby33/bin:/c/Program: Files/Microsoft  
     MPI/Bin:/c/texlive/2023/bin/windows:/c/Program: Files
     (x86)/Common                    : Files/Oracle/Java/javapath:/c/Users/masbi/.pyenv/pyenv-win/bin:/c/Users/masbi/.pyenv/pyenv-win/shims:/c/tools/ruby31/bin:/c/Program
     Files/Microsoft/jdk-11.0.16.101-hotspot/bin:/c/Windows/system32:/c/tools/Python3x/Scripts:/c/tools/Python3x:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Windows/System32/OpenSSH:/c/ProgramData/chocolatey/bin:/c/Program: Files/Microsoft
     VS                              : Code/bin:/c/Program
     Files/PostgreSQL/14/bin:/c/Program: Files
     (x86)/NVIDIA                    : Corporation/PhysX/Common:/c/Program
     Files/NVIDIA                    : Corporation/NVIDIA
     NvDLISR:/c/Program              : Files/dotnet:/c/Shortcuts:/c/ProgramData/nvm:/c/Program
     Files/Microsoft                 : SQL
     Server/150/Tools/Binn:/c/Program: Files/Microsoft
     SQL                             : Server/Client
     SDK/ODBC/170/Tools/Binn:/c/Program: Files/Microsoft
     SQL                             : Server/130/Tools/Binn:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program
     Files                           : (x86)/GitExtensions:/c/Program
     Files/PostgreSQL/15/bin:/c/texlive/2022/bin/win32:/c/ProgramData/nvm:/c/Program: Files/nodejs:/c/Program
     Files                           : (x86)/Microsoft
     SQL                             : Server/160/DTS/Binn:/c/Program
     Files/Azure                     : Data
     Studio/bin:/c/Program           : Files
     (x86)/Microsoft                 : SQL
     Server/160/Tools/Binn:/c/Program: Files/Microsoft
     SQL                             : Server/160/Tools/Binn:/c/Program
     Files/Microsoft                 : SQL
     Server/160/DTS/Binn:/c/Program  : Files/PowerShell/7:/c/Program
     Files/Amazon/AWSCLIV2:/c/Program: Files/Amazon/SessionManagerPlugin/bin:/c/Program
     Files/Docker/Docker/resources/bin:/c/Program: Files/GitHub
     CLI:/cmd:/mingw64/bin:/usr/bin:/c/Program: Files/PostgreSQL/16/bin:/c/Program
     Files/NVIDIA                    : Corporation/Nsight
     Compute                         : 2024.1.0:/c/Users/masbi/AppData/Local/pnpm:/c/users/masbi/appdata/local/pnpm:/c/tools/ruby31/bin:/c/users/masbi/appdata/local/microsoft/windowsapps:/c/program
     files/kdiff3:/c/program         : files/oracle/virtualbox:/c/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin:/c/programdata/nvm:/c/users/masbi/.local/bin:/c/users/masbi/appdata/roaming/python/python310/scripts:/c/users/masbi/appdata/local/programs/oh-my-posh/bin:/c/users/masbi/.dotnet/tools:/c/Users/masbi/.dotnet/tools:/c/ghcup/bin:/c/Users/masbi/appdata/local/microsoft/windowsapps:/c/ProgramData/nvm:/c/Program      
     Files/nodejs:/c/users/masbi/appdata/local/pandoc:/c/users/masbi/appdata/roaming/python/scripts:/c/Program: Files/Azure
     Data                            : Studio/bin:/c/users/masbi/.pyprojectx:/c/Users/masbi/AppData/Roaming/cabal/bin:/c/tools/ghc-9.8.1/bin:/c/ProgramData/mingw64/mingw64/bin:/c/Users/masbi/.pyenv/pyenv-win/bin:/c/Users/masbi/.pyenv/pyenv-win/shims:/c/ProgramData/nvm:/c/Program
     Files/nodejs:/usr/bin/vendor_perl:/usr/bin/core_perl:
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    :
     PYTHON_PATH                     :

     conda not found
     ***pip packages***
     /c/Users/masbi/.pyenv/pyenv-win/shims/pip
     Package    Version
     ---------- -------
     pip        24.0
     setuptools 69.2.0
     
</pre></details>
```

**Additional context**
Output of the pip command:
```
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
Collecting cudf-cu12
  Downloading cudf-cu12-24.2.2.tar.gz (6.9 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Users\masbi\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\masbi\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\masbi\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\masbi\AppData\Local\Temp\pip-build-env-hqo8nkgq\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\masbi\AppData\Local\Temp\pip-build-env-hqo8nkgq\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\masbi\AppData\Local\Temp\pip-build-env-hqo8nkgq\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\masbi\AppData\Local\Temp\pip-build-env-hqo8nkgq\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 90, in <module>
      RuntimeError: Bad params
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by bdice** [comment]
Hi @masbicudo, please review the installation guide here. https://docs.rapids.ai/install

Windows is only supported through WSL and not native Windows. Python 3.9-3.11 are supported but not 3.12.
