### ISSUE TITLE
[BUG] Fail to install in python 3.11.9

### ISSUE THREAD

**Issue by Camilochiang** [rapidsai/cudf#15565]
Environment:

python 3.11.9
rapids 24.04
nvidia driver 520.61.05
CUDA version 11.8
Ubuntu 22.04.4 LTS`

```
python -m pip install \
    --extra-index-url=https://pypi.nvidia.com \
    cudf-cu11==24.4.* dask-cudf-cu11==24.4.* cuml-cu11==24.4.* \
    cugraph-cu11==24.4.* cuspatial-cu11==24.4.* cuproj-cu11==24.4.* \
    cuxfilter-cu11==24.4.* cucim-cu11==24.4.* pylibraft-cu11==24.4.* \
    raft-dask-cu11==24.4.* cuvs-cu11==24.4.*
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
Collecting cudf-cu11==24.4.*
  Using cached https://pypi.nvidia.com/cudf-cu11/cudf_cu11-24.4.0-cp311-cp311-manylinux_2_28_x86_64.whl (471.9 MB)
Collecting dask-cudf-cu11==24.4.*
  Using cached https://pypi.nvidia.com/dask-cudf-cu11/dask_cudf_cu11-24.4.0-py3-none-any.whl (48 kB)
Collecting cuml-cu11==24.4.*
  Using cached https://pypi.nvidia.com/cuml-cu11/cuml_cu11-24.4.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1270.1 MB)
Collecting cugraph-cu11==24.4.*
  Using cached https://pypi.nvidia.com/cugraph-cu11/cugraph_cu11-24.4.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1486.5 MB)
Collecting cuspatial-cu11==24.4.*
  Using cached https://pypi.nvidia.com/cuspatial-cu11/cuspatial_cu11-24.4.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (135.6 MB)
Collecting cuproj-cu11==24.4.*
  Using cached https://pypi.nvidia.com/cuproj-cu11/cuproj_cu11-24.4.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (947 kB)
Collecting cuxfilter-cu11==24.4.*
  Using cached https://pypi.nvidia.com/cuxfilter-cu11/cuxfilter_cu11-24.4.1-py3-none-any.whl (83 kB)
Collecting cucim-cu11==24.4.*
  Using cached https://pypi.nvidia.com/cucim-cu11/cucim_cu11-24.4.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.8 MB)
Collecting pylibraft-cu11==24.4.*
  Using cached https://pypi.nvidia.com/pylibraft-cu11/pylibraft_cu11-24.4.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (823.6 MB)
Collecting raft-dask-cu11==24.4.*
  Using cached https://pypi.nvidia.com/raft-dask-cu11/raft_dask_cu11-24.4.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (214.7 MB)
Collecting cuvs-cu11==24.4.*
  Using cached https://pypi.nvidia.com/cuvs-cu11/cuvs_cu11-24.4.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (610.3 MB)
Collecting cachetools (from cudf-cu11==24.4.*)
  Using cached cachetools-5.3.3-py3-none-any.whl.metadata (5.3 kB)
Collecting cubinlinker-cu11 (from cudf-cu11==24.4.*)
  Using cached cubinlinker_cu11-0.3.0.post1.tar.gz (6.5 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/virtualenvs/AGS_3_11_venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/virtualenvs/AGS_3_11_venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/virtualenvs/AGS_3_11_venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-75ppppzr/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-75ppppzr/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-75ppppzr/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-75ppppzr/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 81, in <module>
      RuntimeError: Bad params
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
````

Posible due no wheel for [cubinlinker-cu11](https://pypi.nvidia.com/cubinlinker-cu11/) and Python 3.11 yet.

**Comment by bdice** [comment]
Thanks for the report @Camilochiang -- we have nightly builds for Python 3.11, but perhaps these didn't make it to the release channel. You can try running `pip install -i https://pypi.anaconda.org/rapidsai-wheels-nightly/simple cubinlinker-cu11` to work around this in the immediate term. I've followed up with our devops team to check on the status.
