### ISSUE TITLE
I am not able to install cudf with Cuda12.4 python 3.11.7 driver = 551 [BUG] 

### ISSUE THREAD

**Issue by harsh123-baba** [rapidsai/cudf#15711]
**While installing the cudf **
i tried to install cudf in my windows machine that is having RTX 6000 GPU and python 3.11.7

`
(env) PS F:\Harshit\harshit_k9> pip install cudf-cu12  --extra-index-url=https://pypi.nvidia.com/    
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com/
Collecting cudf-cu12
  Using cached cudf_cu12-24.4.1.tar.gz (2.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
        File "C:\Users\RT Lab\AppData\Local\Temp\pip-build-env-4qjfae_n\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 147, in download_wheel
          return download_manual(wheel_directory, distribution, version)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\RT Lab\AppData\Local\Temp\pip-build-env-4qjfae_n\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 114, in download_manual
          raise RuntimeError(f"Didn't find wheel for {distribution} {version}")
      Traceback (most recent call last):
        File "C:\Users\RT Lab\AppData\Local\Temp\pip-build-env-4qjfae_n\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 147, in download_wheel
          return download_manual(wheel_directory, distribution, version)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\RT Lab\AppData\Local\Temp\pip-build-env-4qjfae_n\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 114, in download_manual
          raise RuntimeError(f"Didn't find wheel for {distribution} {version}")
      RuntimeError: Didn't find wheel for cudf-cu12 24.4.1
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "F:\Harshit\harshit_k9\env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "F:\Harshit\harshit_k9\env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\Harshit\harshit_k9\env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\RT Lab\AppData\Local\Temp\pip-build-env-4qjfae_n\overlay\Lib\site-packages\nvidia_stub\buildapi.py", line 29, in build_wheel
          return download_wheel(pathlib.Path(wheel_directory), config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\RT Lab\AppData\Local\Temp\pip-build-env-4qjfae_n\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 149, in download_wheel
          report_install_failure(distribution, version, exception_context)
        File "C:\Users\RT Lab\AppData\Local\Temp\pip-build-env-4qjfae_n\overlay\Lib\site-packages\nvidia_stub\error.py", line 63, in report_install_failure
          raise InstallFailedError(
      nvidia_stub.error.InstallFailedError:
      *******************************************************************************
     
      The installation of cudf-cu12 for version 24.4.1 failed.
     
      This is a special placeholder package which downloads a real wheel package
      from https://pypi.nvidia.com. If https://pypi.nvidia.com is not reachable, we
      cannot download the real wheel file to install.
     
      You might try installing this package via
      ```
      $ pip install --extra-index-url https://pypi.nvidia.com cudf-cu12
      ```
     
      Here is some debug information about your platform to include in any bug
      report:
     
      Python Version: CPython 3.11.7
      Operating System: Windows 10
      CPU Architecture: AMD64
      Driver Version: 551.61
      CUDA Version: 12.4
     
      *******************************************************************************
     
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

`

**Comment by beckernick** [comment]
It looks like you're trying to install cuDF on your raw Windows system. To use cuDF on Windows, you need to use WSL2 (Windows Subsystem for Linux).

The [RAPIDS Quick Start](https://rapids.ai/#quick-start) has a link to the [RAPIDS on WSL2 installation instructions](https://docs.rapids.ai/install#wsl2), which should hopefully get you up and running.

I'm going to close this issue, but please feel free to re-open if you run into any issues!
