### ISSUE TITLE
Assertion error while using applymap to change the output dtype 

### ISSUE THREAD

**Issue by Salonijain27** [rapidsai/cudf#162]
I ran the following lines:
```
import pandas as pd                   
from pygdf import DataFrame   
df_pygdf = DataFrame()    
df_pygdf["col_1"] = [1,2,3,4,5,6,7]     
df_pygdf["col_1"] = df_pygdf["col_1"].applymap(lambda x: float(x),out_dtype=float)    
```
and obtained the error:
```
Traceback (most recent call last):
  File "example_code.py", line 11, in <module>
    df_pygdf["col_1"] = df_pygdf["col_1"].applymap(lambda x: float(x),out_dtype=float)
  File "/conda/envs/gdf/lib/python3.6/site-packages/pygdf-0.1.0a2+212.g8636cc6-py3.6.egg/pygdf/series.py", line 638, in applymap
    res_col = self._column.applymap(udf, out_dtype=out_dtype)
  File "/conda/envs/gdf/lib/python3.6/site-packages/pygdf-0.1.0a2+212.g8636cc6-py3.6.egg/pygdf/numerical.py", line 222, in applymap
    return self.replace(data=out)
  File "/conda/envs/gdf/lib/python3.6/site-packages/pygdf-0.1.0a2+212.g8636cc6-py3.6.egg/pygdf/column.py", line 285, in replace
    return type(self)(**params)
  File "/conda/envs/gdf/lib/python3.6/site-packages/pygdf-0.1.0a2+212.g8636cc6-py3.6.egg/pygdf/numerical.py", line 62, in __init__
    assert self._dtype == self._data.dtype
AssertionError
```

**Comment by Salonijain27** [comment]
workaround for the above issue is to use astype on the column, we can add 'astype' to convert the data into the required dtype.
 import pandas as pd                   
from pygdf import DataFrame   
df_pygdf = DataFrame()    
df_pygdf["col_1"] = [1,2,3,4,5,6,7]     
df_pygdf["col_1"] = df_pygdf["col_1"].applymap(lambda x: float(x)).astype(float)
