### ISSUE TITLE
[BUG] UnicodeDecodeError: 'cp949' codec can't decode byte 0xf0 in position 2252: illegal multibyte sequence

### ISSUE THREAD

**Issue by nogader** [rapidsai/cudf#16699]
When the installation command is executed, following error message is generated; 

```(venv) C:\>pip install --extra-index-url=https://pypi.nvidia.com cudf-cu12```
```
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
Collecting cudf-cu12
  Using cached cudf_cu12-24.8.2.tar.gz (2.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "C:\Users\anonymous\miniconda3\envs\main\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\anonymous\miniconda3\envs\main\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\anonymous\miniconda3\envs\main\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\anonymous\AppData\Local\Temp\pip-build-env-ujt0e2xi\overlay\Lib\site-packages\nvidia_stub\buildapi.py", line 29, in build_wheel
          return download_wheel(pathlib.Path(wheel_directory), config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\anonymous\AppData\Local\Temp\pip-build-env-ujt0e2xi\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 171, in download_wheel
          metadata = get_metadata_from_pkg_info(src_dir)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\anonymous\AppData\Local\Temp\pip-build-env-ujt0e2xi\overlay\Lib\site-packages\nvidia_stub\wheel.py", line 165, in get_metadata_from_pkg_info
          pkg_info = f.read()
                     ^^^^^^^^
      UnicodeDecodeError: 'cp949' codec can't decode byte 0xf0 in position 2252: illegal multibyte sequence
      [end of output]


  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

my pc spec:
cpu: 13980hx
gpu: 4080 mobile
ram: 32gb
nvidia driver: 560.81
cuda: 12.6
os: english windows 11 with japanese and korean language input system installed 

i suspect it has something to do with korean input system since cp949 is korean language codec but don't know exact solution to this problem.  

any suggestions?

thank you.

**Comment by davidwendt** [comment]
We don't support Windows yet https://github.com/rapidsai/cudf/issues/28
