### ISSUE TITLE
[BUG] Cython should now be a dependency of the cudf conda package

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#1686]
After installing cudf from the rapidsai-nightly channel, I'm trying to start a dask-cuda-worker process but get errors about needing Cython.

Looks like the cudf conda package needs to mark Cython as pre-req.

```
dask-cuda-worker ${hostname}:${port}
```

```
Traceback (most recent call last):
  File "/opt/conda/bin/dask-cuda-worker", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cython' distribution was not found and is required by cudf
```

**Comment by kkraus14** [comment]
Fixed by #1694
