### ISSUE TITLE
[FEA] Implement col_level keyword argument for melt

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1721]
To utilize `cudf.melt`, dask-cudf needs the `col_level` keyword implemented in `cudf.melt`.

Without it, we run into the following:

```
import cudf
from dask.dataframe import melt
sample = cudf.DataFrame({'a':[1,2,3], 'b':[4,5,6], 'c':[7,8,9]})
dsample = dask_cudf.from_cudf(sample, npartitions=2)
print(sample)
print(melt(dsample, id_vars=['a'], value_vars=['b', 'c']))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    155     try:
--> 156         yield
    157     except Exception as e:

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   3764     with raise_on_meta_error(funcname(func), udf=kwargs.pop('udf', False)):
-> 3765         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   3766 

/conda/envs/rapids/lib/python3.7/site-packages/dask/utils.py in __call__(self, obj, *args, **kwargs)
    771     def __call__(self, obj, *args, **kwargs):
--> 772         return getattr(obj, self.method)(*args, **kwargs)
    773 

/conda/envs/rapids/lib/python3.7/site-packages/cudf-0.7.0+212.gbf3764e7.dirty-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py in melt(self, **kwargs)
   1340         from cudf.reshape.general import melt
-> 1341         return melt(self, **kwargs)
   1342 

TypeError: melt() got an unexpected keyword argument 'col_level'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-167-a5fd130cf759> in <module>
      4 dsample = dask_cudf.from_cudf(sample, npartitions=2)
      5 print(sample)
----> 6 print(melt(dsample, id_vars=['a'], value_vars=['b', 'c']))

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/reshape.py in melt(frame, id_vars, value_vars, var_name, value_name, col_level)
    245                                 value_vars=value_vars,
    246                                 var_name=var_name, value_name=value_name,
--> 247                                 col_level=col_level, token='melt')

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in map_partitions(self, func, *args, **kwargs)
    561         >>> ddf.map_partitions(func).clear_divisions()  # doctest: +SKIP
    562         """
--> 563         return map_partitions(func, self, *args, **kwargs)
    564 
    565     @insert_meta_param_description(pad=12)

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in map_partitions(func, *args, **kwargs)
   3803         # Use non-normalized kwargs here, as we want the real values (not
   3804         # delayed values)
-> 3805         meta = _emulate(func, *args, udf=True, **kwargs)
   3806     else:
   3807         meta = make_meta(meta, index=meta_index)

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   3763     """
   3764     with raise_on_meta_error(funcname(func), udf=kwargs.pop('udf', False)):
-> 3765         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   3766 
   3767 

/conda/envs/rapids/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    171                 "{2}")
    172         msg = msg.format(" in `{0}`".format(funcname) if funcname else "", repr(e), tb)
--> 173         raise ValueError(msg)
    174 
    175 

ValueError: Metadata inference failed in `melt`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
TypeError("melt() got an unexpected keyword argument 'col_level'")

Traceback:
---------
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/utils.py", line 156, in raise_on_meta_error
    yield
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py", line 3765, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask/utils.py", line 772, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
  File "/conda/envs/rapids/lib/python3.7/site-packages/cudf-0.7.0+212.gbf3764e7.dirty-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py", line 1341, in melt
    return melt(self, **kwargs)
```

We can probably either implement this as a placeholder that does nothing (and assert that the kwarg is None) (though I haven't tested whether that would resolve the downstream dask issue) or actually implement the functionality now that we have MultiIndex.

**Comment by beckernick** [comment]
Implementing `col_level=None` as a keyword argument does resolve the downstream dask-cudf issue. I would vote we make a quick PR to do just this small change, instead of actually implementing multi-level melt (which will likely take some careful consideration). I'll do this now.

If others disagree, whoever takes on multi-index melt can just supersede my PR.
