### ISSUE TITLE
[BUG] Categorical Series prevent use of `to_cupy` method

### ISSUE THREAD

**Issue by wphicks** [rapidsai/cudf#17381]
**Describe the bug**
Currently, if a cuDF dataframe includes a categorical series, it cannot be converted to a cupy array using the `to_cupy` method.

**Steps/Code to reproduce bug**
```python
import cudf
import pandas as pd

if __name__ == '__main__':
    pd_df = pd.DataFrame({
        "A": pd.Series(["a", "b"], dtype="category")
    })
    cudf_df = cudf.DataFrame({
        "A": cudf.Series(["a", "b"], dtype="category")
    })

    print("PANDAS")
    print(pd_df.to_numpy())  # Succeeds
    print("cuDF")
    print(cudf_df.to_cupy())  # Raises NotImplementedError
```

**Expected behavior**
Categorical series conversion to cupy arrays should follow the pattern set by Pandas for conversion to numpy arrays.

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda

**Comment by wphicks** [comment]
As requested offline, output of the test case:
```
$ python test_categorical.py
PANDAS
[['a']
 ['b']]
cuDF
Traceback (most recent call last):
  File "/raid/whicks/proj_cuml/test_categorical.py", line 15, in <module>
    print(cudf_df.to_cupy())
          ^^^^^^^^^^^^^^^^^
  File "/raid/whicks/miniforge3/envs/cuml_dev/lib/python3.12/site-packages/cudf/utils/performance_tracking.py", line 51, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/raid/whicks/miniforge3/envs/cuml_dev/lib/python3.12/site-packages/cudf/core/frame.py", line 496, in to_cupy
    return self._to_array(
           ^^^^^^^^^^^^^^^
  File "/raid/whicks/miniforge3/envs/cuml_dev/lib/python3.12/site-packages/cudf/utils/performance_tracking.py", line 51, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/raid/whicks/miniforge3/envs/cuml_dev/lib/python3.12/site-packages/cudf/core/frame.py", line 447, in _to_array
    raise NotImplementedError(
NotImplementedError: category cannot be exposed as an array
```

**Comment by mroeschke** [comment]
Thanks for the report.

Agreed for categorical columns to match pandas, this should be returning the categorical values. For your specific example though with a categorical of strings, cupy doesn't support string data

```python
In [6]: import cupy

In [7]: cupy.array(["a"])
ValueError: Unsupported dtype <U1
```
