### ISSUE TITLE
[BUG] Series initialization fails when list is passed as data

### ISSUE THREAD

**Issue by trstovall** [rapidsai/cudf#1842]
**Describe the bug**
Series initialization fails when list is passed as data.

**Steps/Code to reproduce bug**
```
from cudf import Series
s = Series([1,2,3])
```
```
from cudf import DataFrame
df = DataFrame({'a': [1,2,3]})
```

**Expected behavior**
```
from cudf import Series, DataFrame
from array import array

s = Series(array('b', [1,2,3]))
df = DataFrame({'a': array('b': [1,2,3])})
```

**Environment details (please complete the following information):**
- Docker
- cudf installed from source (branch-0.8)

**Comment by trstovall** [comment]
# Output from `cudf/print_env.sh`
```
root@dad7e55b1e1c:~# /cudf/print_env.sh
**git***
Not inside a git repository

***OS Information***
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
Linux dad7e55b1e1c 4.4.0-137-generic #163-Ubuntu SMP Mon Sep 24 13:14:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

***GPU Information***
Thu May 23 21:03:09 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-SXM2...  Off  | 00000000:05:00.0 Off |                    0 |
| N/A   37C    P0    43W / 300W |  11320MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-SXM2...  Off  | 00000000:06:00.0 Off |                    0 |
| N/A   33C    P0    43W / 300W |   1212MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P100-SXM2...  Off  | 00000000:84:00.0 Off |                    0 |
| N/A   31C    P0    44W / 300W |   3547MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P100-SXM2...  Off  | 00000000:85:00.0 Off |                    0 |
| N/A   35C    P0    44W / 300W |   1104MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

***CPU***
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                56
On-line CPU(s) list:   0-55
Thread(s) per core:    2
Core(s) per socket:    14
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2650L v4 @ 1.70GHz
Stepping:              1
CPU MHz:               1420.628
CPU max MHz:           2500.0000
CPU min MHz:           1200.0000
BogoMIPS:              3401.36
Virtualization:        VT-x
Hypervisor vendor:     vertical
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              35840K
NUMA node0 CPU(s):     0-13,28-41
NUMA node1 CPU(s):     14-27,42-55
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts flush_l1d

***CMake***
/conda/bin/cmake
cmake version 3.14.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).

***g++***
/usr/bin/g++
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


***nvcc***
/usr/local/cuda/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

***Python***
/conda/bin/python
Python 3.7.3

***Environment Variables***
PATH                            : /conda/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LD_LIBRARY_PATH                 : :/usr/local/cuda/lib64:/usr/local/lib:/conda/lib:/usr/local/cuda/lib64:/usr/local/lib
NUMBAPRO_NVVM                   : /usr/local/cuda/nvvm/lib64/libnvvm.so
NUMBAPRO_LIBDEVICE              : /usr/local/cuda/nvvm/libdevice/
CONDA_PREFIX                    : 
PYTHON_PATH                     : 

***conda packages***
/conda/bin/conda
# packages in environment at /conda:
#
# Name                    Version                   Build  Channel
absl-py                   0.7.1                    pypi_0    pypi
arrow-cpp                 0.12.1           py37h0e61e49_0    conda-forge
asn1crypto                0.24.0                   py37_0  
astor                     0.8.0                    pypi_0    pypi
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                    openblas  
bleach                    3.1.0                      py_0    conda-forge
bokeh                     1.1.0                    py37_0  
boost                     1.68.0          py37h8619c78_1001    conda-forge
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
boto3                     1.9.134                    py_0  
botocore                  1.12.134                   py_0  
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0  
cffi                      1.12.3           py37h8022711_0    conda-forge
chardet                   3.0.4                    py37_1  
click                     7.0                      pypi_0    pypi
cloudpickle               1.0.0                      py_0    conda-forge
cmake                     3.14.4               hf94ab9c_0    conda-forge
cmake-setuptools          0.1.3                    pypi_0    pypi
conda                     4.6.14                   py37_0    conda-forge
cryptography              2.6.1            py37h1ba5d50_0  
cudatoolkit               10.0.130                      0  
cudf                      0.8.0a1+132.g2f36e57.dirty          pypi_0    pypi
cuml                      0.7.0                    pypi_0    pypi
curl                      7.64.1               hf8cf82a_0    conda-forge
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.7           py37he1b5a44_0    conda-forge
cytoolz                   0.9.0.1         py37h14c3975_1001    conda-forge
dask-core                 1.2.2                      py_0    conda-forge
dask-cudf                 0.0.0.dev0               pypi_0    pypi
dask-cuml                 0.8.0a0                  pypi_0    pypi
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
distributed               1.28.1                   py37_0    conda-forge
docutils                  0.14                     py37_0  
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
freetype                  2.9.1                h8a8886c_1  
gast                      0.2.2                    pypi_0    pypi
google-pasta              0.1.6                    pypi_0    pypi
grpcio                    1.20.1                   pypi_0    pypi
h5py                      2.9.0                    pypi_0    pypi
heapdict                  1.0.0                 py37_1000    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                      py37_0  
intel-openmp              2019.3                      199  
ipykernel                 5.1.1            py37h24bf2e0_0    conda-forge
ipython                   7.5.0            py37h24bf2e0_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.13.3                   py37_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jmespath                  0.9.4                      py_0  
joblib                    0.13.2                   py37_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.0.1                    py37_0    conda-forge
jupyter_client            5.2.4                      py_3    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.35.5           py37hf63ae98_0  
jupyterlab_server         0.2.0                    py37_0  
keras-applications        1.0.7                    pypi_0    pypi
keras-preprocessing       1.0.9                    pypi_0    pypi
kiwisolver                1.1.0                    pypi_0    pypi
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               10_openblas    conda-forge
libcblas                  3.8.0               10_openblas    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
liblapack                 3.8.0               10_openblas    conda-forge
libopenblas               0.3.3                h5a2b251_3  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.6.1             hdbcaa40_1001    conda-forge
libsodium                 1.0.16            h14c3975_1001    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.10               h2733197_2  
libuv                     1.29.1               h516909a_0    conda-forge
llvmlite                  0.29.0rc1        py37hf484d3e_0    numba
markdown                  3.1.1                    pypi_0    pypi
markupsafe                1.1.1            py37h14c3975_0    conda-forge
matplotlib                3.1.0                    pypi_0    pypi
mistune                   0.8.4           py37h14c3975_1000    conda-forge
mkl                       2019.3                      199  
more-itertools            4.3.0                 py37_1000    conda-forge
msgpack-python            0.6.1            py37h6bb024c_0    conda-forge
nbconvert                 5.5.0                      py_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  he6710b0_1  
ninja                     1.9.0            py37hfd86e86_0  
notebook                  5.7.8                    py37_0    conda-forge
numba                     0.44.0rc1       np116py37hf484d3e_0    numba
numpy                     1.16.3           py37he5ce36f_0    conda-forge
nvgraph                   0.1.0.dev0           cuda10.0_9    nvidia/label/cuda10.0
nvstrings-cuda100         0.0.0.dev0               pypi_0    pypi
olefile                   0.46                     py37_0  
openblas                  0.3.6                h6e990d7_2    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
packaging                 19.0                     py37_0  
pandas                    0.23.4          py37h637b7d7_1000    conda-forge
pandoc                    2.7.2                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parquet-cpp               1.5.1                         4    conda-forge
parso                     0.4.0                      py_0    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    6.0.0            py37h34e0f95_0  
pip                       19.0.3                   py37_0  
pluggy                    0.11.0                     py_0    conda-forge
prometheus_client         0.6.0                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
protobuf                  3.7.1                    pypi_0    pypi
psutil                    5.6.2            py37h516909a_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.8.0                      py_0    conda-forge
pyarrow                   0.12.1           py37hbbcf98d_0    conda-forge
pycosat                   0.6.3            py37h14c3975_0  
pycparser                 2.19                     py37_0  
pygments                  2.4.0                      py_0    conda-forge
pyopenssl                 19.0.0                   py37_0  
pyparsing                 2.4.0                      py_0  
pyrsistent                0.15.2           py37h516909a_0    conda-forge
pysocks                   1.6.8                    py37_0  
pytest                    4.5.0                    py37_0    conda-forge
python                    3.7.3                h5b0a415_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytorch                   1.1.0           py3.7_cuda10.0.130_cudnn7.5.1_0    pytorch
pytz                      2019.1                     py_0    conda-forge
pyyaml                    5.1              py37h14c3975_0    conda-forge
pyzmq                     18.0.1           py37hc4ba49a_1    conda-forge
readline                  7.0                  h7b6447c_5  
requests                  2.21.0                   py37_0  
rhash                     1.3.6             h14c3975_1001    conda-forge
ruamel_yaml               0.15.46          py37h14c3975_0  
s3fs                      0.2.1                      py_0  
s3transfer                0.2.0                    py37_0  
scikit-learn              0.21.1           py37h22eb022_0  
scipy                     1.2.1            py37he2b7bc3_0  
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.0.1                   py37_0  
six                       1.12.0                   py37_0  
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.27.2               h7b6447c_0  
tb-nightly                1.14.0a20190522          pypi_0    pypi
tblib                     1.4.0                      py_0    conda-forge
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.2                    py37_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
tf-estimator-nightly      1.14.0.dev2019052301          pypi_0    pypi
tf-nightly                1.14.1.dev20190523          pypi_0    pypi
tf-nightly-gpu            1.14.1.dev20190522          pypi_0    pypi
thrift-cpp                0.12.0            h0a07b25_1002    conda-forge
tk                        8.6.9             h84994c4_1001    conda-forge
toolz                     0.9.0                    pypi_0    pypi
torchvision               0.3.0           py37_cu10.0.130_1    pytorch
tornado                   6.0.2            py37h516909a_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
urllib3                   1.24.1                   py37_0  
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.15.4                   pypi_0    pypi
wheel                     0.33.1                   py37_0  
wrapt                     1.11.1                   pypi_0    pypi
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zeromq                    4.3.1             hf484d3e_1000    conda-forge
zict                      0.1.4                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  
```

**Comment by trstovall** [comment]
**Python session with stacktrace:**
```
root@dad7e55b1e1c:/cudf# python
Python 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 23:01:00) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cudf import Series
/conda/lib/python3.7/site-packages/numba/cuda/envvars.py:16: NumbaDeprecationWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated, found use of NUMBAPRO_NVVM=/usr/local/cuda/nvvm/lib64/libnvvm.so.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-numbapro-environment-variables
  warnings.warn(errors.NumbaDeprecationWarning(msg))
>>> s = Series([1,2,3])
/conda/lib/python3.7/site-packages/numba/cuda/envvars.py:16: NumbaDeprecationWarning: 
Environment variables with the 'NUMBAPRO' prefix are deprecated, found use of NUMBAPRO_NVVM=/usr/local/cuda/nvvm/lib64/libnvvm.so.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-numbapro-environment-variables
  warnings.warn(errors.NumbaDeprecationWarning(msg))
Traceback (most recent call last):
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+132.g2f36e57.dirty-py3.7-linux-x86_64.egg/cudf/dataframe/columnops.py", line 448, in as_column
    data = as_column(memoryview(arbitrary))
TypeError: memoryview: a bytes-like object is required, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/conda/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 111, in __new__
    inst.driver = open_cudalib('nvvm', ccc=True)
  File "/conda/lib/python3.7/site-packages/numba/cuda/cudadrv/libs.py", line 46, in open_cudalib
    path = get_cudalib(lib)
  File "/conda/lib/python3.7/site-packages/numba/cuda/cudadrv/libs.py", line 37, in get_cudalib
    return get_cuda_paths()['nvvm'].info
  File "/conda/lib/python3.7/site-packages/numba/cuda/cuda_paths.py", line 160, in get_cuda_paths
    'nvvm': _get_nvvm_path(),
  File "/conda/lib/python3.7/site-packages/numba/cuda/cuda_paths.py", line 138, in _get_nvvm_path
    candidates = find_lib('nvvm', libdir)
  File "/conda/lib/python3.7/site-packages/numba/findlib.py", line 35, in find_lib
    return find_file(regex, libdir)
  File "/conda/lib/python3.7/site-packages/numba/findlib.py", line 47, in find_file
    entries = os.listdir(ldir)
NotADirectoryError: [Errno 20] Not a directory: '/usr/local/cuda/nvvm/lib64/libnvvm.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+132.g2f36e57.dirty-py3.7-linux-x86_64.egg/cudf/dataframe/series.py", line 85, in __init__
    dtype=dtype)
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+132.g2f36e57.dirty-py3.7-linux-x86_64.egg/cudf/dataframe/columnops.py", line 463, in as_column
    nan_as_null=nan_as_null
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+132.g2f36e57.dirty-py3.7-linux-x86_64.egg/cudf/dataframe/columnops.py", line 393, in as_column
    pamask, padata = buffers_from_pyarrow(arbitrary)
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+132.g2f36e57.dirty-py3.7-linux-x86_64.egg/cudf/utils/utils.py", line 156, in buffers_from_pyarrow
    copy_array(arrow_dev_array, mask_dev_array)
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+132.g2f36e57.dirty-py3.7-linux-x86_64.egg/cudf/utils/cudautils.py", line 132, in copy_array
    gpu_copy.forall(arr.size)(arr, out)
  File "/conda/lib/python3.7/site-packages/numba/cuda/compiler.py", line 267, in __call__
    kernel = self.kernel.specialize(*args)
  File "/conda/lib/python3.7/site-packages/numba/cuda/compiler.py", line 817, in specialize
    kernel = self.compile(argtypes)
  File "/conda/lib/python3.7/site-packages/numba/cuda/compiler.py", line 836, in compile
    kernel.bind()
  File "/conda/lib/python3.7/site-packages/numba/cuda/compiler.py", line 544, in bind
    self._func.get()
  File "/conda/lib/python3.7/site-packages/numba/cuda/compiler.py", line 422, in get
    ptx = self.ptx.get()
  File "/conda/lib/python3.7/site-packages/numba/cuda/compiler.py", line 393, in get
    **self._extra_options)
  File "/conda/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 468, in llvm_to_ptx
    cu = CompilationUnit()
  File "/conda/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 146, in __init__
    self.driver = NVVM()
  File "/conda/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 116, in __new__
    raise NvvmSupportError(errmsg % e)
numba.cuda.cudadrv.error.NvvmSupportError: libNVVM cannot be found. Do `conda install cudatoolkit`:
[Errno 20] Not a directory: '/usr/local/cuda/nvvm/lib64/libnvvm.so'
```

**Comment by trstovall** [comment]
```
root@dad7e55b1e1c:/cudf# ls -al /usr/local/cuda/nvvm/lib64/libnvvm.so
lrwxrwxrwx 1 root root 12 Sep 12  2018 /usr/local/cuda/nvvm/lib64/libnvvm.so -> libnvvm.so.3
```

**Comment by shwina** [comment]
Thanks @trstovall - fix coming up!

**Comment by shwina** [comment]
@trstovall 

Sorry, I'm actually unable to reproduce this. I read too fast and thought this was relating to passing the `index` a list - which is a bug I've been dealing with lately:

```
In [7]: s = cudf.DataFrame({'a': [1, 2, 3], 'b': [2, 3, 4]}, [1, 2, 3])                                                                                                                 
In [8]: print(s)                                                                                                                                                                       
```

But I'm not able to reproduce your issue:

```
In [11]: from cudf import DataFrame                                                                                                                                                     

In [12]: df = DataFrame({'a': [1,2,3]})                                                                                                                                                 

In [13]: print(df)                                                                                                                                                                      
   a
0  1
1  2
2  3

```

**Comment by ayushdg** [comment]
@trstovall I have a feeling this is an environment issue.
 If possible could you try the steps suggested [here](https://github.com/rapidsai/cudf/blob/branch-0.8/CONTRIBUTING.md#setting-up-your-build-environment) and report back on your findings.

**Comment by trstovall** [comment]
@ayushdg Yes, it's an environment issue.  The build arg `NUMBAPRO_NVVM` was set to `/usr/local/cuda/nvvm/lib64/libnvvm.so` as previously expected.  Now, `cudf` expects `NUMBAPRO_NVVM=/usr/local/cuda/nvvm/lib64/`.  Setting the env variable resolves the issue.
