### ISSUE TITLE
[FEA] Please expose groupby object attributes .groups and support .keys()

### ISSUE THREAD

**Issue by deltadu** [rapidsai/cudf#1865]
It would be useful if dask-cudf groupby object supports .keys() or expose .groups attribute like Pandas does.

code:
import dask_cudf as dd
diamonds = dd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv')
sorted = diamonds.sort_values(['color', 'cut'])
gp = sorted.groupby(['color', 'cut'])
gp.groups

Traceback (most recent call last):
  File "/conda/envs/rapids/lib/python3.6/site-packages/dask/dataframe/groupby.py", line 1228, in __getattr__
    return self[key]
  File "/conda/envs/rapids/lib/python3.6/site-packages/dask/dataframe/groupby.py", line 1219, in __getitem__
    g._meta = g._meta[key]
  File "/conda/envs/rapids/lib/python3.6/site-packages/cudf/groupby/groupby.py", line 282, in __getitem__
    raise KeyError("Column not found: " + str(arg))
KeyError: 'Column not found: groups'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/rapids/lib/python3.6/site-packages/dask/dataframe/groupby.py", line 1230, in __getattr__
    raise AttributeError(e)
AttributeError: 'Column not found: groups'

**Comment by jrhemstad** [comment]
Superseded by https://github.com/rapidsai/cudf/issues/3082
