### ISSUE TITLE
[FEA] Support Column creation with np.array scalars

### ISSUE THREAD

**Issue by trstovall** [rapidsai/cudf#2206]
**Is your feature request related to a problem? Please describe.**
cuDF should recognize 0-dimension np.arrays as scalars.  Since it does not, Python literals are used, and the column must be resized with `cudf.Column.astype`.

**Describe the solution you'd like**
```
import numpy as np
import cudf
df = cudf.DataFrame({'a': range(5)})
df['b'] = np.array(1, dtype='b')
```
```
>>> df.dtypes
a    int64
b     int8
dtype: object
```

**Describe alternatives you've considered**
```
import numpy as np
import pandas as pd
df = pd.DataFrame({'a': range(5)})
df['b'] = np.array(1, dtype='b')
```
```
>>> df.dtypes
a    int64
b     int8
dtype: object
```

**Additional context**
```
>>> df['b'] = np.array(1, dtype='b')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/lib/python3.7/site-packages/cudf-0.9.0a0+1073.g73e0849-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py", line 338, in __setitem__
    self.add_column(name, col)
  File "/conda/lib/python3.7/site-packages/cudf-0.9.0a0+1073.g73e0849-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py", line 1214, in add_column
    data, forceindex=forceindex, name=name
  File "/conda/lib/python3.7/site-packages/cudf-0.9.0a0+1073.g73e0849-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py", line 1183, in _prepare_series_for_add
    series = self._sanitize_values(series, SCALAR)
  File "/conda/lib/python3.7/site-packages/cudf-0.9.0a0+1073.g73e0849-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py", line 1161, in _sanitize_values
    raise ValueError("Length of values does not match index length")
ValueError: Length of values does not match index length
```

**Comment by ayushdg** [comment]
Seems like cudf uses `np.isscalar` for scalar type checking but might probably be able to use `np.ndim(x) == 0`.

The docs here have more info: https://docs.scipy.org/doc/numpy/reference/generated/numpy.isscalar.html

**Comment by kkraus14** [comment]
> Seems like cudf uses `np.isscalar` for scalar type checking but might probably be able to use `np.ndim(x) == 0`.
> 
> The docs here have more info: https://docs.scipy.org/doc/numpy/reference/generated/numpy.isscalar.html

I believe we previously did that and it caused issues elsewhere, but I could be mistaken. I vaguely remember thinking that we didn't need to handle 0-dimension arrays but I was obviously mistaken 😅
