### ISSUE TITLE
[FEA] Handle `bytes` dtypes from Pandas

### ISSUE THREAD

**Issue by trstovall** [rapidsai/cudf#2219]
**Describe the bug**
`cudf.from_pandas` fails to convert `pandas.DataFrame` when the dataframe has `bytes`-like datatype.

**Steps/Code to reproduce bug**
```python
>>> from cudf import from_pandas
>>> from pandas import DataFrame
>>> df = DataFrame({'a': [b'a', b'b']})

>>> from_pandas(df)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/lib/python3.7/site-packages/cudf-0.9.0a0+1084.gcc1ade1-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py", line 3390, in from_pandas
    return DataFrame.from_pandas(obj)
  File "/conda/lib/python3.7/site-packages/cudf-0.9.0a0+1084.gcc1ade1-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py", line 2798, in from_pandas
    df[colk] = Series(vals, nan_as_null=nan_as_null)
  File "/conda/lib/python3.7/site-packages/cudf-0.9.0a0+1084.gcc1ade1-py3.7-linux-x86_64.egg/cudf/dataframe/series.py", line 98, in __init__
    data, nan_as_null=nan_as_null, dtype=dtype, name=name
  File "/conda/lib/python3.7/site-packages/cudf-0.9.0a0+1084.gcc1ade1-py3.7-linux-x86_64.egg/cudf/dataframe/columnops.py", line 333, in as_column
    data = as_column(pa.Array.from_pandas(arbitrary))
  File "/conda/lib/python3.7/site-packages/cudf-0.9.0a0+1084.gcc1ade1-py3.7-linux-x86_64.egg/cudf/dataframe/columnops.py", line 434, in as_column
    pamask, padata = buffers_from_pyarrow(arbitrary)
  File "/conda/lib/python3.7/site-packages/cudf-0.9.0a0+1084.gcc1ade1-py3.7-linux-x86_64.egg/cudf/utils/utils.py", line 175, in buffers_from_pyarrow
    np.array(buffers[1]).view(new_dtype)[
  File "/conda/lib/python3.7/site-packages/numpy/core/_internal.py", line 494, in _view_is_safe
    raise TypeError("Cannot change data-type for object array.")
TypeError: Cannot change data-type for object array.
```

**Environment overview (please complete the following information)**
Docker container, cudf built from source.  branch-0.9

**Comment by kkraus14** [comment]
@trstovall What would be the expected for the behavior of this from your perspective?

The Pandas column will be of Python bytes objects which aren't strings and string methods won't work on them. If you typecased to a "bytes" dtype it returns an arbitrary resolution fixed width column that we could potentially handle in the future with nested types.

**Comment by randerzander** [comment]
@kkraus14 @trstovall from offline discussion it sounds like this is an artifact of Hive and Spark jobs creating `char` and `varchar` columns that PyArrow sees as `bytes`.

Please correct me if I'm wrong, @trstovall, but the actual usage you're targeting here is to be able to read these as string encoded values, right?

**Comment by trstovall** [comment]
@randerzander Yes, that's correct.

**Comment by GregoryKimball** [comment]
Please let us know if you encounter new issues with your Hive and Spark jobs.
