### ISSUE TITLE
[FEA] Support including filename column for read_csv

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#2269]
### Description

As a user, when I call `read_csv` on a directory, I often want to keep track of which file in the directory my data came from. Consistent with https://github.com/dask/dask/pull/3908, I would want a keyword argument similar to `include_path_col`.

Currently, this fails as the argument is passed through with the other keyword arguments to `cudf.read_csv`.

### Example
Will add a public example shortly, but the stacktrace looks like:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-87-62157a846193> in <module>
     12                                dtype=dtypes,
     13                                skip_blank_lines=True,
---> 14                                include_path_col=True
     15                               )
     16 

/conda/envs/rapids/lib/python3.7/site-packages/dask_cudf-0.0.1+256.g41c95a8-py3.7.egg/dask_cudf/io/csv.py in read_csv(path, chunksize, **kwargs)
     18         return func(path, blocksize=chunksize, **kwargs)
     19     else:
---> 20         return _internal_read_csv(path=path, chunksize=chunksize, **kwargs)
     21 
     22 

/conda/envs/rapids/lib/python3.7/site-packages/dask_cudf-0.0.1+256.g41c95a8-py3.7.egg/dask_cudf/io/csv.py in _internal_read_csv(path, chunksize, **kwargs)
     49         return read_csv_without_chunksize(path, **kwargs)
     50 
---> 51     meta = cudf.read_csv(filenames[0], **kwargs)
     52     dsk = {}
     53     i = 0

TypeError: read_csv() got an unexpected keyword argument 'include_path_col'
```

**Comment by VibhuJawa** [comment]
For planning purposes:

The behavior to support is as followed in `dask` . 

```
include_path_column : bool or str, optional
    Whether or not to include the path to each particular file. If True a new
    column is added to the dataframe called ``path``. If str, sets new column
    name. Default is False.
```

Link: 
https://github.com/dask/dask/blob/7b4f90f0a708cbb97ebb498c78f7931d82ec99db/dask/dataframe/io/csv.py#L521-L524

**Comment by ayushdg** [comment]
Just synced with @VibhuJawa offline. My thoughts on the approach.
- I'm too sure if cuDF readers need to include a `include_path_column` argument or not (since pandas doesn't support this). The current approach in dask is to use the underlying data frames csv reader. get the data and then add a column to the underlying with the file paths within the dask codebase itself. (I think here: https://github.com/dask/dask/blob/master/dask/dataframe/io/csv.py#L79)
- The stack trace shows some error when checking dtypes of the meta and Dataframe with the categorical filepath column). It is likely that there is some meta issue or the `pd.from_categorical` call instead of a `cudf` call is likely messing up the meta somehow?

Debugging through the dask/dask_cudf codepath and observing the behavior there should be beneficial.

**Comment by VibhuJawa** [comment]
After exploring more i believe the error is stemming because of a failure when trying to create a dask dataframe from categorical series : 

Looking into fixing that. 

Minimal Example:

```python
import dask
import cudf
import pandas as pd
import dask_cudf
```

```python
s1 = dask.delayed(lambda x: x)(cudf.DataFrame({'1':cudf.Series(pd.Categorical.from_codes([0,0], ['a','b']))}))

s2 = dask.delayed(lambda x:x)(cudf.DataFrame({'1':cudf.Series(pd.Categorical.from_codes([1,1], ['a','b']))}))
```

```python
dask_cudf.from_delayed([s1,s2]).compute()
```

Error Trace:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-5190bcd41fff> in <module>
----> 1 dask_cudf.from_delayed([s1,s2]).compute()

/data/vjawa/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    173         dask.base.compute
    174         """
--> 175         (result,) = compute(self, traverse=False, **kwargs)
    176         return result
    177 

/data/vjawa/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    444     keys = [x.__dask_keys__() for x in collections]
    445     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 446     results = schedule(dsk, keys, **kwargs)
    447     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    448 

/data/vjawa/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/local.py in get_sync(dsk, keys, **kwargs)
    530     """
    531     kwargs.pop("num_workers", None)  # if num_workers present, remove it
--> 532     return get_async(apply_sync, 1, dsk, keys, **kwargs)
    533 
    534 

/data/vjawa/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    474             # Seed initial tasks into the thread pool
    475             while state["ready"] and len(state["running"]) < num_workers:
--> 476                 fire_task()
    477 
    478             # Main loop, wait on tasks to finish, insert new ones

/data/vjawa/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/local.py in fire_task()
    469                         pack_exception,
    470                     ),
--> 471                     callback=queue.put,
    472                 )
    473 

/data/vjawa/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/local.py in apply_sync(func, args, kwds, callback)
    519 def apply_sync(func, args=(), kwds={}, callback=None):
    520     """ A naive synchronous version of apply_async """
--> 521     res = func(*args, **kwds)
    522     if callback is not None:
    523         callback(res)

/data/vjawa/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    236         failed = False
    237     except BaseException as e:
--> 238         result = pack_exception(e, dumps)
    239         failed = True
    240     return key, result, failed

/data/vjawa/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    231     try:
    232         task, data = loads(task_info)
--> 233         result = _execute_task(task, data)
    234         id = get_id()
    235         result = dumps((result, id))

/data/vjawa/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

/data/vjawa/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/dataframe/utils.py in check_meta(x, meta, funcname, numeric_equal)
    624         bad_dtypes = [
    625             (col, a, b)
--> 626             for col, a, b in dtypes.fillna("-").itertuples()
    627             if not equal_dtypes(a, b)
    628         ]

/data/vjawa/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/dataframe/utils.py in <listcomp>(.0)
    625             (col, a, b)
    626             for col, a, b in dtypes.fillna("-").itertuples()
--> 627             if not equal_dtypes(a, b)
    628         ]
    629         if bad_dtypes:

/data/vjawa/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/dataframe/utils.py in equal_dtypes(a, b)
    599             return False
    600         if is_categorical_dtype(a) and is_categorical_dtype(b):
--> 601             if UNKNOWN_CATEGORIES in a.categories or UNKNOWN_CATEGORIES in b.categories:
    602                 return True
    603             return a == b

TypeError: argument of type 'NoneType' is not iterable
```

**Comment by VibhuJawa** [comment]
The issue has been triaged  to the discrepancy in behavior for `Categorical series dtype` for `cudf` described in #2864 .  


For testing my hypothesis,  I set the categories at  this [line] like below (https://github.com/rapidsai/cudf/blob/86760c316f98cf46ea3b7bdbe51cfdab75366f9d/python/cudf/cudf/core/column/categorical.py#L235
) and can verify that `include_path_column` works . 

```
dtype = CategoricalDtype(categories=list(categories), ordered=ordered)
```

**Comment by beckernick** [comment]
Note that this now succeeds for the codepath that we go down when we prepend `file://` to the path.

**Comment by randerzander** [comment]
As of the latest 0.14 nightlies, even including the `file://` prefix no longer works:
```
>>> dd.read_csv('file://part_test/part_*/*.csv', include_path_column=True).compute()
   id  val                                         path
0   0    1  /home/rgelhausen/part_test/part_0/file0.csv
0   0    1  /home/rgelhausen/part_test/part_1/file1.csv

>>> dask_cudf.read_csv('file://part_test/part_*/*.csv', include_path_column=True).compute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rgelhausen/conda/envs/rapids-20200522_1643/lib/python3.7/site-packages/dask_cudf/io/csv.py", line 17, in read_csv
    return func(path, blocksize=chunksize, **kwargs)
  File "/home/rgelhausen/conda/envs/rapids-20200522_1643/lib/python3.7/site-packages/dask/dataframe/io/csv.py", line 580, in read
    **kwargs,
  File "/home/rgelhausen/conda/envs/rapids-20200522_1643/lib/python3.7/site-packages/dask/dataframe/io/csv.py", line 473, in read_pandas
    path=path,
  File "/home/rgelhausen/conda/envs/rapids-20200522_1643/lib/python3.7/site-packages/dask/dataframe/io/csv.py", line 291, in text_blocks_to_pandas
    np.zeros(len(head), dtype=int), paths
  File "/home/rgelhausen/conda/envs/rapids-20200522_1643/lib/python3.7/site-packages/cudf/core/dataframe.py", line 733, in assign
    new[k] = v
  File "/home/rgelhausen/conda/envs/rapids-20200522_1643/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/rgelhausen/conda/envs/rapids-20200522_1643/lib/python3.7/site-packages/cudf/core/dataframe.py", line 559, in __setitem__
    self.insert(len(self._data), arg, value)
  File "/home/rgelhausen/conda/envs/rapids-20200522_1643/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/rgelhausen/conda/envs/rapids-20200522_1643/lib/python3.7/site-packages/cudf/core/dataframe.py", line 1715, in insert
    value = utils.scalar_broadcast_to(value, len(self))
  File "/home/rgelhausen/conda/envs/rapids-20200522_1643/lib/python3.7/site-packages/cudf/utils/utils.py", line 73, in scalar_broadcast_to
    return scalar_broadcast_to(scalar.categories[0], size).astype(dtype)
  File "/home/rgelhausen/conda/envs/rapids-20200522_1643/lib/python3.7/site-packages/cudf/core/column/column.py", line 828, in astype
    return self.as_numerical_column(dtype, **kwargs)
  File "/home/rgelhausen/conda/envs/rapids-20200522_1643/lib/python3.7/site-packages/cudf/core/column/string.py", line 2080, in as_numerical_column
    type due to presence of non-floating values."
ValueError: Could not convert strings to float                         type due to presence of non-floating values.
```

**Comment by VibhuJawa** [comment]
> As of the latest 0.14 nightlies, even including the `file://` prefix no longer works:

Thanks for the report @randerzander ,  looking into this now. 


For completeness this only fails with a single row i believe:

i.e ONLY below fails:
```python
!mkdir test_dir
cudf.DataFrame({'a':[1],'b':[1]}).to_csv('test_dir/test_1.csv',index=False)
dask_cudf.read_csv('file://test_dir/*.csv', include_path_column=True).compute()
``` 

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-f5a752433a9a> in <module>
      1 get_ipython().system('mkdir test_dir')
      2 cudf.DataFrame({'a':[1],'b':[1]}).to_csv('test_dir/test_1.csv',index=False)
----> 3 dask_cudf.read_csv('file://test_dir/*.csv', include_path_column=True).compute()

/nvme/0/vjawa/dev/rapids/cudf/python/dask_cudf/dask_cudf/io/csv.py in read_csv(path, chunksize, **kwargs)
     15     if "://" in str(path):
     16         func = make_reader(cudf.read_csv, "read_csv", "CSV")
---> 17         return func(path, blocksize=chunksize, **kwargs)
     18     else:
     19         return _internal_read_csv(path=path, chunksize=chunksize, **kwargs)

/nvme/0/vjawa/dev/rapids/compose/etc/conda/cuda_10.2/envs/notebooks/lib/python3.7/site-packages/dask/dataframe/io/csv.py in read(urlpath, blocksize, collection, lineterminator, compression, sample, enforce, assume_missing, storage_options, include_path_column, **kwargs)
    578             storage_options=storage_options,
    579             include_path_column=include_path_column,
--> 580             **kwargs,
    581         )
    582 

/nvme/0/vjawa/dev/rapids/compose/etc/conda/cuda_10.2/envs/notebooks/lib/python3.7/site-packages/dask/dataframe/io/csv.py in read_pandas(reader, urlpath, blocksize, collection, lineterminator, compression, sample, enforce, assume_missing, storage_options, include_path_column, **kwargs)
    471         enforce=enforce,
    472         specified_dtypes=specified_dtypes,
--> 473         path=path,
    474     )
    475 

/nvme/0/vjawa/dev/rapids/compose/etc/conda/cuda_10.2/envs/notebooks/lib/python3.7/site-packages/dask/dataframe/io/csv.py in text_blocks_to_pandas(reader, block_lists, header, head, kwargs, collection, enforce, specified_dtypes, path)
    289                 **{
    290                     colname: pd.Categorical.from_codes(
--> 291                         np.zeros(len(head), dtype=int), paths
    292                     )
    293                 }

/nvme/0/vjawa/dev/rapids/cudf/python/cudf/cudf/core/dataframe.py in assign(self, **kwargs)
    792         new = self.copy()
    793         for k, v in kwargs.items():
--> 794             new[k] = v
    795         return new
    796 

/nvme/0/vjawa/dev/rapids/compose/etc/conda/cuda_10.2/envs/notebooks/lib/python3.7/contextlib.py in inner(*args, **kwds)
     72         def inner(*args, **kwds):
     73             with self._recreate_cm():
---> 74                 return func(*args, **kwds)
     75         return inner
     76 

/nvme/0/vjawa/dev/rapids/cudf/python/cudf/cudf/core/dataframe.py in __setitem__(self, arg, value)
    572                     # disc. with pandas here
    573                     # pandas raises key error here
--> 574                     self.insert(len(self._data), arg, value)
    575 
    576         elif isinstance(

/nvme/0/vjawa/dev/rapids/compose/etc/conda/cuda_10.2/envs/notebooks/lib/python3.7/contextlib.py in inner(*args, **kwds)
     72         def inner(*args, **kwds):
     73             with self._recreate_cm():
---> 74                 return func(*args, **kwds)
     75         return inner
     76 

/nvme/0/vjawa/dev/rapids/cudf/python/cudf/cudf/core/dataframe.py in insert(self, loc, name, value)
   2554 
   2555         if is_scalar(value):
-> 2556             value = utils.scalar_broadcast_to(value, len(self))
   2557 
   2558         if len(self) == 0:

/nvme/0/vjawa/dev/rapids/cudf/python/cudf/cudf/utils/utils.py in scalar_broadcast_to(scalar, size, dtype)
     71 
     72     if isinstance(scalar, pd.Categorical):
---> 73         return scalar_broadcast_to(scalar.categories[0], size).astype(dtype)
     74 
     75     if isinstance(scalar, str) and (is_string_dtype(dtype) or dtype is None):

/nvme/0/vjawa/dev/rapids/cudf/python/cudf/cudf/core/column/column.py in astype(self, dtype, **kwargs)
    826             return self.as_string_column(dtype, **kwargs)
    827         else:
--> 828             return self.as_numerical_column(dtype, **kwargs)
    829 
    830     def as_categorical_column(self, dtype, **kwargs):

/nvme/0/vjawa/dev/rapids/cudf/python/cudf/cudf/core/column/string.py in as_numerical_column(self, dtype, **kwargs)
   3808                 raise ValueError(
   3809                     "Could not convert strings to float \
-> 3810                         type due to presence of non-floating values."
   3811                 )
   3812 

ValueError: Could not convert strings to float                         type due to presence of non-floating values.
```

#### But rows of size 2+ work


```python
!mkdir test_dir
cudf.DataFrame({'a':[1,2],'b':[1,2]}).to_csv('test_dir/test_1.csv',index=False)
dask_cudf.read_csv('file://test_dir/*.csv', include_path_column=True).compute()
```

```
	a	b	path
0	1	1	/home/rapids/notebooks/sandbox/test_dir/test_1...
1	2	2	/home/rapids/notebooks/sandbox/test_dir/test_1...
```

```python
!mkdir test_dir
for n in range(1,10):
    try:
        cudf.DataFrame({'a':[1]*n,'b':[1]*n}).to_csv('test_dir/test_1.csv',index=False)
        dask_cudf.read_csv('file://test_dir/*.csv', include_path_column=True).compute()
        print("Success n = {}".format(n))
    except:
         print("Failue n = {}".format(n))
```

```python
mkdir: cannot create directory ‘test_dir’: File exists
Failue n = 1
Success n = 2
Success n = 3
Success n = 4
Success n = 5
Success n = 6
Success n = 7
Success n = 8
Success n = 9
```

**Comment by VibhuJawa** [comment]
Cudf Minimal Example of the issue: 

```python
import numpy as np
import pandas as pd
import cudf

head = cudf.DataFrame({'a':[1]})
cat_s = pd.Categorical.from_codes(np.zeros(len(head), dtype=int), categories=['cat.csv'])
head.assign(path=cat_s)
```

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-14996323db6f> in <module>
      5 head = cudf.DataFrame({'a':[1]})
      6 cat_s = pd.Categorical.from_codes(np.zeros(len(head), dtype=int), categories=['cat.csv'])
----> 7 head.assign(path=cat_s)

/nvme/0/vjawa/dev/rapids/cudf/python/cudf/cudf/core/dataframe.py in assign(self, **kwargs)
    792         new = self.copy()
    793         for k, v in kwargs.items():
--> 794             new[k] = v
    795         return new
    796 

/nvme/0/vjawa/dev/rapids/compose/etc/conda/cuda_10.2/envs/notebooks/lib/python3.7/contextlib.py in inner(*args, **kwds)
     72         def inner(*args, **kwds):
     73             with self._recreate_cm():
---> 74                 return func(*args, **kwds)
     75         return inner
     76 

/nvme/0/vjawa/dev/rapids/cudf/python/cudf/cudf/core/dataframe.py in __setitem__(self, arg, value)
    572                     # disc. with pandas here
    573                     # pandas raises key error here
--> 574                     self.insert(len(self._data), arg, value)
    575 
    576         elif isinstance(

/nvme/0/vjawa/dev/rapids/compose/etc/conda/cuda_10.2/envs/notebooks/lib/python3.7/contextlib.py in inner(*args, **kwds)
     72         def inner(*args, **kwds):
     73             with self._recreate_cm():
---> 74                 return func(*args, **kwds)
     75         return inner
     76 

/nvme/0/vjawa/dev/rapids/cudf/python/cudf/cudf/core/dataframe.py in insert(self, loc, name, value)
   2554 
   2555         if is_scalar(value):
-> 2556             value = utils.scalar_broadcast_to(value, len(self))
   2557 
   2558         if len(self) == 0:

/nvme/0/vjawa/dev/rapids/cudf/python/cudf/cudf/utils/utils.py in scalar_broadcast_to(scalar, size, dtype)
     71 
     72     if isinstance(scalar, pd.Categorical):
---> 73         return scalar_broadcast_to(scalar.categories[0], size).astype(dtype)
     74 
     75     if isinstance(scalar, str) and (is_string_dtype(dtype) or dtype is None):

/nvme/0/vjawa/dev/rapids/cudf/python/cudf/cudf/core/column/column.py in astype(self, dtype, **kwargs)
    826             return self.as_string_column(dtype, **kwargs)
    827         else:
--> 828             return self.as_numerical_column(dtype, **kwargs)
    829 
    830     def as_categorical_column(self, dtype, **kwargs):

/nvme/0/vjawa/dev/rapids/cudf/python/cudf/cudf/core/column/string.py in as_numerical_column(self, dtype, **kwargs)
   3808                 raise ValueError(
   3809                     "Could not convert strings to float \
-> 3810                         type due to presence of non-floating values."
   3811                 )
   3812 

ValueError: Could not convert strings to float                         type due to presence of non-floating values.
```

Below works: 
```
import numpy as np
head = cudf.DataFrame({'a':[1,2]})
cat_s = pd.Categorical.from_codes(np.zeros(len(head), dtype=int), categories=['cat.csv'])
head.assign(path=cat_s)
```

```python
head = cudf.DataFrame({'a':[1]})
head['a'] = cudf.Series(pd.Categorical.from_codes(np.zeros(len(head), dtype=int), categories=['cat.csv']))
head
```

Its probably something we do in `assign` . Taking a look.
