### ISSUE TITLE
`dask/cudf` runs OOM and core dumps on operations following `GroupBy.agg`

### ISSUE THREAD

**Issue by trstovall** [rapidsai/cudf#2285]
```
>>> df
<dask_cudf.DataFrame | 3750 tasks | 96 npartitions>
>>> 
>>> df = df.groupby(
...     [col + '_dup' for col in groupby_key]
... )
>>> df
<dask.dataframe.groupby.DataFrameGroupBy object at 0x7fc600b82e48>
>>> 
>>> df = df.agg({
...     **{'retail_price': 'sum', 'unit_qty': 'sum'},
...     **{k: 'min' for k in groupby_key}
... })
>>> 
>>> df
<dask_cudf.DataFrame | 3861 tasks | 1 npartitions>
>>> 
>>> df = df.reset_index(
...     '_'
... )
WARNING: Logging before flag parsing goes to stderr.
E0618 19:57:05.578486 140486081763072 driver.py:321] Call to cuMemcpyDtoD results in CUDA_ERROR_INVALID_VALUE
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/conda/lib/python3.7/site-packages/dask_cudf/core.py", line 420, in reset_index
    sizes = np.asarray(compute(*map(delayed(len), dfs)))
  File "/conda/lib/python3.7/site-packages/dask/base.py", line 398, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/conda/lib/python3.7/site-packages/dask/threaded.py", line 76, in get
    pack_exception=pack_exception, **kwargs)
  File "/conda/lib/python3.7/site-packages/dask/local.py", line 462, in get_async
    raise_exception(exc, tb)
  File "/conda/lib/python3.7/site-packages/dask/compatibility.py", line 112, in reraise
    raise exc
  File "/conda/lib/python3.7/site-packages/dask/local.py", line 230, in execute_task
    result = _execute_task(task, data)
  File "/conda/lib/python3.7/site-packages/dask/core.py", line 118, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/conda/lib/python3.7/site-packages/dask/core.py", line 118, in <listcomp>
    args2 = [_execute_task(a, cache) for a in args]
  File "/conda/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/conda/lib/python3.7/site-packages/dask/optimization.py", line 942, in __call__
    dict(zip(self.inkeys, args)))
  File "/conda/lib/python3.7/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/conda/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/conda/lib/python3.7/site-packages/dask/dataframe/methods.py", line 163, in assign
    return df.assign(**kwargs)
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+938.g1ebf10f-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py", line 377, in assign
    new = self.copy()
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+938.g1ebf10f-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py", line 934, in copy
    df._cols[k] = self._cols[k].copy(deep)
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+938.g1ebf10f-py3.7-linux-x86_64.egg/cudf/dataframe/series.py", line 163, in copy
    result._column = self._column.copy(deep)
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+938.g1ebf10f-py3.7-linux-x86_64.egg/cudf/dataframe/column.py", line 357, in copy
    deep = self.copy_data()
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+938.g1ebf10f-py3.7-linux-x86_64.egg/cudf/dataframe/column.py", line 349, in copy_data
    return self.replace(data=self.data.copy())
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+938.g1ebf10f-py3.7-linux-x86_64.egg/cudf/dataframe/buffer.py", line 189, in copy
    return Buffer(mem=cudautils.copy_array(self.mem),
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+938.g1ebf10f-py3.7-linux-x86_64.egg/cudf/utils/cudautils.py", line 129, in copy_array
    out.copy_to_device(arr)
  File "/conda/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 212, in _require_cuda_context
    return fn(*args, **kws)
  File "/conda/lib/python3.7/site-packages/numba/cuda/cudadrv/devicearray.py", line 188, in copy_to_device
    _driver.device_to_device(self, ary, self.alloc_size, stream=stream)
  File "/conda/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1874, in device_to_device
    fn(device_pointer(dst), device_pointer(src), size, *varargs)
  File "/conda/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 293, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/conda/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 328, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [1] Call to cuMemcpyDtoD results in CUDA_ERROR_INVALID_VALUE
>>> terminate called after throwing an instance of 'thrust::system::system_error'
  what():  rmm_allocator::allocate(): RMM_ALLOC: unspecified launch failure
Aborted (core dumped)
```

**Comment by kkraus14** [comment]
This should be resolved as of 0.13 with the big groupby refactor. Closing.
