### ISSUE TITLE
[BUG] groupby aggregation is causing out of memory

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#2287]
I'm having a data-frame of size, ~300 million records x 25 columns. When I read that csv with dask-cudf and do groupby and an aggregation operation like `count` or `sum`, I see memory exception like below.

Data can't be published publicly hence giving dummy data:
(But if needed, I can help provide you the actual csv file being used internally. Please feel free to slack me.)
```python
import cudf
import dask_cudf
import pandas as pd
import numpy as np
df = pd.DataFrame({})
df['x']= np.random.randint(2927815, size=292781506)
df['x1']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x2']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x3']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x4']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x5']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x6']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x7']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x8']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x9']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x10']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x11']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x12']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x13']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x14']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x15']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x16']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x17']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x18']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x19']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x20']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x21']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x22']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x23']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x24']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df['x25']= np.random.uniform(low=0.01, high=132643767.3, size=(292781506,))
df.to_csv('sample.csv')
```

Actual code:
```python
import cudf
import dask_cudf
from dask.distributed import Client, wait
from dask_cuda import LocalCUDACluster
cluster = LocalCUDACluster(device_memory_limit=int(16e9))
client = Client(cluster)
df = dask_cudf.read_csv('sample.csv',chunksize='50 MiB')
df_grouped = df.groupby(["x"]).count()
print(df_grouped.head())
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-6be08e1d0701> in <module>
----> 1 print(df_grouped.head())

/conda/envs/cudf/lib/python3.7/site-packages/dask/dataframe/core.py in head(self, n, npartitions, compute)
    898 
    899         if compute:
--> 900             result = result.compute()
    901         return result
    902 

/conda/envs/cudf/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    154         dask.base.compute
    155         """
--> 156         (result,) = compute(self, traverse=False, **kwargs)
    157         return result
    158 

/conda/envs/cudf/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    396     keys = [x.__dask_keys__() for x in collections]
    397     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 398     results = schedule(dsk, keys, **kwargs)
    399     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    400 

/conda/envs/cudf/lib/python3.7/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2508                     should_rejoin = False
   2509             try:
-> 2510                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2511             finally:
   2512                 for f in futures.values():

/conda/envs/cudf/lib/python3.7/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1799                 direct=direct,
   1800                 local_worker=local_worker,
-> 1801                 asynchronous=asynchronous,
   1802             )
   1803 

/conda/envs/cudf/lib/python3.7/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
    762             return future
    763         else:
--> 764             return sync(self.loop, func, *args, **kwargs)
    765 
    766     def __repr__(self):

/conda/envs/cudf/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    329             e.wait(10)
    330     if error[0]:
--> 331         six.reraise(*error[0])
    332     else:
    333         return result[0]

/conda/envs/cudf/lib/python3.7/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

/conda/envs/cudf/lib/python3.7/site-packages/distributed/utils.py in f()
    314             if timeout is not None:
    315                 future = gen.with_timeout(timedelta(seconds=timeout), future)
--> 316             result[0] = yield future
    317         except Exception as exc:
    318             error[0] = sys.exc_info()

/conda/envs/cudf/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

/conda/envs/cudf/lib/python3.7/site-packages/tornado/gen.py in run(self)
    740                     if exc_info is not None:
    741                         try:
--> 742                             yielded = self.gen.throw(*exc_info)  # type: ignore
    743                         finally:
    744                             # Break up a reference to itself

/conda/envs/cudf/lib/python3.7/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1656                             exc = CancelledError(key)
   1657                         else:
-> 1658                             six.reraise(type(exception), exception, traceback)
   1659                         raise exc
   1660                     if errors == "skip":

/conda/envs/cudf/lib/python3.7/site-packages/six.py in reraise(tp, value, tb)
    690                 value = tp()
    691             if value.__traceback__ is not tb:
--> 692                 raise value.with_traceback(tb)
    693             raise value
    694         finally:

/conda/envs/cudf/lib/python3.7/site-packages/dask/compatibility.py in apply()
     91     def apply(func, args, kwargs=None):
     92         if kwargs:
---> 93             return func(*args, **kwargs)
     94         else:
     95             return func(*args)

/conda/envs/cudf/lib/python3.7/site-packages/dask/dataframe/groupby.py in _groupby_aggregate()
    232 
    233 def _groupby_aggregate(df, aggfunc=None, levels=None):
--> 234     return aggfunc(df.groupby(level=levels, sort=False))
    235 
    236 

/conda/envs/cudf/lib/python3.7/site-packages/dask/utils.py in __call__()
    770 
    771     def __call__(self, obj, *args, **kwargs):
--> 772         return getattr(obj, self.method)(*args, **kwargs)
    773 
    774     def __reduce__(self):

/conda/envs/cudf/lib/python3.7/site-packages/cudf/groupby/groupby.py in sum()
    438 
    439     def sum(self):
--> 440         return self._apply_basic_agg("sum")
    441 
    442     def mean(self):

/conda/envs/cudf/lib/python3.7/site-packages/cudf/groupby/groupby.py in _apply_basic_agg()
    237                     agg_groupby._df._cols[by] = self._df._cols[by]
    238         return cpp_apply_basic_agg(agg_groupby, agg_type,
--> 239                                    sort_results=self.sort)
    240 
    241     def apply_multiindex_or_single_index(self, result):

cudf/bindings/groupby/groupby.pyx in cudf.bindings.groupby.groupby.apply_basic_agg()

cudf/bindings/groupby/groupby.pyx in cudf.bindings.groupby.groupby.apply_groupby()

RuntimeError: parallel_for failed: out of memory
```

Version:
branch-0.8

Additional context:
I've tried reducing the chunk size to as little as 25MiB as well and still see this issue.

**Comment by randerzander** [comment]
May be fixed by #2396 and dask/#5184

**Comment by GarrisonD** [comment]
I create a data frame this way (it has only 3 groups):

```python3
import cudf
import numpy as np

df = cudf.DataFrame()

for i in range(5): df[f'col_{i}'] = np.random.randint(3, size=100_000_000, dtype='int8')
    
df.dtypes
```

```
Out[1]: 
col_0    int8
col_1    int8
col_2    int8
col_3    int8
col_4    int8
dtype: object
```

And after that, I am trying to:

```python3
agg = {
    'col_1': ['mean'],
    'col_2': ['mean'],
    'col_3': ['mean'],
}

df.groupby('col_0').agg(agg)
```

```
Out[2]: 
          col_1     col_2     col_3
col_0                              
0      1.000180  1.000014  0.999990
1      1.000027  1.000018  0.999688
2      0.999865  0.999915  0.999913
```

And I end up with 0.8 GB used memory in GPU.

But if I try to get `mean` for the `col_4` as well I get an out-of-memory error:

```python3
agg = {
    'col_1': ['mean'],
    'col_2': ['mean'],
    'col_3': ['mean'],
    'col_4': ['mean'],
}

%time df.groupby('col_0').agg(agg)
```

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<timed eval> in <module>

~/miniconda3/envs/test/lib/python3.7/site-packages/cudf/groupby/groupby.py in agg(self, func)
     44 
     45     def agg(self, func):
---> 46         return self._apply_aggregation(func)
     47 
     48     def size(self):

~/miniconda3/envs/test/lib/python3.7/site-packages/cudf/groupby/groupby.py in _apply_aggregation(self, agg)
     97         Applies the aggregation function(s) ``agg`` on all columns
     98         """
---> 99         result = self._groupby.compute_result(agg)
    100         nvtx_range_pop()
    101         return result

~/miniconda3/envs/test/lib/python3.7/site-packages/cudf/groupby/groupby.py in compute_result(self, agg)
    233 
    234         out_key_columns, out_value_columns = _groupby_engine(
--> 235             self.key_columns, self.value_columns, aggs_as_list, self.sort
    236         )
    237 

~/miniconda3/envs/test/lib/python3.7/site-packages/cudf/groupby/groupby.py in _groupby_engine(key_columns, value_columns, aggs, sort)
    413     """
    414     out_key_columns, out_value_columns = cpp_apply_groupby(
--> 415         key_columns, value_columns, aggs
    416     )
    417 

cudf/bindings/groupby/groupby.pyx in cudf.bindings.groupby.groupby.apply_groupby()

RuntimeError: RMM error encountered at: /conda/conda-bld/libcudf_1566415000697/work/cpp/src/column/legacy/column.cpp:222: 4 RMM_ERROR_OUT_OF_MEMORY
```

Does anybody know why additional `int8` column in aggregation blows up memory requirements from 0.8 GB to 11+ GB?

***

My wooden workstation:

**CPU**: Intel i7-4790
**RAM**: 16GB 1600MHz
**GPU**: NVidia GTX 1080 Ti

**Comment by GarrisonD** [comment]
@kkraus14 @harrism Any pointer on the above would help. Thank you!

**Comment by kkraus14** [comment]
@galipremsagar can you check if this is still an issue?

**Comment by galipremsagar** [comment]
The original issue still seems to exist on a machine with 4 T4's. Seeing the GPU memory usage blow up, this looks like a memory pressure issue to me.

```python
>>> import cudf
>>> import dask_cudf
>>> from dask.distributed import Client, wait
>>> from dask_cuda import LocalCUDACluster
>>> cluster = LocalCUDACluster(device_memory_limit=int(16e9))
>>> client = Client(cluster)
>>> df = dask_cudf.read_csv('sample.csv',chunksize='50 MiB')
>>> df_grouped = df.groupby(["x"]).count()
>>> print(df_grouped.head())
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((<function apply at 0x7f531462cd40>, <function _groupby_aggregate at 0x7f520c9a5200>, [(<function _concat at 0x7f522039b680>, [         Unnamed: 0  x1  x2  x3  x4  x5  x6  ...  x19  x20  x21  x22  x23  x24  x25
x                                            ...                                   
417996            1   1   1   1   1   1   1  ...    1    1    1    1    1    1    1
2462786           4   4   4   4   4   4   4  ...    4    4    4    4    4    4    4
882387            1   1   1   1   1   1   1  ...    1    1    1    1    1    1    1
1939776           2   2   2   2   2   2   2  ...    2    2    2    2    2    2    2
872417            2   2   2   2   2   2   2  ...    2    2    2    2    2    2    2
...             ...  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...  ...
2125622           2   2   2   2   2   2   2  ...    2    2    2    2    2    2    2
989282            2   2   2   2   2   2   2  ...    2    2    2    2    2    2    2
2271272           7   7   7   7 
kwargs:    {}
Exception: MemoryError('std::bad_alloc: CUDA error at: /conda/conda-bld/librmm_1590586404909/work/include/rmm/mr/device/cuda_memory_resource.hpp66: cudaErrorMemoryAllocation out of memory')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.17.2+7.g22195a4.dirty-py3.7.egg/dask/dataframe/core.py", line 1004, in head
    return self._head(n=n, npartitions=npartitions, compute=compute, safe=True)
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.17.2+7.g22195a4.dirty-py3.7.egg/dask/dataframe/core.py", line 1037, in _head
    result = result.compute()
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.17.2+7.g22195a4.dirty-py3.7.egg/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.17.2+7.g22195a4.dirty-py3.7.egg/dask/base.py", line 444, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/conda/envs/cudf/lib/python3.7/site-packages/distributed/client.py", line 2674, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/conda/envs/cudf/lib/python3.7/site-packages/distributed/client.py", line 1974, in gather
    asynchronous=asynchronous,
  File "/conda/envs/cudf/lib/python3.7/site-packages/distributed/client.py", line 824, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/conda/envs/cudf/lib/python3.7/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/conda/envs/cudf/lib/python3.7/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/conda/envs/cudf/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/conda/envs/cudf/lib/python3.7/site-packages/distributed/client.py", line 1833, in _gather
    raise exception.with_traceback(traceback)
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.17.2+7.g22195a4.dirty-py3.7.egg/dask/utils.py", line 31, in apply
    return func(*args, **kwargs)
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.17.2+7.g22195a4.dirty-py3.7.egg/dask/dataframe/groupby.py", line 281, in _groupby_aggregate
    return aggfunc(df.groupby(level=levels, sort=sort, **dropna), **kwargs)
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.17.2+7.g22195a4.dirty-py3.7.egg/dask/utils.py", line 895, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
  File "/conda/envs/cudf/lib/python3.7/site-packages/cudf/core/groupby/groupby.py", line 254, in _agg_func_name_with_args
    return self.agg(func)
  File "/conda/envs/cudf/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/conda/envs/cudf/lib/python3.7/site-packages/cudf/core/groupby/groupby.py", line 141, in agg
    result = self._groupby.aggregate(self.obj, normalized_aggs)
  File "cudf/_lib/groupby.pyx", line 144, in cudf._lib.groupby.GroupBy.aggregate
MemoryError: std::bad_alloc: CUDA error at: /conda/conda-bld/librmm_1590586404909/work/include/rmm/mr/device/cuda_memory_resource.hpp66: cudaErrorMemoryAllocation out of memory
```


However the issue @GarrisonD mentioned in this thread seems to be fixed. With a 16GB card(T4) the code you have posted seems to be working well. The memory usage never crossed 2.5GB for me.

```python
In [1]: import cudf 
   ...: import numpy as np 
   ...:  
   ...: df = cudf.DataFrame()                   

In [2]: for i in range(5): df[f'col_{i}'] = np.r
   ...: andom.randint(3, size=100_000_000, dtype
   ...: ='int8')                                

In [3]: agg = { 
   ...:     'col_1': ['mean'], 
   ...:     'col_2': ['mean'], 
   ...:     'col_3': ['mean'], 
   ...: }                                       

In [4]: df.groupby('col_0').agg(agg)            
Out[4]: 
          col_1     col_2     col_3
           mean      mean      mean
col_0                              
0      0.999917  0.999813  0.999733
1      0.999730  1.000295  1.000019
2      1.000045  0.999972  1.000127

In [5]: agg = { 
   ...:     'col_1': ['mean'], 
   ...:     'col_2': ['mean'], 
   ...:     'col_3': ['mean'], 
   ...:     'col_4': ['mean'], 
   ...: }                                       

In [6]: df.groupby('col_0').agg(agg)            
Out[6]: 
          col_1     col_2     col_3     col_4
           mean      mean      mean      mean
col_0                                        
0      0.999917  0.999813  0.999733  1.000065
1      0.999730  1.000295  1.000019  1.000084
2      1.000045  0.999972  1.000127  0.999845

In [7]: %time df.groupby('col_0').agg(agg)      
CPU times: user 423 ms, sys: 229 ms, total: 652 ms
Wall time: 707 ms
Out[7]: 
          col_1     col_2     col_3     col_4
           mean      mean      mean      mean
col_0                                        
0      0.999917  0.999813  0.999733  1.000065
1      0.999730  1.000295  1.000019  1.000084
2      1.000045  0.999972  1.000127  0.999845

In [8]: %timeit df.groupby('col_0').agg(agg)    
600 ms ± 42.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by beckernick** [comment]
We've made quite a few memory management improvements since the May 2020. I suspect this example is no longer a problem.
