### ISSUE TITLE
[BUG] dask-cudf join fails

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#2412]
cudf/dask-cudf is failing in a simple join operation (I think it's simple?) 

```python
import cudf
import dask.array as da
import numpy as np
import dask.dataframe as dd
from distributed.utils import log_errors

def f():
    with log_errors(pdb=True):
        # Create a simple random array
        # n_rows = 5000000
        n_rows = 500000
        n_keys = 10
        chunks = n_rows // 100
        left = dd.concat([
            da.random.random(n_rows, chunks=chunks).to_dask_dataframe(columns='x'),
            da.random.randint(0, n_keys, size=n_rows,
                chunks=chunks).to_dask_dataframe(columns='id'),], axis=1).persist()

        right = dd.concat([
            da.random.random(n_rows, chunks=chunks).to_dask_dataframe(columns='y'),
            da.random.randint(0, n_keys, size=n_rows,
                chunks=chunks).to_dask_dataframe(columns='id'),], axis=1).persist()


        print('converting to cudf...')
        gright = right.map_partitions(cudf.from_pandas)
        gleft = left.map_partitions(cudf.from_pandas)

        print('merging...')
        res = gleft.merge(gright, on=['id'], how='left')
        res = res.persist()
        out = res.head()
        print(out)

if __name__ == "__main__":
    f()
```

It fails with `RMM_ERROR_OUT_OF_MEMORY`:

```
distributed.utils - ERROR - RMM error encountered at: ../src/join/join_compute_api.h:332: 4 RMM_ERROR_OUT_OF_MEMORY
Traceback (most recent call last):
  File "/home/nfs/bzaitlen/GitRepos/distributed/distributed/utils.py", line 712, in log_errors
    yield
  File "dask-cudf-scatter-test.py", line 31, in f
    res = res.persist()
  File "/home/nfs/bzaitlen/GitRepos/dask/dask/base.py", line 148, in persist
    (result,) = persist(self, traverse=False, **kwargs)
  File "/home/nfs/bzaitlen/GitRepos/dask/dask/base.py", line 639, in persist
    results = schedule(dsk, keys, **kwargs)
  File "/home/nfs/bzaitlen/GitRepos/dask/dask/local.py", line 532, in get_sync
    return get_async(apply_sync, 1, dsk, keys, **kwargs)
  File "/home/nfs/bzaitlen/GitRepos/dask/dask/local.py", line 499, in get_async
    fire_task()
  File "/home/nfs/bzaitlen/GitRepos/dask/dask/local.py", line 471, in fire_task
    callback=queue.put,
  File "/home/nfs/bzaitlen/GitRepos/dask/dask/local.py", line 521, in apply_sync
    res = func(*args, **kwds)
  File "/home/nfs/bzaitlen/GitRepos/dask/dask/local.py", line 238, in execute_task
    result = pack_exception(e, dumps)
  File "/home/nfs/bzaitlen/GitRepos/dask/dask/local.py", line 233, in execute_task
    result = _execute_task(task, data)
  File "/home/nfs/bzaitlen/GitRepos/dask/dask/core.py", line 118, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/home/nfs/bzaitlen/GitRepos/dask/dask/core.py", line 118, in <listcomp>
    args2 = [_execute_task(a, cache) for a in args]
  File "/home/nfs/bzaitlen/GitRepos/dask/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/home/nfs/bzaitlen/GitRepos/cudf/python/dask_cudf/dask_cudf/join_impl.py", line 62, in merge
    return left.merge(right, on=on, how=how, suffixes=(lsuffix, rsuffix))
  File "/home/nfs/bzaitlen/GitRepos/cudf/python/cudf/cudf/dataframe/dataframe.py", line 1964, in merge
    lhs._cols, rhs._cols, left_on, right_on, how, method
  File "cudf/bindings/join.pyx", line 26, in cudf.bindings.join.join
  File "cudf/bindings/join.pyx", line 107, in cudf.bindings.join.join
RuntimeError: RMM error encountered at: ../src/join/join_compute_api.h:332: 4 RMM_ERROR_OUT_OF_MEMORY
> /home/nfs/bzaitlen/GitRepos/distributed/distributed/utils.py(724)log_errors()
```

I'm fairly certain this particular join was working in 0.8 but I still have to confirm that.  

Do you @shwina or @kkraus14 have any thoughts here ?

*Note: this is the test I am using for the dask-ucx join benchmark*

cc @mrocklin

**Comment by kkraus14** [comment]
Looks like it went OOM according to RMM. Have you watched `nvidia-smi` while this is running to see if anything looks off or if all GPU's memories are skyrocketing?

**Comment by mrocklin** [comment]
Ah, right, here might be the problem:

```python
        n_keys = 10
```

We should recall that joins will have as many output rows as there are pairwise matches in the left and right sides.  To control for quadraticly scaling output size we'll probably want a number of keys that is on the order of the number of rows.

**Comment by quasiben** [comment]
@mrocklin @kkraus14 yes, the memory explosion was a problem on my end.  Apologies -- closing
