### ISSUE TITLE
[FEA]GpuDataReader doesn't support parquet

### ISSUE THREAD

**Issue by leizhanggit** [rapidsai/cudf#2443]
**Is your feature request related to a problem? Please describe.**
GpuDataReader doesn't support parquet. Although I have seen it has function parquet(), however, when I run training, an error pop up: 

> java.lang.UnsupportedOperationException: No Parquet read options are supported

```
	at ml.dmlc.xgboost4j.scala.spark.rapids.GpuDataset$.ml$dmlc$xgboost4j$scala$spark$rapids$GpuDataset$$buildParquetOptions(GpuDataset.scala:600)
	at ml.dmlc.xgboost4j.scala.spark.rapids.GpuDataset$.getParquetPartFileReader(GpuDataset.scala:546)
	at ml.dmlc.xgboost4j.scala.spark.rapids.GpuDataset$.ml$dmlc$xgboost4j$scala$spark$rapids$GpuDataset$$getPartFileReader(GpuDataset.scala:500)
	at ml.dmlc.xgboost4j.scala.spark.rapids.GpuDataset.buildRDD(GpuDataset.scala:93)
	at ml.dmlc.xgboost4j.scala.spark.rapids.GpuDataset.mapColumnarSingleBatchPerPartition(GpuDataset.scala:108)
	at ml.dmlc.xgboost4j.scala.spark.rapids.GpuDataset.findNumClasses(GpuDataset.scala:146)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.getNumberClasses(XGBoostClassifier.scala:228)
	at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.fit(XGBoostClassifier.scala:247)
	at line5bf9c094a9e34bb49e6bbd4913f2a43074.$read$$iw$$iw$$iw$$iw$$iw$$iw$$anonfun$1.apply(command-1436081708071208:14)
	at line5bf9c094a9e34bb49e6bbd4913f2a43074.$read$$iw$$iw$$iw$$iw$$iw$$iw$$anonfun$1.apply(command-1436081708071208:14)
	at line5bf9c094a9e34bb49e6bbd4913f2a43074.$read$$iw$$iw$$iw$$iw$$iw$$iw$Benchmark$.time(command-1436081708071208:4)
	at line5bf9c094a9e34bb49e6bbd4913f2a43074.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-1436081708071208:13)
	at line5bf9c094a9e34bb49e6bbd4913f2a43074.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-1436081708071208:68)
	at line5bf9c094a9e34bb49e6bbd4913f2a43074.$read$$iw$$iw$$iw$$iw.<init>(command-1436081708071208:70)
	at line5bf9c094a9e34bb49e6bbd4913f2a43074.$read$$iw$$iw$$iw.<init>(command-1436081708071208:72)
	at line5bf9c094a9e34bb49e6bbd4913f2a43074.$read$$iw$$iw.<init>(command-1436081708071208:74)
	at line5bf9c094a9e34bb49e6bbd4913f2a43074.$read$$iw.<init>(command-1436081708071208:76)
	at line5bf9c094a9e34bb49e6bbd4913f2a43074.$read.<init>(command-1436081708071208:78)
	at line5bf9c094a9e34bb49e6bbd4913f2a43074.$read$.<init>(command-1436081708071208:82)
	at line5bf9c094a9e34bb49e6bbd4913f2a43074.$read$.<clinit>(command-1436081708071208)
	at line5bf9c094a9e34bb49e6bbd4913f2a43074.$eval$.$print$lzycompute(<notebook>:7)

```

**Comment by jlowe** [comment]
This is something specific to xgboost and is not related to cudf.  I would recommend posting an issue against https://github.com/rapidsai/xgboost but issues appear to be turned off there.   Instead I suggest raising the issue at https://github.com/rapidsai/spark-examples/issues where the GPU-accelerated xgboost examples are using GpuDataReader.

The error indicates GpuDataReader is being passed extra parsing options, probably via the `options` method, and the Parquet parser currently does not support any specified options.  When filing the new issue, I recommend pointing to or pasting any relevant code needed to reproduce the error, e.g.: any code that is calling methods on GpuDataReader.
