### ISSUE TITLE
[DOC] Incorrectly documented Boost dependency

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#2599]
## Report incorrect documentation

**Location of incorrect documentation**
https://github.com/rapidsai/cudf/blob/branch-0.10/CONTRIBUTING.md#setting-up-your-build-environment

**Describe the problems or issues found in the documentation**
The Build From Source instructions list that cuDF depends on `libboost_filesystem` version 1.58 which can be satisfied on Ubuntu 16.04 via `sudo apt-get install libboost-all-dev`. However, as of 305db1fbe9d9cfeaf355242ad2a436afdb82d27c when attempting to run a Python cuDF script, I receive the error:

```
Traceback (most recent call last):
  File "repro.py", line 1, in <module>
    import cudf
  File "/home/jhemstad/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/cudf-0.9.0a0+2783.g305db1f.dirty-py3.7-linux-x86_64.egg/cudf/__init__.py", line 5, in <module>
    from cudf import dataframe, datasets
  File "/home/jhemstad/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/cudf-0.9.0a0+2783.g305db1f.dirty-py3.7-linux-x86_64.egg/cudf/dataframe/__init__.py", line 3, in <module>
    from cudf.dataframe import (
  File "/home/jhemstad/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/cudf-0.9.0a0+2783.g305db1f.dirty-py3.7-linux-x86_64.egg/cudf/dataframe/categorical.py", line 10, in <module>
    import cudf.bindings.replace as cpp_replace
ImportError: libboost_filesystem.so.1.68.0: cannot open shared object file: No such file or directory
```

Which implies that we actually depend on version 1.68. 

**Suggested fix for documentation**

Update version and suggest that the boost dependency cannot be resolved via default channels in Ubuntu 16.04.

**Comment by rongou** [comment]
Perhaps this can be closed. By default libcudf links to boost shared libraries, which are provided by the `boost-cpp` conda package that should be part of the conda environment. So normally one does not need to apt install boost any more.
