### ISSUE TITLE
[BUG] cudf.DataFrame.from_gpu_matrix dosen't work with large matrix 

### ISSUE THREAD

**Issue by abc99lr** [rapidsai/cudf#2710]
**Describe the bug**

When using `cudf.DataFrame.from_gpu_matrix` to convert a GPU matrix into data frame, I got ` Call to cuLaunchKernel results in CUDA_ERROR_INVALID_VALUE` error. The size of the matrix is 8800000*28*4B = 985.6 MB which is smaller than 1GB. I got this error on a DGX machine with V100 16GB GPU on it. Converting smaller GPU matrix (e.g. selecting first 1000 rows from the matrix) works fine. 

**Steps/Code to reproduce bug**
```
(cuml_rf_bench) rlan@prm-dgx-25:/gpfs/fs1/rlan/rf_bench/gbm-bench$ python 
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf
>>> print(cudf.__version__)
0.10.0a+810.g50a9dc7
>>> import numpy as np 
>>> from numba import cuda
>>> 
>>> x_cpu = np.random.randint(1000, size=(8800000, 28), dtype=np.int32)
>>> 
>>> x_gpu = cuda.to_device(x_cpu)
>>> x_gpu_df = cudf.DataFrame.from_gpu_matrix(x_gpu)
ERROR:Call to cuLaunchKernel results in CUDA_ERROR_INVALID_VALUE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/fs1/rlan/anaconda3/envs/cuml_rf_bench/lib/python3.7/site-packages/cudf/core/dataframe.py", line 3355, in from_gpu_matrix
    data = data.transpose()  # to mimic the pandas behaviour
  File "/gpfs/fs1/rlan/anaconda3/envs/cuml_rf_bench/lib/python3.7/site-packages/numba/cuda/cudadrv/devicearray.py", line 147, in transpose
    return transpose(self)
  File "/gpfs/fs1/rlan/anaconda3/envs/cuml_rf_bench/lib/python3.7/site-packages/numba/cuda/kernels/transpose.py", line 63, in transpose
    kernel[blocks, threads, stream](a, b)
  File "/gpfs/fs1/rlan/anaconda3/envs/cuml_rf_bench/lib/python3.7/site-packages/numba/cuda/compiler.py", line 808, in __call__
    cfg(*args)
  File "/gpfs/fs1/rlan/anaconda3/envs/cuml_rf_bench/lib/python3.7/site-packages/numba/cuda/compiler.py", line 538, in __call__
    sharedmem=self.sharedmem)
  File "/gpfs/fs1/rlan/anaconda3/envs/cuml_rf_bench/lib/python3.7/site-packages/numba/cuda/compiler.py", line 612, in _kernel_call
    cu_func(*kernelargs)
  File "/gpfs/fs1/rlan/anaconda3/envs/cuml_rf_bench/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1575, in __call__
    self.sharedmem, streamhandle, args)
  File "/gpfs/fs1/rlan/anaconda3/envs/cuml_rf_bench/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1619, in launch_kernel
    None)
  File "/gpfs/fs1/rlan/anaconda3/envs/cuml_rf_bench/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 294, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/gpfs/fs1/rlan/anaconda3/envs/cuml_rf_bench/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 329, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [1] Call to cuLaunchKernel results in CUDA_ERROR_INVALID_VALUE
>>> x_gpu_df = cudf.DataFrame.from_gpu_matrix(x_gpu[:1000, :])
>>> 
``` 

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal 
 - Method of cuDF install: I install cudf using the provide environment .yml file from cuml branch-0.10 

**Environment details**

```
(cuml_rf_bench) rlan@prm-dgx-25:/gpfs/fs1/rlan/rf_bench/cudf$ sh print_env.sh 
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
print_env.sh: 10: [: true: unexpected operator
     Not inside a git repository
     
     ***OS Information***
     DGX_NAME="DGX Server"
     DGX_PRETTY_NAME="NVIDIA DGX Server"
     DGX_SWBUILD_DATE="2017-09-02"
     DGX_SWBUILD_VERSION="3.1.2"
     DGX_COMMIT_ID="f8777eb93fa38db7ba2c0648ba3738f8ffede979"
     DGX_SERIAL_NUMBER=QTFCOU74500E6
     
     DGX_OTA_VERSION="3.1.4"
     DGX_OTA_DATE="Tue Feb 13 15:50:09 PST 2018"
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=16.04
     DISTRIB_CODENAME=xenial
     DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
     NAME="Ubuntu"
     VERSION="16.04.6 LTS (Xenial Xerus)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 16.04.6 LTS"
     VERSION_ID="16.04"
     HOME_URL="http://www.ubuntu.com/"
     SUPPORT_URL="http://help.ubuntu.com/"
     BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
     VERSION_CODENAME=xenial
     UBUNTU_CODENAME=xenial
     Linux prm-dgx-25 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Thu Aug 29 17:11:45 2019       
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla V100-SXM2...  On   | 00000000:06:00.0 Off |                    0 |
     | N/A   29C    P0    56W / 300W |   4504MiB / 16130MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla V100-SXM2...  On   | 00000000:07:00.0 Off |                    0 |
     | N/A   29C    P0    41W / 300W |     11MiB / 16130MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla V100-SXM2...  On   | 00000000:0A:00.0 Off |                    0 |
     | N/A   28C    P0    41W / 300W |     11MiB / 16130MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   3  Tesla V100-SXM2...  On   | 00000000:0B:00.0 Off |                    0 |
     | N/A   27C    P0    42W / 300W |     11MiB / 16130MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   4  Tesla V100-SXM2...  On   | 00000000:85:00.0 Off |                    0 |
     | N/A   27C    P0    40W / 300W |     11MiB / 16130MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   5  Tesla V100-SXM2...  On   | 00000000:86:00.0 Off |                    0 |
     | N/A   28C    P0    42W / 300W |     11MiB / 16130MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   6  Tesla V100-SXM2...  On   | 00000000:89:00.0 Off |                    0 |
     | N/A   28C    P0    42W / 300W |     11MiB / 16130MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   7  Tesla V100-SXM2...  On   | 00000000:8A:00.0 Off |                    0 |
     | N/A   29C    P0    43W / 300W |     11MiB / 16130MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |    0     24390      C   ...anaconda3/envs/cuml_rf_bench/bin/python  4493MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:          x86_64
     CPU op-mode(s):        32-bit, 64-bit
     Byte Order:            Little Endian
     CPU(s):                80
     On-line CPU(s) list:   0-79
     Thread(s) per core:    2
     Core(s) per socket:    20
     Socket(s):             2
     NUMA node(s):          2
     Vendor ID:             GenuineIntel
     CPU family:            6
     Model:                 79
     Model name:            Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
     Stepping:              1
     CPU MHz:               2699.984
     CPU max MHz:           3600.0000
     CPU min MHz:           1200.0000
     BogoMIPS:              4392.11
     Virtualization:        VT-x
     L1d cache:             32K
     L1i cache:             32K
     L2 cache:              256K
     L3 cache:              51200K
     NUMA node0 CPU(s):     0-19,40-59
     NUMA node1 CPU(s):     20-39,60-79
     Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts flush_l1d
     
     ***CMake***
     /gpfs/fs1/rlan/anaconda3/envs/cuml_rf_bench/bin/cmake
     cmake version 3.14.5
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
     Copyright (C) 2015 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /gpfs/sw/software/CUDA/10.0.130/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2018 NVIDIA Corporation
     Built on Sat_Aug_25_21:08:01_CDT_2018
     Cuda compilation tools, release 10.0, V10.0.130
     
     ***Python***
     /gpfs/fs1/rlan/anaconda3/envs/cuml_rf_bench/bin/python
     Python 3.7.3
     
     ***Environment Variables***
     PATH                            : /gpfs/sw/software/CUDA/10.0.130:/gpfs/sw/software/CUDA/10.0.130/bin:/gpfs/fs1/rlan/anaconda3/envs/cuml_rf_bench/bin:/gpfs/fs1/rlan/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
     LD_LIBRARY_PATH                 : /gpfs/sw/software/CUDA/10.0.130/extras/CUPTI/lib64:/gpfs/sw/software/CUDA/10.0.130/lib64
     NUMBAPRO_NVVM                   : 
     NUMBAPRO_LIBDEVICE              : 
     CONDA_PREFIX                    : /gpfs/fs1/rlan/anaconda3/envs/cuml_rf_bench
     PYTHON_PATH                     : 
     
     ***conda packages***
     conda is /gpfs/fs1/rlan/anaconda3/condabin/conda
     /gpfs/fs1/rlan/anaconda3/condabin/conda
     # packages in environment at /gpfs/fs1/rlan/anaconda3/envs/cuml_rf_bench:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main  
     arrow-cpp                 0.14.1           py37h6b969ab_0    conda-forge
     atomicwrites              1.3.0                      py_0    conda-forge
     attrs                     19.1.0                     py_0    conda-forge
     backcall                  0.1.0                    py37_0  
     blas                      1.0                    openblas  
     bleach                    3.1.0                    py37_0  
     bokeh                     1.3.4                    py37_0    conda-forge
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     brotli                    1.0.7             he1b5a44_1000    conda-forge
     bzip2                     1.0.8                h516909a_0    conda-forge
     c-ares                    1.15.0            h516909a_1001    conda-forge
     ca-certificates           2019.5.15                     1  
     certifi                   2019.6.16                py37_1  
     cffi                      1.12.3           py37h8022711_0    conda-forge
     chardet                   3.0.4                    pypi_0    pypi
     click                     7.0                        py_0    conda-forge
     cloudpickle               1.2.1                      py_0    conda-forge
     cmake                     3.14.5               hf94ab9c_0    conda-forge
     cudatoolkit               10.0.130                      0  
     cudf                      0.10.0a                py37_810    rapidsai-nightly
     curl                      7.65.3               hf8cf82a_0    conda-forge
     cython                    0.29.13          py37he1b5a44_0    conda-forge
     cytoolz                   0.10.0           py37h516909a_0    conda-forge
     dask                      2.3.0                      py_0    conda-forge
     dask-core                 2.3.0                      py_0    conda-forge
     dask-cuda                 0.10.0a0+8.gd4d0d9f          pypi_0    pypi
     dask-cudf                 0.10.0a                py37_810    rapidsai-nightly
     dask-glm                  0.1.0                         0    conda-forge
     dask-ml                   1.0.0                      py_0    conda-forge
     decorator                 4.4.0                    py37_1  
     defusedxml                0.6.0                      py_0  
     distributed               2.3.2                      py_1    conda-forge
     dlpack                    0.2                  he1b5a44_0    conda-forge
     double-conversion         3.1.5                he1b5a44_1    conda-forge
     entrypoints               0.3                      py37_0  
     expat                     2.2.5             he1b5a44_1003    conda-forge
     fastavro                  0.22.4           py37h516909a_0    conda-forge
     freetype                  2.10.0               he983fc9_1    conda-forge
     fsspec                    0.4.3                      py_0    conda-forge
     gflags                    2.2.2             he1b5a44_1001    conda-forge
     glog                      0.4.0                he1b5a44_1    conda-forge
     gmp                       6.1.2                h6c8ec71_1  
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     heapdict                  1.0.0                 py37_1000    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     idna                      2.8                      pypi_0    pypi
     importlib_metadata        0.18                     py37_0    conda-forge
     ipykernel                 5.1.2            py37h39e3cac_0  
     ipython                   7.7.0            py37h39e3cac_0  
     ipython_genutils          0.2.0                    py37_0  
     jedi                      0.15.1                   py37_0  
     jinja2                    2.10.1                     py_0    conda-forge
     joblib                    0.13.2                     py_0    conda-forge
     jpeg                      9c                h14c3975_1001    conda-forge
     jsonschema                3.0.2                    py37_0  
     jupyter_client            5.3.1                      py_0  
     jupyter_core              4.5.0                      py_0  
     kaggle                    1.5.5                    pypi_0    pypi
     krb5                      1.16.3            h05b26f9_1001    conda-forge
     libclang                  8.0.0                h6bb024c_0    rapidsai
     libcudf                   0.10.0a            cuda10.0_810    rapidsai-nightly
     libcumlprims              0.9.0                cuda10.0_0    nvidia
     libcurl                   7.65.3               hda55be3_0    conda-forge
     libedit                   3.1.20170329      hf8c457e_1001    conda-forge
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1             he1b5a44_1006    conda-forge
     libgcc-ng                 9.1.0                hdf63c60_0  
     libgfortran-ng            7.3.0                hdf63c60_0  
     libnvstrings              0.10.0a             cuda10.0_16    rapidsai-nightly
     libopenblas               0.3.6                h5a2b251_1  
     libpng                    1.6.37               hed695b0_0    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librmm                    0.10.0a             cuda10.0_17    rapidsai-nightly
     libsodium                 1.0.16               h1bed415_0  
     libssh2                   1.8.2                h22169c7_2    conda-forge
     libstdcxx-ng              9.1.0                hdf63c60_0  
     libtiff                   4.0.10            h57b8799_1003    conda-forge
     libuv                     1.31.0               h516909a_0    conda-forge
     llvmlite                  0.29.0           py37hfd453ef_1    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     markupsafe                1.1.1            py37h14c3975_0    conda-forge
     mistune                   0.8.4            py37h7b6447c_0  
     more-itertools            7.2.0                      py_0    conda-forge
     msgpack-python            0.6.1            py37h6bb024c_0    conda-forge
     multipledispatch          0.6.0                      py_0    conda-forge
     nb_conda_kernels          2.2.2                    py37_0  
     nbconvert                 5.5.0                      py_0  
     nbformat                  4.4.0                    py37_0  
     nccl                      2.4.6.1              cuda10.0_0    nvidia
     ncurses                   6.1               hf484d3e_1002    conda-forge
     nomkl                     3.0                           0  
     notebook                  6.0.0                    py37_0  
     numba                     0.45.1           py37hb3f55d8_0    conda-forge
     numpy                     1.16.4           py37h99e49ec_0  
     numpy-base                1.16.4           py37h2f8d375_0  
     nvstrings                 0.10.0a                 py37_16    rapidsai-nightly
     olefile                   0.46                       py_0    conda-forge
     openblas                  0.3.6                         1  
     openblas-devel            0.3.6                         1  
     openssl                   1.1.1c               h7b6447c_1  
     packaging                 19.0                       py_0    conda-forge
     pandas                    0.24.2           py37hb3f55d8_0    conda-forge
     pandoc                    2.2.3.2                       0  
     pandocfilters             1.4.2                    py37_1  
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.5.1                      py_0  
     partd                     1.0.0                      py_0    conda-forge
     patsy                     0.5.1                      py_0    conda-forge
     pexpect                   4.7.0                    py37_0  
     pickleshare               0.7.5                    py37_0  
     pillow                    6.1.0            py37h6b7be26_1    conda-forge
     pip                       19.2.3                   py37_0    conda-forge
     pluggy                    0.12.0                     py_0    conda-forge
     prometheus_client         0.7.1                      py_0  
     prompt_toolkit            2.0.9                    py37_0  
     psutil                    5.6.3            py37h516909a_0    conda-forge
     ptyprocess                0.6.0                    py37_0  
     py                        1.8.0                      py_0    conda-forge
     pyarrow                   0.14.1           py37h8b68381_0    conda-forge
     pycparser                 2.19                     py37_1    conda-forge
     pygments                  2.4.2                      py_0  
     pyparsing                 2.4.2                      py_0    conda-forge
     pyrsistent                0.14.11          py37h7b6447c_0  
     pytest                    5.1.1                    py37_0    conda-forge
     python                    3.7.3                h33d41f4_1    conda-forge
     python-dateutil           2.8.0                      py_0    conda-forge
     python-slugify            3.0.3                    pypi_0    pypi
     pytz                      2019.2                     py_0    conda-forge
     pyyaml                    5.1.2            py37h516909a_0    conda-forge
     pyzmq                     18.1.0           py37he6710b0_0  
     re2                       2019.08.01           he1b5a44_0    conda-forge
     readline                  8.0                  hf8c457e_0    conda-forge
     requests                  2.22.0                   pypi_0    pypi
     rhash                     1.3.6             h14c3975_1001    conda-forge
     rmm                       0.10.0a                 py37_17    rapidsai-nightly
     scikit-learn              0.21.2           py37h22eb022_0  
     scipy                     1.3.1            py37he2b7bc3_0  
     send2trash                1.5.0                    py37_0  
     setuptools                41.2.0                   py37_0    conda-forge
     six                       1.12.0                py37_1000    conda-forge
     snappy                    1.1.7             he1b5a44_1002    conda-forge
     sortedcontainers   
```

**Additional context**
Please ignore the existing process on GPU id 0 above. I got this error even no job is running on GPU. This issue looks similar to https://github.com/rapidsai/cudf/issues/2419, but I am not that sure if they are related.  

Thanks for looking into this.

**Comment by abc99lr** [comment]
This issue is reproducible on my work station with Titan V GPU. 
```
(cuml_dev) rlan@rlan-dt:~$ 
(cuml_dev) rlan@rlan-dt:~$ 
(cuml_dev) rlan@rlan-dt:~$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf
>>> 
>>> 
>>> import numpy as np
>>> from numba import cuda
>>> x_cpu = np.random.randint(1000, size=(8800000, 28), dtype=np.int32)
>>> x_gpu = cuda.to_device(x_cpu)
>>> x_gpu_df = cudf.DataFrame.from_gpu_matrix(x_gpu)
ERROR:Call to cuLaunchKernel results in CUDA_ERROR_INVALID_VALUE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rlan/anaconda3/envs/cuml_dev/lib/python3.7/site-packages/cudf/dataframe/dataframe.py", line 2774, in from_gpu_matrix
    data = data.transpose()  # to mimic the pandas behaviour
  File "/home/rlan/anaconda3/envs/cuml_dev/lib/python3.7/site-packages/numba/cuda/cudadrv/devicearray.py", line 147, in transpose
    return transpose(self)
  File "/home/rlan/anaconda3/envs/cuml_dev/lib/python3.7/site-packages/numba/cuda/kernels/transpose.py", line 63, in transpose
    kernel[blocks, threads, stream](a, b)
  File "/home/rlan/anaconda3/envs/cuml_dev/lib/python3.7/site-packages/numba/cuda/compiler.py", line 808, in __call__
    cfg(*args)
  File "/home/rlan/anaconda3/envs/cuml_dev/lib/python3.7/site-packages/numba/cuda/compiler.py", line 538, in __call__
    sharedmem=self.sharedmem)
  File "/home/rlan/anaconda3/envs/cuml_dev/lib/python3.7/site-packages/numba/cuda/compiler.py", line 612, in _kernel_call
    cu_func(*kernelargs)
  File "/home/rlan/anaconda3/envs/cuml_dev/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1517, in __call__
    self.sharedmem, streamhandle, args)
  File "/home/rlan/anaconda3/envs/cuml_dev/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1561, in launch_kernel
    None)
  File "/home/rlan/anaconda3/envs/cuml_dev/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 293, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/rlan/anaconda3/envs/cuml_dev/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 328, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [1] Call to cuLaunchKernel results in CUDA_ERROR_INVALID_VALUE
>>> 
>>> 
>>> 
>>> 
```

**Comment by ayushdg** [comment]
Seems like size >= 2097120 results in the `CUDA_ERROR_INVALID_VALUE`, anything less than this value works fine. Number of columns does not seem to affect the behavior. (T4 GPU)
```
x_cpu = np.random.randint(1000, size=(2097119, 1), dtype=np.int64) # This is fine
x_cpu = np.random.randint(1000, size=(2097120, 1), dtype=np.int64) # Error
```

**Comment by AK-ayush** [comment]
After inspection, I figured out that `transpose()` method on `numba cuda array` causing this error. It seems that numba cuda can't transpose the multi-dimensional array of size `>=2097120`(T4 GPU). 
Also for smaller arrays, `transpose()` method is the reason behind slowness of `from_gpu_matrix()`.

**Comment by AK-ayush** [comment]
This can be solved by utilizing the alternative apis from cupy library instead of using `transpose()` method from numba cuda.
