### ISSUE TITLE
[FEA] Decimal datatype support for cuDF and `from_arrow` support

### ISSUE THREAD

**Issue by joetl** [rapidsai/cudf#2888]
**Describe the bug**
cudf.DataFrame.from_arrow errors if the source arrow table has decimal fields
same for cudf.from_pandas errors if the source arrow table has decimal fields

**Steps/Code to reproduce bug**
import pandas as pd
import itertools
import cudf
N = 1000000
df = pd.DataFrame({'a': list(itertools.islice(itertools.cycle([0, 1, 2, 3]), N)), 'b': list(range(N))})
import decimal
df = df.assign(d=df['a'].apply(decimal.Decimal), e=df['b'].apply(decimal.Decimal))
cdf = cudf.from_pandas(df)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/cudf/dataframe/dataframe                                                                                                .py", line 3733, in from_pandas
    return DataFrame.from_pandas(obj)
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/cudf/dataframe/dataframe                                                                                                .py", line 3093, in from_pandas
    df[colk] = Series(vals, nan_as_null=nan_as_null)
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/cudf/dataframe/series.py                                                                                                ", line 117, in __init__
    data, nan_as_null=nan_as_null, dtype=dtype, name=name
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/cudf/dataframe/columnops                                                                                                .py", line 447, in as_column
    data = as_column(pa.Array.from_pandas(arbitrary))
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/cudf/dataframe/columnops                                                                                                .py", line 549, in as_column
    pamask, padata = buffers_from_pyarrow(arbitrary)
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/cudf/utils/utils.py", li                                                                                                ne 135, in buffers_from_pyarrow
    np.array(buffers[1]).view(new_dtype)[
  File "/home/ubuntu/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/core/_internal.py"                                                                                                , line 494, in _view_is_safe
    raise TypeError("Cannot change data-type for object array.")
TypeError: Cannot change data-type for object array.

**Environment overview (please complete the following information)**
 - Environment location: [ Cloud(AWS: AMI : Deep Learning AMI (Ubuntu 16.04) Version 24.2)]
 - Method of cuDF install: [conda]

**Comment by kkraus14** [comment]
@joetl we currently don't have a Decimal dtype in cuDF but it's planned for the future. Once it's implemented this will be possible. Changing this to a feature request.

**Comment by jrhemstad** [comment]
Superseded by https://github.com/rapidsai/cudf/issues/3556
