### ISSUE TITLE
[BUG] Cannot convert arrow-deserialized pandas DataFrame to cudf DataFrame

### ISSUE THREAD

**Issue by wjsi** [rapidsai/cudf#3015]
**Describe the bug**
When calling ``cudf.from_pandas`` on DataFrames deserialized from pyarrow, a TypeError with the message "expected a writable bytes-like object" is raised.

**Steps/Code to reproduce bug**
```python
import cudf
import cupy
import pyarrow as pa
import numpy as np
import pandas as pd

df = pd.DataFrame(dict(col=np.random.random((100,))))
deser_df = pa.deserialize(bytes(pa.serialize(df).to_buffer()))
cudf.from_pandas(deser_df)
```

will produce an error
```
Traceback (most recent call last):
  File "/home/wenjun/miniconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-b6959b4d6dc9>", line 1, in <module>
    cudf.from_pandas(deser_df)
  File "/home/wenjun/miniconda3/lib/python3.7/site-packages/cudf/dataframe/dataframe.py", line 2538, in from_pandas
    return DataFrame.from_pandas(obj)
  File "/home/wenjun/miniconda3/lib/python3.7/site-packages/cudf/dataframe/dataframe.py", line 2086, in from_pandas
    df[colk] = Series(vals, nan_as_null=nan_as_null)
  File "/home/wenjun/miniconda3/lib/python3.7/site-packages/cudf/dataframe/series.py", line 81, in __init__
    dtype=dtype)
  File "/home/wenjun/miniconda3/lib/python3.7/site-packages/cudf/dataframe/columnops.py", line 258, in as_column
    data = as_column(rmm.to_device(arbitrary), nan_as_null=nan_as_null)
  File "/home/wenjun/miniconda3/lib/python3.7/site-packages/librmm_cffi/wrapper.py", line 241, in to_device
    to.copy_to_device(ary, stream=stream)
  File "/home/wenjun/miniconda3/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 212, in _require_cuda_context
    return fn(*args, **kws)
  File "/home/wenjun/miniconda3/lib/python3.7/site-packages/numba/cuda/cudadrv/devicearray.py", line 205, in copy_to_device
    _driver.host_to_device(self, ary, sz, stream=stream)
  File "/home/wenjun/miniconda3/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1809, in host_to_device
    fn(device_pointer(dst), host_pointer(src), size, *varargs)
  File "/home/wenjun/miniconda3/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1727, in host_pointer
    return mviewbuf.memoryview_get_buffer(obj, forcewritable)
TypeError: expected a writable bytes-like object
```

However, the code

```python
import cudf
import cupy
import pyarrow as pa
import numpy as np
import pandas as pd

s = pd.Series(np.random.random((100,)))
deser_s = pa.deserialize(bytes(pa.serialize(s).to_buffer()))
cudf.from_pandas(deser_s)
```

returns without errors.

**Expected behavior**
As we just copy data from host to device, requiring the memory of source dataframes to be writable is not needed.

**Environment details**
Result of conda list:

```
$conda list
# packages in environment at /home/wenjun/miniconda3:
#
# Name                    Version                   Build  Channel
apipkg                    1.5                      py37_0  
arrow-cpp                 0.11.1           py37h5c3f529_1  
asn1crypto                0.24.0                   py37_0  
atomicwrites              1.3.0                    py37_1  
attrs                     19.1.0                   py37_1  
backcall                  0.1.0                    py37_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py37_0  
bokeh                     1.2.0                    py37_0  
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2019.5.15                     0  
certifi                   2019.6.16                py37_0  
cffi                      1.12.2           py37h2e261b9_1  
chardet                   3.0.4                    py37_1  
conda                     4.6.14                   py37_0  
coverage                  4.5.3            py37h7b6447c_0  
cryptography              2.6.1            py37h1ba5d50_0  
cudatoolkit               10.0.130                      0  
cudf-cuda100              0.6.1                    pypi_0    pypi
cupy-cuda100              6.1.0                    pypi_0    pypi
cython                    0.29.7                   pypi_0    pypi
dbus                      1.13.6               h746ee38_0  
decorator                 4.4.0                    py37_1  
defusedxml                0.6.0                      py_0  
entrypoints               0.3                      py37_0  
execnet                   1.6.0                      py_0  
expat                     2.2.6                he6710b0_0  
fastrlock                 0.4                      pypi_0    pypi
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_1  
gevent                    1.4.0            py37h7b6447c_0  
gflags                    2.2.2                he6710b0_0  
glib                      2.56.2               hd408876_0  
glog                      0.3.5                hf484d3e_1  
gmp                       6.1.2                h6c8ec71_1  
greenlet                  0.4.15           py37h7b6447c_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
icu                       58.2                 h9c2bf20_1  
idna                      2.8                      py37_0  
importlib_metadata        0.17                     py37_1  
intel-openmp              2019.3                      199  
ipykernel                 5.1.0            py37h39e3cac_0  
ipython                   7.5.0            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.4.2                    py37_0  
jedi                      0.13.3                   py37_0  
jinja2                    2.10.1                   py37_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.0.1                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.2.4                    py37_0  
jupyter_console           6.0.0                    py37_0  
jupyter_core              4.4.0                    py37_0  
libboost                  1.67.0               h46d08c1_4  
libedit                   3.1.20181209         hc058e9b_0  
libevent                  2.1.8                h1ba5d50_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.8.0                hd408876_0  
libsodium                 1.0.16               h1bed415_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.10               h2733197_2  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                he19cac6_0  
llvmlite                  0.29.0                   pypi_0    pypi
lz4                       2.1.9            py37h7b6447c_0  
lz4-c                     1.8.1.2              h14c3975_0  
markupsafe                1.1.1            py37h7b6447c_0  
mistune                   0.8.4            py37h7b6447c_0  
mkl                       2019.3                      199  
mkl_fft                   1.0.12           py37ha843d7b_0  
mkl_random                1.0.2            py37hd81dba3_0  
mock                      3.0.5                    py37_0  
more-itertools            7.0.0                    py37_0  
nbconvert                 5.4.1                    py37_3  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  he6710b0_1  
notebook                  5.7.8                    py37_0  
numba                     0.41.0                   pypi_0    pypi
numexpr                   2.6.9            py37h9e4a6bb_0  
numpy                     1.16.3                   pypi_0    pypi
numpy-base                1.16.4           py37hde5b4d6_0  
nvstrings-cuda100         0.3.0.post1              pypi_0    pypi
olefile                   0.46                     py37_0  
openssl                   1.1.1c               h7b6447c_1  
packaging                 19.0                     py37_0  
pandas                    0.24.2           py37he6710b0_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
parso                     0.4.0                      py_0  
pcre                      8.43                 he6710b0_0  
pexpect                   4.7.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    6.0.0            py37h34e0f95_0  
pip                       19.0.3                   py37_0  
pluggy                    0.12.0                     py_0  
prometheus_client         0.6.0                    py37_0  
prompt_toolkit            2.0.9                    py37_0  
protobuf                  3.8.0            py37he6710b0_0  
psutil                    5.6.2            py37h7b6447c_0  
ptyprocess                0.6.0                    py37_0  
py                        1.8.0                    py37_0  
pyarrow                   0.12.1                   pypi_0    pypi
pycosat                   0.6.3            py37h14c3975_0  
pycparser                 2.19                     py37_0  
pygments                  2.3.1                    py37_0  
pyopenssl                 19.0.0                   py37_0  
pyparsing                 2.4.0                      py_0  
pyqt                      5.9.2            py37h05f1152_2  
pyrsistent                0.14.11          py37h7b6447c_0  
pysocks                   1.6.8                    py37_0  
pytest                    4.6.2                    py37_0  
pytest-cov                2.7.1                      py_0  
pytest-forked             1.0.2                    py37_0  
pytest-timeout            1.3.3                    py37_0  
pytest-xdist              1.28.0                     py_0  
python                    3.7.3                h0371630_0  
python-dateutil           2.8.0                    py37_0  
pytz                      2019.1                     py_0  
pyyaml                    5.1              py37h7b6447c_0  
pyzmq                     18.0.0           py37he6710b0_0  
qt                        5.9.7                h5867ecd_1  
qtconsole                 4.4.3                    py37_0  
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   py37_0  
ruamel_yaml               0.15.46          py37h14c3975_0  
scipy                     1.2.1            py37h7c811a0_0  
send2trash                1.5.0                    py37_0  
setuptools                41.0.0                   py37_0  
sip                       4.19.8           py37hf484d3e_0  
six                       1.12.0                   py37_0  
snappy                    1.1.7                hbae5bb6_3  
sqlite                    3.27.2               h7b6447c_0  
terminado                 0.8.2                    py37_0  
testpath                  0.4.2                    py37_0  
thrift-cpp                0.11.0               h02b749d_3  
tk                        8.6.8                hbc83047_0  
tornado                   6.0.2            py37h7b6447c_0  
traitlets                 4.3.2                    py37_0  
urllib3                   1.24.1                   py37_0  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
wheel                     0.33.1                   py37_0  
widgetsnbextension        3.4.2                    py37_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zeromq                    4.3.1                he6710b0_3  
zipp                      0.5.1                      py_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0
```

**Comment by kkraus14** [comment]
@wjsi I believe this is fixed in a new version of Numba, could you try updating Numba to 0.45.1 and trying again?

**Comment by wjsi** [comment]
@kkraus14 After reinstalling cudf with ``nvidia/label/cuda10.0`` channel the issue is fixed.
