### ISSUE TITLE
[BUG] Get "RMM initialization error" using Java binding "Table.readCSV" .

### ISSUE THREAD

**Issue by firestarman** [rapidsai/cudf#3215]
**Describe the bug**
Got "rmm initialization error" when using java binding "Table.readCSV" on version 0.10. 
This PR https://github.com/rapidsai/cudf/pull/3139 seems only fix the path calling from RMM java bindings, if calling from "Table", which does not depend on RMM Java, RMM is still not initialized.   

`19/10/25 13:42:58 ERROR TaskSetManager: Task 5 in stage 1.0 failed 4 times; aborting job
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 5 in stage 1.0 failed 4 times, most recent failure: Lost task 5.3 in stage 1.0 (TID 53, 10.19.183.78, executor 0): ai.rapids.cudf.CudfException: rmm_allocator::allocate(): RMM_ALLOC: cudaErrorInitializationError: initialization error
	at ai.rapids.cudf.Table.gdfReadCSV(Native Method)
	at ai.rapids.cudf.Table.readCSV(Table.java:551)
	at ai.rapids.spark.CSVPartitionReader.readToTable(GpuBatchScanExec.scala:415)
	at ai.rapids.spark.CSVPartitionReader.readBatch(GpuBatchScanExec.scala:384)
	at ai.rapids.spark.CSVPartitionReader.next(GpuBatchScanExec.scala:431)`

**Comment by jlowe** [comment]
#3139 went into branch-0.11, but this is reported against 0.10.

Does your 0.10 build contain #3140?  That change should address the relatively recent RMM change where it must be initialized before being used.

**Comment by firestarman** [comment]
> #3139 went into branch-0.11, but this is reported against 0.10.
> 
> Does your 0.10 build contain #3140? That change should address the relatively recent RMM change where it must be initialized before being used.

Yes, fix  #3140 is included. But seems it has the same issue with #3139, only fix the path calling from RMM java bindings, if calling from "Table", which does not depend on RMM Java, RMM is still not initialized.

**Comment by firestarman** [comment]
Here is a fix i can imagine and it works.  https://github.com/firestarman/cudf/commit/ed03d5aa4372670e2575537eb800cb70612b49f2

**Comment by jlowe** [comment]
I posted #3228 which should address this by tying loading native dependencies with initializing RMM.  Then we don't have to track down all the cudf classes that might need RMM initialized.
