### ISSUE TITLE
RMM_ERROR_OUT_OF_MEMORY while trying to create cudf.DataFrame

### ISSUE THREAD

**Issue by DoDzilla-ai** [rapidsai/cudf#3508]
**Describe the bug**
Getting the `rmm.rmm.RMMError: RMM_ERROR_OUT_OF_MEMORY` even with the smallest numpy array when I try to create a `cudf.DataFrame`. 

**Steps/Code to reproduce bug**
First I installed the libraries using this command (provided from ["Getting Started"](https://rapids.ai/start.html) page of rapids.
```
conda install -c rapidsai-nightly -c nvidia -c conda-forge \
    -c defaults rapids=0.11 python=3.6 cudatoolkit=10.1
```
After the installation, I tried to test it with:

```
import cudf
import numpy as np

numpy_data = np.random.rand(10, 10)
X_gpu = cudf.DataFrame({'fea%d'%i: numpy_data[:, i] for i in range(numpy_data.shape[1])})
```
**Traceback**
```Traceback (most recent call last):
  File "/home/dodzilla/.PyCharm2019.3/config/scratches/scratch.py", line 5, in <module>
    X_gpu = cudf.DataFrame({'fea%d'%i: numpy_data[:, i] for i in range(numpy_data.shape[1])})
  File "/home/dodzilla/anaconda3/envs/aiclap-backend/lib/python3.6/site-packages/cudf/core/dataframe.py", line 185, in __init__
    self.insert(i, col_name, series, forceindex=index is not None)
  File "/home/dodzilla/anaconda3/envs/aiclap-backend/lib/python3.6/site-packages/cudf/core/dataframe.py", line 1559, in insert
    value, forceindex=forceindex, name=column
  File "/home/dodzilla/anaconda3/envs/aiclap-backend/lib/python3.6/site-packages/cudf/core/dataframe.py", line 1518, in _prepare_series_for_add
    series = Series(col, name=name) if not SCALAR else col
  File "/home/dodzilla/anaconda3/envs/aiclap-backend/lib/python3.6/site-packages/cudf/core/series.py", line 124, in __init__
    data, nan_as_null=nan_as_null, dtype=dtype, name=name
  File "/home/dodzilla/anaconda3/envs/aiclap-backend/lib/python3.6/site-packages/cudf/core/column/column.py", line 1228, in as_column
    data = as_column(rmm.to_device(arbitrary), nan_as_null=nan_as_null)
  File "/home/dodzilla/anaconda3/envs/aiclap-backend/lib/python3.6/site-packages/rmm/rmm.py", line 217, in to_device
    to = device_array_like(ary, stream=stream)
  File "/home/dodzilla/anaconda3/envs/aiclap-backend/lib/python3.6/site-packages/rmm/rmm.py", line 206, in device_array_like
    return device_array(ary.shape, ary.dtype, ary.strides, stream=stream)
  File "/home/dodzilla/anaconda3/envs/aiclap-backend/lib/python3.6/site-packages/rmm/rmm.py", line 182, in device_array
    addr = librmm.rmm_alloc(datasize, stream)
  File "rmm/_lib/lib.pyx", line 192, in rmm._lib.lib.rmm_alloc
  File "rmm/_lib/lib.pyx", line 179, in rmm._lib.lib.c_alloc
  File "rmm/_lib/lib.pyx", line 44, in rmm._lib.lib.check_error
rmm.rmm.RMMError: RMM_ERROR_OUT_OF_MEMORY

Process finished with exit code 1
```

**nvidia-smi**
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   61C    P0    24W /  N/A |    741MiB /  6078MiB |      4%      Default |
+-------------------------------+----------------------+----------------------+
```

_libgcc_mutex | 0.1
arrow-cpp | 0.15.0
bokeh | 1.4.0
boost-cpp | 1.70.0
brotli | 1.0.7
bzip2 | 1.0.8
c-ares | 1.15.0
ca-certificates | 2019.11.28
cairo | 1.16.0
certifi | 2019.11.28
cfitsio | 3.470
click | 7.0
cloudpickle | 1.2.2
cudatoolkit | 10.1.243
cudf | 0.11.0a191203
cudnn | 7.6.0
cugraph | 0.11.0a1191203
cuml | 0.11.0a1191203
cupy | 6.5.0
curl | 7.65.3
cuspatial | 0.11.0a191203
cython | 0.29.14
cytoolz | 0.10.1
dask | 2.8.1
dask-core | 2.8.1
dask-cuda | 0.11.0b191203
dask-cudf | 0.11.0a191203
dask-xgboost | 0.2.0.dev28
distributed | 2.8.1
dlpack | 0.2
double-conversion | 3.1.5
expat | 2.2.5
fastavro | 0.22.7
fastrlock | 0.4
fontconfig | 2.13.1
freetype | 2.10.0
freexl | 1.0.5
fsspec | 0.6.1
gdal | 2.4.3
geos | 3.7.2
geotiff | 1.5.1
gettext | 0.19.8.1
gflags | 2.2.2
giflib | 5.1.7
glib | 2.58.3
glog | 0.4.0
grpc-cpp | 1.23.0
hdf4 | 4.2.13
hdf5 | 1.10.5
heapdict | 1.0.1
icu | 64.2
jinja2 | 2.10.3
joblib | 0.14.0
jpeg | 9c
json-c | 0.13.1
kealib | 1.4.10
krb5 | 1.16.3
libblas | 3.8.0
libcblas | 3.8.0
libcudf | 0.11.0a191203
libcugraph | 0.11.0a1191203
libcuml | 0.11.0a1191203
libcumlprims | 0.11.0a191203
libcurl | 7.65.3
libcuspatial | 0.11.0a191203
libdap4 | 3.20.4
libedit | 3.1.20181209
libevent | 2.1.10
libffi | 3.2.1
libgcc-ng | 9.1.0
libgdal | 2.4.3
libgfortran-ng | 7.3.0
libiconv | 1.15
libkml | 1.3.0
liblapack | 3.8.0
libnetcdf | 4.7.1
libnvstrings | 0.11.0a191203
libopenblas | 0.3.7
libpng | 1.6.37
libpq | 11.5
libprotobuf | 3.8.0
librmm | 0.11.0b191203
libspatialite | 4.3.0a
libssh2 | 1.8.2
libstdcxx-ng | 9.1.0
libtiff | 4.1.0
libuuid | 2.32.1
libxcb | 1.13
libxgboost | 1.0.0.SNAPSHOT
libxml2 | 2.9.10
llvmlite | 0.29.0
locket | 0.2.0
lz4-c | 1.8.3
markupsafe | 1.1.1
msgpack-python | 0.6.2
nccl | 2.4.6.1
ncurses | 6.1
numba | 0.45.1
numpy | 1.17.3
nvstrings | 0.11.0a191203
olefile | 0.46
openjpeg | 2.3.1
openssl | 1.1.1d
packaging | 19.2
pandas | 0.24.2
parquet-cpp | 1.5.1
partd | 1.0.0
pcre | 8.43
pillow | 6.2.1
pip | 19.3.1
pixman | 0.38.0
poppler | 0.67.0
poppler-data | 0.4.9
postgresql | 11.5
proj | 6.2.1
psutil | 5.6.7
pthread-stubs | 0.4
py-xgboost | 1.0.0.SNAPSHOT
pyarrow | 0.15.0
pynvml | 8.0.3
pyparsing | 2.4.5
python | 3.6.7
python-dateutil | 2.8.1
pytz | 2019.3
pyyaml | 5.2
rapids | 0.11.0
rapids-xgboost | 0.11.0
re2 | 2019.12.01
readline | 8.0
rmm | 0.11.0b191203
scikit-learn | 0.22
scipy | 1.3.2
setuptools | 42.0.2
six | 1.13.0
snappy | 1.1.7
sortedcontainers | 2.1.0
sqlite | 3.30.1
tblib | 1.4.0
thrift-cpp | 0.12.0
tk | 8.6.10
toolz | 0.10.0
tornado | 6.0.3
tzcode | 2019a
uriparser | 0.9.3
wheel | 0.33.6
xerces-c | 3.2.2
xgboost | 1.0.0.SNAPSHOT
xorg-kbproto | 1.0.7
xorg-libice | 1.0.10
xorg-libsm | 1.2.3
xorg-libx11 | 1.6.9
xorg-libxau | 1.0.9
xorg-libxdmcp | 1.1.3
xorg-libxext | 1.3.4
xorg-libxrender | 0.9.10
xorg-renderproto | 0.11.1
xorg-xextproto | 7.3.0
xorg-xproto | 7.0.31
xz | 5.2.4
yaml | 0.2.2
zict | 1.0.0
zlib | 1.2.11
zstd | 1.4.3

**Comment by DoDzilla-ai** [comment]
For some reason, it is working as I expected the day after I posted this issue. I didn't change anything. Could it be I restarted the PC? (dummy dumm dumm me)
