### ISSUE TITLE
[BUG] librmm.so is built for old CUDA, but not supported at RHEL8

### ISSUE THREAD

**Issue by kaigai** [rapidsai/cudf#3529]
**Describe the bug**
`import cudf` on RHEL8 raises the following error.
```
[kaigai@iwashi ~]$ python3
Python 3.6.8 (default, Oct  7 2019, 17:58:22)
[GCC 8.2.1 20180905 (Red Hat 8.2.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/cudf/__init__.py", line 3, in <module>
    from cudf import dataframe
  File "/usr/local/lib64/python3.6/site-packages/cudf/dataframe/__init__.py", line 1, in <module>
    from cudf.dataframe import (buffer, dataframe, series,
  File "/usr/local/lib64/python3.6/site-packages/cudf/dataframe/buffer.py", line 3, in <module>
    from librmm_cffi import librmm as rmm
  File "/usr/local/lib64/python3.6/site-packages/librmm_cffi/__init__.py", line 50, in <module>
    librmm_api = ffi.dlopen(_get_lib_name())
OSError: cannot load library '/usr/local/lib64/python3.6/site-packages/librmm.so': libcudart.so.9.2: cannot open shared object file: No such file or directory
```

It looks to me `librmm.so` (I'm not certain about its purpose) is built for CUDA-9.2, thus does not try to load newer libraries like CUDA-10.2, and so on.
RHEL8 is newly supported at CUDA-10.1, thus, installation of CUDA-9.2 is not an option.

**Steps/Code to reproduce bug**
```
# dnf install python3-pip
# pip3 install cudf

$ python3
  :
>>> import cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/cudf/__init__.py", line 3, in <module>
    from cudf import dataframe
  File "/usr/local/lib64/python3.6/site-packages/cudf/dataframe/__init__.py", line 1, in <module>
    from cudf.dataframe import (buffer, dataframe, series,
  File "/usr/local/lib64/python3.6/site-packages/cudf/dataframe/buffer.py", line 3, in <module>
    from librmm_cffi import librmm as rmm
  File "/usr/local/lib64/python3.6/site-packages/librmm_cffi/__init__.py", line 50, in <module>
    librmm_api = ffi.dlopen(_get_lib_name())
OSError: cannot load library '/usr/local/lib64/python3.6/site-packages/librmm.so': libcudart.so.9.2: cannot open shared object file: No such file or directory
```

**Environment overview (please complete the following information)**
- Environment location: Bare-metal
- Method of cuDF install: pip3 as above
- OS: CentOS 8 (kernel: 4.18.0-80.11.2.el8_0.x86_64)
- CUDA: 10.2 + Driver: 440.33.01

CUDA related packages are below:
```
[kaigai@iwashi ~]$ rpm -qa | grep cuda
cuda-driver-dev-10-2-10.2.89-1.x86_64
cuda-cuobjdump-10-2-10.2.89-1.x86_64
cuda-nvcc-10-2-10.2.89-1.x86_64
cuda-nvprof-10-2-10.2.89-1.x86_64
cuda-nsight-10-2-10.2.89-1.x86_64
cuda-10.2.89-1.x86_64
nvidia-driver-cuda-440.33.01-1.el8.x86_64
cuda-cudart-dev-10-2-10.2.89-1.x86_64
cuda-cusparse-10-2-10.2.89-1.x86_64
cuda-nvjpeg-10-2-10.2.89-1.x86_64
cuda-cupti-10-2-10.2.89-1.x86_64
cuda-nvtx-10-2-10.2.89-1.x86_64
cuda-documentation-10-2-10.2.89-1.x86_64
cuda-tools-10-2-10.2.89-1.x86_64
nvidia-driver-cuda-libs-440.33.01-1.el8.x86_64
cuda-drivers-440.33.01-1.x86_64
cuda-nvdisasm-10-2-10.2.89-1.x86_64
cuda-cufft-10-2-10.2.89-1.x86_64
cuda-curand-dev-10-2-10.2.89-1.x86_64
cuda-cusparse-dev-10-2-10.2.89-1.x86_64
cuda-npp-dev-10-2-10.2.89-1.x86_64
cuda-nvjpeg-dev-10-2-10.2.89-1.x86_64
cuda-nvrtc-dev-10-2-10.2.89-1.x86_64
cuda-libraries-10-2-10.2.89-1.x86_64
cuda-gdb-10-2-10.2.89-1.x86_64
cuda-memcheck-10-2-10.2.89-1.x86_64
cuda-sanitizer-api-10-2-10.2.89-1.x86_64
cuda-toolkit-10-2-10.2.89-1.x86_64
cuda-license-10-2-10.2.89-1.x86_64
cuda-cufft-dev-10-2-10.2.89-1.x86_64
cuda-cusolver-10-2-10.2.89-1.x86_64
cuda-misc-headers-10-2-10.2.89-1.x86_64
cuda-nvgraph-10-2-10.2.89-1.x86_64
cuda-nvml-dev-10-2-10.2.89-1.x86_64
cuda-runtime-10-2-10.2.89-1.x86_64
cuda-nvprune-10-2-10.2.89-1.x86_64
cuda-command-line-tools-10-2-10.2.89-1.x86_64
cuda-nsight-compute-10-2-10.2.89-1.x86_64
cuda-10-2-10.2.89-1.x86_64
cuda-cudart-10-2-10.2.89-1.x86_64
cuda-cusolver-dev-10-2-10.2.89-1.x86_64
cuda-nvgraph-dev-10-2-10.2.89-1.x86_64
cuda-demo-suite-10-2-10.2.89-1.x86_64
cuda-compiler-10-2-10.2.89-1.x86_64
cuda-samples-10-2-10.2.89-1.x86_64
cuda-visual-tools-10-2-10.2.89-1.x86_64
cuda-curand-10-2-10.2.89-1.x86_64
cuda-npp-10-2-10.2.89-1.x86_64
cuda-nvrtc-10-2-10.2.89-1.x86_64
cuda-libraries-dev-10-2-10.2.89-1.x86_64
cuda-nsight-systems-10-2-10.2.89-1.x86_64
cuda-nvvp-10-2-10.2.89-1.x86_64
```

Best regards,

**Comment by kkraus14** [comment]
@kaigai installing cudf from pip is no longer supported, we also do not yet support CUDA 10.2. Please use conda to install or install from source and report back if you continue to have issues.
