### ISSUE TITLE
[BUG] groupby_agg fails on latest dask_cudf

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#3717]
**Describe the bug**
 groupby_agg fails on latest dask_cudf

**Steps/Code to reproduce bug**

```python
import dask_cudf
import cudf

n = 1
df = cudf.DataFrame({'a':[0,1,0,1]*n,'b':[0,0,2,1]*n,'c':[0,0,0,0]*n})
df = dask_cudf.from_cudf(df,npartitions=2)

group_counts = df.groupby(['a','b']).agg({'c':'count'})
group_counts.compute()
```

Stack Trace
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    168     try:
--> 169         yield
    170     except Exception as e:

/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   4839     with raise_on_meta_error(funcname(func), udf=kwargs.pop("udf", False)):
-> 4840         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   4841 

/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/dask/dataframe/groupby.py in _agg_finalize(df, aggregate_funcs, finalize_funcs, level)
    901     # finish the final aggregation level
--> 902     df = _groupby_apply_funcs(df, funcs=aggregate_funcs, level=level)
    903 

/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/dask/dataframe/groupby.py in _groupby_apply_funcs(df, *index, **kwargs)
    874     funcs = kwargs.pop("funcs")
--> 875     grouped = _groupby_raise_unaligned(df, **kwargs)
    876 

/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/dask/dataframe/groupby.py in _groupby_raise_unaligned(df, **kwargs)
    161         kwargs.update(by=list(by))
--> 162     return df.groupby(**kwargs)
    163 

/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/cudf/core/dataframe.py in groupby(self, by, sort, as_index, method, level, group_keys, dropna)
   2717                 level=level,
-> 2718                 dropna=dropna,
   2719             )

/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/cudf/core/groupby/groupby.py in __init__(self, df, by, as_index, level, sort, method, dropna)
    124             sort=sort,
--> 125             dropna=dropna,
    126         )

/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/cudf/core/groupby/groupby.py in __init__(self, obj, by, level, as_index, sort, dropna)
    232                 raise TypeError("Cannot use both 'by' and 'level'")
--> 233             by = self.get_by_from_level(level)
    234         self.level = level

/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/cudf/core/groupby/groupby.py in get_by_from_level(self, level)
    310             if len(level) > 1 or level[0] != 0:
--> 311                 raise ValueError("level != 0 only valid with MultiIndex")
    312             by_list.append(cudf.Series(self.obj.index))

ValueError: level != 0 only valid with MultiIndex

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-10-edf25d0a417b> in <module>
      3 df = dask_cudf.from_cudf(df,npartitions=2)
      4 
----> 5 group_counts = df.groupby(['a','b']).agg({'c':'count'})
      6 group_counts.compute()

/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/dask/dataframe/groupby.py in agg(self, arg, split_every, split_out)
   1740     @derived_from(pd.core.groupby.DataFrameGroupBy)
   1741     def agg(self, arg, split_every=None, split_out=1):
-> 1742         return self.aggregate(arg, split_every=split_every, split_out=split_out)
   1743 
   1744 

/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/dask/dataframe/groupby.py in aggregate(self, arg, split_every, split_out)
   1735 
   1736         return super(DataFrameGroupBy, self).aggregate(
-> 1737             arg, split_every=split_every, split_out=split_out
   1738         )
   1739 

/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/dask/dataframe/groupby.py in aggregate(self, arg, split_every, split_out)
   1520             split_every=split_every,
   1521             split_out=split_out,
-> 1522             split_out_setup=split_out_on_index,
   1523         )
   1524 

/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/dask/dataframe/core.py in apply_concat_apply(args, chunk, aggregate, combine, meta, token, chunk_kwargs, aggregate_kwargs, combine_kwargs, split_every, split_out, split_out_setup, split_out_setup_kwargs, **kwargs)
   4794     if meta is no_default:
   4795         meta_chunk = _emulate(chunk, *args, udf=True, **chunk_kwargs)
-> 4796         meta = _emulate(aggregate, _concat([meta_chunk]), udf=True, **aggregate_kwargs)
   4797     meta = make_meta(
   4798         meta, index=(getattr(make_meta(dfs[0]), "index", None) if dfs else None)

/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   4838     """
   4839     with raise_on_meta_error(funcname(func), udf=kwargs.pop("udf", False)):
-> 4840         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   4841 
   4842 

/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    188         )
    189         msg = msg.format(" in `{0}`".format(funcname) if funcname else "", repr(e), tb)
--> 190         raise ValueError(msg)
    191 
    192 

ValueError: Metadata inference failed in `_agg_finalize`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
ValueError('level != 0 only valid with MultiIndex')

Traceback:
---------
  File "/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/dask/dataframe/utils.py", line 169, in raise_on_meta_error
    yield
  File "/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/dask/dataframe/core.py", line 4840, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/dask/dataframe/groupby.py", line 902, in _agg_finalize
    df = _groupby_apply_funcs(df, funcs=aggregate_funcs, level=level)
  File "/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/dask/dataframe/groupby.py", line 875, in _groupby_apply_funcs
    grouped = _groupby_raise_unaligned(df, **kwargs)
  File "/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/dask/dataframe/groupby.py", line 162, in _groupby_raise_unaligned
    return df.groupby(**kwargs)
  File "/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/cudf/core/dataframe.py", line 2718, in groupby
    dropna=dropna,
  File "/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/cudf/core/groupby/groupby.py", line 125, in __init__
    dropna=dropna,
  File "/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/cudf/core/groupby/groupby.py", line 233, in __init__
    by = self.get_by_from_level(level)
  File "/raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan/lib/python3.7/site-packages/cudf/core/groupby/groupby.py", line 311, in get_by_from_level
    raise ValueError("level != 0 only valid with MultiIndex")
```

**Expected behavior**

**Environment overview (please complete the following information)**
 - Method of cuDF install: [conda]

```
# packages in environment at /raid/vjawa/conda_install/conda_env/envs/cudf_12_8_jan:
cudf                      0.12.0b200108          py37_839    rapidsai-nightly
dask-cudf                 0.12.0b200108          py37_839    rapidsai-nightly
libcudf                   0.12.0b200108      cuda10.1_839    rapidsai-nightly
```

**Additional context**
It works at `cudf` level.

**Comment by VibhuJawa** [comment]
On ashwins `https://github.com/rapidsai/cudf/pull/3741` pr below is still failing on `distributed`  but works with `standalone` dask. 

The file read in the code is attached [here](https://gist.github.com/VibhuJawa/bad5a2694dd73392a547b84fbc488800). 

```python
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
import dask_cudf
import cudf
cluster = LocalCUDACluster(CUDA_VISIBLE_DEVICES="0,1,2")
client = Client(cluster)


pr_df_r = dask_cudf.read_csv('test_file_cudf.csv').repartition(npartitions=10)
pr_df_g = pr_df_r.groupby(['pr_item_sk']).agg({'pr_review_rating': ['count', 'mean']}).reset_index()
pr_df_g.compute()
```



Stack Trace:

```
/raid/vjawa/conda/conda_installation/envs/cudf_dev_ashwin/lib/python3.7/site-packages/cudf/core/dataframe.py:380: UserWarning: Columns may not be added to a DataFrame using a new attribute name. A new attribute will be created: 'multi_cols'
  UserWarning,
/raid/vjawa/conda/conda_installation/envs/cudf_dev_ashwin/lib/python3.7/site-packages/cudf/core/dataframe.py:380: UserWarning: Columns may not be added to a DataFrame using a new attribute name. A new attribute will be created: 'multi_cols'
  UserWarning,
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-6e4eb627f84e> in <module>
      9 pr_df_r = dask_cudf.read_csv('test_file_cudf.csv').repartition(npartitions=10)
     10 pr_df_g = pr_df_r.groupby(['pr_item_sk']).agg({'pr_review_rating': ['count', 'mean']}).reset_index()
---> 11 pr_df_g.compute()

/raid/vjawa/conda/conda_installation/envs/cudf_dev_ashwin/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    163         dask.base.compute
    164         """
--> 165         (result,) = compute(self, traverse=False, **kwargs)
    166         return result
    167 

/raid/vjawa/conda/conda_installation/envs/cudf_dev_ashwin/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    434     keys = [x.__dask_keys__() for x in collections]
    435     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 436     results = schedule(dsk, keys, **kwargs)
    437     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    438 

/raid/vjawa/conda/conda_installation/envs/cudf_dev_ashwin/lib/python3.7/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2574                     should_rejoin = False
   2575             try:
-> 2576                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2577             finally:
   2578                 for f in futures.values():

/raid/vjawa/conda/conda_installation/envs/cudf_dev_ashwin/lib/python3.7/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1872                 direct=direct,
   1873                 local_worker=local_worker,
-> 1874                 asynchronous=asynchronous,
   1875             )
   1876 

/raid/vjawa/conda/conda_installation/envs/cudf_dev_ashwin/lib/python3.7/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    767         else:
    768             return sync(
--> 769                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    770             )
    771 

/raid/vjawa/conda/conda_installation/envs/cudf_dev_ashwin/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    333     if error[0]:
    334         typ, exc, tb = error[0]
--> 335         raise exc.with_traceback(tb)
    336     else:
    337         return result[0]

/raid/vjawa/conda/conda_installation/envs/cudf_dev_ashwin/lib/python3.7/site-packages/distributed/utils.py in f()
    317             if callback_timeout is not None:
    318                 future = gen.with_timeout(timedelta(seconds=callback_timeout), future)
--> 319             result[0] = yield future
    320         except Exception as exc:
    321             error[0] = sys.exc_info()

/raid/vjawa/conda/conda_installation/envs/cudf_dev_ashwin/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

/raid/vjawa/conda/conda_installation/envs/cudf_dev_ashwin/lib/python3.7/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1728                             exc = CancelledError(key)
   1729                         else:
-> 1730                             raise exception.with_traceback(traceback)
   1731                         raise exc
   1732                     if errors == "skip":

/raid/vjawa/conda/conda_installation/envs/cudf_dev_ashwin/lib/python3.7/site-packages/dask/optimization.py in __call__()
    980         if not len(args) == len(self.inkeys):
    981             raise ValueError("Expected %d args, got %d" % (len(self.inkeys), len(args)))
--> 982         return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
    983 
    984     def __reduce__(self):

/raid/vjawa/conda/conda_installation/envs/cudf_dev_ashwin/lib/python3.7/site-packages/dask/core.py in get()
    147     for key in toposort(dsk):
    148         task = dsk[key]
--> 149         result = _execute_task(task, cache)
    150         cache[key] = result
    151     result = _execute_task(out, cache)

/raid/vjawa/conda/conda_installation/envs/cudf_dev_ashwin/lib/python3.7/site-packages/dask/core.py in _execute_task()
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

/raid/vjawa/conda/conda_installation/envs/cudf_dev_ashwin/lib/python3.7/site-packages/dask/utils.py in apply()
     27 def apply(func, args, kwargs=None):
     28     if kwargs:
---> 29         return func(*args, **kwargs)
     30     else:
     31         return func(*args)

/raid/vjawa/conda/conda_installation/envs/cudf_dev_ashwin/lib/python3.7/site-packages/dask/dataframe/core.py in apply_and_enforce()
   4979             return meta
   4980         if is_dataframe_like(df):
-> 4981             check_matching_columns(meta, df)
   4982             c = meta.columns
   4983         else:

/raid/vjawa/conda/conda_installation/envs/cudf_dev_ashwin/lib/python3.7/site-packages/dask/dataframe/utils.py in check_matching_columns()
    676             " the columns in the provided metadata\n"
    677             "  Extra:   %s\n"
--> 678             "  Missing: %s" % (extra, missing)
    679         )
    680 

ValueError: The columns in the computed data do not match the columns in the provided metadata
  Extra:   ['index']
  Missing: ['pr_item_sk']
```
