### ISSUE TITLE
[FEA] groupby could support median

### ISSUE THREAD

**Issue by jangorecki** [rapidsai/cudf#3736]
median was implemented in #2905 but it doesn't yet work for groupby.
I am on 0.11.0.
```py
df = cu.DataFrame({'a': [1.,3,4,1.], 'b': [4.,5,6,-10], 'c': [6., 7., 5., 10.]})
df.c.median()
#6.5
df.groupby('a').c.median()
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#AttributeError: 'SeriesGroupBy' object has no attribute 'median'
df.groupby(['a','b']).agg({'c':'median'})
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "/home/jan/anaconda3/envs/cudf/lib/python3.6/site-packages/cudf/core/groupby/groupby.py", line 46, in agg
#    return self._apply_aggregation(func)
#  File "/home/jan/anaconda3/envs/cudf/lib/python3.6/site-packages/cudf/core/groupby/groupby.py", line 132, in _apply_aggregation
#    result = self._groupby.compute_result(agg)
#  File "/home/jan/anaconda3/envs/cudf/lib/python3.6/site-packages/cudf/core/groupby/groupby.py", line 370, in compute_result
#    self.dropna,
#  File "/home/jan/anaconda3/envs/cudf/lib/python3.6/site-packages/cudf/core/groupby/groupby.py", line 551, in _groupby_engine
#    key_columns, value_columns, aggs, dropna=dropna
#  File "cudf/_lib/groupby.pyx", line 81, in cudf._lib.groupby.groupby
#KeyError: 'median'
```

**Comment by devavret** [comment]
Removing the libcudf label because median was added in #3597 but it has existed in legacy groupby since #2605

**Comment by jangorecki** [comment]
@kkraus14 Thank you for addressing this issue. When looking at this PR I don't see any info added to changelog about adding support for median function, maybe worth to mention that there.

**Comment by kkraus14** [comment]
@jangorecki it was added in a large groupby refactor in #4346 that closed a bunch of groupby issues.

**Comment by jangorecki** [comment]
@kkraus14 Yes, I know, I've seen it, and I am referring to exactly this PR that there could be changelog entry mentioning `median` keyword, so anyone who reads changelog may got that info from there, without having to search github issues.
