### ISSUE TITLE
[BUG] Unable to assign values to empty Dataframe

### ISSUE THREAD

**Issue by bsuryadevara** [rapidsai/cudf#3779]
**Describe the bug**
Creating empty Dataframe with columns set and assigning values to columns is throwing an error.

**Steps/Code to reproduce bug**
```
>>> import cudf
>>> columns = ["A", "B"]
>>> gdf = cudf.DataFrame({col: [""] for col in columns})
>>> gdf = gdf[:0]
>>> gdf["A"] = ["foo", "bar"]
>>> gdf["B"] = ["foo", "bar"]
>>> gdf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/dataframe.py", line 748, in __repr__
    output = self.get_renderable_dataframe()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/dataframe.py", line 712, in get_renderable_dataframe
    output = self.copy(deep=False)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/dataframe.py", line 1402, in copy
    out.index = index
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/dataframe.py", line 327, in __setattr__
    object.__setattr__(self, key, col)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/dataframe.py", line 1200, in index
    raise ValueError(msg)
ValueError: Length mismatch: Expected axis has 2 elements, new values have 0 elements
>>> gdf.shape
(0, 2)
```

**Expected behavior**
```
>>> import cudf
>>> columns = ["A", "B"]
>>> gdf = cudf.DataFrame({col: [""] for col in columns})
>>> gdf = gdf[:0]
>>> gdf["A"] = ["foo", "bar"]
>>> gdf["B"] = ["foo", "bar"]
>>> gdf
     A    B
0  foo  foo
1  bar  bar
```

**Environment details**
```
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     Not inside a git repository
     
     ***OS Information***
     DGX_NAME="DGX Server"
     DGX_PRETTY_NAME="NVIDIA DGX Server"
     DGX_SWBUILD_DATE="2019-04-24"
     DGX_SWBUILD_VERSION="4.1.0"
     DGX_COMMIT_ID="2c52306"
     DGX_PLATFORM="DGX Server for DGX-1"
     DGX_SERIAL_NUMBER="QTFCOU6430065-R1"
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
     NAME="Ubuntu"
     VERSION="18.04.3 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.3 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux dgx03 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Tue Jan 14 07:28:14 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla V100-SXM2...  On   | 00000000:85:00.0 Off |                    0 |
     | N/A   33C    P0    56W / 300W |   1125MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              80
     On-line CPU(s) list: 0-79
     Thread(s) per core:  2
     Core(s) per socket:  20
     Socket(s):           2
     NUMA node(s):        2
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               79
     Model name:          Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
     Stepping:            1
     CPU MHz:             2247.685
     CPU max MHz:         3600.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            4390.14
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            256K
     L3 cache:            51200K
     NUMA node0 CPU(s):   0-19,40-59
     NUMA node1 CPU(s):   20-39,60-79
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts flush_l1d
     
     ***CMake***
     /opt/conda/envs/rapids/bin/cmake
     cmake version 3.14.5
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2018 NVIDIA Corporation
     Built on Sat_Aug_25_21:08:01_CDT_2018
     Cuda compilation tools, release 10.0, V10.0.130
     
     ***Python***
     /opt/conda/envs/rapids/bin/python
     Python 3.7.6
     
     ***Environment Variables***
     PATH                            : /opt/conda/envs/rapids/bin:/opt/conda/condabin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/conda/bin:/conda/bin:/conda/bin
     LD_LIBRARY_PATH                 : /opt/conda/envs/rapids/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/lib
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /opt/conda/envs/rapids
     PYTHON_PATH                     :
     
     ***conda packages***
     /opt/conda/condabin/conda
     # packages in environment at /opt/conda/envs/rapids:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main    conda-forge
     _tflow_select             2.1.0                       gpu
     absl-py                   0.9.0                    py37_0    conda-forge
     aiohttp                   3.6.2            py37h516909a_0    conda-forge
     alabaster                 0.7.12                     py_0    conda-forge
     appdirs                   1.4.3                      py_1    conda-forge
     arrow-cpp                 0.15.0           py37h090bef1_2    conda-forge
     astor                     0.7.1                      py_0    conda-forge
     async-timeout             3.0.1                   py_1000    conda-forge
     attrs                     19.3.0                     py_0    conda-forge
     babel                     2.8.0                      py_0    conda-forge
     backcall                  0.1.0                      py_0    conda-forge
     black                     19.10b0                  py37_0    conda-forge
     blas                      2.14                   openblas    conda-forge
     bleach                    3.1.0                      py_0    conda-forge
     bokeh                     1.4.0                    py37_0    conda-forge
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     brotli                    1.0.7             he1b5a44_1000    conda-forge
     bzip2                     1.0.8                h516909a_2    conda-forge
     c-ares                    1.15.0            h516909a_1001    conda-forge
     ca-certificates           2019.11.28           hecc5488_0    conda-forge
     cairo                     1.16.0            hfb77d84_1002    conda-forge
     certifi                   2019.11.28               py37_0    conda-forge
     cffi                      1.13.2           py37h8022711_0    conda-forge
     cfitsio                   3.470                hb60a0a2_2    conda-forge
     chardet                   3.0.4                 py37_1003    conda-forge
     click                     7.0                      pypi_0    pypi
     click-plugins             1.1.1                      py_0    conda-forge
     cligj                     0.5.0                      py_0    conda-forge
     cloudpickle               1.2.2                      py_1    conda-forge
     clx                       0.12.0                   pypi_0    pypi
     cmake                     3.14.5               hf94ab9c_0    conda-forge
     cmake_setuptools          0.1.3                      py_0    rapidsai-nightly
     colorcet                  2.0.1                      py_0    conda-forge
     commonmark                0.9.1                      py_0    conda-forge
     confluent-kafka           1.3.0                    pypi_0    pypi
     cryptography              2.8              py37h72c5cf5_1    conda-forge
     cudatashader              0.1                       dev_0    <develop>
     cudatoolkit               10.0.130                      0    nvidia
     cudf                      0.12.0b0+589.g61b9f2f2e          pypi_0    pypi
     cudnn                     7.6.0                cuda10.0_0    nvidia
     cugraph                   0.12.0a0+182.g14384d5.dirty          pypi_0    pypi
     cuml                      0.12.0a0+372.g666fcf8f          pypi_0    pypi
     cupti                     10.0.130                      0
     cupy                      6.6.0            py37h809cb0f_1    conda-forge
     curl                      7.65.3               hf8cf82a_0    conda-forge
     cuspatial                 0.12.0a0+8.g4c4c327          pypi_0    pypi
     cuxfilter                 0.12.0a200108           py37_45    rapidsai-nightly
     cycler                    0.10.0                     py_2    conda-forge
     cyrus-sasl                2.1.27               he38ecfd_0    conda-forge
     cython                    0.29.14          py37he1b5a44_0    conda-forge
     cytoolz                   0.10.1           py37h516909a_0    conda-forge
     dask                      2.9.1                      py_0    conda-forge
     dask-core                 2.9.1                      py_0    conda-forge
     dask-cuda                 0.12.0a200107           py37_45    rapidsai-nightly
     dask-cudf                 0.12.0b0+589.g61b9f2f2e          pypi_0    pypi
     dask-glm                  0.2.0                      py_1    conda-forge
     dask-labextension         1.1.0                      py_0    conda-forge
     dask-ml                   1.1.1                      py_0    conda-forge
     dask-xgboost              0.1.5                    pypi_0    pypi
     datashader                0.9.0                      py_0    conda-forge
     datashape                 0.5.4                      py_1    conda-forge
     dbus                      1.13.6               he372182_0    conda-forge
     decorator                 4.4.1                      py_0    conda-forge
     defusedxml                0.6.0                      py_0    conda-forge
     distributed               2.9.1                      py_0    conda-forge
     dlpack                    0.2                  he1b5a44_1    conda-forge
     docutils                  0.15.2                   py37_0    conda-forge
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     doxygen                   1.8.16               hd1b7508_1    conda-forge
     entrypoints               0.3                   py37_1000    conda-forge
     expat                     2.2.5             he1b5a44_1004    conda-forge
     fastavro                  0.22.9           py37h516909a_0    conda-forge
     fastrlock                 0.4             py37he1b5a44_1000    conda-forge
     fiona                     1.8.9.post2      py37hdff7cfa_0    conda-forge
     flake8                    3.7.9                    py37_0    conda-forge
     flatbuffers               1.11.0               he1b5a44_0    conda-forge
     fontconfig                2.13.1            h86ecdb6_1001    conda-forge
     freetype                  2.10.0               he983fc9_1    conda-forge
     freexl                    1.0.5             h14c3975_1002    conda-forge
     fribidi                   1.0.5             h516909a_1002    conda-forge
     fsspec                    0.6.2                      py_0    conda-forge
     future                    0.18.2                   py37_0    conda-forge
     gast                      0.2.2                      py_0    conda-forge
     gdal                      2.4.3            py37h5f563d9_9    conda-forge
     geopandas                 0.6.2                      py_0    conda-forge
     geos                      3.7.2                he1b5a44_2    conda-forge
     geotiff                   1.5.1                hbd99317_7    conda-forge
     gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
     gflags                    2.2.2             he1b5a44_1002    conda-forge
     giflib                    5.1.7                h516909a_1    conda-forge
     glib                      2.58.3          py37h6f030ca_1002    conda-forge
     glog                      0.4.0                he1b5a44_1    conda-forge
     gmp                       6.1.2             hf484d3e_1000    conda-forge
     google-pasta              0.1.8                      py_0    conda-forge
     graphite2                 1.3.13            hf484d3e_1000    conda-forge
     graphviz                  2.42.3               h0511662_0    conda-forge
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     grpcio                    1.23.0           py37he9ae1f9_0    conda-forge
     gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
     gstreamer                 1.14.5               h36ae1b5_0    conda-forge
     h5py                      2.10.0          nompi_py37h513d04c_101    conda-forge
     harfbuzz                  2.4.0                h9f30f68_3    conda-forge
     hdf4                      4.2.13            hf30be14_1003    conda-forge
     hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     hypothesis                5.1.0                      py_0    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     idna                      2.8                   py37_1000    conda-forge
     imageio                   2.6.1                    py37_0    conda-forge
     imagesize                 1.2.0                      py_0    conda-forge
     importlib_metadata        1.3.0                    py37_0    conda-forge
     ipykernel                 5.1.3            py37h5ca1d4c_0    conda-forge
     ipython                   7.3.0            py37h24bf2e0_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     jedi                      0.15.2                   py37_0    conda-forge
     jinja2                    2.10.3                     py_0    conda-forge
     joblib                    0.14.1                     py_0    conda-forge
     jpeg                      9c                h14c3975_1001    conda-forge
     json-c                    0.13.1            h14c3975_1001    conda-forge
     json5                     0.8.5                      py_0    conda-forge
     jsonschema                3.2.0                    py37_0    conda-forge
     jupyter-server-proxy      1.2.0                      py_0    conda-forge
     jupyter_client            5.3.3                    py37_1    conda-forge
     jupyter_core              4.6.1                    py37_0    conda-forge
     jupyterlab                1.2.4                      py_0    conda-forge
     jupyterlab-nvdashboard    0.1.11                   pypi_0    pypi
     jupyterlab_server         1.0.6                      py_0    conda-forge
     kealib                    1.4.10            h58c409b_1005    conda-forge
     keras-applications        1.0.8                      py_1    conda-forge
     keras-preprocessing       1.1.0                      py_0    conda-forge
     kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
     krb5                      1.16.4               h2fd8d38_0    conda-forge
     lapack                    3.6.1                ha44fe06_2    conda-forge
     ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
     libblas                   3.8.0               14_openblas    conda-forge
     libcblas                  3.8.0               14_openblas    conda-forge
     libclang                  8.0.0                h6bb024c_0    rapidsai
     libcudf                   0.12.0b200109     cuda10.0_1016    rapidsai-nightly
     libcumlprims              0.12.0a200107        cuda10.0_0    rapidsai-nightly
     libcurl                   7.65.3               hda55be3_0    conda-forge
     libcypher-parser          0.6.2                         1    rapidsai
     libdap4                   3.20.4               hd3bb157_0    conda-forge
     libedit                   3.1.20170329      hf8c457e_1001    conda-forge
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1             he1b5a44_1006    conda-forge
     libgcc-ng                 7.3.0                hdf63c60_2    conda-forge
     libgcrypt                 1.8.4             hf484d3e_1000    conda-forge
     libgdal                   2.4.3                h2f07a13_9    conda-forge
     libgfortran               3.0.0                         1    conda-forge
     libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
     libgpg-error              1.36                 he1b5a44_0    conda-forge
     libgsasl                  1.8.0             h19a2143_1004    conda-forge
     libiconv                  1.15              h516909a_1005    conda-forge
     libkml                    1.3.0             h4fcabce_1010    conda-forge
     liblapack                 3.8.0               14_openblas    conda-forge
     liblapacke                3.8.0               14_openblas    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libnetcdf                 4.7.1           nompi_h94020b1_102    conda-forge
     libntlm                   1.4               h14c3975_1002    conda-forge
     libnvstrings              0.12.0b200109     cuda10.0_1016    rapidsai-nightly
     libopenblas               0.3.7                h5ec1e0e_6    conda-forge
     libpng                    1.6.37               hed695b0_0    conda-forge
     libpq                     11.5                 hd9ab2ff_2    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librdkafka                1.2.2                hb2b7465_0    conda-forge
     librmm                    0.12.0a200109      cuda10.0_155    rapidsai-nightly
     libsodium                 1.0.17               h516909a_0    conda-forge
     libspatialindex           1.9.3                he1b5a44_1    conda-forge
     libspatialite             4.3.0a            h4f6d029_1032    conda-forge
     libssh2                   1.8.2                h22169c7_2    conda-forge
     libstdcxx-ng              7.3.0                hdf63c60_2    conda-forge
     libtiff                   4.1.0                hfc65ed5_0    conda-forge
     libtool                   2.4.6             h14c3975_1002    conda-forge
     libuuid                   2.32.1            h14c3975_1000    conda-forge
     libuv                     1.33.1               h516909a_0    conda-forge
     libxcb                    1.13              h14c3975_1002    conda-forge
     libxml2                   2.9.10               hee79883_0    conda-forge
     llvmlite                  0.30.0           py37h8b12597_1    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     make                      4.2.1             h14c3975_2004    conda-forge
     markdown                  3.0.1                    pypi_0    pypi
     markupsafe                1.1.1            py37h516909a_0    conda-forge
     matplotlib                3.1.2                    py37_1    conda-forge
     matplotlib-base           3.1.2            py37h250f245_1    conda-forge
     mccabe                    0.6.1                      py_1    conda-forge
     mistune                   0.8.4           py37h516909a_1000    conda-forge
     mockito                   1.2.0                    pypi_0    pypi
     more-itertools            8.0.2                      py_0    conda-forge
     msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
     multidict                 4.7.3            py37h516909a_0    conda-forge
     multipledispatch          0.6.0                      py_0    conda-forge
     munch                     2.5.0                      py_0    conda-forge
     mypy_extensions           0.4.3                    py37_0    conda-forge
     nbconvert                 5.6.1                    py37_0    conda-forge
     nbformat                  4.4.0                      py_1    conda-forge
     nbsphinx                  0.5.0                      py_0    conda-forge
     nccl                      2.4.6.1              cuda10.0_0    nvidia
     ncurses                   6.1               hf484d3e_1002    conda-forge
     networkx                  2.4                        py_0    conda-forge
     nodejs                    13.0.0               h10a4023_1    conda-forge
     notebook                  6.0.1                    py37_0    conda-forge
     numba                     0.46.0           py37hb3f55d8_1    conda-forge
     numpy                     1.17.3           py37h95a1406_0    conda-forge
     numpydoc                  0.9.2                      py_0    conda-forge
     nvstrings                 0.12.0b200109         py37_1016    rapidsai-nightly
     nvstrings-cuda100         0.0.0.dev0               pypi_0    pypi
     olefile                   0.46                       py_0    conda-forge
     openblas                  0.3.7                he1df0ab_6    conda-forge
     openjpeg                  2.3.1                h981e76c_3    conda-forge
     openssl                   1.1.1d               h516909a_0    conda-forge
     opt_einsum                3.1.0                      py_0    conda-forge
     packaging                 19.2                       py_0    conda-forge
     pandas                    0.24.2           py37hb3f55d8_1    conda-forge
     pandoc                    1.19.2                        0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     panel                     0.6.4                         0    conda-forge
     pango                     1.42.4               ha030887_1    conda-forge
     param                     1.9.2                      py_0    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.5.2                      py_0    conda-forge
     partd                     1.1.0                      py_0    conda-forge
     pathspec                  0.7.0                      py_0    conda-forge
     patsy                     0.5.1                      py_0    conda-forge
     pcre                      8.43                 he1b5a44_0    conda-forge
     pexpect                   4.7.0                    py37_0    conda-forge
     pickleshare               0.7.5                 py37_1000    conda-forge
     pillow                    6.2.1            py37hd70f55b_1    conda-forge
     pip                       19.3.1                   py37_0    conda-forge
     pixman                    0.38.0            h516909a_1003    conda-forge
     pluggy                    0.13.0                   py37_0    conda-forge
     poppler                   0.67.0               h14e79db_8    conda-forge
     poppler-data              0.4.9                         1    conda-forge
     postgresql                11.5                 hc63931a_2    conda-forge
     proj                      6.2.1                hc80f0dc_0    conda-forge
     prometheus_client         0.7.1                      py_0    conda-forge
     prompt-toolkit            2.0.10                   pypi_0    pypi
     protobuf                  3.8.0            py37he1b5a44_2    conda-forge
     psutil                    5.6.7            py37h516909a_0    conda-forge
     pthread-stubs             0.4               h14c3975_1001    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     py                        1.8.1                      py_0    conda-forge
     pyarrow                   0.15.0           py37h8b68381_1    conda-forge
     pycodestyle               2.5.0                      py_0    conda-forge
     pycparser                 2.19                     py37_1    conda-forge
     pyct                      0.4.6                      py_0    conda-forge
     pyct-core                 0.4.6                      py_0    conda-forge
     pyee                      6.0.0                      py_0    conda-forge
     pyflakes                  2.1.1                      py_0    conda-forge
     pygments                  2.5.2                      py_0    conda-forge
     pynvml                    8.0.3                      py_0    conda-forge
     pyopenssl                 19.1.0                   py37_0    conda-forge
     pyparsing                 2.4.6                      py_0    conda-forge
     pyppeteer                 0.0.25                     py_1    conda-forge
     pyproj                    2.4.2.post1      py37h12732c1_0    conda-forge
     pyqt                      5.9.2            py37hcca6a23_4    conda-forge
     pyrsistent                0.15.6           py37h516909a_0    conda-forge
     pysocks                   1.7.1                    py37_0    conda-forge
     pytest                    5.3.2                    py37_0    conda-forge
     python                    3.7.6                h357f687_1    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     python-whois              0.7.2                    pypi_0    pypi
     pytz                      2019.3                     py_0    conda-forge
     pyviz_comms               0.7.2                      py_0    conda-forge
     pywavelets                1.1.1            py37hc1659b7_0    conda-forge
     pyyaml                    5.2              py37h516909a_0    conda-forge
     pyzmq                     18.1.1           py37h1768529_0    conda-forge
     qt                        5.9.7                h0c104cb_3    conda-forge
     rapidjson                 1.1.0             he1b5a44_1002    conda-forge
     re2                       2020.01.01           he1b5a44_0    conda-forge
     readline                  8.0                  hf8c457e_0    conda-forge
     recommonmark              0.6.0                      py_0    conda-forge
     regex                     2019.12.20       py37h516909a_0    conda-forge
     requests                  2.22.0                   py37_1    conda-forge
     rhash                     1.3.6             h14c3975_1001    conda-forge
     rmm                       0.12.0a0+113.g15fafa2          pypi_0    pypi
     rtree                     0.9.3            py37h7b0cdae_0    conda-forge
     scikit-image              0.16.2           py37hb3f55d8_0    conda-forge
     scikit-learn              0.22             py37hcdab131_1    conda-forge
     scipy                     1.4.1            py37h921218d_0    conda-forge
     seaborn                   0.9.0                      py_2    conda-forge
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                44.0.0                   py37_0    conda-forge
     shapely                   1.6.4           py37hec07ddf_1006    conda-forge
     simpervisor               0.3                        py_1    conda-forge
     sip                       4.19.8          py37hf484d3e_1000    conda-forge
     six                       1.13.0                   py37_0    conda-forge
     snappy                    1.1.7             he1b5a44_1003    conda-forge
     snowballstemmer           2.0.0                      py_0    conda-forge
     sortedcontainers          2.1.0                      py_0    conda-forge
     sphinx                    2.3.1                      py_0    conda-forge
     sphinx-markdown-tables    0.0.10                   pypi_0    pypi
     sphinx_rtd_theme          0.4.3                      py_0    conda-forge
     sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
     sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
     sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
     sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
     sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
     sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
     sphinxcontrib-websupport  1.1.2                      py_0    conda-forge
     sqlite                    3.30.1               hcee41ef_0    conda-forge
     statsmodels               0.10.2           py37hc1659b7_0    conda-forge
     tblib                     1.6.0                      py_0    conda-forge
     tensorboard               2.0.0              pyhb38c66f_1
     tensorflow                2.0.0           gpu_py37h768510d_0
     tensorflow-base           2.0.0           gpu_py37h0ec5d1f_0
     tensorflow-estimator      2.0.0              pyh2649769_0
     termcolor                 1.1.0                      py_2    conda-forge
     terminado                 0.8.3                    py37_0    conda-forge
     testpath                  0.4.4                      py_0    conda-forge
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.10               hed695b0_0    conda-forge
     toml                      0.10.0                     py_0    conda-forge
     toolz                     0.10.0                     py_0    conda-forge
     torch                     1.3.1                    pypi_0    pypi
     tornado                   6.0.3            py37h516909a_0    conda-forge
     tqdm                      4.41.1                     py_0    conda-forge
     traitlets                 4.3.3                    py37_0    conda-forge
     typed-ast                 1.4.0            py37h516909a_0    conda-forge
     typing_extensions         3.7.4.1                  py37_0    conda-forge
     tzcode                    2019a             h516909a_1002    conda-forge
     umap-learn                0.3.10                   py37_1    conda-forge
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     urllib3                   1.25.7                   py37_0    conda-forge
     wcwidth                   0.1.8                      py_0    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     websockets                8.1              py37h516909a_0    conda-forge
     werkzeug                  0.16.0                     py_0    conda-forge
     wheel                     0.33.6                   py37_0    conda-forge
     wrapt                     1.11.2           py37h516909a_0    conda-forge
     xarray                    0.14.1                     py_1    conda-forge
     xerces-c                  3.2.2             h8412b87_1004    conda-forge
     xgboost                   1.0.0-SNAPSHOT           pypi_0    pypi
     xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
     xorg-libice               1.0.10               h516909a_0    conda-forge
     xorg-libsm                1.2.3             h84519dc_1000    conda-forge
     xorg-libx11               1.6.9                h516909a_0    conda-forge
     xorg-libxau               1.0.9                h14c3975_0    conda-forge
     xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
     xorg-libxext              1.3.4                h516909a_0    conda-forge
     xorg-libxpm               3.5.13               h516909a_0    conda-forge
     xorg-libxrender           0.9.10            h516909a_1002    conda-forge
     xorg-libxt                1.1.5             h516909a_1003    conda-forge
     xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
     xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
     xorg-xproto               7.0.31            h14c3975_1007    conda-forge
     xz                        5.2.4             h14c3975_1001    conda-forge
     yaml                      0.2.2                h516909a_1    conda-forge
     yarl                      1.3.0           py37h516909a_1000    conda-forge
     zeromq                    4.3.2                he1b5a44_2    conda-forge
     zict                      1.0.0                    pypi_0    pypi
     zipp                      0.6.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1006    conda-forge
     zstd                      1.4.3                h3b9ef0a_0    conda-forge
     
</pre></details>
```

**Additional context**

**Comment by thomcom** [comment]
The `DataFrame` has an empty index @Ashwin Trikuta Srinath, the columns have indexes but the `DataFrame` does not.

**Comment by thomcom** [comment]
`self.copy` is failing for that reason. A purer reproducer is just 
```
>>> import cudf
>>> columns = ["A", "B"]
>>> gdf = cudf.DataFrame({col: [""] for col in columns})
>>> gdf = gdf[:0]
>>> gdf["A"] = ["foo", "bar"]
>>> gdf["B"] = ["foo", "bar"]
>>> hdf = gdf.copy(deep=False)
```

**Comment by shwina** [comment]
To clear any confusion, I think you mean to tag me here, @thomcom :)

**Comment by kkraus14** [comment]
@shwina this is still an issue post #3741, in adding the columns there's still a `RangeIndex` of size 0 and that breaks everything.
