### ISSUE TITLE
[BUG] some parquet files written useing the GPU cannot be read on the GPU

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#4034]
**Describe the bug**
I ran into an issue recently where I was working with spark and rapids.  The output of a GPU write could not be read by the CPU code.  Sadly the data itself is sensitive so I cannot just hand it out.  But I am happy to work with individuals to try and reproduce the issue.

**Steps/Code to reproduce bug**
It looks like it has something to do the dictionary because when I use the parquer-mr tools to cat it I see the following exception.

```
$ java -cp ./target/parquet-tools-1.11.0.jar:./target/dependency/\* org.apache.parquet.tools.Main cat --debug ../../rapids-plugin-4-spark/gpu.snappy.parquet
....
org.apache.parquet.io.ParquetDecodingException: Can not read value at 273868 in block 0 in file file:/<>/gpu.snappy.parquet
	at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:251)
	at org.apache.parquet.hadoop.ParquetReader.read(ParquetReader.java:132)
	at org.apache.parquet.tools.command.CatCommand.execute(CatCommand.java:86)
	at org.apache.parquet.tools.Main.main(Main.java:223)
Caused by: org.apache.parquet.io.ParquetDecodingException: Can't read value in column [geo_location_event] required binary geo_location_event at value 273868 out of 275000, 133868 out of 135000 in currentPage. repetition level: 0, definition level: 0
	at org.apache.parquet.column.impl.ColumnReaderBase.readValue(ColumnReaderBase.java:523)
	at org.apache.parquet.column.impl.ColumnReaderImpl.readValue(ColumnReaderImpl.java:30)
	at org.apache.parquet.column.impl.ColumnReaderBase.writeCurrentValueToConverter(ColumnReaderBase.java:409)
	at org.apache.parquet.column.impl.ColumnReaderImpl.writeCurrentValueToConverter(ColumnReaderImpl.java:30)
	at org.apache.parquet.io.RecordReaderImplementation.read(RecordReaderImplementation.java:406)
	at org.apache.parquet.hadoop.InternalParquetRecordReader.nextKeyValue(InternalParquetRecordReader.java:226)
	... 3 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1372
	at org.apache.parquet.column.values.dictionary.PlainValuesDictionary$PlainBinaryDictionary.decodeToBinary(PlainValuesDictionary.java:122)
	at org.apache.parquet.column.values.dictionary.DictionaryValuesReader.readBytes(DictionaryValuesReader.java:83)
	at org.apache.parquet.column.impl.ColumnReaderBase$2$6.read(ColumnReaderBase.java:344)
	at org.apache.parquet.column.impl.ColumnReaderBase.readValue(ColumnReaderBase.java:503)
	... 8 more
org.apache.parquet.io.ParquetDecodingException: Can not read value at 273868 in block 0 in file file:<>/gpu.snappy.parquet

```

**Expected behavior**
I would expect the output of writing a parquet file could be read by spark and other similar tools.

**Environment overview (please complete the following information)**
This is using 0.13-SNAPSHOT (6351671f27c48753935dcee64f54e25b9885c52e) that I built myself.  I am running on Ubuntu.

**Comment by OlivierNV** [comment]
Looking at the code corresponding to the stack, it looks like one written dictionary index for a string column exceeds the dictionary size (appears to occur towards the end of one of the first data pages). Will try to narrow down how this could happen...
