### ISSUE TITLE
[BUG] uint8's throw exceptions

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#4243]
**Describe the bug**

In 0.12:

```
import cudf, numpy as np
cudf.Series([1], dtype=np.uint8)
```
=>
```
Traceback (most recent call last):
  File "/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/column/column.py", line 1303, in as_column
    memoryview(arbitrary), dtype=dtype, nan_as_null=nan_as_null
TypeError: memoryview: a bytes-like object is required, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/series.py", line 124, in __init__
    data = column.as_column(data, nan_as_null=nan_as_null, dtype=dtype)
  File "/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/column/column.py", line 1318, in as_column
    pa_type = np_to_pa_dtype(np.dtype(dtype))
  File "/conda/envs/rapids/lib/python3.7/site-packages/cudf/utils/dtypes.py", line 38, in np_to_pa_dtype
    return _np_pa_dtypes[np.dtype(dtype).type]
KeyError: <class 'numpy.uint8'>
```

Exception also thrown with `cudf.from_pandas(pd.Series([1], dtype=np.uint8))`

**Steps/Code to reproduce bug**

1. Run env & docker python cmd as from https://github.com/rapidsai/rmm/issues/306
2. Run above self-contained code

**Expected behavior**

gpu series created

**Environment overview (please complete the following information)**

See https://github.com/rapidsai/rmm/issues/306

**Additional context**

`int8` seems to work fine

**Comment by jrhemstad** [comment]
We don't current support unsigned types, so I'm guessing that's the issue.

**Comment by lmeyerov** [comment]
Ah, ok, then the expectation would be graceful handling, e.g., `Series` and `DataFrame` either throw a `NotImplemented` exn or coerce, and somewhere more prominent in the docs

**Comment by kkraus14** [comment]
Closing in favor of #2819
