### ISSUE TITLE
Container build success but ImportError: cannot import name 'librmm'

### ISSUE THREAD

**Issue by DC-Shi** [rapidsai/cudf#431]
- Built from container as README.md instructed.
- commit dae6026475aa19947fcf46c792cd11a18a32c43b
- Ubuntu 16.04.5 LTS, 4.15.0-36 kernel, DGX station with 4 V100s
- Driver version 410.74 CUDA Version: 10.0

The container build without error, then I start the container and try to run import, but failed:
```
daochen@dgxstation:~/github/cudf$ docker run --rm --runtime=nvidia -it cudf bash

root@310bcd41d293:/# source activate cudf
(cudf) root@310bcd41d293:/# python -c "import cudf"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/conda/envs/cudf/lib/python3.5/site-packages/cudf-0.3.0+138.gdae6026-py3.5-linux-x86_64.egg/cudf/__init__.py", line 2, in <module>
    from cudf import dataframe             # noqa: F401
  File "/conda/envs/cudf/lib/python3.5/site-packages/cudf-0.3.0+138.gdae6026-py3.5-linux-x86_64.egg/cudf/dataframe/__init__.py", line 1, in <module>
    from cudf.dataframe import (buffer, dataframe, series,  # noqa: F401
  File "/conda/envs/cudf/lib/python3.5/site-packages/cudf-0.3.0+138.gdae6026-py3.5-linux-x86_64.egg/cudf/dataframe/buffer.py", line 3, in <module>
    from librmm_cffi import librmm as rmm
ImportError: cannot import name 'librmm'
```
Tried to list what `librmm_cffi` contains:
```
>>> import librmm_cffi
>>> librmm_cffi.
librmm_cffi.RMMError(          librmm_cffi.__format__(        librmm_cffi.__ne__(            librmm_cffi.__str__(
librmm_cffi._RMMWrapper(       librmm_cffi.__ge__(            librmm_cffi.__new__(           librmm_cffi.__subclasshook__(
librmm_cffi.__cached__         librmm_cffi.__getattribute__(  librmm_cffi.__package__        librmm_cffi.absolute_import
librmm_cffi.__class__(         librmm_cffi.__gt__(            librmm_cffi.__path__           librmm_cffi.atexit
librmm_cffi.__delattr__(       librmm_cffi.__hash__(          librmm_cffi.__reduce__(        librmm_cffi.librmm_config
librmm_cffi.__dict__           librmm_cffi.__init__(          librmm_cffi.__reduce_ex__(     librmm_cffi.os
librmm_cffi.__dir__(           librmm_cffi.__le__(            librmm_cffi.__repr__(          librmm_cffi.sys
librmm_cffi.__doc__            librmm_cffi.__loader__         librmm_cffi.__setattr__(       librmm_cffi.wrapper
librmm_cffi.__eq__(            librmm_cffi.__lt__(            librmm_cffi.__sizeof__(
librmm_cffi.__file__           librmm_cffi.__name__           librmm_cffi.__spec__
```

PS:
I tested my friend's successful install(he installed using conda way), and changed the `librmm_cffi/__init__.py` file in site-packages, remove the last line `del _RMMWrapper` would also show above error, then I revert the edit and still failed. After waiting for several minutes, it turn back normal. I don't know whether this is related to some cache issues.

**Comment by kkraus14** [comment]
@randerzander See ongoing PR in #434 to help drive resolution.
