### ISSUE TITLE
[BUG] writing csv fails with categorical column 

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#4530]
**Describe the bug**
Writing csv fails with categorical column 

**Steps/Code to reproduce bug**
```python
import cudf
df = cudf.DataFrame({'a':['0','1','2']})
df['a']=df['a'].astype('category')
df.to_csv('test')
```
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/raid/vjawa/miniconda3/envs/cudf_march_16/lib/python3.7/site-packages/cudf/core/dataframe.py", line 3897, in to_csv
    chunksize,
  File "/raid/vjawa/miniconda3/envs/cudf_march_16/lib/python3.7/site-packages/cudf/io/csv.py", line 122, in to_csv
    rows_per_chunk=rows_per_chunk,
  File "cudf/_lib/csv.pyx", line 247, in cudf._lib.csv.write_csv
  File "cudf/_lib/csv.pyx", line 311, in cudf._lib.csv.write_csv
  File "cudf/_lib/cudf.pyx", line 370, in cudf._lib.cudf.column_view_from_string_column
AttributeError: 'CategoricalColumn' object has no attribute 'nvstrings'
```

**Environment overview (please complete the following information)**
```
cudf                      0.13.0a200316         py37_4041    rapidsai-nightly
dask-cudf                 0.13.0a200316         py37_4041    rapidsai-nightly
libcudf                   0.13.0a200316     cuda10.1_4041    rapidsai-nightly
```

**Comment by VibhuJawa** [comment]
We also don't support `.to_parquet` with `categorical` columns. 

```
File "/raid/vjawa/miniconda3/envs/cudf_march_16/lib/python3.7/site-packages/cudf/io/parquet.py", line 193, in to_parquet
    "'category' column dtypes are currently not "
ValueError: 'category' column dtypes are currently not supported by the gpu accelerated parquet writer
```

**Comment by OlivierNV** [comment]
Assuming the python categorical is mapped to DICTIONARY32 columns on the cpp side, it shouldn't be too difficult to add (string dictionaries are relatively simple, other dictionary types require a bit more code but should be doable for 0.14)

**Comment by kkraus14** [comment]
Python categorical is not mapped to `DICTIONARY32` yet

**Comment by harrism** [comment]
@kkraus14 is this is scope for 0.14?

**Comment by kkraus14** [comment]
No, this would require hooking up Python to Dictionary32 and hooking up Dictionary32 to cuIO.

**Comment by beckernick** [comment]
This is resolved for csv, but not parquet.

**Comment by GregoryKimball** [comment]
Closing in favor of #10115
