### ISSUE TITLE
[BUG] dask-cudf groupby yields error on category column

### ISSUE THREAD

**Issue by rnyak** [rapidsai/cudf#4608]
**Describe the bug**
@taureandyernv @randerzander for viz.

I am trying to groupby with dask-cudf on a category column. It yields the error below. 
Dask version is 2.12.0

**Steps/Code to reproduce bug**
```
import dask
import cudf
import dask_cudf as dcu
df = dask.datasets.timeseries()
ddf = dcu.from_dask_dataframe(df)
ddf.dtypes
id            int64
name     object
x            float64
y            float64
dtype: object

ddf['name']=ddf['name'].astype('category')

ddf.dtypes
id            int64
name    category
x           float64
y           float64

ddf.groupby('name').agg({'x': ['mean', 'max'], 'y': ['mean', 'count']}).compute()
```
We get the following error:

```
......
......
IndexError: 

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-25-53cb03531f6d> in <module>
----> 1 ddf.groupby('name').agg({'x': ['mean', 'max'], 'y': ['mean', 'count']}).compute()

~/yes/envs/rapids_13_tpcx/lib/python3.7/site-packages/dask/dataframe/groupby.py in agg(self, arg, split_every, split_out)
   1756     @derived_from(pd.core.groupby.DataFrameGroupBy)
   1757     def agg(self, arg, split_every=None, split_out=1):
-> 1758         return self.aggregate(arg, split_every=split_every, split_out=split_out)
   1759 
   1760 

~/yes/envs/rapids_13_tpcx/lib/python3.7/site-packages/dask/dataframe/groupby.py in aggregate(self, arg, split_every, split_out)
   1751 
   1752         return super(DataFrameGroupBy, self).aggregate(
-> 1753             arg, split_every=split_every, split_out=split_out
   1754         )
   1755 

~/yes/envs/rapids_13_tpcx/lib/python3.7/site-packages/dask/dataframe/groupby.py in aggregate(self, arg, split_every, split_out)
   1532             split_out=split_out,
   1533             split_out_setup=split_out_on_index,
-> 1534             sort=self.sort,
   1535         )
   1536 

~/yes/envs/rapids_13_tpcx/lib/python3.7/site-packages/dask/dataframe/core.py in apply_concat_apply(args, chunk, aggregate, combine, meta, token, chunk_kwargs, aggregate_kwargs, combine_kwargs, split_every, split_out, split_out_setup, split_out_setup_kwargs, sort, **kwargs)
   4891 
   4892     if meta is no_default:
-> 4893         meta_chunk = _emulate(chunk, *args, udf=True, **chunk_kwargs)
   4894         meta = _emulate(aggregate, _concat([meta_chunk]), udf=True, **aggregate_kwargs)
   4895     meta = make_meta(

~/yes/envs/rapids_13_tpcx/lib/python3.7/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   4936     """
   4937     with raise_on_meta_error(funcname(func), udf=kwargs.pop("udf", False)):
-> 4938         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   4939 
   4940 

~/yes/envs/rapids_13_tpcx/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

~/yes/envs/rapids_13_tpcx/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    191         )
    192         msg = msg.format(" in `{0}`".format(funcname) if funcname else "", repr(e), tb)
--> 193         raise ValueError(msg)
    194 
    195 

ValueError: Metadata inference failed in `_groupby_apply_funcs`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
IndexError()
.....
```
I tried to add `meta=keyword` in the `agg()` but it did not work.  

**Expected behavior**
```
df.groupby('name').agg({'x': ['mean', 'max'], 'y': ['mean', 'count']}).compute().head()
```
![image](https://user-images.githubusercontent.com/16246900/77098716-2ce93980-69e9-11ea-9d15-6e32086be969.png)

**Environment overview (please complete the following information)**
 - Environment location:  Conda
 - Method of cuDF install: Conda - rapids nightly (cudf 0.13.0a200317)

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Comment by kkraus14** [comment]
cc @shwina I think we should look into this

**Comment by shwina** [comment]
@rnyak could you please post the rest of the trace if any? This is the trace I get which looks to be different than yours:

<details>

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    171     try:
--> 172         yield
    173     except Exception as e:

~/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   4940     with raise_on_meta_error(funcname(func), udf=kwargs.pop("udf", False)):
-> 4941         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   4942

~/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/dataframe/groupby.py in _groupby_apply_funcs(df, *index, **kwargs)
    880     for result_column, func, func_kwargs in funcs:
--> 881         r = func(grouped, **func_kwargs)
    882

~/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/dataframe/groupby.py in _apply_func_to_column(df_like, column, func)
    917
--> 918     return func(df_like[column])
    919

~/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/utils.py in __call__(self, obj, *args, **kwargs)
    879     def __call__(self, obj, *args, **kwargs):
--> 880         return getattr(obj, self.method)(*args, **kwargs)
    881

~/workspace/github/shwina/cudf/python/cudf/cudf/core/groupby/groupby.py in _agg_func_name_with_args(self, func_name, *args, **kwargs)
    259         func.__name__ = func_name
--> 260         return self.agg(func)
    261

~/workspace/github/shwina/cudf/python/cudf/cudf/core/groupby/groupby.py in agg(self, func)
    491     def agg(self, func):
--> 492         result = super().agg(func)
    493

~/workspace/github/shwina/cudf/python/cudf/cudf/core/groupby/groupby.py in agg(self, func)
    167         # copy categorical information from keys to the result index:
--> 168         result.index._copy_categories(self.grouping.keys)
    169

~/workspace/github/shwina/cudf/python/cudf/cudf/core/frame.py in _copy_categories(self, other, include_index)
    852                     size=col.size,
--> 853                     offset=col.offset,
    854                 )

~/workspace/github/shwina/cudf/python/cudf/cudf/core/column/column.py in build_categorical_column(categories, codes, mask, size, offset, ordered)
   1027         offset=offset,
-> 1028         children=(as_column(codes),),
   1029     )

~/workspace/github/shwina/cudf/python/cudf/cudf/core/column/column.py in as_column(arbitrary, nan_as_null, dtype, length)
   1118         if dtype is None:
-> 1119             raise TypeError(f"dtype cannot be None if 'arbitrary' is a Buffer")
   1120         data = build_column(arbitrary, dtype=dtype)

TypeError: dtype cannot be None if 'arbitrary' is a Buffer

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-4-53cb03531f6d> in <module>
----> 1 ddf.groupby('name').agg({'x': ['mean', 'max'], 'y': ['mean', 'count']}).compute()

~/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/dataframe/groupby.py in agg(self, arg, split_every, split_out)
   1756     @derived_from(pd.core.groupby.DataFrameGroupBy)
   1757     def agg(self, arg, split_every=None, split_out=1):
-> 1758         return self.aggregate(arg, split_every=split_every, split_out=split_out)
   1759
   1760

~/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/dataframe/groupby.py in aggregate(self, arg, split_every, split_out)
   1751
   1752         return super(DataFrameGroupBy, self).aggregate(
-> 1753             arg, split_every=split_every, split_out=split_out
   1754         )
   1755

~/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/dataframe/groupby.py in aggregate(self, arg, split_every, split_out)
   1532             split_out=split_out,
   1533             split_out_setup=split_out_on_index,
-> 1534             sort=self.sort,
   1535         )
   1536

~/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/dataframe/core.py in apply_concat_apply(args, chunk, aggregate, combine, meta, token, chunk_kwargs, aggregate_kwargs, combine_kwargs, split_every, s
plit_out, split_out_setup, split_out_setup_kwargs, sort, **kwargs)
   4894
   4895     if meta is no_default:
-> 4896         meta_chunk = _emulate(chunk, *args, udf=True, **chunk_kwargs)
   4897         meta = _emulate(aggregate, _concat([meta_chunk]), udf=True, **aggregate_kwargs)
   4898     meta = make_meta(

~/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   4939     """
   4940     with raise_on_meta_error(funcname(func), udf=kwargs.pop("udf", False)):
-> 4941         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   4942
   4943

~/miniconda3/envs/cudf_dev/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

~/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    191         )
    192         msg = msg.format(" in `{0}`".format(funcname) if funcname else "", repr(e), tb)
--> 193         raise ValueError(msg)
    194
    195

ValueError: Metadata inference failed in `_groupby_apply_funcs`.

You have supplied a custom function and Dask is unable to
determine the type of output that that function returns.

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
TypeError("dtype cannot be None if 'arbitrary' is a Buffer")

Traceback:
---------
  File "/home/ashwint/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/dataframe/utils.py", line 172, in raise_on_meta_error
    yield
  File "/home/ashwint/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/dataframe/core.py", line 4941, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/home/ashwint/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/dataframe/groupby.py", line 881, in _groupby_apply_funcs
    r = func(grouped, **func_kwargs)
  File "/home/ashwint/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/dataframe/groupby.py", line 918, in _apply_func_to_column
    return func(df_like[column])
  File "/home/ashwint/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/dask/utils.py", line 880, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
  File "/home/ashwint/workspace/github/shwina/cudf/python/cudf/cudf/core/groupby/groupby.py", line 260, in _agg_func_name_with_args
    return self.agg(func)
  File "/home/ashwint/workspace/github/shwina/cudf/python/cudf/cudf/core/groupby/groupby.py", line 492, in agg
    result = super().agg(func)
  File "/home/ashwint/workspace/github/shwina/cudf/python/cudf/cudf/core/groupby/groupby.py", line 168, in agg
    result.index._copy_categories(self.grouping.keys)
  File "/home/ashwint/workspace/github/shwina/cudf/python/cudf/cudf/core/frame.py", line 853, in _copy_categories
    offset=col.offset,
  File "/home/ashwint/workspace/github/shwina/cudf/python/cudf/cudf/core/column/column.py", line 1028, in build_categorical_column
    children=(as_column(codes),),
  File "/home/ashwint/workspace/github/shwina/cudf/python/cudf/cudf/core/column/column.py", line 1119, in as_column
    raise TypeError(f"dtype cannot be None if 'arbitrary' is a Buffer")

```
</details>

**Comment by shwina** [comment]
Tracked down this bug to the way we handle `meta_nonempty` for categoricals in `dask_cudf`. Fix coming up.
