### ISSUE TITLE
[BUG] Concating large number of Empty DataFrames Errors Out

### ISSUE THREAD

**Issue by mlahir1** [rapidsai/cudf#4629]
On conda nightly from march 20, 2020 5: AM CST

Expected Bgaviour:
```
>>> a1  = [delayed(cudf.DataFrame({'a':[]})) for i in range(66)] 
>>> delayed(cudf.concat)(a1).compute()

Index: [], Empty DataFrame
Columns: [a]
```

Actual Behaviour:
```
>>> a1  = [delayed(cudf.DataFrame({'a':[]})) for i in range(66)] 
>>> 
>>> delayed(cudf.concat)(a1).compute()
distributed.worker - WARNING -  Compute Failed
Function:  concat
args:      ([Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: [], Empty DataFrame
Columns: [a]
Index: []
kwargs:    {}
Exception: RuntimeError('cuDF failure at: /conda/conda-bld/libcudf_1584690097596/work/cpp/include/cudf/detail/utilities/cuda.cuh:65: num_blocks must be > 0')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask/base.py", line 437, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/client.py", line 2595, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/client.py", line 1893, in gather
    asynchronous=asynchronous,
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/client.py", line 780, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils.py", line 348, in sync
    raise exc.with_traceback(tb)
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/utils.py", line 332, in f
    result[0] = yield future
  File "/conda/envs/rapids/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/conda/envs/rapids/lib/python3.7/site-packages/distributed/client.py", line 1752, in _gather
    raise exception.with_traceback(traceback)
  File "/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/reshape.py", line 98, in concat
    return DataFrame._concat(objs, axis=axis, ignore_index=ignore_index)
  File "/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/frame.py", line 199, in _concat
    libcudfxx.concat.concat_tables(tables, ignore_index=ignore_index)
  File "cudf/_libxx/concat.pyx", line 46, in cudf._libxx.concat.concat_tables
  File "cudf/_libxx/concat.pyx", line 54, in cudf._libxx.concat.concat_tables
RuntimeError: cuDF failure at: /conda/conda-bld/libcudf_1584690097596/work/cpp/include/cudf/detail/utilities/cuda.cuh:65: num_blocks must be > 0
```

**Comment by kkraus14** [comment]
cc @trxcllnt @trevorsm7

**Comment by jrhemstad** [comment]
I've got the fix incoming.
