### ISSUE TITLE
[BUG] Creating multiple columns with static value causes error

### ISSUE THREAD

**Issue by mlahir1** [rapidsai/cudf#4657]
cudf build from conda nightlies 6 AM EST

Expected Output:
```
>>> import cudf
>>> df = cudf.DataFrame()
>>> df[['a', 'b']] =0
>>> df
Empty DataFrame
Columns: [a, b]
Index: []
```

Actual Output:
```
>>> df = cudf.DataFrame()
>>> df[['a', 'b']] =0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/dataframe.py", line 612, in __setitem__
    self._data[col][:] = value
  File "/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/column_accessor.py", line 46, in __getitem__
    return self._data[key]
KeyError: 'b'
```

**Comment by randerzander** [comment]
@mlahir1 I'm confused what behavior you're looking for here.

The same snippet with Pandas also fails, albeit with a different type of error:
```
>>> import pandas as pd
>>> df = pd.DataFrame()
>>> df[['a', 'b']] = 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rgelhausen/conda/envs/rapids/lib/python3.7/site-packages/pandas/core/frame.py", line 3484, in __setitem__
    self._setitem_array(key, value)
  File "/home/rgelhausen/conda/envs/rapids/lib/python3.7/site-packages/pandas/core/frame.py", line 3511, in _setitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/home/rgelhausen/conda/envs/rapids/lib/python3.7/site-packages/pandas/core/indexing.py", line 1285, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "/home/rgelhausen/conda/envs/rapids/lib/python3.7/site-packages/pandas/core/indexing.py", line 1092, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "/home/rgelhausen/conda/envs/rapids/lib/python3.7/site-packages/pandas/core/indexing.py", line 1177, in _validate_read_indexer
    key=key, axis=self.obj._get_axis_name(axis)
KeyError: "None of [Index(['a', 'b'], dtype='object')] are in the [columns]"
```

Are you looking to create two empty columns? If so, you can do:
```
import cudf

>>> df = cudf.DataFrame()
>>> df['a'] = 0
>>> df['b'] = 0
>>> df
Empty DataFrame
Columns: [a, b]
Index: []
```

**Comment by mlahir1** [comment]
@randerzander I can re-write the code. I think its not ideal to go back and keep re-writing because something is not-working. I have a project which uses this code in a lot of places. SO, i refactor this code to way it works now, and what if it breaks later?

creating multiple columns this way `df[['a', 'b']] = 0` was working until Friday and now I suddenly see an error because of this.

**Comment by rgsl888prabhu** [comment]
It also fails in the following scenario, I will fix all of them along with this.
```
>>> import cudf
>>> df=cudf.DataFrame({"a":[1, 2, 3]})
>>> df[['b', 'c']]=10
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rgsl888/Projects/cython/cudf/python/cudf/cudf/core/dataframe.py", line 612, in __setitem__
    self._data[col][:] = value
  File "/home/rgsl888/Projects/cython/cudf/python/cudf/cudf/core/column_accessor.py", line 46, in __getitem__
    return self._data[key]
KeyError: 'b'
>>> 

```

**Comment by rgsl888prabhu** [comment]
After a discussion in the PR, came to conclusion that we will not be supporting this behavior as pandas doesn't.

**Comment by shwina** [comment]
@mlahir1 Apologies for the change in behaviour. The prior behaviour was most definitely a bug and not an intended feature. We now raise a `KeyError` similar to Pandas in this situation. If it's alright with you, can we go ahead and close this issue out?

**Comment by mlahir1** [comment]
@shwina @randerzander 
thats fine. I have anyways changed my code. I have brought it to notice since my workflow failed, and I hope you guys are aware of this.

Thanks.

**Comment by kkraus14** [comment]
Closing this as wontfix, thanks!
