### ISSUE TITLE
[BUG]dask_cudf nunique gives incorrect results

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#4663]
**Describe the bug**

dask_cudf nunique gives incorrect results

**Steps/Code to reproduce bug**
```python
import dask_cudf
import cudf

df = dask_cudf.from_cudf(cudf.DataFrame({"key":[1,1],'val':[1,2]}),npartitions=1)
df.groupby(['key']).val.nunique().compute()

```

```
	val
0	1
1	1
```

**Expected behavior**
```python
df.to_dask_dataframe().groupby(['key']).val.nunique().compute()
```
```
key
1    2
Name: val, dtype: int64
```
**Environment overview (please complete the following information)**
 - Method of cuDF install: [conda]

```python
# packages in environment at /raid/vjawa/conda/conda_installation/envs/cudf_march_23:
cudf                      0.13.0a200323         py37_4667    rapidsai-nightly
dask-cudf                 0.13.0a200323         py37_4667    rapidsai-nightly
libcudf                   0.13.0a200323     cuda10.1_4667    rapidsai-nightly
dask                      2.12.0                     py_0    conda-forge
dask-core                 2.12.0                     py_0    conda-forge
dask-cuda                 0.13.0b200323           py37_73    rapidsai-nightly
dask-cudf                 0.13.0a200323         py37_4667    rapidsai-nightly
```
**Additional context**

Seems like mainline-dask may have problems that can be related:

Dask issue https://github.com/dask/dask/issues/4869
Pandas issue : https://github.com/pandas-dev/pandas/issues/26515

**Comment by VibhuJawa** [comment]
CC: @razajafri  and @jakirkham

**Comment by jakirkham** [comment]
cc @rjzamora

**Comment by rjzamora** [comment]
I fear this may be a result of differences in behavior between cudf and pandas for `apply` (Note that @kkraus14 and @shwina have also discovered that apply is problematic for std)...  I'll do my best to find a fix here

**Comment by VibhuJawa** [comment]
Before you jump deep into that do you expect it to be more performant that something like below ?

```python
def agg_count_distinct(df, group_key, counted_key, client): 
     """Returns a Series that is the result of counting distinct instances of 'counted_key' within each 'group_key'. 
     The series' index will have one entry per unique 'group_key' value. 
     Workaround for lack of nunique aggregate function on Dask df. 
     """ 
     return ( 
         df.drop_duplicates( 
             [group_key, counted_key], split_out=len(client.scheduler_info()["workers"]) 
         ) 
         .groupby(group_key)[counted_key] 
         .count() 
     ) 
```

**Comment by rjzamora** [comment]
@VibhuJawa - In an ideal world, the `nunique` aggregation would be faster than your workaround.  However, since dask is using `apply`,  I would expect your version to be much faster for large partitions (apply is slow).  I'm not sure if there is a clean way to remove the use of `apply` from the dask code -  I know @quasiben has ben pndering this lately.

**Comment by VibhuJawa** [comment]
>Since dask is using apply, I would expect your version to be much faster for large partitions (apply is slow). 

Thanks for clarification. 

Got it, I think in this case we can wait on this particular feature from a work-flows perspective.  

CC: @beckernick / @randerzander/ @ayushdg , in case you guys have more inputs on this.

**Comment by beckernick** [comment]
This is still present in the current nightly

**Comment by beckernick** [comment]
In the current nightly, it looks like we ultimately throw a NotImplementedError due to the `level` parameter of `reset_index` not being None:

<details>
```python
import dask_cudf
import cudf
​
df = dask_cudf.from_cudf(cudf.DataFrame({"key":[1,1],'val':[1,2]}),npartitions=1)
df.groupby(['key']).val.nunique().compute()
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
~/conda/envs/rapids-21.12/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    175     try:
--> 176         yield
    177     except Exception as e:

~/conda/envs/rapids-21.12/lib/python3.7/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   5786     with raise_on_meta_error(funcname(func), udf=kwargs.pop("udf", False)):
-> 5787         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   5788 

~/conda/envs/rapids-21.12/lib/python3.7/site-packages/dask/dataframe/groupby.py in _nunique_df_chunk(df, *index, **kwargs)
    517         grouped = (
--> 518             g[[name]].apply(_drop_duplicates_reindex).reset_index(level=-1, drop=True)
    519         )

~/conda/envs/rapids-21.12/lib/python3.7/site-packages/cudf/core/dataframe.py in reset_index(self, level, drop, inplace, col_level, col_fill)
   2521         if level is not None:
-> 2522             raise NotImplementedError("level parameter is not supported yet.")
   2523 

NotImplementedError: level parameter is not supported yet.

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
/tmp/ipykernel_75664/1942982108.py in <module>
      3 
      4 df = dask_cudf.from_cudf(cudf.DataFrame({"key":[1,1],'val':[1,2]}),npartitions=1)
----> 5 df.groupby(['key']).val.nunique().compute()
      6 

~/conda/envs/rapids-21.12/lib/python3.7/site-packages/dask/dataframe/groupby.py in nunique(self, split_every, split_out)
   1900             split_out=split_out,
   1901             split_out_setup=split_out_on_index,
-> 1902             sort=self.sort,
   1903         )
   1904 

~/conda/envs/rapids-21.12/lib/python3.7/site-packages/dask/dataframe/core.py in apply_concat_apply(args, chunk, aggregate, combine, meta, token, chunk_kwargs, aggregate_kwargs, combine_kwargs, split_every, split_out, split_out_setup, split_out_setup_kwargs, sort, ignore_index, **kwargs)
   5736 
   5737     if meta is no_default:
-> 5738         meta_chunk = _emulate(chunk, *args, udf=True, **chunk_kwargs)
   5739         meta = _emulate(
   5740             aggregate, _concat([meta_chunk], ignore_index), udf=True, **aggregate_kwargs

~/conda/envs/rapids-21.12/lib/python3.7/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   5785     """
   5786     with raise_on_meta_error(funcname(func), udf=kwargs.pop("udf", False)):
-> 5787         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   5788 
   5789 

~/conda/envs/rapids-21.12/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

~/conda/envs/rapids-21.12/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    195         )
    196         msg = msg.format(f" in `{funcname}`" if funcname else "", repr(e), tb)
--> 197         raise ValueError(msg) from e
    198 
    199 

ValueError: Metadata inference failed in `_nunique_df_chunk`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
NotImplementedError('level parameter is not supported yet.')

Traceback:
---------
  File "/home/nicholasb/conda/envs/rapids-21.12/lib/python3.7/site-packages/dask/dataframe/utils.py", line 176, in raise_on_meta_error
    yield
  File "/home/nicholasb/conda/envs/rapids-21.12/lib/python3.7/site-packages/dask/dataframe/core.py", line 5787, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/home/nicholasb/conda/envs/rapids-21.12/lib/python3.7/site-packages/dask/dataframe/groupby.py", line 518, in _nunique_df_chunk
    g[[name]].apply(_drop_duplicates_reindex).reset_index(level=-1, drop=True)
  File "/home/nicholasb/conda/envs/rapids-21.12/lib/python3.7/site-packages/cudf/core/dataframe.py", line 2522, in reset_index
    raise NotImplementedError("level parameter is not supported yet.")
```
</details>

**Comment by vyasr** [comment]
It looks like this works now:
```
In [19]: 
    ...: df = dask_cudf.from_cudf(cudf.DataFrame({"key":[1,1],'val':[1,2]}),npartitions=1)
    ...: df.groupby(['key']).val.nunique().compute()
Out[19]: 
key
1    2
Name: val, dtype: int32
```
