### ISSUE TITLE
[BUG] TypeError in `reindex` for CategoricalColumn

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#4734]
**Describe the bug**
When we do a `reindex` of a `Series` with no name, we internally default the name to `0`, which will cause concatenation failure at this line:
https://github.com/rapidsai/cudf/blob/branch-0.14/python/cudf/cudf/core/frame.py#L1315

**Steps/Code to reproduce bug**
```python
>>> import cudf
>>> s = cudf.Series(['a','b'], dtype='category')
>>> s.reindex()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/cudf/lib/python3.7/site-packages/cudf/core/series.py", line 322, in reindex
    return self.to_frame(name).reindex(idx, copy=copy)[name]
  File "/conda/envs/cudf/lib/python3.7/site-packages/cudf/core/dataframe.py", line 1447, in reindex
    df = DataFrame(None, idx).join(df, how="left", sort=True)
  File "/conda/envs/cudf/lib/python3.7/site-packages/cudf/core/dataframe.py", line 2464, in join
    method=method,
  File "/conda/envs/cudf/lib/python3.7/site-packages/cudf/core/dataframe.py", line 2312, in merge
    method,
  File "/conda/envs/cudf/lib/python3.7/site-packages/cudf/core/frame.py", line 1315, in _merge
    codes=cat_codes.get(name + "_codes", col),
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

**Expected behavior**
We should be stringifying `name`

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: from source

**Environment details**
Output of the `cudf/print_env.sh` script here: 
[env.txt](https://github.com/rapidsai/cudf/files/4399404/env.txt)

**Additional context**

**Comment by galipremsagar** [comment]
Fixed by #4733
