### ISSUE TITLE
[BUG] Certain quantifier regex patterns erroneously fail to compile

### ISSUE THREAD

**Issue by kuhushukla** [rapidsai/cudf#4746]
**Describe the bug**
A recent change in cudf regex parser `return error for invalid quantifier` per `575e944f777df0b904be0a8f1a9722ded0c045a6` fails some patterns that passed earlier that seem reasonable to pass in the first place.

**Steps/Code to reproduce bug**
Following tests fail :
```
 TEST_F(StringsContainsTests, custom_anynl)
    {
        std::string medium_regex = "(.|\\n)*";

        std::vector<const char*> h_strings{
            "hello"
        };
        cudf::test::strings_column_wrapper strings( h_strings.begin(), h_strings.end(),
            thrust::make_transform_iterator( h_strings.begin(), [] (auto str) { return str!=nullptr; }));

        auto strings_view = cudf::strings_column_view(strings);
        {
            auto results = cudf::strings::matches_re(strings_view, medium_regex);
            cudf::experimental::bool8 h_expected[] = {true};
            cudf::test::fixed_width_column_wrapper<cudf::experimental::bool8> expected( h_expected, h_expected+h_strings.size(),
                thrust::make_transform_iterator( h_strings.begin(), [] (auto str) { return str!=nullptr; }));
            cudf::test::expect_columns_equal(*results,expected);
        }
    }

    TEST_F(StringsContainsTests, dotStarWithBraces)
        {
            std::string medium_regex = "(.)*";

            std::vector<const char*> h_strings{
                "hello"
            };
            cudf::test::strings_column_wrapper strings( h_strings.begin(), h_strings.end(),
                thrust::make_transform_iterator( h_strings.begin(), [] (auto str) { return str!=nullptr; }));

            auto strings_view = cudf::strings_column_view(strings);
            {
                auto results = cudf::strings::matches_re(strings_view, medium_regex);
                cudf::experimental::bool8 h_expected[] = {true};
                cudf::test::fixed_width_column_wrapper<cudf::experimental::bool8> expected( h_expected, h_expected+h_strings.size(),
                    thrust::make_transform_iterator( h_strings.begin(), [] (auto str) { return str!=nullptr; }));
                cudf::test::expect_columns_equal(*results,expected);
            }
        }
```
they thorw 
```
C++ exception with description "cuDF failure at: /home/kuhus/Reps/cudf/cpp/src/strings/regex/regcomp.cpp:504: invalid regex pattern: nothing to repeat at position 6" thrown in the test body.
```
and, 
```
C++ exception with description "cuDF failure at: /home/kuhus/Reps/cudf/cpp/src/strings/regex/regcomp.cpp:504: invalid regex pattern: nothing to repeat at position 3" thrown in the test body.
```
respectively.
**Expected behavior**
These tests above passed before the change.

**Environment overview (please complete the following information)**
 cudf 0.14 on Ubuntu 18.04

**Comment by davidwendt** [comment]
Another example with the same error and conditions:
```
>>> s = cudf.Series(["0.0.0.0", "5.79.97.178"])
>>> reg=r"^(100\.(6[4-9]|[7-9][0-9]|1([0-1][0-9]|2[0-7]))\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))\.([0-9]|[1-9][0-9]|1([0-9][0-9])|2([0-4][0-9]|5[0-5]))$)"
>>> s.str.match(reg)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/cudf/lib/python3.7/site-packages/cudf/core/column/string.py", line 1736, in match
    cpp_match_re(self._column, pat), **kwargs
  File "cudf/_libxx/strings/contains.pyx", line 67, in cudf._libxx.strings.contains.match_re
RuntimeError: cuDF failure at: /cudf/cpp/src/strings/regex/regcomp.cpp:504: invalid regex pattern: nothing to repeat at position 80
```
Also, I was able to reproduce with the minimal pattern of `r"(9)|2" so it looks like the ")" plus quantifier is causing the problem.
