### ISSUE TITLE
[BUG] Expected array-like (array or non-string sequence), got 0 0.0

### ISSUE THREAD

**Issue by divyegala** [rapidsai/cudf#4858]
Tagging the issue that was opened in cuml: https://github.com/rapidsai/cuml/issues/1886. I don't have transfer rights, but if any of the cudf owners could transfer this, then it would be great.

**Comment by galipremsagar** [comment]
Here's a minimal repro:
```python
>>> import cudf
>>> s = cudf.Series([0.0,1.0])
>>> from sklearn.metrics import accuracy_score
>>> accuracy_score(s,s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/cudf/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 185, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/conda/envs/cudf/lib/python3.7/site-packages/sklearn/metrics/_classification.py", line 81, in _check_targets
    type_true = type_of_target(y_true)
  File "/conda/envs/cudf/lib/python3.7/site-packages/sklearn/utils/multiclass.py", line 241, in type_of_target
    'got %r' % y)
ValueError: Expected array-like (array or non-string sequence), got 0    0.0
1    1.0
dtype: float64
>>> accuracy_score(s.to_pandas(),s.to_pandas())
1.0
```

The issue is we need to have `__array__` attribute in place for `cudf.Series`.
