### ISSUE TITLE
libgdf_cffi.wrapper.GDFError: CUDA ERROR when creating gdf from pandas dataframe

### ISSUE THREAD

**Issue by a-agrz** [rapidsai/cudf#497]
`>>> pdf = pd.DataFrame({'a': [0, 1, 2, 3],'b': [0.1, 0.2, None, 0.3]})`
`>>> df = cudf.DataFrame.from_pandas(pdf)`
`ERROR: CUDA Runtime call cudaGetLastError() in line 203 of file /cudf/cpp/src/bitmask/valid_ops.cu failed with no kernel image is available for execution on the device (48).
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/cudf/lib/python3.6/site-packages/cudf-0.4.0-py3.6-linux-x86_64.egg/cudf/dataframe/dataframe.py", line 1513, in from_pandas
    df[colk] = Series(dataframe[colk].values, nan_as_null=nan_as_null)
  File "/conda/envs/cudf/lib/python3.6/site-packages/cudf-0.4.0-py3.6-linux-x86_64.egg/cudf/dataframe/series.py", line 75, in __init__
    data = columnops.as_column(data, nan_as_null=nan_as_null)
  File "/conda/envs/cudf/lib/python3.6/site-packages/cudf-0.4.0-py3.6-linux-x86_64.egg/cudf/dataframe/columnops.py", line 178, in as_column
    data = as_column(rmm.to_device(arbitrary), nan_as_null=nan_as_null)
  File "/conda/envs/cudf/lib/python3.6/site-packages/cudf-0.4.0-py3.6-linux-x86_64.egg/cudf/dataframe/columnops.py", line 172, in as_column
    data = data.set_mask(mask)
  File "/conda/envs/cudf/lib/python3.6/site-packages/cudf-0.4.0-py3.6-linux-x86_64.egg/cudf/dataframe/column.py", line 213, in set_mask
    return self.replace(mask=mask, null_count=null_count)
  File "/conda/envs/cudf/lib/python3.6/site-packages/cudf-0.4.0-py3.6-linux-x86_64.egg/cudf/dataframe/column.py", line 319, in replace
    return type(self)(**params)
  File "/conda/envs/cudf/lib/python3.6/site-packages/cudf-0.4.0-py3.6-linux-x86_64.egg/cudf/dataframe/numerical.py", line 68, in __init__
    super(NumericalColumn, self).__init__(**kwargs)
  File "/conda/envs/cudf/lib/python3.6/site-packages/cudf-0.4.0-py3.6-linux-x86_64.egg/cudf/dataframe/columnops.py", line 35, in __init__
    super(TypedColumnBase, self).__init__(**kwargs)
  File "/conda/envs/cudf/lib/python3.6/site-packages/cudf-0.4.0-py3.6-linux-x86_64.egg/cudf/dataframe/column.py", line 107, in __init__
    size=len(self))
  File "/conda/envs/cudf/lib/python3.6/site-packages/cudf-0.4.0-py3.6-linux-x86_64.egg/cudf/_gdf.py", line 513, in count_nonzero_mask
    libgdf.gdf_count_nonzero_mask(mask_ptr, size, nnz)
  File "/conda/envs/cudf/lib/python3.6/site-packages/libgdf_cffi/wrapper.py", line 27, in wrap
    raise GDFError(errname, msg)
libgdf_cffi.wrapper.GDFError: CUDA ERROR. cudaSuccess: no error`

![image](https://user-images.githubusercontent.com/17067880/49813549-f6455d80-fd67-11e8-817d-2e75b53087f5.png)

**Comment by kkraus14** [comment]
@a-agrz We only support Pascal and newer architectures and the error you're getting is because your card doesn't support a new enough compute capability for cuDF. We should clarify this error message and I will open an issue for this.

**Comment by 1oscar** [comment]
X_df = pd.DataFrame({'fea%d'%i: X[:, i] for i in range(X.shape[1])})
X_gpu = cudf.DataFrame.from_pandas(X_df)

what():  CUDA error encountered at: /jenkins/workspace/gpuCIv2/cudf/branches/cudf-pip-build/cpp/src/bitmask/valid_ops.cu:170: 48 cudaErrorNoKernelImageForDevice no kernel image is available for execution on the device
Aborted
