### ISSUE TITLE
[BUG] String split via string accessor fails in dask-cudf

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#5127]
Using `str.split` on a Dask cuDF Series is currently failing. Example below.

```python
import dask_cudf
import cudf
​
df = cudf.DataFrame({
    "a":["this is", "this is"]
})
​
ddf = dask_cudf.from_cudf(df, 1)
ddf.a.str.split(" ")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-9c214cb96fa5> in <module>
      7 
      8 ddf = dask_cudf.from_cudf(df, 1)
----> 9 ddf.a.str.split(" ")

/raid/nicholasb/miniconda3/envs/rapids--20200506-cuda101-1018/lib/python3.7/site-packages/dask/dataframe/accessor.py in split(self, pat, n, expand)
    131         else:
    132             meta = (self._series.name, object)
--> 133         return self._function_map("split", pat=pat, n=n, expand=expand, meta=meta)
    134 
    135     @derived_from(pd.core.strings.StringMethods)

/raid/nicholasb/miniconda3/envs/rapids--20200506-cuda101-1018/lib/python3.7/site-packages/dask/dataframe/accessor.py in _function_map(self, attr, *args, **kwargs)
     71             kwargs,
     72             meta=meta,
---> 73             token=token,
     74         )
     75 

/raid/nicholasb/miniconda3/envs/rapids--20200506-cuda101-1018/lib/python3.7/site-packages/dask/dataframe/core.py in map_partitions(self, func, *args, **kwargs)
    640         >>> ddf.map_partitions(func).clear_divisions()  # doctest: +SKIP
    641         """
--> 642         return map_partitions(func, self, *args, **kwargs)
    643 
    644     @insert_meta_param_description(pad=12)

/raid/nicholasb/miniconda3/envs/rapids--20200506-cuda101-1018/lib/python3.7/site-packages/dask/dataframe/core.py in map_partitions(func, meta, enforce_metadata, transform_divisions, *args, **kwargs)
   5049         meta = _emulate(func, *args, udf=True, **kwargs)
   5050     else:
-> 5051         meta = make_meta(meta, index=meta_index)
   5052 
   5053     if all(isinstance(arg, Scalar) for arg in args):

/raid/nicholasb/miniconda3/envs/rapids--20200506-cuda101-1018/lib/python3.7/site-packages/dask/utils.py in __call__(self, arg, *args, **kwargs)
    504         """
    505         meth = self.dispatch(type(arg))
--> 506         return meth(arg, *args, **kwargs)
    507 
    508     @property

/raid/nicholasb/miniconda3/envs/rapids--20200506-cuda101-1018/lib/python3.7/site-packages/dask/dataframe/utils.py in make_meta_object(x, index)
    335         )
    336     if isinstance(x, tuple) and len(x) == 2:
--> 337         return _empty_series(x[0], x[1], index=index)
    338     elif isinstance(x, (list, tuple)):
    339         if not all(isinstance(i, tuple) and len(i) == 2 for i in x):

/raid/nicholasb/miniconda3/envs/rapids--20200506-cuda101-1018/lib/python3.7/site-packages/dask/dataframe/utils.py in _empty_series(name, dtype, index)
    279             pd.Categorical([UNKNOWN_CATEGORIES]), name=name, index=index
    280         ).iloc[:0]
--> 281     return pd.Series([], dtype=dtype, name=name, index=index)
    282 
    283 

/raid/nicholasb/miniconda3/envs/rapids--20200506-cuda101-1018/lib/python3.7/site-packages/pandas/core/series.py in __init__(self, data, index, dtype, name, copy, fastpath)
    213 
    214             if index is not None:
--> 215                 index = ensure_index(index)
    216 
    217             if data is None:

/raid/nicholasb/miniconda3/envs/rapids--20200506-cuda101-1018/lib/python3.7/site-packages/pandas/core/indexes/base.py in ensure_index(index_like, copy)
   5742         return index_like
   5743     if hasattr(index_like, "name"):
-> 5744         return Index(index_like, name=index_like.name, copy=copy)
   5745 
   5746     if is_iterator(index_like):

/raid/nicholasb/miniconda3/envs/rapids--20200506-cuda101-1018/lib/python3.7/site-packages/pandas/core/indexes/base.py in __new__(cls, data, dtype, copy, name, fastpath, tupleize_cols, **kwargs)
    515 
    516         elif hasattr(data, "__array__"):
--> 517             return Index(np.asarray(data), dtype=dtype, copy=copy, name=name, **kwargs)
    518         elif data is None or is_scalar(data):
    519             cls._scalar_data_error(data)

/raid/nicholasb/miniconda3/envs/rapids--20200506-cuda101-1018/lib/python3.7/site-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
     83 
     84     """
---> 85     return array(a, dtype, copy=False, order=order)
     86 
     87 

/raid/nicholasb/miniconda3/envs/rapids--20200506-cuda101-1018/lib/python3.7/site-packages/cudf/core/frame.py in __array__(self, dtype)
   1053             To explicitly construct a GPU array, consider using \
   1054             cupy.asarray(...)\nTo explicitly construct a \
-> 1055             host array, consider using .to_array()"
   1056         )
   1057 

TypeError: Implicit conversion to a host NumPy array via __array__ is not allowed,             To explicitly construct a GPU array, consider using             cupy.asarray(...)
To explicitly construct a             host array, consider using .to_array()
```

**Environment**
cuDF version: '0.14.0a+4185.g9133ff2'
Dask 2.15.0

**Comment by galipremsagar** [comment]
@beckernick Currently we don't support `expand=False` setting in `split` because of no nested list support in columns. Hence for the above-mentioned example to work we will have to pass `expand=True` and `n`.

```python
>>> import dask_cudf
>>> import cudf
>>> df = cudf.DataFrame({
...     "a":["this is", "this is"]
... })
>>> ddf = dask_cudf.from_cudf(df, 1)
>>> ddf.a.str.split(" ").compute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.16.0+9.gf82e08c-py3.7.egg/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.16.0+9.gf82e08c-py3.7.egg/dask/base.py", line 444, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.16.0+9.gf82e08c-py3.7.egg/dask/local.py", line 527, in get_sync
    return get_async(apply_sync, 1, dsk, keys, **kwargs)
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.16.0+9.gf82e08c-py3.7.egg/dask/local.py", line 471, in get_async
    fire_task()
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.16.0+9.gf82e08c-py3.7.egg/dask/local.py", line 466, in fire_task
    callback=queue.put,
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.16.0+9.gf82e08c-py3.7.egg/dask/local.py", line 516, in apply_sync
    res = func(*args, **kwds)
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.16.0+9.gf82e08c-py3.7.egg/dask/local.py", line 227, in execute_task
    result = pack_exception(e, dumps)
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.16.0+9.gf82e08c-py3.7.egg/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.16.0+9.gf82e08c-py3.7.egg/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.16.0+9.gf82e08c-py3.7.egg/dask/optimization.py", line 988, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.16.0+9.gf82e08c-py3.7.egg/dask/core.py", line 151, in get
    result = _execute_task(task, cache)
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.16.0+9.gf82e08c-py3.7.egg/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.16.0+9.gf82e08c-py3.7.egg/dask/utils.py", line 30, in apply
    return func(*args, **kwargs)
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.16.0+9.gf82e08c-py3.7.egg/dask/dataframe/core.py", line 5131, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask-2.16.0+9.gf82e08c-py3.7.egg/dask/dataframe/accessor.py", line 48, in _delegate_method
    out = getattr(getattr(obj, accessor, obj), attr)(*args, **kwargs)
  File "/conda/envs/cudf/lib/python3.7/site-packages/cudf/core/column/string.py", line 851, in split
    "`expand=False` setting is not supported yet"
NotImplementedError: `expand=False` setting is not supported yet

>>> ddf.a.str.split(" ",expand=True, n=1).compute()
      0   1
0  this  is
1  this  is
>>> 
```
