### ISSUE TITLE
[BUG] `.cat.add_categories` errors when values of different dtype are added

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#5264]
**Describe the bug**
`add_categories` errors when values of different dtype to that of existing categories are being added.

**Steps/Code to reproduce bug**
```python
>>> import cudf
>>> s = cudf.Series([1, 2, 3], dtype="category")
/conda/envs/cudf/lib/python3.7/site-packages/cudf/core/column/categorical.py:1047: FutureWarning: Constructing a CategoricalDtype without specifying `ordered` will default to `ordered=False` in a future version; `ordered=None` must be explicitly passed.
  and (dtype.ordered is None)
>>> s
0    1
1    2
2    3
dtype: category
Categories (3, int64): [1, 2, 3]
>>> s.cat.add_categories(['a','b'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/cudf/lib/python3.7/site-packages/cudf/core/column/categorical.py", line 285, in add_categories
    new_categories = self._column.categories.append(new_categories)
  File "/conda/envs/cudf/lib/python3.7/site-packages/cudf/core/column/column.py", line 632, in append
    return ColumnBase._concat([self, as_column(other)])
  File "/conda/envs/cudf/lib/python3.7/site-packages/cudf/core/column/column.py", line 210, in _concat
    raise ValueError("All columns must be the same type")
ValueError: All columns must be the same type
>>> s.to_pandas().cat.add_categories(['a','b'])
0    1
1    2
2    3
dtype: category
Categories (5, object): [1, 2, 3, a, b]
```

**Expected behavior**
`.cat.add_categories` seems to be missing a type-cast to a common `dtype` before performing an append on columns.

**Environment overview (please complete the following information)**
 - Environment Location: Docker
 - Method of cuDF install: from source(`branch-0.14`)

**Comment by galipremsagar** [comment]
Fixed by #5271
