### ISSUE TITLE
[BUG] dask_cudf read_parquet fails on latest nightly  

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#5579]
**Describe the bug**
`dask_cudf` read_parquet fails on latest nightly  

**Steps/Code to reproduce bug**
```python3
>>> import cudf
>>> import dask_cudf
>>> dask_cudf.from_cudf(cudf.DataFrame({'a':[1,2,3]}),npartitions=1).to_parquet('test_parquet')

>>> dask_cudf.read_parquet('test_parquet')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nvme/0/vjawa/conda/envs/cudf_15_june_25/lib/python3.7/site-packages/dask_cudf/io/parquet.py", line 213, in read_parquet
    **kwargs,
  File "/nvme/0/vjawa/conda/envs/cudf_15_june_25/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py", line 234, in read_parquet
    **kwargs
  File "/nvme/0/vjawa/conda/envs/cudf_15_june_25/lib/python3.7/site-packages/dask_cudf/io/parquet.py", line 17, in read_metadata
    meta, stats, parts, index = ArrowEngine.read_metadata(*args, **kwargs)
ValueError: not enough values to unpack (expected 4, got 3)
```

**Expected behavior**
This works with cudf and dask mainline code. 
```python
>>> dask.dataframe.read_parquet('test_parquet').head()
/nvme/0/vjawa/conda/envs/cudf_15_june_25/lib/python3.7/site-packages/dask/dataframe/core.py:6177: UserWarning: Insufficient elements for `head`. 5 elements requested, only 3 elements available. Try passing larger `npartitions` to `head`.
  warnings.warn(msg.format(n, len(r)))
       a
index   
0      1
1      2
2      3
```
```python
>>> df = cudf.read_parquet('test_parquet/part.0.parquet')
>>> df
   index  a
0      0  1
1      1  2
2      2  3
```

**Environment overview (please complete the following information)**
 - Method of cuDF install: [conda]

**Environment details**
```python3
# packages in environment at /nvme/0/vjawa/conda/envs/cudf_15_june_25:
cudf                      0.15.0a200625   py37_gf52f04291_1773    rapidsai-nightly
dask-cudf                 0.15.0a200625   py37_gf52f04291_1773    rapidsai-nightly
libcudf                   0.15.0a200625   cuda10.2_gf52f04291_1773    rapidsai-nightly
(cudf_15_june_25) vjawa@dt01:/nvme/0/vjawa$ conda list | grep dask
dask                      2.19.0                     py_0    conda-forge
dask-core                 2.19.0                     py_0    conda-forge
dask-cudf                 0.15.0a200625   py37_gf52f04291_1773    rapidsai-nightly
```

**Comment by VibhuJawa** [comment]
CC: @rjzamora

**Comment by rjzamora** [comment]
Sorry about this @VibhuJawa - We merged aligned changes in cudf and dask in the same day, so the latest cudf won't work with 2.19.0.

**Comment by VibhuJawa** [comment]
> Sorry about this @VibhuJawa - We merged aligned changes in cudf and dask in the same day, so the latest cudf won't work with 2.19.0.

Thanks rick, can confirm moving to dask+master(Commit: g7138f470 ) fixes stuff. Closing the issue.
