### ISSUE TITLE
[BUG] cudf.concat() throws concatenating Categorical columns when ignore_index=True

### ISSUE THREAD

**Issue by trxcllnt** [rapidsai/cudf#5718]
**Describe the bug**
After https://github.com/rapidsai/cudf/pull/5649, `Frame._concat()` throws an error when one of the input frames has a categorical column, but the others do not.

**Steps/Code to reproduce bug**
```python
>>> import cudf
>>> df1 = cudf.DataFrame({'cat': cudf.Series(["one", "two"], dtype="category")})
>>> df2 = cudf.DataFrame({"c": [10, 11, 22, 33, 44, 100]}, index=[7, 8, 9, 10, 11, 20])
>>> cudf.concat([df1, df2], ignore_index=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ptaylor/dev/rapids/cudf/python/cudf/cudf/core/reshape.py", line 193, in concat
    objs, axis=axis, ignore_index=ignore_index, sort=sort
  File "/home/ptaylor/dev/rapids/compose/etc/conda/cuda_10.2/envs/rapids/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/ptaylor/dev/rapids/cudf/python/cudf/cudf/core/frame.py", line 281, in _concat
    cast_cols_to_common_dtypes(indices, columns, dtypes, categories)
  File "/home/ptaylor/dev/rapids/cudf/python/cudf/cudf/core/frame.py", line 191, in cast_cols_to_common_dtypes
    cols[idx]
AttributeError: 'StringColumn' object has no attribute 'cat'
```

**Expected behavior**
The dataframes are concatenated without issue.

**Additional context**
Removing these two lines fixes the issue and doesn't lead to other test failures: https://github.com/rapidsai/cudf/blob/ce826c57c8cafb7d78f33873ca8c0c030fa42087/python/cudf/cudf/core/frame.py#L258-L259

However when I try to add a DF with a CategoricalColumn to `test_concat.py::test_concat_empty_dataframes()`, pandas fills the expected categorical column with the value `-1`, but our CategoricalColumn writes `-1` into the _codes_, causing its values to report NaN, and failing the `assert_eq` on line 516 here: https://github.com/rapidsai/cudf/blob/ce826c57c8cafb7d78f33873ca8c0c030fa42087/python/cudf/cudf/tests/test_concat.py#L507-L520
```
E   DataFrame.iloc[:, 0] (column name="cat") values are different (80.0 %)
E   [left]:  [one, two, -1, -1, -1, -1, -1, -1, -1, -1]
E   [right]: [one, two, nan, nan, nan, nan, nan, nan, nan, nan]
```

**Comment by trxcllnt** [comment]
cc: @galipremsagar
