### ISSUE TITLE
[BUG] dask_cudf.read_parquet can't read specific file, or list of files

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#5783]
```
import pandas as pd
import dask.dataframe as dd
import dask_cudf

pd.DataFrame({'a': [0]}).to_parquet('test/0.parquet')
pd.DataFrame({'a': [1]}).to_parquet('test/1.parquet')

dd.read_parquet('test/0.parquet').head()
```
Output:
```
	a
0	0
```

Now, trying to read a single Parquet file:
```
dask_cudf.read_parquet('test/0.parquet').head()
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rgelhausen/conda/envs/new/lib/python3.7/site-packages/dask/dataframe/core.py", line 1005, in head
    return self._head(n=n, npartitions=npartitions, compute=compute, safe=True)
  File "/home/rgelhausen/conda/envs/new/lib/python3.7/site-packages/dask/dataframe/core.py", line 1038, in _head
    result = result.compute()
  File "/home/rgelhausen/conda/envs/new/lib/python3.7/site-packages/dask/base.py", line 167, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/rgelhausen/conda/envs/new/lib/python3.7/site-packages/dask/base.py", line 447, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/rgelhausen/conda/envs/new/lib/python3.7/site-packages/dask/local.py", line 527, in get_sync
    return get_async(apply_sync, 1, dsk, keys, **kwargs)
  File "/home/rgelhausen/conda/envs/new/lib/python3.7/site-packages/dask/local.py", line 471, in get_async
    fire_task()
  File "/home/rgelhausen/conda/envs/new/lib/python3.7/site-packages/dask/local.py", line 466, in fire_task
    callback=queue.put,
  File "/home/rgelhausen/conda/envs/new/lib/python3.7/site-packages/dask/local.py", line 516, in apply_sync
    res = func(*args, **kwds)
  File "/home/rgelhausen/conda/envs/new/lib/python3.7/site-packages/dask/local.py", line 227, in execute_task
    result = pack_exception(e, dumps)
  File "/home/rgelhausen/conda/envs/new/lib/python3.7/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/home/rgelhausen/conda/envs/new/lib/python3.7/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/rgelhausen/conda/envs/new/lib/python3.7/site-packages/dask/core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/rgelhausen/conda/envs/new/lib/python3.7/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/rgelhausen/conda/envs/new/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py", line 276, in read_parquet_part
    dfs = [func(fs, rg, columns.copy(), index, **kwargs) for rg in part]
  File "/home/rgelhausen/conda/envs/new/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py", line 276, in <listcomp>
    dfs = [func(fs, rg, columns.copy(), index, **kwargs) for rg in part]
  File "/home/rgelhausen/conda/envs/new/lib/python3.7/site-packages/dask_cudf/io/parquet.py", line 73, in read_partition
    if len(partition_keys) > 0:
TypeError: object of type 'NoneType' has no len()
```

I get the same error if I pass a list of filenames.

**Comment by quasiben** [comment]
@randerzander is the fix here doing something like:

```python
if partition_keys is None:
    return df
```

if so, happy to submit a PR for the fix

**Comment by quasiben** [comment]
cc @rjzamora

**Comment by rjzamora** [comment]
This should have been fixed by #5775 - Arre you on the latest version of cudf?

**Comment by quasiben** [comment]
I was not.  @randerzander do you want to test with latest and close if it's resolved ?

**Comment by randerzander** [comment]
@rjzamora my bad. I tried recreating my env shortly after your PR merged, probably before the conda packages got updated.

After trying again this afternoon, this issue is resolved. Thanks!
