### ISSUE TITLE
[QST] Setting include search path for jitify/nvrtc with cuDF built from source

### ISSUE THREAD

**Issue by aadamson** [rapidsai/cudf#5847]
**What is your question?**

I'm trying to build cuDF from source. The build seems to have succeeded fine (I can import cudf; I can create and inspect dataframes). However, when I try to do any operation that requires JIT compiling a kernel, I run into compilation errors that seem to indicate that nvrtc/jitify can't find the libcudacxx (particularly simt) headers.

Running
```python
import cudf

s1 = cudf.Series([1,2,3,None,4])
s2 = cudf.Series([1,2,3,None,4])
print(s1)
print(s1 + s2)
print(s1 * s2)
```
fails with
```
0       1
1       2
2       3
3    null
4       4
dtype: int64
---------------------------------------------------
--- JIT compile log for  ---
---------------------------------------------------
cudf/wrappers/timestamps.hpp(35): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(35): error: expected a ";"

cudf/wrappers/timestamps.hpp(38): error: not a class or struct name

cudf/wrappers/timestamps.hpp(64): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(64): error: too many arguments for class template "cudf::detail::timestamp"

cudf/wrappers/timestamps.hpp(64): error: expected a ";"

cudf/wrappers/timestamps.hpp(69): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(69): error: too many arguments for class template "cudf::detail::timestamp"

cudf/wrappers/timestamps.hpp(69): error: expected a ";"

cudf/wrappers/timestamps.hpp(74): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(74): error: too many arguments for class template "cudf::detail::timestamp"

cudf/wrappers/timestamps.hpp(74): error: expected a ";"

cudf/wrappers/timestamps.hpp(79): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(79): error: too many arguments for class template "cudf::detail::timestamp"

cudf/wrappers/timestamps.hpp(79): error: expected a ";"

cudf/wrappers/timestamps.hpp(84): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(84): error: too many arguments for class template "cudf::detail::timestamp"

cudf/wrappers/timestamps.hpp(84): error: expected a ";"

cudf/wrappers/timestamps.hpp(86): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(87): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(88): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(89): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(90): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(118): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(118): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(118): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(119): error: class "std::numeric_limits<cudf::timestamp_D>" has already been defined

cudf/wrappers/timestamps.hpp(119): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(119): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(119): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(120): error: class "std::numeric_limits<cudf::timestamp_D>" has already been defined

cudf/wrappers/timestamps.hpp(120): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(120): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(120): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(121): error: class "std::numeric_limits<cudf::timestamp_D>" has already been defined

cudf/wrappers/timestamps.hpp(121): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(121): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(121): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(122): error: class "std::numeric_limits<cudf::timestamp_D>" has already been defined

cudf/wrappers/timestamps.hpp(122): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(122): error: name followed by "::" must be a class or namespace name

cudf/wrappers/timestamps.hpp(122): error: name followed by "::" must be a class or namespace name

traits.h(9): error: name followed by "::" must be a class or namespace name

traits.h(9): error: the global scope has no "value"

traits.h(13): error: name followed by "::" must be a class or namespace name

traits.h(13): error: the global scope has no "value"

traits.h(22): error: name followed by "::" must be a class or namespace name

traits.h(22): error: expected a ";"

operation.h(7): error: name followed by "::" must be a class or namespace name

operation.h(99): error: common_type is not a template

type_traits(9): error: class "__jitify_type_traits_ns::enable_if<<error-constant>, void>" has no member "type"
          detected during instantiation of type "__jitify_type_traits_ns::enable_if_t<<error-constant>, void>" 
operation.h(99): here

operation.h(108): error: common_type is not a template

type_traits(9): error: class "__jitify_type_traits_ns::enable_if<false, void>" has no member "type"
          detected during instantiation of type "__jitify_type_traits_ns::enable_if_t<false, void>" 
operation.h(108): here

operation.h(109): error: invalid redeclaration of member function template "TypeOut Mod::operate<TypeOut,TypeLhs,TypeRhs,<unnamed>>(TypeLhs, TypeRhs)"
(100): here

operation.h(116): error: common_type is not a template

operation.h(117): error: invalid redeclaration of member function template "TypeOut Mod::operate<TypeOut,TypeLhs,TypeRhs,<unnamed>>(TypeLhs, TypeRhs)"
(100): here

operation.h(126): error: common_type is not a template

operation.h(135): error: common_type is not a template

operation.h(136): error: invalid redeclaration of member function template "TypeOut RMod::operate<TypeOut,TypeLhs,TypeRhs,<unnamed>>(TypeLhs, TypeRhs)"
(127): here

operation.h(143): error: common_type is not a template

operation.h(144): error: invalid redeclaration of member function template "TypeOut RMod::operate<TypeOut,TypeLhs,TypeRhs,<unnamed>>(TypeLhs, TypeRhs)"
(127): here

operation.h(465): error: name followed by "::" must be a class or namespace name

operation.h(465): error: too many arguments for variable template "is_integral_v"

operation.h(465): error: expected an expression

operation.h(478): error: name followed by "::" must be a class or namespace name

operation.h(478): error: too many arguments for variable template "is_integral_v"

operation.h(478): error: expected an expression

operation.h(479): error: invalid redeclaration of member function template "TypeOut PMod::operate<TypeOut,TypeLhs,TypeRhs,<unnamed>>(TypeLhs, TypeRhs)"
(466): here

68 errors detected in this compilation.

---------------------------------------------------
Traceback (most recent call last):
  File "cudf_test.py", line 6, in <module>
    print(s1 + s2)
  File ".../python3.6/cudf/core/series.py", line 1022, in __add__
    return self._binaryop(other, "add")
  File ".../python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File ".../python3.6/cudf/core/series.py", line 1002, in _binaryop
    outcol = lhs._column.binary_operator(fn, rhs, reflect=reflect)
  File ".../python3.6/cudf/core/column/numerical.py", line 95, in binary_operator
    lhs=self, rhs=rhs, op=binop, out_dtype=out_dtype, reflect=reflect
  File ".../python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File ".../python3.6/cudf/core/column/numerical.py", line 434, in _numeric_column_binop
    out = libcudf.binaryop.binaryop(lhs, rhs, op, out_dtype)
  File "cudf/_lib/binaryop.pyx", line 202, in cudf._lib.binaryop.binaryop
  File "cudf/_lib/binaryop.pyx", line 106, in cudf._lib.binaryop.binaryop_v_v
RuntimeError: Runtime compilation failed
```

strace seems to indicate that nvrtc/jitify is only looking for simt/chrono.h in the current working directory and /usr/include. Is this expected behavior, or have I made a mistake during the build?

Is there an environment variable that I can provide to change the search path, or some location in either cudf or jitify that I can patch to accommodate other search paths?

**Comment by kkraus14** [comment]
@aadamson How did you build / install libcudf from source? IIRC we vendor the `libcudacxx` / `libcxx` bits into the libcudf includes via cmake and install them alongside the libcudf includes and expect to find them there.

**Comment by kkraus14** [comment]
Closing as no response.
