### ISSUE TITLE
[BUG] cudf.read_csv(s3_path) fails with "TypeError: 'coroutine' object is not subscriptable"

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#6088]
Code:
```
import cudf
df = cudf.read_csv(s3_path)
```

Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/rapids/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/io/csv.py", line 52, in read_csv
    **kwargs,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/utils/ioutils.py", line 983, in get_filepath_or_buffer
    with fs.open(paths[0]) as f:
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/spec.py", line 844, in open
    **kwargs
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 394, in _open
    autocommit=autocommit, requester_pays=requester_pays)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 1276, in __init__
    cache_type=cache_type)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/spec.py", line 1134, in __init__
    self.details = fs.info(path)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 719, in info
    return sync(self.loop, self._info, path, bucket, key, kwargs, version_id)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/asyn.py", line 51, in sync
    raise exc.with_traceback(tb)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/fsspec/asyn.py", line 35, in f
    result[0] = await future
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 660, in _info
    Key=key, **version_id_kw(version_id), **self.req_kw)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 214, in _call_s3
    raise translate_boto_error(err)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/s3fs/core.py", line 207, in _call_s3
    return await method(**additional_kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/aiobotocore/client.py", line 121, in _make_api_call
    operation_model, request_dict, request_context)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/aiobotocore/client.py", line 140, in _make_request
    return await self._endpoint.make_request(operation_model, request_dict)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/aiobotocore/endpoint.py", line 90, in _send_request
    exception):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/aiobotocore/endpoint.py", line 199, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/aiobotocore/hooks.py", line 29, in _emit
    response = handler(**kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/botocore/utils.py", line 1214, in redirect_from_error
    new_region = self.get_bucket_region(bucket, response)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/botocore/utils.py", line 1272, in get_bucket_region
    headers = response['ResponseMetadata']['HTTPHeaders']
TypeError: 'coroutine' object is not subscriptable
```

I wasn't seeing this error until a couple of days ago, not sure what changed. 

I am using this docker container: `FROM rapidsai/rapidsai-nightly:0.15-cuda10.2-base-ubuntu18.04`. And the only command I ran was installing s3fs via `conda install -c conda-forge s3fs`.

**Comment by kkraus14** [comment]
Connected offline and this is an issue with `fsspec` and the latest version of `s3fs`. Closing this issue as @chinmaychandak is going to open an issue on the upstream fsspec repo.
