### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dmitra79** [rapidsai/cudf#6455]
**Describe the bug**
I get an error trying to import cudf:

**Steps/Code to reproduce bug**
```
>>> import cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/z0022z7b/anaconda3/envs/mindsynchro/lib/python3.7/site-packages/cudf/__init__.py", line 7, in <module>
    from cudf import core, datasets
  File "/home/z0022z7b/anaconda3/envs/mindsynchro/lib/python3.7/site-packages/cudf/core/__init__.py", line 3, in <module>
    from cudf.core import buffer, column
  File "/home/z0022z7b/anaconda3/envs/mindsynchro/lib/python3.7/site-packages/cudf/core/column/__init__.py", line 1, in <module>
    from cudf.core.column.categorical import CategoricalColumn  # noqa: F401
  File "/home/z0022z7b/anaconda3/envs/mindsynchro/lib/python3.7/site-packages/cudf/core/column/categorical.py", line 11, in <module>
    import cudf._libxx as libcudfxx
  File "/home/z0022z7b/anaconda3/envs/mindsynchro/lib/python3.7/site-packages/cudf/_libxx/__init__.py", line 5, in <module>
    from . import (
  File "cudf/_libxx/aggregation.pxd", line 9, in init cudf._libxx.reduce
  File "cudf/_libxx/aggregation.pyx", line 11, in init cudf._libxx.aggregation
  File "/home/z0022z7b/anaconda3/envs/mindsynchro/lib/python3.7/site-packages/cudf/utils/cudautils.py", line 7, in <module>
    from numba import cuda, numpy_support
ImportError: cannot import name 'numpy_support' from 'numba' (/home/z0022z7b/anaconda3/envs/mindsynchro/lib/python3.7/site-packages/numba/__init__.py)
```

**Environment overview (please complete the following information)**
cudf installed with conda: conda install -c rapidsai -c nvidia -c numba -c conda-forge cudf=0.13 python=3.7 cudatoolkit=10.1
Environment: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-45-generic x86_64)

**Environment details**
<details><summary>Click here to see environment details</summary><pre>

     **git***
     Not inside a git repository

     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
     NAME="Ubuntu"
     VERSION="18.04.2 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.2 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux CTUSBAMIBI-GPU01 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

     ***GPU Information***
     Tue Oct  6 20:37:20 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Quadro RTX 6000     Off  | 00000000:1F:00.0 Off |                  Off |
     | 33%   31C    P0    61W / 260W |      0MiB / 24220MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Quadro RTX 6000     Off  | 00000000:20:00.0 Off |                  Off |
     | 33%   35C    P0    60W / 260W |      0MiB / 24220MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   2  Quadro RTX 6000     Off  | 00000000:23:00.0 Off |                  Off |
     | 32%   35C    P0    53W / 260W |      0MiB / 24220MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   3  Quadro RTX 6000     Off  | 00000000:24:00.0 Off |                  Off |
     | 32%   31C    P0     1W / 260W |      0MiB / 24220MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+

     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+

     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              40
     On-line CPU(s) list: 0-39
     Thread(s) per core:  2
     Core(s) per socket:  10
     Socket(s):           2
     NUMA node(s):        2
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               85
     Model name:          Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz
     Stepping:            7
     CPU MHz:             1000.498
     CPU max MHz:         2201.0000
     CPU min MHz:         1000.0000
     BogoMIPS:            4400.00
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            1024K
     L3 cache:            14080K
     NUMA node0 CPU(s):   0-9,20-29
     NUMA node1 CPU(s):   10-19,30-39
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni flush_l1d arch_capabilities

     ***CMake***

     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

     ***nvcc***

     ***Python***
     /home/z0022z7b/anaconda3/envs/mindsynchro/bin/python
     Python 3.7.9

     ***Environment Variables***
     PATH                            : /home/z0022z7b/anaconda3/envs/mindsynchro/bin:/home/z0022z7b/anaconda3/bin:/home/z0022z7b/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/z0022z7b/anaconda3/envs/mindsynchro
     PYTHON_PATH                     :

     ***conda packages***
     /home/z0022z7b/anaconda3/bin/conda
     # packages in environment at /home/z0022z7b/anaconda3/envs/mindsynchro:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     arrow-cpp                 0.15.0           py37h090bef1_2    conda-forge
     blas                      1.0                         mkl
     boost-cpp                 1.70.0               h7b93d67_3    conda-forge
     brotli                    1.0.9                he6710b0_0
     bzip2                     1.0.8                h7b6447c_0
     c-ares                    1.16.1               h7b6447c_0
     ca-certificates           2020.7.22                     0
     certifi                   2020.6.20                py37_0
     cudatoolkit               10.1.243             h6bb024c_0    nvidia
     cudf                      0.13.0                   py37_0    rapidsai
     cudnn                     7.6.5                cuda10.1_0
     cupy                      7.8.0            py37h0632833_1    conda-forge
     dlpack                    0.3                  he6710b0_1
     double-conversion         3.1.5                he6710b0_1
     fastavro                  1.0.0.post1      py37h7b6447c_0
     fastparquet               0.3.2            py37heb32a55_0
     fastrlock                 0.5              py37he6710b0_0
     fsspec                    0.6.3                      py_0    conda-forge
     gflags                    2.2.2                he6710b0_0
     glog                      0.4.0                he6710b0_0
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     icu                       67.1                 he1b5a44_0    conda-forge
     intel-openmp              2020.2                      254
     ld_impl_linux-64          2.33.1               h53a641e_7
     libcudf                   0.13.0               cuda10.1_0    rapidsai
     libedit                   3.1.20191231         h14c3975_1
     libevent                  2.1.10               hcdb4288_2    conda-forge
     libffi                    3.3                  he6710b0_2
     libgcc-ng                 9.1.0                hdf63c60_0
     libllvm10                 10.0.1               hbcb73fb_5
     libnvstrings              0.13.0               cuda10.1_0    rapidsai
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librmm                    0.13.0               cuda10.1_0    rapidsai
     libstdcxx-ng              9.1.0                hdf63c60_0
     llvmlite                  0.34.0           py37h269e1b5_4
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     mkl                       2020.2                      256
     mkl-service               2.3.0            py37he904b0f_0
     mkl_fft                   1.2.0            py37h23d657b_0
     mkl_random                1.1.1            py37h0573a6f_0
     nccl                      2.4.6.1              cuda10.1_0    nvidia
     ncurses                   6.2                  he6710b0_1
     numba                     0.51.2           py37h04863e7_1
     numpy                     1.19.1           py37hbc911f0_0
     numpy-base                1.19.1           py37hfa32c7d_0
     nvstrings                 0.13.0                   py37_0    rapidsai
     openssl                   1.1.1h               h7b6447c_0
     pandas                    0.25.3           py37hb3f55d8_0    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     pip                       20.2.3                   py37_0
     pyarrow                   0.15.0           py37h8b68381_1    conda-forge
     python                    3.7.9                h7579374_0
     python-dateutil           2.8.1                      py_0
     python-snappy             0.5.4            py37he6710b0_0
     python_abi                3.7                     1_cp37m    conda-forge
     pytz                      2020.1                     py_0
     re2                       2019.08.01           he6710b0_0
     readline                  8.0                  h7b6447c_0
     rmm                       0.13.0                   py37_0    rapidsai
     setuptools                50.3.0           py37hb0f4dca_1
     six                       1.15.0                     py_0
     snappy                    1.1.8                he6710b0_0
     sqlite                    3.33.0               h62c20be_0
     tbb                       2020.3               hfd86e86_0
     thrift                    0.13.0           py37he6710b0_0
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.10               hbc83047_0
     uriparser                 0.9.3                he6710b0_1
     wheel                     0.35.1                     py_0
     xz                        5.2.5                h7b6447c_0
     zlib                      1.2.11               h7b6447c_3
     zstd                      1.4.4                h3b9ef0a_2    conda-forge

</pre></details>

**Comment by dmitra79** [comment]
Apparently cudf=0.13 is not compatible with latest Numba. Upgraded to cudf=0.15 which fixed the problem
