### ISSUE TITLE
[FEA] Support constructing `datetime64[ms]` series with `pd.NaT`

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cudf#6456]
**Is your feature request related to a problem? Please describe.**
Currently when I construct a datetime series with `pandas.NaT`:

```python
import cudf as gd
import pandas as pd
gd.Series(["2020-05-01 08:00:00", pd.NaT], dtype="<M8[ms]")
```

It throws:
```
Traceback (most recent call last):
  File "/home/wangm/dev/rapids/cudf/python/cudf/cudf/core/column/column.py", line 1772, in as_column
    memoryview(arbitrary), dtype=dtype, nan_as_null=nan_as_null
TypeError: memoryview: a bytes-like object is required, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wangm/dev/rapids/cudf/python/cudf/cudf/core/column/column.py", line 1801, in as_column
    else nan_as_null,
  File "pyarrow/array.pxi", line 269, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 38, in pyarrow.lib._sequence_to_array
TypeError: an integer is required (got type str)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wangm/dev/rapids/cudf/python/cudf/cudf/core/series.py", line 188, in __init__
    data = column.as_column(data, nan_as_null=nan_as_null, dtype=dtype)
  File "/home/wangm/dev/rapids/cudf/python/cudf/cudf/core/column/column.py", line 1823, in as_column
    else np.dtype(native_dtype),
  File "/home/wangm/dev/rapids/compose/etc/conda/cuda_10.2/envs/rapids/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: cannot convert float NaN to integer
```

**Describe the solution you'd like**
`cudf.Series` constructor works with null values, which match with pandas behavior.

**Describe alternatives you've considered**
```python
gd.Series(["2020-05-01 08:00:00", None], dtype="<M8[ms]")
```

**Additional context**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit 305f1dc6935c5257c018e129dfbc17c90739b647 (HEAD -> i6129, origin/i6129)
     Author: Michael Wang <michelwang0905@icloud.com>
     Date:   Tue Oct 6 20:37:17 2020 -0700
     
     changelog
     **git submodules***
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
     NAME="Ubuntu"
     VERSION="18.04.5 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.5 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux wangm-ws 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Tue Oct  6 20:57:30 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 450.66       Driver Version: 450.66       CUDA Version: 11.0     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  Quadro RTX 8000     Off  | 00000000:15:00.0 Off |                  Off |
     | 33%   40C    P8    28W / 260W |    592MiB / 48601MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              12
     On-line CPU(s) list: 0-11
     Thread(s) per core:  2
     Core(s) per socket:  6
     Socket(s):           1
     NUMA node(s):        1
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               85
     Model name:          Intel(R) Xeon(R) Gold 6128 CPU @ 3.40GHz
     Stepping:            4
     CPU MHz:             1270.621
     CPU max MHz:         3700.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            6800.00
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            1024K
     L3 cache:            19712K
     NUMA node0 CPU(s):   0-11
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke md_clear flush_l1d
     
     ***CMake***
     /home/wangm/dev/rapids/compose/etc/conda/cuda_10.2/envs/rapids/bin/cmake
     cmake version 3.17.0
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/local/bin/g++
     g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2019 NVIDIA Corporation
     Built on Wed_Oct_23_19:24:38_PDT_2019
     Cuda compilation tools, release 10.2, V10.2.89
     
     ***Python***
     /home/wangm/dev/rapids/compose/etc/conda/cuda_10.2/envs/rapids/bin/python
     Python 3.7.8
     
     ***Environment Variables***
     PATH                            : /home/wangm/dev/rapids/compose/etc/conda/cuda_10.2/envs/rapids/bin:/home/wangm/dev/rapids/compose/etc/conda/cuda_10.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/cuda-10.2/bin
     LD_LIBRARY_PATH                 : /home/wangm/dev/rapids/compose/etc/conda/cuda_10.2/envs/rapids/lib:/home/wangm/dev/rapids/compose/etc/conda/cuda_10.2/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda-10.2/lib64:/usr/local/lib:/home/wangm/dev/rapids/rmm/build/release:/home/wangm/dev/rapids/cudf/cpp/build/release:/home/wangm/dev/rapids/cudf/cpp/build/release:/home/wangm/dev/rapids/cuml/cpp/build/release:/home/wangm/dev/rapids/cugraph/cpp/build/release:/home/wangm/dev/rapids/cuspatial/cpp/build/release
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/wangm/dev/rapids/compose/etc/conda/cuda_10.2/envs/rapids
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/wangm/dev/rapids/compose/etc/conda/cuda_10.2/bin/conda
     # packages in environment at /home/wangm/dev/rapids/compose/etc/conda/cuda_10.2/envs/rapids:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       1_gnu    conda-forge
     abseil-cpp                20200225.2           he1b5a44_2    conda-forge
     alabaster                 0.7.12                     py_0    conda-forge
     apipkg                    1.5                      pypi_0    pypi
     appdirs                   1.4.3                      py_1    conda-forge
     argon2-cffi               20.1.0           py37h8f50634_1    conda-forge
     arrow-cpp                 1.0.1           py37hba6904a_7_cuda    conda-forge
     arrow-cpp-proc            1.0.1                      cuda    conda-forge
     asvdb                     0.4.1               gd6cd8f2_36    rapidsai
     async_generator           1.10                       py_0    conda-forge
     attrs                     20.2.0             pyh9f0ad1d_0    conda-forge
     aws-c-common              0.4.57               he1b5a44_1    conda-forge
     aws-c-event-stream        0.1.6                h72b8ae1_3    conda-forge
     aws-checksums             0.1.9                h346380f_0    conda-forge
     aws-sdk-cpp               1.8.54               h69f4914_0    conda-forge
     babel                     2.8.0                      py_0    conda-forge
     backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
     backports                 1.0                        py_2    conda-forge
     backports.functools_lru_cache 1.6.1                      py_0    conda-forge
     black                     19.10b0                  py37_0    conda-forge
     bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
     bokeh                     2.2.1            py37hc8dfbb8_0    conda-forge
     boost                     1.74.0           py37h429e714_0    conda-forge
     boost-cpp                 1.74.0               h9359b55_0    conda-forge
     boto3                     1.15.11            pyh9f0ad1d_0    conda-forge
     botocore                  1.18.11            pyh9f0ad1d_0    conda-forge
     brotli                    1.0.9                he1b5a44_0    conda-forge
     brotlipy                  0.7.0           py37h516909a_1000    conda-forge
     bzip2                     1.0.8                h516909a_3    conda-forge
     c-ares                    1.16.1               h516909a_3    conda-forge
     ca-certificates           2020.6.20            hecda079_0    conda-forge
     cairo                     1.16.0            h3fc0475_1005    conda-forge
     certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
     cffi                      1.14.3           py37h2b28604_0    conda-forge
     cfgv                      3.2.0                      py_0    conda-forge
     cfitsio                   3.470                hce51eda_6    conda-forge
     chardet                   3.0.4           py37hc8dfbb8_1007    conda-forge
     clang                     8.0.1                hc9558a2_2    conda-forge
     clang-tools               8.0.1                hc9558a2_2    conda-forge
     clangxx                   8.0.1                         2    conda-forge
     click                     7.1.2              pyh9f0ad1d_0    conda-forge
     click-plugins             1.1.1                      py_0    conda-forge
     cligj                     0.5.0                      py_0    conda-forge
     cloudpickle               1.6.0                      py_0    conda-forge
     cmake                     3.17.0               h28c56e5_0    conda-forge
     cmake_setuptools          0.1.3                      py_0    rapidsai
     commonmark                0.9.1                      py_0    conda-forge
     cryptography              3.1.1            py37hb09aad4_0    conda-forge
     cudatoolkit               10.2.89              h6bb024c_0    nvidia
     cudnn                     7.6.5                cuda10.2_0
     cupy                      7.8.0            py37h940342b_1    conda-forge
     curl                      7.71.1               he644dc0_8    conda-forge
     cython                    0.29.21          py37h3340039_0    conda-forge
     cytoolz                   0.11.0           py37h8f50634_0    conda-forge
     dask                      2.29.0                     py_0    conda-forge
     dask-core                 2.29.0                     py_0    conda-forge
     dask-cuda                 0.16.0a201002           py37_93    rapidsai-nightly
     dask-glm                  0.2.0                      py_1    conda-forge
     dask-ml                   1.7.0                      py_0    conda-forge
     decorator                 4.4.2                      py_0    conda-forge
     defusedxml                0.6.0                      py_0    conda-forge
     distlib                   0.3.1              pyh9f0ad1d_0    conda-forge
     distributed               2.29.0           py37hc8dfbb8_0    conda-forge
     dlpack                    0.3                  he1b5a44_1    conda-forge
     docutils                  0.16             py37hc8dfbb8_1    conda-forge
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     doxygen                   1.8.20               h0e019cf_0    conda-forge
     editdistance              0.5.3            py37h3340039_1    conda-forge
     entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
     execnet                   1.7.1                    pypi_0    pypi
     expat                     2.2.9                he1b5a44_2    conda-forge
     faiss-proc                1.0.0                      cuda    rapidsai-nightly
     fastavro                  1.0.0.post1      py37h8f50634_0    conda-forge
     fastrlock                 0.5              py37h3340039_0    conda-forge
     filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
     fiona                     1.8.17           py37ha3d844c_0    conda-forge
     flake8                    3.8.3                      py_1    conda-forge
     flatbuffers               1.12.0               he1b5a44_0    conda-forge
     fontconfig                2.13.1            h1056068_1002    conda-forge
     freetype                  2.10.2               he06d7ca_0    conda-forge
     freexl                    1.0.5             h516909a_1002    conda-forge
     fsspec                    0.8.3                      py_0    conda-forge
     future                    0.18.2           py37hc8dfbb8_1    conda-forge
     gdal                      3.1.2            py37h518339e_1    conda-forge
     geopandas                 0.7.0                      py_1    conda-forge
     geos                      3.8.1                he1b5a44_0    conda-forge
     geotiff                   1.6.0                ha04d9d0_1    conda-forge
     gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     giflib                    5.2.1                h516909a_2    conda-forge
     glib                      2.66.1               h680cd38_0    conda-forge
     glog                      0.4.0                h49b9bf7_3    conda-forge
     gmp                       6.2.0                he1b5a44_2    conda-forge
     grpc-cpp                  1.30.2               heedbac9_0    conda-forge
     hdf4                      4.2.13            hf30be14_1003    conda-forge
     hdf5                      1.10.6          nompi_h3c11f04_101    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     hypothesis                5.28.0                     py_0    conda-forge
     icu                       67.1                 he1b5a44_0    conda-forge
     identify                  1.5.5              pyh9f0ad1d_0    conda-forge
     idna                      2.10               pyh9f0ad1d_0    conda-forge
     imagesize                 1.2.0                      py_0    conda-forge
     importlib-metadata        1.7.0            py37hc8dfbb8_0    conda-forge
     importlib_metadata        1.7.0                         0    conda-forge
     iniconfig                 1.0.1              pyh9f0ad1d_0    conda-forge
     ipykernel                 5.3.4            py37h43977f1_0    conda-forge
     ipython                   7.18.1           py37hc6149b9_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     isort                     5.0.7            py37hc8dfbb8_0    conda-forge
     jedi                      0.17.2           py37hc8dfbb8_0    conda-forge
     jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
     jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
     joblib                    0.17.0                     py_0    conda-forge
     jpeg                      9d                   h516909a_0    conda-forge
     json-c                    0.13.1            hbfbb72e_1002    conda-forge
     jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
     jupyter_client            6.1.7                      py_0    conda-forge
     jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
     jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
     kealib                    1.4.13               h33137a7_1    conda-forge
     krb5                      1.17.1               hfafb76e_3    conda-forge
     lcms2                     2.11                 hbd6801e_0    conda-forge
     ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
     libblas                   3.8.0               17_openblas    conda-forge
     libcblas                  3.8.0               17_openblas    conda-forge
     libcumlprims              0.16.0a200930   cuda10.2_g1c28023_35    rapidsai-nightly
     libcurl                   7.71.1               hcdd3856_8    conda-forge
     libcypher-parser          0.6.2                         1    rapidsai
     libdap4                   3.20.6               h1d1bd15_1    conda-forge
     libedit                   3.1.20191231         he28a2e2_2    conda-forge
     libev                     4.33                 h516909a_1    conda-forge
     libevent                  2.1.10               hcdb4288_2    conda-forge
     libfaiss                  1.6.3           he61ee18_1_cuda    conda-forge
     libffi                    3.2.1             he1b5a44_1007    conda-forge
     libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
     libgdal                   3.1.2                hb2a6f5f_1    conda-forge
     libgfortran-ng            7.5.0               hae1eefd_17    conda-forge
     libgfortran4              7.5.0               hae1eefd_17    conda-forge
     libgomp                   9.3.0               h5dbcf3e_17    conda-forge
     libhwloc                  2.3.0                h3c4fd83_0    conda-forge
     libiconv                  1.16                 h516909a_0    conda-forge
     libkml                    1.3.0             h74f7ee3_1012    conda-forge
     liblapack                 3.8.0               17_openblas    conda-forge
     libllvm10                 10.0.1               he513fc3_3    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libnetcdf                 4.7.4           nompi_h84807e1_105    conda-forge
     libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
     libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
     libpng                    1.6.37               hed695b0_2    conda-forge
     libpq                     12.3                 h5513abc_0    conda-forge
     libprotobuf               3.12.4               h8b12597_0    conda-forge
     librmm                    0.16.0a201002   cuda10.2_g273f92d_397    rapidsai-nightly
     libsodium                 1.0.18               h516909a_1    conda-forge
     libspatialindex           1.9.3                he1b5a44_3    conda-forge
     libspatialite             4.3.0a            h57f1b35_1039    conda-forge
     libssh2                   1.9.0                hab1572f_5    conda-forge
     libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
     libthrift                 0.13.0               hbe8ec66_6    conda-forge
     libtiff                   4.1.0                hc7e4089_6    conda-forge
     libutf8proc               2.5.0                h516909a_2    conda-forge
     libuuid                   2.32.1            h14c3975_1000    conda-forge
     libuv                     1.40.0               h516909a_0    conda-forge
     libwebp-base              1.1.0                h516909a_3    conda-forge
     libxcb                    1.13              h14c3975_1002    conda-forge
     libxml2                   2.9.10               h68273f3_2    conda-forge
     llvmlite                  0.34.0           py37h5202443_1    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.9.2                he1b5a44_3    conda-forge
     markdown                  3.2.2                      py_0    conda-forge
     markupsafe                1.1.1            py37h8f50634_1    conda-forge
     mccabe                    0.6.1                      py_1    conda-forge
     mimesis                   4.0.0              pyh9f0ad1d_0    conda-forge
     mistune                   0.8.4           py37h8f50634_1001    conda-forge
     more-itertools            8.5.0                      py_0    conda-forge
     msgpack-python            1.0.0            py37h99015e2_1    conda-forge
     multipledispatch          0.6.0                      py_0    conda-forge
     munch                     2.5.0                      py_0    conda-forge
     mypy_extensions           0.4.3            py37hc8dfbb8_1    conda-forge
     nbclient                  0.5.0                      py_0    conda-forge
     nbconvert                 6.0.7            py37hc8dfbb8_0    conda-forge
     nbformat                  5.0.7                      py_0    conda-forge
     nbsphinx                  0.7.1              pyh9f0ad1d_0    conda-forge
     nccl                      2.7.8.1              hc6a2c23_0    conda-forge
     ncurses                   6.2                  he1b5a44_1    conda-forge
     nest-asyncio              1.4.1                      py_0    conda-forge
     networkx                  2.5                        py_0    conda-forge
     nodeenv                   1.5.0              pyh9f0ad1d_0    conda-forge
     notebook                  6.1.4            py37hc8dfbb8_0    conda-forge
     numba                     0.51.2           py37h9fdb41a_0    conda-forge
     numpy                     1.19.1           py37h7ea13bd_2    conda-forge
     numpydoc                  1.1.0                      py_1    conda-forge
     olefile                   0.46                       py_0    conda-forge
     openjpeg                  2.3.1                h981e76c_3    conda-forge
     openssl                   1.1.1h               h516909a_0    conda-forge
     packaging                 20.4               pyh9f0ad1d_0    conda-forge
     pandas                    1.1.2            py37h3340039_0    conda-forge
     pandoc                    1.19.2                        0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     parquet-cpp               1.5.1                         1    conda-forge
     parso                     0.7.1              pyh9f0ad1d_0    conda-forge
     partd                     1.1.0                      py_0    conda-forge
     pathspec                  0.8.0              pyh9f0ad1d_0    conda-forge
     pcre                      8.44                 he1b5a44_0    conda-forge
     pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
     pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
     pillow                    7.2.0            py37h718be6c_1    conda-forge
     pip                       20.2.3                     py_0    conda-forge
     pixman                    0.38.0            h516909a_1003    conda-forge
     pluggy                    0.13.1           py37hc8dfbb8_2    conda-forge
     poppler                   0.89.0               h4190859_1    conda-forge
     poppler-data              0.4.9                         0    conda-forge
     postgresql                12.3                 h8573dbc_0    conda-forge
     pre-commit                2.7.1            py37hc8dfbb8_0    conda-forge
     pre_commit                2.7.1                         0    conda-forge
     proj                      7.1.0                h966b41f_1    conda-forge
     prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
     prompt-toolkit            3.0.7                      py_0    conda-forge
     psutil                    5.7.2            py37h8f50634_0    conda-forge
     pthread-stubs             0.4               h14c3975_1001    conda-forge
     ptvsd                     4.3.2                    pypi_0    pypi
     ptyprocess                0.6.0                 py37_1000    conda-forge
     py                        1.9.0              pyh9f0ad1d_0    conda-forge
     py-cpuinfo                7.0.0              pyh9f0ad1d_0    conda-forge
     pyarrow                   1.0.1           py37h72578d1_7_cuda    conda-forge
     pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
     pycparser                 2.20               pyh9f0ad1d_2    conda-forge
     pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
     pygal                     2.4.0                      py_0    conda-forge
     pygments                  2.7.1                      py_0    conda-forge
     pynvml                    8.0.4                      py_1    conda-forge
     pyopenssl                 19.1.0                   py37_0    conda-forge
     pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
     pyproj                    2.6.1.post1      py37hb5dadc3_1    conda-forge
     pyrsistent                0.17.3           py37h8f50634_0    conda-forge
     pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
     pytest                    6.1.0            py37hc8dfbb8_0    conda-forge
     pytest-benchmark          3.2.3              pyh9f0ad1d_0    conda-forge
     pytest-forked             1.3.0                    pypi_0    pypi
     pytest-xdist              2.1.0                    pypi_0    pypi
     python                    3.7.8           h425cb1d_1_cpython    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     python-louvain            0.13                       py_0    conda-forge
     python_abi                3.7                     1_cp37m    conda-forge
     pytz                      2020.1             pyh9f0ad1d_0    conda-forge
     pyyaml                    5.3.1            py37h8f50634_0    conda-forge
     pyzmq                     19.0.2           py37hac76be4_0    conda-forge
     rapidjson                 1.1.0             hf484d3e_1002    conda-forge
     rapids-pytest-benchmark   0.0.13                     py_0    rapidsai
     re2                       2020.08.01           he1b5a44_1    conda-forge
     readline                  8.0                  he28a2e2_2    conda-forge
     recommonmark              0.6.0                      py_0    conda-forge
     regex                     2020.9.27        py37h8f50634_0    conda-forge
     requests                  2.24.0             pyh9f0ad1d_0    conda-forge
     rhash                     1.3.6             h14c3975_1001    conda-forge
     rtree                     0.9.4            py37h8526d28_1    conda-forge
     s3transfer                0.3.3            py37hc8dfbb8_1    conda-forge
     scikit-learn              0.23.1           py37h8a51577_0    conda-forge
     scipy                     1.5.2            py37hb14ef9d_0    conda-forge
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                49.6.0           py37hc8dfbb8_1    conda-forge
     shapely                   1.7.1            py37hedb1597_0    conda-forge
     six                       1.15.0             pyh9f0ad1d_0    conda-forge
     snappy                    1.1.8                he1b5a44_3    conda-forge
     snowballstemmer           2.0.0                      py_0    conda-forge
     sortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forge
     spdlog                    1.7.0                hc9558a2_2    conda-forge
     sphinx                    3.2.1                      py_0    conda-forge
     sphinx-copybutton         0.3.0              pyh9f0ad1d_0    conda-forge
     sphinx-markdown-tables    0.0.15                   pypi_0    pypi
     sphinx_rtd_theme          0.5.0              pyh9f0ad1d_0    conda-forge
     sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
     sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
     sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
     sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
     sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
     sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
     sphinxcontrib-websupport  1.2.4              pyh9f0ad1d_0    conda-forge
     sqlite                    3.33.0               h4cf870e_0    conda-forge
     streamz                   0.6.0                    pypi_0    pypi
     tbb                       2020.2               hc9558a2_0    conda-forge
     tblib                     1.6.0                      py_0    conda-forge
     terminado                 0.9.1            py37hc8dfbb8_0    conda-forge
     testpath                  0.4.4                      py_0    conda-forge
     threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
     tiledb                    2.0.8                h3effe38_1    conda-forge
     tk                        8.6.10               hed695b0_0    conda-forge
     toml                      0.10.1             pyh9f0ad1d_0    conda-forge
     toolz                     0.11.1                     py_0    conda-forge
     tornado                   6.0.4            py37h8f50634_1    conda-forge
     traitlets                 5.0.4                      py_1    conda-forge
     treelite                  0.92             py37h023e13c_2    conda-forge
     treelite-runtime          0.92                     pypi_0    pypi
     typed-ast                 1.4.1            py37h516909a_0    conda-forge
     typing_extensions         3.7.4.2                    py_0    conda-forge
     tzcode                    2020a                h516909a_0    conda-forge
     ucx                       1.8.1+g6b29558       ha5db111_0    rapidsai
     ucx-py                    0.16.0a201003   py37_g6b29558_183    rapidsai-nightly
     umap-learn                0.4.6            py37hc8dfbb8_0    conda-forge
     urllib3                   1.25.10                    py_0    conda-forge
     virtualenv                20.0.20          py37hc8dfbb8_1    conda-forge
     wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
     xerces-c                  3.2.3                hfe33f54_1    conda-forge
     xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
     xorg-libice               1.0.10               h516909a_0    conda-forge
     xorg-libsm                1.2.3             h84519dc_1000    conda-forge
     xorg-libx11               1.6.12               h516909a_0    conda-forge
     xorg-libxau               1.0.9                h14c3975_0    conda-forge
     xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
     xorg-libxext              1.3.4                h516909a_0    conda-forge
     xorg-libxrender           0.9.10            h516909a_1002    conda-forge
     xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
     xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
     xorg-xproto               7.0.31            h14c3975_1007    conda-forge
     xz                        5.2.5                h516909a_1    conda-forge
     yaml                      0.2.5                h516909a_0    conda-forge
     zeromq                    4.3.3                he1b5a44_1    conda-forge
     zict                      2.0.0                      py_0    conda-forge
     zipp                      3.3.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1009    conda-forge
     zstd                      1.4.5                h6597ccf_2    conda-forge
     
</pre></details>

**Comment by davidwendt** [comment]
The following works in case it helps:
```
gd.Series(["2020-05-01 08:00:00", None], dtype="<M8[ms]")
```

**Comment by isVoid** [comment]
Confirmed the issue still exists in 0.18.

**Comment by mroeschke** [comment]
This appears to work in 25.04, so closing

```python
In [14]: import cudf as gd
    ...: import pandas as pd
    ...: gd.Series(["2020-05-01 08:00:00", pd.NaT], dtype="<M8[ms]")
Out[14]: 
0    2020-05-01 08:00:00.000
1                        NaT
dtype: datetime64[ms]
```
