### ISSUE TITLE
[BUG] LocalCUDACluster -- NoneType has no attribute 'process'

### ISSUE THREAD

**Issue by drabastomek** [rapidsai/cudf#6467]
**Describe the bug**
When starting a `LocalCUDACluster` it throws `tornado.application` error.

Full stack:

```
tornado.application - ERROR - Exception in callback <bound method Nanny.memory_monitor of <Nanny: None, threads: 1>>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tornado/ioloop.py", line 907, in _run
    return self.callback()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/nanny.py", line 414, in memory_monitor
    process = self.process.process
AttributeError: 'NoneType' object has no attribute 'process'
```

**Steps/Code to reproduce bug**
```
from dask_cuda import LocalCUDACluster
cluster = LocalCUDACluster()
```

**Expected behavior**
`LocalCUDACluster()` should return the object without error.

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

```
docker pull rapidsai/rapidsai-nightly:cuda11.0-runtime-ubuntu18.04
docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 \
    rapidsai/rapidsai-nightly:cuda11.0-runtime-ubuntu18.04
```

**Comment by drabastomek** [comment]
Just checked and the issues is still present even if I use CUDA 10.2.

**Comment by kkraus14** [comment]
Moving this to the dask_cuda repo.
