### ISSUE TITLE
[BUG] `std::bad_alloc` in `libcudf.copying.table_slice`

### ISSUE THREAD

**Issue by pentschev** [rapidsai/cudf#6525]
I'm getting the following error in latest nightly:

```python
$ python dask_cuda/benchmarks/local_cudf_merge.py
Traceback (most recent call last):
  File "dask_cuda/benchmarks/local_cudf_merge.py", line 349, in <module>
    main(parse_args())
  File "dask_cuda/benchmarks/local_cudf_merge.py", line 216, in main
    took_list.append(run(client, args, n_workers, write_profile=None))
  File "dask_cuda/benchmarks/local_cudf_merge.py", line 162, in run
    ddf_base = get_random_ddf(
  File "dask_cuda/benchmarks/local_cudf_merge.py", line 122, in get_random_ddf
    ddf = new_dd_object(graph, name, meta, divisions)
  File "/datasets/pentschev/miniconda3/envs/rn-110-0.16.201014/lib/python3.8/site-packages/dask/dataframe/core.py", line 6321, in new_dd_object
    return get_parallel_type(meta)(dsk, name, meta, divisions)
  File "/datasets/pentschev/miniconda3/envs/rn-110-0.16.201014/lib/python3.8/site-packages/dask_cudf/core.py", line 81, in __init__
    meta = dd.core.make_meta(meta)
  File "/datasets/pentschev/miniconda3/envs/rn-110-0.16.201014/lib/python3.8/site-packages/dask/utils.py", line 505, in __call__
    return meth(arg, *args, **kwargs)
  File "/datasets/pentschev/miniconda3/envs/rn-110-0.16.201014/lib/python3.8/site-packages/dask_cudf/backends.py", line 115, in make_meta_cudf
    return x.head(0)
  File "/datasets/pentschev/miniconda3/envs/rn-110-0.16.201014/lib/python3.8/site-packages/cudf/core/dataframe.py", line 980, in head
    return self.iloc[:n]
  File "/datasets/pentschev/miniconda3/envs/rn-110-0.16.201014/lib/python3.8/site-packages/cudf/core/indexing.py", line 179, in __getitem__
    return self._getitem_tuple_arg(arg)
  File "/datasets/pentschev/miniconda3/envs/rn-110-0.16.201014/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/datasets/pentschev/miniconda3/envs/rn-110-0.16.201014/lib/python3.8/site-packages/cudf/core/indexing.py", line 413, in _getitem_tuple_arg
    df = columns_df._slice(arg[0])
  File "/datasets/pentschev/miniconda3/envs/rn-110-0.16.201014/lib/python3.8/site-packages/cudf/core/frame.py", line 565, in _slice
    libcudf.copying.table_slice(
  File "cudf/_lib/copying.pyx", line 347, in cudf._lib.copying.table_slice
  File "cudf/_lib/table.pyx", line 210, in cudf._lib.table.Table.data_view
  File "cudf/_lib/table.pyx", line 259, in cudf._lib.table.make_table_view
MemoryError: std::bad_alloc
```

This can be easily reproduced just by simply running https://github.com/rapidsai/dask-cuda/blob/branch-0.16/dask_cuda/benchmarks/local_cudf_merge.py with default arguments (see above). The same works on a conda environment I have from October 2nd.

Any ideas what could be the cause for this? Let me know if you need additional information.

**Comment by pentschev** [comment]
Yesterday's build also works, the following update is causing the issue, which points to a change from yesterday or today:

```
The following packages will be UPDATED:

  cudf               0.16.0a201013-cuda_11.0_py38_g06e4189~ --> 0.16.0a201014-cuda_11.0_py38_gc6dfa6e3ed_1977
  dask-cudf             0.16.0a201013-py38_gdd3eb62847_1976 --> 0.16.0a201014-py38_gc6dfa6e3ed_1977
```

**Comment by shwina** [comment]
@pentschev I'm unable to reproduce this on either branch 0.16 or branch 0.17. Any chance it could be a broken environment or something?

**Comment by kkraus14** [comment]
It looks like you'd be going from build `1975` --> `1977` of only cudf but not libcudf in the above which is a likely source of a broken environment.

**Comment by pentschev** [comment]
Any chance there's something wrong with our conda repo? If I try to build a new environment right now, conda is picking `1977` for `cudf` but `1975` for `libcudf`:

<details>

```
$ conda create -n rn-110-0.16.201014 -c rapidsai-nightly -c nvidia -c conda-forge -c defaults python=3.8 cudatoolkit=11.0 cudf=0.16 dask-cudf=0.16 dask-cuda=0.16
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.8.5

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /datasets/pentschev/miniconda3/envs/rn-110-0.16.201014

  added / updated specs:
    - cudatoolkit=11.0
    - cudf=0.16
    - dask-cuda=0.16
    - dask-cudf=0.16
    - python=3.8


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bokeh-2.2.2                |   py38h32f6830_0         7.0 MB  conda-forge
    dask-cuda-0.16.0a201014    |          py38_96          76 KB  rapidsai-nightly
    fsspec-0.8.4               |             py_0          65 KB  conda-forge
    llvmlite-0.34.0            |   py38h4f45e52_2         312 KB  conda-forge
    numba-0.51.2               |   py38hc5bc63f_0         3.7 MB  conda-forge
    pillow-8.0.0               |   py38h9776b28_0         686 KB  conda-forge
    typing_extensions-3.7.4.3  |             py_0          25 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        11.8 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  abseil-cpp         conda-forge/linux-64::abseil-cpp-20200225.2-he1b5a44_2
  arrow-cpp          conda-forge/linux-64::arrow-cpp-1.0.1-py38h179f8b4_13_cuda
  arrow-cpp-proc     conda-forge/linux-64::arrow-cpp-proc-1.0.1-cuda
  aws-c-common       conda-forge/linux-64::aws-c-common-0.4.59-he1b5a44_0
  aws-c-event-stream conda-forge/linux-64::aws-c-event-stream-0.1.6-h84e28f3_5
  aws-checksums      conda-forge/linux-64::aws-checksums-0.1.9-he252421_2
  aws-sdk-cpp        conda-forge/linux-64::aws-sdk-cpp-1.8.59-h9b98462_1
  bokeh              conda-forge/linux-64::bokeh-2.2.2-py38h32f6830_0
  boost-cpp          conda-forge/linux-64::boost-cpp-1.72.0-h9359b55_3
  brotli             conda-forge/linux-64::brotli-1.0.9-he1b5a44_2
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h516909a_3
  c-ares             conda-forge/linux-64::c-ares-1.16.1-h516909a_3
  ca-certificates    conda-forge/linux-64::ca-certificates-2020.6.20-hecda079_0
  certifi            conda-forge/linux-64::certifi-2020.6.20-py38h924ce5b_2
  click              conda-forge/noarch::click-7.1.2-pyh9f0ad1d_0
  cloudpickle        conda-forge/noarch::cloudpickle-1.6.0-py_0
  cudatoolkit        nvidia/linux-64::cudatoolkit-11.0.221-h6bb024c_0
  cudf               rapidsai-nightly/linux-64::cudf-0.16.0a201014-cuda_11.0_py38_gc6dfa6e3ed_1977
  cudnn              nvidia/linux-64::cudnn-8.0.0-cuda11.0_0
  cupy               rapidsai-nightly/linux-64::cupy-8.0.0-py38hb7c6141_0
  cytoolz            conda-forge/linux-64::cytoolz-0.11.0-py38h1e0a361_1
  dask               conda-forge/noarch::dask-2.30.0-py_0
  dask-core          conda-forge/noarch::dask-core-2.30.0-py_0
  dask-cuda          rapidsai-nightly/linux-64::dask-cuda-0.16.0a201014-py38_96
  dask-cudf          rapidsai-nightly/linux-64::dask-cudf-0.16.0a201014-py38_gc6dfa6e3ed_1977
  distributed        conda-forge/linux-64::distributed-2.30.0-py38h32f6830_1
  dlpack             conda-forge/linux-64::dlpack-0.3-he1b5a44_1
  fastavro           conda-forge/linux-64::fastavro-1.0.0.post1-py38h1e0a361_1
  fastrlock          conda-forge/linux-64::fastrlock-0.5-py38h950e882_1
  freetype           conda-forge/linux-64::freetype-2.10.3-he06d7ca_0
  fsspec             conda-forge/noarch::fsspec-0.8.4-py_0
  gflags             conda-forge/linux-64::gflags-2.2.2-he1b5a44_1004
  glog               conda-forge/linux-64::glog-0.4.0-h49b9bf7_3
  grpc-cpp           conda-forge/linux-64::grpc-cpp-1.32.0-h7997a97_1
  heapdict           conda-forge/noarch::heapdict-1.0.1-py_0
  icu                conda-forge/linux-64::icu-67.1-he1b5a44_0
  jinja2             conda-forge/noarch::jinja2-2.11.2-pyh9f0ad1d_0
  jpeg               conda-forge/linux-64::jpeg-9d-h516909a_0
  krb5               conda-forge/linux-64::krb5-1.17.1-hfafb76e_3
  lcms2              conda-forge/linux-64::lcms2-2.11-hbd6801e_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.35-h769bd43_9
  libblas            conda-forge/linux-64::libblas-3.8.0-17_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-17_openblas
  libcudf            rapidsai-nightly/linux-64::libcudf-0.16.0a201013-cuda11.0_g06e41894eb_1975
  libcurl            conda-forge/linux-64::libcurl-7.71.1-hcdd3856_8
  libedit            conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2
  libev              conda-forge/linux-64::libev-4.33-h516909a_1
  libevent           conda-forge/linux-64::libevent-2.1.10-hcdb4288_3
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1007
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.3.0-h5dbcf3e_17
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-9.3.0-he4bcb1c_17
  libgfortran5       conda-forge/linux-64::libgfortran5-9.3.0-he4bcb1c_17
  libgomp            conda-forge/linux-64::libgomp-9.3.0-h5dbcf3e_17
  liblapack          conda-forge/linux-64::liblapack-3.8.0-17_openblas
  libllvm10          conda-forge/linux-64::libllvm10-10.0.1-he513fc3_3
  libnghttp2         conda-forge/linux-64::libnghttp2-1.41.0-h8cfc5f6_2
  libopenblas        conda-forge/linux-64::libopenblas-0.3.10-pthreads_h4812303_5
  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_2
  libprotobuf        conda-forge/linux-64::libprotobuf-3.13.0.1-h8b12597_0
  librmm             rapidsai-nightly/linux-64::librmm-0.16.0a201014-cuda11.0_gb7cdbc4_399
  libssh2            conda-forge/linux-64::libssh2-1.9.0-hab1572f_5
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.3.0-h2ae2ef3_17
  libthrift          conda-forge/linux-64::libthrift-0.13.0-h5aa387f_6
  libtiff            conda-forge/linux-64::libtiff-4.1.0-hc7e4089_6
  libutf8proc        conda-forge/linux-64::libutf8proc-2.5.0-h516909a_2
  libwebp-base       conda-forge/linux-64::libwebp-base-1.1.0-h516909a_3
  llvmlite           conda-forge/linux-64::llvmlite-0.34.0-py38h4f45e52_2
  locket             conda-forge/noarch::locket-0.2.0-py_2
  lz4-c              conda-forge/linux-64::lz4-c-1.9.2-he1b5a44_3
  markupsafe         conda-forge/linux-64::markupsafe-1.1.1-py38h8df0ef7_2
  msgpack-python     conda-forge/linux-64::msgpack-python-1.0.0-py38hbf85e49_2
  nccl               nvidia/linux-64::nccl-2.7.8.1-h4962215_0
  ncurses            conda-forge/linux-64::ncurses-6.2-he1b5a44_2
  numba              conda-forge/linux-64::numba-0.51.2-py38hc5bc63f_0
  numpy              conda-forge/linux-64::numpy-1.19.2-py38hbc27379_1
  olefile            conda-forge/noarch::olefile-0.46-py_0
  openssl            conda-forge/linux-64::openssl-1.1.1h-h516909a_0
  orc                conda-forge/linux-64::orc-1.6.5-hd3605a7_0
  packaging          conda-forge/noarch::packaging-20.4-pyh9f0ad1d_0
  pandas             conda-forge/linux-64::pandas-1.1.3-py38hc5bc63f_2
  parquet-cpp        conda-forge/noarch::parquet-cpp-1.5.1-2
  partd              conda-forge/noarch::partd-1.1.0-py_0
  pillow             conda-forge/linux-64::pillow-8.0.0-py38h9776b28_0
  pip                conda-forge/noarch::pip-20.2.3-py_0
  psutil             conda-forge/linux-64::psutil-5.7.2-py38h8df0ef7_1
  pyarrow            conda-forge/linux-64::pyarrow-1.0.1-py38h93feb13_13_cuda
  pynvml             conda-forge/noarch::pynvml-8.0.4-py_1
  pyparsing          conda-forge/noarch::pyparsing-2.4.7-pyh9f0ad1d_0
  python             conda-forge/linux-64::python-3.8.6-h852b56e_0_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  python_abi         conda-forge/linux-64::python_abi-3.8-1_cp38
  pytz               conda-forge/noarch::pytz-2020.1-pyh9f0ad1d_0
  pyyaml             conda-forge/linux-64::pyyaml-5.3.1-py38h8df0ef7_1
  re2                conda-forge/linux-64::re2-2020.10.01-he1b5a44_0
  readline           conda-forge/linux-64::readline-8.0-he28a2e2_2
  rmm                rapidsai-nightly/linux-64::rmm-0.16.0a201014-cuda_11.0_py38_gb7cdbc4_399
  setuptools         conda-forge/linux-64::setuptools-49.6.0-py38h924ce5b_2
  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0
  snappy             conda-forge/linux-64::snappy-1.1.8-he1b5a44_3
  sortedcontainers   conda-forge/noarch::sortedcontainers-2.2.2-pyh9f0ad1d_0
  spdlog             conda-forge/linux-64::spdlog-1.7.0-hc9558a2_2
  sqlite             conda-forge/linux-64::sqlite-3.33.0-h4cf870e_1
  tblib              conda-forge/noarch::tblib-1.6.0-py_0
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_1
  toolz              conda-forge/noarch::toolz-0.11.1-py_0
  tornado            conda-forge/linux-64::tornado-6.0.4-py38h1e0a361_2
  typing_extensions  conda-forge/noarch::typing_extensions-3.7.4.3-py_0
  wheel              conda-forge/noarch::wheel-0.35.1-pyh9f0ad1d_0
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  yaml               conda-forge/linux-64::yaml-0.2.5-h516909a_0
  zict               conda-forge/noarch::zict-2.0.0-py_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1010
  zstd               conda-forge/linux-64::zstd-1.4.5-h6597ccf_2


Proceed ([y]/n)?
```

</details>

**Comment by kkraus14** [comment]
We ran out of space in our conda channel and the cuda 11 build of libcudf didn't get uploaded: https://anaconda.org/rapidsai-nightly/libcudf/files?version=0.16.0a201014

@rapidsai/ops is working on resolving the problem

**Comment by pentschev** [comment]
I can confirm the issue was the missing updated libcudf package, building a new conda environment now has fixed it. Thanks @kkraus14 and @shwina .
