### ISSUE TITLE
[FEA] Ability to set multiple columns with a scalar value in cudf.DataFrame

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#6577]
**Is your feature request related to a problem? Please describe.**
In Pandas dataframe we can set multiple columns at once by specifying them as a list. `cudf.DataFrame` currently supports doing it via a scalar, but errors when a list is given. I'd like to request a similar ability in `cudf.DataFrame` too.

```python
>>> import pandas as pd
>>> pdf = pd.DataFrame({'a':[10, 20, 30, 40]})
>>> pdf
    a
0  10
1  20
2  30
3  40
>>> pdf[['b','z']] = 101
>>> pdf
    a    b    z
0  10  101  101
1  20  101  101
2  30  101  101
3  40  101  101
>>> import cudf
>>> df = cudf.DataFrame({'a':[10, 20, 30, 40]})
>>> df
    a
0  10
1  20
2  30
3  40
>>> df[['b','z']] = 101
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.7/site-packages/cudf/core/dataframe.py", line 790, in __setitem__
    self._data[col][:] = value
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.7/site-packages/cudf/core/column_accessor.py", line 48, in __getitem__
    return self._data[key]
KeyError: 'b'
```

**Describe alternatives you've considered**
The alternative is to loop through the list(`['b','z']`) and set the values.

**Comment by beckernick** [comment]
I believe this may just be the scalar case, as I think we implemented this for setitem with arrays in https://github.com/rapidsai/cudf/issues/2758

```python
import cudf
import numpy as np
​
df = cudf.DataFrame({'a':[10, 20, 30, 40]})
df[['b','z']] = np.arange(4)
print(df)
    a  b  z
0  10  0  0
1  20  1  1
2  30  2  2
3  40  3  3
```
