### ISSUE TITLE
Easy GPU OOM for basic tasks

### ISSUE THREAD

**Issue by pseudotensor** [rapidsai/cudf#6594]
For a 43GB csv, running:

```
def fun():
    from dask.distributed import Client, wait
    from dask_cuda import LocalCUDACluster
    import dask_cudf
    with LocalCUDACluster() as cluster:
        with Client(cluster) as client:

            X = dask_cudf.read_csv("ipums_2000-2015.csv")
            print(X.iloc[-10:].compute())

if __name__ == '__main__':
    fun()
```

leads to GPU OOM because the GPU is being filled up with the entire dataset apparently.

This is quite inefficient for a simple slicing operation.  I don't know if this is dask at fault or dask_cudf/cudf at fault, but it makes using slices of large datasets not really possible.

One major benefit of dask/cudf was to be able to delay operations, generate a task graph, and to minimize what is on the GPU.  Yet here just getting 10 rows eats both of my GPUs memory each with 11GB and goes OOM:

```
(base) jon@mr-dl10:/data/jon$ time python dask_cudf_ipums.py
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (<function apply at 0x7f7267d83268>, <function _read_csv at 0x7f70f5659d08>, ['ipums_2000-2015.csv', array([dtype('O'), dtype('int64'), dtype('int64'), dtype('int64'),
       dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'),
       dtype('int8'), dtype('int64'), dtype('float64'), dtype('float64'),
       dtype('int64'), dtype('int64'), dtype('int64'), dtype('int8'),
       dtype('int8'), dtype('int8'), dtype('int8'), dtype('int8'),
       dtype('int8'), dtype('int8'), dtype('int8'), dtype('int8'),
       dtype('int8'), dtype('int8'), dtype('int8'), dtype('int64'),
       dtype('int8'), dtype('int8'), dtype('int8'), dtype('int8'),
       dtype('int8'), dtype('int8'), dtype('int8'), dtype('int64'),
       dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'),
       dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'),
       dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'),
       dtype('int64'), dtype('int64'), dtype('
kwargs:    {}
Exception: MemoryError('std::bad_alloc: CUDA error at: /conda/conda-bld/librmm_1591196499881/work/include/rmm/mr/device/cuda_memory_resource.hpp66: cudaErrorMemoryAllocation out of memory',)

distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (<function apply at 0x7f7267d83268>, <function _read_csv at 0x7f70f5659d08>, ['ipums_2000-2015.csv', array([dtype('O'), dtype('int64'), dtype('int64'), dtype('int64'),
       dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'),
       dtype('int8'), dtype('int64'), dtype('float64'), dtype('float64'),
       dtype('int64'), dtype('int64'), dtype('int64'), dtype('int8'),
       dtype('int8'), dtype('int8'), dtype('int8'), dtype('int8'),
       dtype('int8'), dtype('int8'), dtype('int8'), dtype('int8'),
       dtype('int8'), dtype('int8'), dtype('int8'), dtype('int64'),
       dtype('int8'), dtype('int8'), dtype('int8'), dtype('int8'),
       dtype('int8'), dtype('int8'), dtype('int8'), dtype('int64'),
       dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'),
       dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'),
       dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'),
       dtype('int64'), dtype('int64'), dtype('
kwargs:    {}
Exception: MemoryError('std::bad_alloc: CUDA error at: /conda/conda-bld/librmm_1591196499881/work/include/rmm/mr/device/cuda_memory_resource.hpp66: cudaErrorMemoryAllocation out of memory',)

Traceback (most recent call last):
  File "dask_cudf_ipums.py", line 12, in <module>
    fun()
  File "dask_cudf_ipums.py", line 9, in fun
    print(X.loc[-10:].compute())
  File "/home/jon/minicondadai/lib/python3.6/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/dask/base.py", line 444, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/distributed/client.py", line 2674, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/distributed/client.py", line 1974, in gather
    asynchronous=asynchronous,
  File "/home/jon/minicondadai/lib/python3.6/site-packages/distributed/client.py", line 824, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/jon/minicondadai/lib/python3.6/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/home/jon/minicondadai/lib/python3.6/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/jon/minicondadai/lib/python3.6/site-packages/distributed/client.py", line 1833, in _gather
    raise exception.with_traceback(traceback)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/dask/utils.py", line 30, in apply
    return func(*args, **kwargs)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/dask_cudf/io/csv.py", line 87, in _read_csv
    return cudf.read_csv(fn, **kwargs)
  File "/home/jon/minicondadai/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/cudf/io/csv.py", line 84, in read_csv
    index_col=index_col,
  File "cudf/_lib/csv.pyx", line 337, in cudf._lib.csv.read_csv
MemoryError: std::bad_alloc: CUDA error at: /conda/conda-bld/librmm_1591196499881/work/include/rmm/mr/device/cuda_memory_resource.hpp66: cudaErrorMemoryAllocation out of memory

real    1m11.621s
user    0m51.478s
sys     0m14.871s
```

**Comment by pseudotensor** [comment]
Sorry, confusion between iloc and loc.  iloc is not supported on dask with version I am using.
