### ISSUE TITLE
[BUG] arrow data: Categorical categories must be unique

### ISSUE THREAD

**Issue by jangorecki** [rapidsai/cudf#6828]
**Describe the bug**

I switched from using csv format to feather format and getting and error for the same dataset. Error is being raised during printing. Sorry for not having minimal example but python is not my native language.

**Steps/Code to reproduce bug**

Generate data in csv and feather
```sh
Rscript -e 'install.packages(c("data.table","arrow"))'
wget https://raw.githubusercontent.com/h2oai/db-benchmark/629755352248c9538fbd924e56356e5592f268be/_data/groupby-datagen.R
Rscript groupby-datagen.R 1e7 1e2 0 0
Rscript -e 'arrow::write_feather(data.table::fread("G1_1e7_1e2_0_0.csv", stringsAsFactors=TRUE, data.table=FALSE), "G1_1e7_1e2_0_0.feather")'
```

cudf using csv
```py
import cudf as cu
x = cu.read_csv("G1_1e7_1e2_0_0.csv", header=0, dtype=['str','str','str','int32','int32','int32','int32','int32','float64'])
x['id1'] = x['id1'].astype('category')
x['id2'] = x['id2'].astype('category')
x['id3'] = x['id3'].astype('category')
ans = x.groupby(['id1'],as_index=False).agg({'v1':'sum'})
print(ans.head(3), flush=True)
```
```
     id1      v1
0  id001  299542
1  id002  300933
2  id003  301968
```

cudf using feather
```py
import cudf as cu
x = cu.io.feather.read_feather("data/G1_1e7_1e2_0_0.feather")
#/home/jan/anaconda3/envs/cudf/lib/python3.8/site-packages/cudf/io/feather.py:15: UserWarning: Using CPU via PyArrow to read #feather 
#dataset, this may be GPU accelerated in the future
#  warnings.warn(
ans = x.groupby(['id1'],as_index=False).agg({'v1':'sum'})
print(ans.head(3), flush=True)
```
```
Traceback (most recent call last):
  File "./cudf/groupby-cudf.py", line 58, in <module>
    print(ans.head(3), flush=True)
  File "/home/jan/anaconda3/envs/cudf/lib/python3.8/site-packages/cudf/core/dataframe.py", line 1025, in __str__
    return self.to_string()
  File "/home/jan/anaconda3/envs/cudf/lib/python3.8/site-packages/cudf/core/dataframe.py", line 1022, in to_string
    return self.__repr__()
  File "/home/jan/anaconda3/envs/cudf/lib/python3.8/site-packages/cudf/core/dataframe.py", line 1272, in __repr__
    return self._clean_renderable_dataframe(output)
  File "/home/jan/anaconda3/envs/cudf/lib/python3.8/site-packages/cudf/core/dataframe.py", line 1151, in _clean_renderable_dataframe
    output = output.to_pandas().to_string(
  File "/home/jan/anaconda3/envs/cudf/lib/python3.8/site-packages/cudf/core/dataframe.py", line 4861, in to_pandas
    out_data[i] = self._data[col_key].to_pandas(index=out_index)
  File "/home/jan/anaconda3/envs/cudf/lib/python3.8/site-packages/cudf/core/column/categorical.py", line 935, in to_pandas
    data = pd.Categorical.from_codes(
  File "/home/jan/anaconda3/envs/cudf/lib/python3.8/site-packages/pandas/core/arrays/categorical.py", line 606, in from_codes
    dtype = CategoricalDtype._from_values_or_dtype(
  File "/home/jan/anaconda3/envs/cudf/lib/python3.8/site-packages/pandas/core/dtypes/dtypes.py", line 277, in _from_values_or_dtype
    dtype = CategoricalDtype(categories, ordered)
  File "/home/jan/anaconda3/envs/cudf/lib/python3.8/site-packages/pandas/core/dtypes/dtypes.py", line 164, in __init__
    self._finalize(categories, ordered, fastpath=False)
  File "/home/jan/anaconda3/envs/cudf/lib/python3.8/site-packages/pandas/core/dtypes/dtypes.py", line 318, in _finalize
    categories = self.validate_categories(categories, fastpath=fastpath)
  File "/home/jan/anaconda3/envs/cudf/lib/python3.8/site-packages/pandas/core/dtypes/dtypes.py", line 495, in validate_categories
    raise ValueError("Categorical categories must be unique")
ValueError: Categorical categories must be unique
```

**Expected behavior**

Printing `ans` should not raise error for feather source data, same as it doesn't for csv data.

**Environment overview (please complete the following information)**

bare-metal
cudf installed from conda

**Environment details**

```
cudf/print_env.sh
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#NameError: name 'cudf' is not defined
```

cudf 0.16
arrow 2.0.0

**Comment by kkraus14** [comment]
`arrow 2.0.0`: We only currently support `arrow 1.0.1`. Any chance you could try with that version and let us know if the issue still persists?

Also, a reproducer that's standalone and doesn't require running an R script to generate the data would be greatly appreciated.

**Comment by jangorecki** [comment]
afaik issue still needs to be addressed.
