### ISSUE TITLE
[BUG]cudf outer merge fails on categorical dtypes

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#6892]
**Describe the bug**
OuterMerge fails on categorical dtypes  

**Steps/Code to reproduce bug**
```python
import cudf
df_1 = cudf.DataFrame({'a':[0],'id':[2]})
df_1['id']=df_1['id'].astype('category')
df_2 = cudf.DataFrame({'b':[3],'id':[2]})
df_2['id']=df_2['id'].astype('category')
df_2.merge(df_1,how='outer')
```

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nvme/0/vjawa/conda/envs/rapids-0.17-dec-3/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/nvme/0/vjawa/conda/envs/rapids-0.17-dec-3/lib/python3.7/site-packages/cudf/core/dataframe.py", line 3962, in merge
    suffixes=suffixes,
  File "/nvme/0/vjawa/conda/envs/rapids-0.17-dec-3/lib/python3.7/site-packages/cudf/core/frame.py", line 3228, in _merge
    to_return = mergeop.perform_merge()
  File "/nvme/0/vjawa/conda/envs/rapids-0.17-dec-3/lib/python3.7/site-packages/cudf/core/join/join.py", line 107, in perform_merge
    output_dtypes = self.compute_output_dtypes()
  File "/nvme/0/vjawa/conda/envs/rapids-0.17-dec-3/lib/python3.7/site-packages/cudf/core/join/join.py", line 494, in compute_output_dtypes
    l_data_join_cols[name], r_data_join_cols[name], self.how
  File "/nvme/0/vjawa/conda/envs/rapids-0.17-dec-3/lib/python3.7/site-packages/cudf/core/join/join.py", line 434, in libcudf_to_output_casting_rules
    dtype_l.categories, dtype_r.categories
  File "/nvme/0/vjawa/conda/envs/rapids-0.17-dec-3/lib/python3.7/site-packages/cudf/core/reshape.py", line 206, in concat
    objs = [obj for obj in objs if obj is not None]
  File "/nvme/0/vjawa/conda/envs/rapids-0.17-dec-3/lib/python3.7/site-packages/cudf/core/index.py", line 257, in __iter__
    cudf.utils.utils.raise_iteration_error(obj=self)
  File "/nvme/0/vjawa/conda/envs/rapids-0.17-dec-3/lib/python3.7/site-packages/cudf/utils/utils.py", line 388, in raise_iteration_error
    f"{obj.__class__.__name__} object is not iterable. "
TypeError: Int64Index object is not iterable. Consider using `.to_arrow()`, `.to_pandas()` or `.values_host` if you wish to iterate over the values.

```

**Expected behavior**
The behaviour we have with pandas 
```python
df_1 = pd.DataFrame({'a':[0],'id':[2]})
df_1['id']=df_1['id'].astype('category')
df_2 = pd.DataFrame({'b':[3],'id':[2]})
df_2['id']=df_2['id'].astype('category')
df_2.merge(df_1,how='outer')
```
```
   b id  a
0  3  2  0

```
**Environment overview (please complete the following information)**
 - Method of cuDF install: [conda]
```python
cudf                      0.17.0a201203   cuda_10.2_py37_g5336301b85_372    rapidsai-nightly
libcudf                   0.17.0a201203   cuda10.2_g5336301b85_372    rapidsai-nightly
```

**Comment by kkraus14** [comment]
@brandon-b-miller can you take a look at this in 0.18?
