### ISSUE TITLE
[BUG] `RuntimeError: Failed to deserialize program` in `cudf._lib.binaryop.binaryop_v_s`

### ISSUE THREAD

**Issue by pentschev** [rapidsai/cudf#6968]
Starting from the cuDF 0.18 build from December 8th, I see a `RuntimeError: Failed to deserialize program` being raised at `cudf._lib.binaryop.binaryop_v_s`. The simplest reproducer is simply running https://github.com/rapidsai/dask-cuda/blob/branch-0.18/dask_cuda/benchmarks/local_cudf_merge.py with its default settings, full traceback below.

<details><summary>Error traceback</summary>

```python-traceback
$ python $CONDA_PREFIX/lib/python3.8/site-packages/dask_cuda/benchmarks/local_cudf_merge.py
distributed.worker - WARNING -  Compute Failed
Function:  execute_task
args:      ((subgraph_callable, (subgraph_callable, (<function _concat at 0x7ff749c4b700>, [(<built-in function getitem>, (<function shuffle_group at 0x7ff71e28f820>, (subgraph_callable,            key  shuffle  payload
0            0        0   177429
1            1        0   101403
2            2        0   212653
3            3        0   661469
4            4        0   582428
...        ...      ...      ...
999995  999995        0   387204
999996  999996        0   150593
999997  999997        0   196646
999998  999998        0   974189
999999  999999        0    71526

[1000000 rows x 3 columns], '_partitions', (subgraph_callable, (subgraph_callable,            key  shuffle  payload
0            0        0   177429
1            1        0   101403
2            2        0   212653
3            3        0   661469
4            4        0   582428
...        ...      ...      ...
999995  999995        0   387204
999996  999996        0   150593
999997  999997        0   196646
999998  999998
kwargs:    {}
Exception: RuntimeError('Failed to deserialize program')

Traceback (most recent call last):
  File "dask_cuda/benchmarks/local_cudf_merge.py", line 370, in <module>
    main(parse_args())
  File "dask_cuda/benchmarks/local_cudf_merge.py", line 232, in main
    took_list.append(run(client, args, n_workers, write_profile=None))
  File "dask_cuda/benchmarks/local_cudf_merge.py", line 176, in run
    data_processed = len(ddf_base) * sum([t.itemsize for t in ddf_base.dtypes])
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/dask/dataframe/core.py", line 3514, in __len__
    return len(s)
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/dask/dataframe/core.py", line 535, in __len__
    return self.reduction(
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/dask/base.py", line 167, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/dask/base.py", line 452, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/distributed/client.py", line 2725, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/distributed/client.py", line 1986, in gather
    return self.sync(
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/distributed/client.py", line 832, in sync
    return sync(
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/distributed/utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/distributed/utils.py", line 324, in f
    result[0] = yield future
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/distributed/client.py", line 1851, in _gather
    raise exception.with_traceback(traceback)
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/dask/optimization.py", line 961, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/dask/core.py", line 151, in get
    result = _execute_task(task, cache)
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/dask/utils.py", line 29, in apply
    return func(*args, **kwargs)
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/dask/dataframe/core.py", line 5298, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/dask/dataframe/shuffle.py", line 786, in set_partitions_pre
    partitions[(s >= divisions.iloc[-1]).values] = len(divisions) - 2
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/cudf/core/series.py", line 1679, in __ge__
    return self._binaryop(other, "ge")
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/cudf/core/series.py", line 1207, in _binaryop
    outcol = lhs._column.binary_operator(fn, rhs, reflect=reflect)
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/cudf/core/column/numerical.py", line 99, in binary_operator
    return _numeric_column_binop(
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/datasets/pentschev/miniconda3/envs/rn-102-0.18.201210/lib/python3.8/site-packages/cudf/core/column/numerical.py", line 606, in _numeric_column_binop
    out = libcudf.binaryop.binaryop(lhs, rhs, op, out_dtype)
  File "cudf/_lib/binaryop.pyx", line 200, in cudf._lib.binaryop.binaryop
  File "cudf/_lib/binaryop.pyx", line 127, in cudf._lib.binaryop.binaryop_v_s
RuntimeError: Failed to deserialize program
```

</details>

Reverting to the build from December 4th the benchmark completes successfully, and that of December 7th fails due to an error coming from RMM, which has been fixed since.

**Comment by galipremsagar** [comment]
Can you try clearing `.cudf`:
``
rm -rf ~/.cudf/*
``

**Comment by pentschev** [comment]
Wow, that was awesome @galipremsagar . Every now and then I see such issues with CuPy but this was the first time for cuDF, and I didn't know there was a cache.  Thanks a lot, this indeed resolved the issue!
