### ISSUE TITLE
[BUG] `pd.set_option("display.max_rows", None`) not supported properly

### ISSUE THREAD

**Issue by drabastomek** [rapidsai/cudf#6978]
**Describe the bug**
Problem creating and operating on Series.

**Steps/Code to reproduce bug**
Minimal example

```python
import cudf

cudf.Series([1,2,3,4,5])
```

throws

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/opt/conda/envs/rapids/lib/python3.8/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/opt/conda/envs/rapids/lib/python3.8/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

/opt/conda/envs/rapids/lib/python3.8/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/series.py in __repr__(self)
   1082         )
   1083 
-> 1084         if len(self) > max_rows and max_rows != 0:
   1085             top = self.head(int(max_rows / 2 + 1))
   1086             bottom = self.tail(int(max_rows / 2 + 1))

TypeError: '>' not supported between instances of 'int' and 'NoneType'
```

**Expected behavior**
A `cudf.Series` is created.

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker
   - `docker pull rapidsai/rapidsai-nightly:cuda11.0-runtime-ubuntu18.04-py3.8`
   - cudf version: `0.17.0a+382.gbd321d1e93`
   - Titan RTX

**Comment by drabastomek** [comment]
cc: @kkraus14

**Comment by shwina** [comment]
I'm unable to reproduce this, both building from source and using the latest nightly docker image. I did:

```
docker pull rapidsai/rapidsai-nightly:cuda10.1-runtime-ubuntu18.04-py3.8
docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 rapidsai/rapidsai-nightly:cuda10.1-runtime-ubuntu18.04-py3.8
```

Perhaps we had a bad docker build previously? Could you please try the latest nightly docker image and see if the issue still persists?

**Comment by galipremsagar** [comment]
This issue is because `display.max_rows` option in your system is set to `None`. `cudf` currently doesn't handle `None` input for `display.max_rows`, a fix for it will be issued in `0.18`.  As a workaround to this issue, we would recommend setting it any positive integer value(for example `60`, which is the deafult value). 

https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html#available-options


```python
>>> import pandas as pd
>>> import cudf
>>> s = cudf.Series([1,2, 3])
>>> s
0    1
1    2
2    3
dtype: int64
>>> pd.set_option("display.max_rows", None)
>>> s
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.7/site-packages/cudf/core/series.py", line 1086, in __repr__
    if len(self) > max_rows and max_rows != 0:
TypeError: '>' not supported between instances of 'int' and 'NoneType'
>>> pd.set_option("display.max_rows", None)
>>> s
0    1
1    2
2    3
dtype: int64
```

**Comment by drabastomek** [comment]
Oh that makes sense -- I couldn't figure out why it wasn't working. Thanks @galipremsagar and @shwina!

**Comment by shwina** [comment]
@galipremsagar has the fix you mentioned above been implemented? Can this be closed out? Thanks!

**Comment by beckernick** [comment]
This has not been resolved, but can be worked around by setting to a positive integer as noted above.

**Comment by galipremsagar** [comment]
Thanks Nick, I just verified we still seem to be running into this issue. I'll open a fix for it soon
