### ISSUE TITLE
[BUG] Conda installation fails because of incompatibility between nvstrings and cudf package

### ISSUE THREAD

**Issue by yogeshg** [rapidsai/cudf#704]
**Describe the bug**

Conda install fails to import `libcudf.so` because `undefined symbol: _ZN9NVStrings17create_from_indexEPSt4pairIPKcmEjb`

```
$ python -c "import cudf"


Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/env/cudf-env/lib/python3.6/site-packages/cudf/__init__.py", line 2, in <module>
    from cudf import dataframe             # noqa: F401
  File "/home/ubuntu/env/cudf-env/lib/python3.6/site-packages/cudf/dataframe/__init__.py", line 1, in <module>
    from cudf.dataframe import (buffer, dataframe, series,  # noqa: F401
  File "/home/ubuntu/env/cudf-env/lib/python3.6/site-packages/cudf/dataframe/dataframe.py", line 18, in <module>
    from cudf import formatting, _gdf
  File "/home/ubuntu/env/cudf-env/lib/python3.6/site-packages/cudf/_gdf.py", line 13, in <module>
    from libgdf_cffi import ffi, libgdf
  File "/home/ubuntu/env/cudf-env/lib/python3.6/site-packages/libgdf_cffi/__init__.py", line 30, in <module>
    libgdf_api = ffi.dlopen(_get_lib_name())
OSError: cannot load library 'libcudf.so': /home/ubuntu/env/cudf-env/lib/python3.6/site-packages/../../libcudf.so: undefined symbol: _ZN9NVStrings17create_from_indexEPSt4pairIPKcmEjb
```

**Steps/Code to reproduce bug**
```
python -c "import cudf"
```

**Expected behavior**

**Environment details (please complete the following information):**
 - Environment location: [AWS]
 - Method of cuDF install: [conda]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
 - Please run and attach the output of the `cudf/print_env.sh` script to gather relevant environment details
 
***git***
commit 81625bcba3178b529175da3315360adb5d166bad (HEAD -> branch-0.6, origin/branch-0.6, origin/HEAD)
Merge: b79c56a ebc067e
Author: Mike Wendt <mike.wendt@me.com>
Date:   Fri Jan 11 09:29:28 2019 -0800

    Merge pull request #650 from mrocklin/remove-google-group-reference
    
    [REVIEW] Remove reference to google groups in pull request template

***OS Information***
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
Linux ip-172-31-24-133 4.4.0-1073-aws #83-Ubuntu SMP Sat Nov 17 00:26:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

***GPU Information***
```
Wed Jan 16 19:24:23 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:1B.0 Off |                    0 |
| N/A   38C    P0    38W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:00:1C.0 Off |                    0 |
| N/A   38C    P0    38W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:00:1D.0 Off |                    0 |
| N/A   37C    P0    41W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   38C    P0    40W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
***CPU***
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    16
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
Stepping:              1
CPU MHz:               1876.656
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4600.11
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-31
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc aperfmperf 
pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser fsgsbase bmi1 hle avx2 smep bmi2 erms inv
pcid rtm rdseed adx xsaveopt

***CMake***
/usr/bin/cmake
cmake version 3.5.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

***g++***
/usr/bin/g++
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

***nvcc***
/usr/local/cuda/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148

***Python***
/home/ubuntu/env/cudf-env/bin/python
Python 3.6.7

***Environment Variables***
```
PATH                            : /home/ubuntu/env/cudf-env/bin:/home/ubuntu/anaconda3/bin/:/home/ubuntu/bin:/home/ubuntu/.local/bin:/home/ubuntu/anaconda3/bin/:/usr/local/cuda/bin:/usr/local/bin:/opt/aws/bin:/usr/local/mpi/bin:/usr/local/cuda/bin:/usr/local/bin:/opt/aws/bin:/home/ubuntu/src/cntk/bin:/usr/local/mpi/bin:/usr/local/cuda/bin:/usr/local/bin:/opt/aws/bin:/usr/local/mpi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LD_LIBRARY_PATH                 : /usr/lib64/openmpi/lib/:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/mpi/lib:/lib/:/home/ubuntu/src/cntk/bindings/python/cntk/libs:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/mpi/lib:/usr/lib64/openmpi/lib/:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/mpi/lib:/lib/:
NUMBAPRO_NVVM                   : 
NUMBAPRO_LIBDEVICE              : 
CONDA_PREFIX                    : /home/ubuntu/env/cudf-env
PYTHON_PATH                     : 
```
***conda packages***
```
/home/ubuntu/anaconda3/bin//conda
# packages in environment at /home/ubuntu/env/cudf-env:
#
# Name                    Version                   Build  Channel
arrow-cpp                 0.10.0           py36h70250a7_0    conda-forge
blas                      1.0                         mkl  
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cffi                      1.11.5          py36h9745a5d_1001    conda-forge
cudf                      0.4.0                    py36_0    rapidsai
cython                    0.28.5          py36hf484d3e_1000    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
intel-openmp              2019.1                      144  
libcudf                   0.4.0                 cuda9.2_0    rapidsai
libcudf_cffi              0.4.0            cuda9.2_py36_0    rapidsai
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
llvmlite                  0.27.0           py36hf484d3e_0    numba
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py36h470a237_1    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numba                     0.42.0          np115py36hf484d3e_0    numba
numpy                     1.15.4           py36h7e9f1db_0  
numpy-base                1.15.4           py36hde5b4d6_0  
nvstrings                 0.2.0            cuda9.2_py36_2    nvidia
openssl                   1.0.2p            h14c3975_1002    conda-forge
pandas                    0.20.3                   py36_1    conda-forge
parquet-cpp               1.5.0.pre            h83d4a3d_0    conda-forge
pip                       18.1                  py36_1000    conda-forge
pyarrow                   0.10.0           py36hfc679d8_0    conda-forge
pycparser                 2.19                       py_0    conda-forge
python                    3.6.7             hd21baee_1001    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
setuptools                40.6.3                   py36_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```
**Additional context**

**Comment by yogeshg** [comment]
I can confirm that `conda install -y  -p cudf_2 -c nvidia nvstrings==0.1.0` lets me atleast import the package.

**Comment by raydouglass** [comment]
Please update nvstrings v0.2.0 to build cuda9.2_py36_3 which should also resolve the issue.
