### ISSUE TITLE
[QST] undefined symbol: _ZN4cudf2io9read_avroERKNS0_19avro_reader_optionsEPN3rmm2mr22device_memory_resourceE

### ISSUE THREAD

**Issue by mikej3737** [rapidsai/cudf#7062]
After a long struggle, I succeeded to build and install cudf from source on ppc64 platform without using conda.
My environment: dokcer container Ubuntu 18.04 

```
Python 3.7.5
```

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Thu_Oct_24_17:58:26_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
```

**ERROR:**
```
>>> import cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/cudf/__init__.py", line 11, in <module>
    from cudf import core, datasets, testing
  File "/usr/local/lib/python3.7/dist-packages/cudf/core/__init__.py", line 3, in <module>
    from cudf.core import buffer, column, common
  File "/usr/local/lib/python3.7/dist-packages/cudf/core/column/__init__.py", line 3, in <module>
    from cudf.core.column.categorical import CategoricalColumn
  File "/usr/local/lib/python3.7/dist-packages/cudf/core/column/categorical.py", line 8, in <module>
    from cudf import _lib as libcudf
  File "/usr/local/lib/python3.7/dist-packages/cudf/_lib/__init__.py", line 4, in <module>
    from . import (
ImportError: /usr/local/lib/python3.7/dist-packages/cudf/_lib/avro.cpython-37m-powerpc64le-linux-gnu.so: undefined symbol: _ZN4cudf2io9read_avroERKNS0_19avro_reader_optionsEPN3rmm2mr22device_memory_resourceE
```

**Comment by harrism** [comment]
@vuule could you triage this?

**Comment by vuule** [comment]
I don't think this is related to the Avro reader implementation, should be a build issue.
FWIW, I had a similar issue when our APIs changed. The solution was to delete the build directories and do a clean build. Not sure if that applies here, since the last `read_avro` API change was 4 months ago.
Could also be a mismatch between versions of different components, not sure how to verify this without conda.

**Comment by harrism** [comment]
@mikej3737 can you try a completely clean build from the latest branch-0.17 source?

**Comment by mikej3737** [comment]
@harrism I tried clean build using  branch-0.17, but still have a same problem.

```
>>> import cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/cudf-0.17.0a0+383.g00ca24625e-py3.7-linux-ppc64le.egg/cudf/__init__.py", line 11, in <module>
    from cudf import core, datasets, testing
  File "/usr/local/lib/python3.7/dist-packages/cudf-0.17.0a0+383.g00ca24625e-py3.7-linux-ppc64le.egg/cudf/core/__init__.py", line 3, in <module>
    from cudf.core import buffer, column, common
  File "/usr/local/lib/python3.7/dist-packages/cudf-0.17.0a0+383.g00ca24625e-py3.7-linux-ppc64le.egg/cudf/core/column/__init__.py", line 3, in <module>
    from cudf.core.column.categorical import CategoricalColumn
  File "/usr/local/lib/python3.7/dist-packages/cudf-0.17.0a0+383.g00ca24625e-py3.7-linux-ppc64le.egg/cudf/core/column/categorical.py", line 8, in <module>
    from cudf import _lib as libcudf
  File "/usr/local/lib/python3.7/dist-packages/cudf-0.17.0a0+383.g00ca24625e-py3.7-linux-ppc64le.egg/cudf/_lib/__init__.py", line 4, in <module>
    from . import (
ImportError: /usr/local/lib/python3.7/dist-packages/cudf-0.17.0a0+383.g00ca24625e-py3.7-linux-ppc64le.egg/cudf/_lib/avro.cpython-37m-powerpc64le-linux-gnu.so: undefined symbol: _ZN4cudf2io9read_avroERKNS0_19avro_reader_optionsEPN3rmm2mr22device_memory_resourceE
```

This is the dump of pip list, hope this helps.
```
absl-py (0.11.0)
addict (2.4.0)
alabaster (0.7.12)
albumentations (0.5.2)
annoy (1.17.0)
antlr4-python3-runtime (4.8)
apipkg (1.5)
appdirs (1.4.4)
apturl (0.5.2)
argon2-cffi (20.1.0)
asn1crypto (0.24.0)
astor (0.8.1)
async-generator (1.10)
attrs (20.3.0)
Babel (2.9.0)
backcall (0.2.0)
bhtsne (0.1.9)
black (19.10b0)
bleach (3.2.1)
Brlapi (0.6.6)
cached-property (1.5.2)
cachetools (4.1.1)
certifi (2020.6.20)
cffi (1.14.4)
cfgv (3.2.0)
chainer (7.7.0)
chainer-chemistry (0.7.1)
chainercv (0.13.1)
chardet (3.0.4)
clang (8.0.1)
click (7.1.2)
cloudpickle (1.6.0)
cmake-setuptools (0.1.3)
colorlog (4.6.2)
commonmark (0.9.1)
configparser (5.0.1)
cryptography (2.1.4)
cudf (0.17.0a0+383.g00ca24625e)
cupshelpers (1.0)
cupy (8.1.0)
cycler (0.10.0)
Cython (0.29.21)
dask (2020.12.0+21.g4a7a2438)
dataclasses (0.6)
decorator (4.4.2)
defer (1.0.6)
defusedxml (0.6.0)
detectron2 (0.3, /detectron2)
dgl (0.4.3)
distlib (0.3.1)
distributed (2020.12.0+11.g4386b756)
distro (1.5.0)
distro-info (0.18ubuntu0.18.04.1)
dlpack (0.1)
docker-pycreds (0.4.0)
docutils (0.16)
efficientnet-pytorch (0.7.0)
entrypoints (0.3)
execnet (1.7.1)
fastavro (1.2.3)
fastrlock (0.5)
filelock (3.0.12)
flake8 (3.8.3)
Flask (1.1.2)
flatbuffers (1.12)
fsspec (0.8.5)
future (0.18.2)
fvcore (0.1.2.post20201209)
gast (0.2.2)
gitdb (4.0.5)
GitPython (3.1.11)
google-auth (1.23.0)
google-auth-oauthlib (0.4.2)
google-pasta (0.2.0)
graphviz (0.15)
grpcio (1.34.0)
gunicorn (20.0.4)
h5py (2.10.0)
HeapDict (1.0.1)
httplib2 (0.9.2)
hydra-colorlog (1.0.0)
hydra-core (1.0.4)
hyperopt (0.2.5)
hypothesis (5.43.4)
identify (1.5.10)
idna (2.6)
imageio (2.9.0)
imagesize (1.2.0)
imgaug (0.4.0)
importlib-metadata (3.1.1)
importlib-resources (3.3.0)
iniconfig (1.1.1)
ipykernel (5.4.2)
ipython (7.19.0)
ipython-genutils (0.2.0)
isort (5.0.7)
itsdangerous (1.1.0)
jedi (0.18.0)
Jinja2 (2.11.2)
joblib (0.17.0)
jsonpatch (1.28)
jsonpointer (2.0)
jsonschema (3.2.0)
jupyter-client (6.1.7)
jupyter-core (4.7.0)
jupyterlab-pygments (0.1.2)
Keras (2.4.3)
Keras-Applications (1.0.8)
Keras-Preprocessing (1.1.2)
keyring (10.6.0)
keyrings.alt (3.0)
kiwisolver (1.3.1)
language-selector (0.1)
launchpadlib (1.10.6)
lazr.restfulclient (0.13.5)
lazr.uri (1.0.3)
lightgbm (3.1.1)
llvmlite (0.32.0)
locket (0.2.0)
louis (3.5.0)
macaroonbakery (1.1.3)
Mako (1.0.7)
Markdown (3.3.3)
MarkupSafe (1.0)
matplotlib (3.3.2)
mccabe (0.6.1)
mimesis (4.1.3)
mistune (0.8.4)
mmcv-full (1.2.1, /mmcv)
mmdet (2.7.0, /mmdetection)
mmpycocotools (12.0.3)
mpi4py (3.0.3)
msgpack (1.0.2)
munch (2.5.0)
nbclient (0.5.1)
nbconvert (6.0.7)
nbformat (5.0.8)
nbsphinx (0.8.0)
nest-asyncio (1.4.3)
networkx (2.5)
nibabel (3.2.1)
nilearn (0.7.0)
nodeenv (1.5.0)
notebook (6.1.6)
numba (0.49.0)
numpy (1.19.4)
numpydoc (1.1.0)
oauth (1.0.1)
oauthlib (3.1.0)
olefile (0.45.1)
omegaconf (2.0.5)
openslide-python (1.1.2)
opt-einsum (3.3.0)
packaging (20.7)
pandas (1.1.4)
pandocfilters (1.4.3)
parso (0.8.1)
partd (1.1.0)
pathspec (0.8.1)
pathtools (0.1.2)
pexpect (4.8.0)
pickleshare (0.7.5)
Pillow (8.0.1)
pip (9.0.1)
plotly (4.14.1)
pluggy (0.13.1)
portalocker (2.0.0)
pre-commit (2.9.3)
pretrainedmodels (0.7.4)
prometheus-client (0.9.0)
promise (2.3)
prompt-toolkit (3.0.8)
protobuf (3.14.0)
psutil (5.7.3)
ptyprocess (0.7.0)
py (1.9.0)
py-cpuinfo (7.0.0)
pyarrow (1.0.1)
pyasn1 (0.4.8)
pyasn1-modules (0.2.8)
pycairo (1.16.2)
pycocotools (2.0.2)
pycodestyle (2.6.0)
pycparser (2.20)
pycrypto (2.6.1)
pycups (1.9.73)
pydicom (2.1.2)
pydot (1.4.1)
pyflakes (2.2.0)
Pygments (2.7.3)
pygobject (3.26.1)
pymacaroons (0.13.0)
pymongo (3.11.2)
PyNaCl (1.1.2)
pyparsing (2.4.7)
pyRFC3339 (1.0)
pyrsistent (0.17.3)
pytest (6.1.2)
pytest-benchmark (3.2.3)
pytest-forked (1.3.0)
pytest-xdist (2.2.0)
python-apt (1.6.5+ubuntu0.3)
python-dateutil (2.8.1)
python-debian (0.1.32)
pytorch-lightning (0.7.6)
pytz (2018.3)
PyWavelets (1.1.1)
pyxdg (0.25)
PyYAML (5.3.1)
pyzmq (20.0.0)
rapidjson (1.0.0)
recommonmark (0.7.1)
regex (2020.11.13)
reportlab (3.4.0)
requests (2.25.0)
requests-oauthlib (1.3.0)
requests-unixsocket (0.1.5)
retrying (1.3.3)
rising (0.2.0.post0)
rmm (0.17.0)
rsa (4.6)
scikit-build (0.11.1)
scikit-image (0.17.2)
scikit-learn (0.23.2)
scipy (1.5.3)
seaborn (0.11.0)
SecretStorage (2.3.1)
Send2Trash (1.5.0)
sentry-sdk (0.19.4)
setuptools (45.0.0)
shortuuid (1.0.1)
simplejson (3.13.2)
six (1.15.0)
smmap (3.0.4)
snowballstemmer (2.0.0)
sortedcontainers (2.3.0)
Sphinx (3.4.1)
sphinx-copybutton (0.3.1)
sphinx-markdown-tables (0.0.15)
sphinx-rtd-theme (0.5.0)
sphinxcontrib-applehelp (1.0.2)
sphinxcontrib-devhelp (1.0.2)
sphinxcontrib-htmlhelp (1.0.3)
sphinxcontrib-jsmath (1.0.1)
sphinxcontrib-qthelp (1.0.3)
sphinxcontrib-serializinghtml (1.1.4)
sphinxcontrib-websupport (1.2.4)
ssh-import-id (5.7)
streamz (0.6.1, /streamz)
subprocess32 (3.5.4)
system-service (0.3)
systemd-python (234)
tabulate (0.8.7)
tblib (1.7.0)
tensorboard (1.15.0)
tensorboard-plugin-wit (1.7.0)
tensorboardX (2.1)
tensorflow (1.15.3)
tensorflow-estimator (1.15.1)
termcolor (1.1.0)
terminado (0.9.1)
terminaltables (3.1.0)
testpath (0.4.4)
threadpoolctl (2.1.0)
tifffile (2020.12.4)
timm (0.2.1)
toml (0.10.2)
toolz (0.11.1)
torch (1.7.0a0)
torchfile (0.1.0)
torchsummary (1.5.1)
torchvision (0.8.0a0+291f7e2)
tornado (6.1)
tqdm (4.51.0)
traitlets (5.0.5)
typed-ast (1.4.2)
typing (3.7.4.3)
typing-extensions (3.7.4.3)
ubuntu-drivers-common (0.0.0)
unattended-upgrades (0.1)
urllib3 (1.22)
virtualenv (20.2.2)
visdom (0.1.8.9)
wadllib (1.3.2)
wandb (0.10.12)
watchdog (0.10.4)
wcwidth (0.2.5)
webencodings (0.5.1)
websocket-client (0.57.0)
Werkzeug (1.0.1)
wheel (0.34.2)
wrapt (1.12.1)
xgboost (1.3.0-SNAPSHOT)
xkit (0.0.0)
yacs (0.1.8)
yapf (0.30.0)
zict (2.0.0)
zipp (3.4.0)
zope.interface (4.3.2)
```

**Comment by harrism** [comment]
I don't know much about Python packaging. I thought we didn't support pip. We also don't test on ppc64.  @kkraus14 to comment/assign when he returns from holiday.

**Comment by kkraus14** [comment]
This looks like an issue of the cudf Cython failing to find a symbol in libcudf. Have you rebuilt / reinstalled libcudf as well?

**Comment by mikej3737** [comment]
@kkraus14 Yes, I rebuild and reinstalled libcudf as well.
Since I'm using docker, it will be a clean build every time.

My dockerfile is like as follows:

```
RUN cd / && \
    git clone -b branch-0.17 https://github.com/rapidsai/cudf.git /cudf && cd /cudf && \
    git submodule update --init --remote --recursive
RUN cd / && \
    git clone https://github.com/dmlc/dlpack.git
ENV CPATH $CPATH:/dlpack/include
RUN cd /cudf/cpp && mkdir build && cd build && \
    cmake .. && \
    make -j48 && make install
RUN cd /cudf/python/cudf && \
    python setup.py build_ext --inplace && \
    python setup.py install
```

**Comment by kkraus14** [comment]
All of your above steps look fine to me. Are you then using the build packages inside this container or shipping them somewhere else?

What is the output of `ldd -v /usr/local/lib/python3.7/dist-packages/cudf/_lib/avro.cpython-37m-powerpc64le-linux-gnu.so` in this environment?

**Comment by mikej3737** [comment]
I will use the build packages inside this container.

**The output of ldd:**
```
# ldd -v /usr/local/lib/python3.7/dist-packages/cudf-0.17.0a0+383.g00ca24625e-py3.7-linux-ppc64le.egg/cudf/_lib/avro.cpython-37m-powerpc64le-linux-gnu.so
	linux-vdso64.so.1 (0x00007fff9b960000)
	libstdc++.so.6 => /usr/lib/powerpc64le-linux-gnu/libstdc++.so.6 (0x00007fff9b690000)
	libgcc_s.so.1 => /lib/powerpc64le-linux-gnu/libgcc_s.so.1 (0x00007fff9b620000)
	libpthread.so.0 => /lib/powerpc64le-linux-gnu/libpthread.so.0 (0x00007fff9b5d0000)
	libc.so.6 => /lib/powerpc64le-linux-gnu/libc.so.6 (0x00007fff9b3a0000)
	libm.so.6 => /lib/powerpc64le-linux-gnu/libm.so.6 (0x00007fff9b250000)
	/lib64/ld64.so.2 (0x00007fff9b980000)

	Version information:
	/usr/local/lib/python3.7/dist-packages/cudf-0.17.0a0+383.g00ca24625e-py3.7-linux-ppc64le.egg/cudf/_lib/avro.cpython-37m-powerpc64le-linux-gnu.so:
		libgcc_s.so.1 (GCC_3.0) => /lib/powerpc64le-linux-gnu/libgcc_s.so.1
		libpthread.so.0 (GLIBC_2.17) => /lib/powerpc64le-linux-gnu/libpthread.so.0
		libc.so.6 (GLIBC_2.17) => /lib/powerpc64le-linux-gnu/libc.so.6
		libstdc++.so.6 (GLIBCXX_3.4.9) => /usr/lib/powerpc64le-linux-gnu/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.18) => /usr/lib/powerpc64le-linux-gnu/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.9) => /usr/lib/powerpc64le-linux-gnu/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.11) => /usr/lib/powerpc64le-linux-gnu/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3) => /usr/lib/powerpc64le-linux-gnu/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.19) => /usr/lib/powerpc64le-linux-gnu/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.21) => /usr/lib/powerpc64le-linux-gnu/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4) => /usr/lib/powerpc64le-linux-gnu/libstdc++.so.6
	/usr/lib/powerpc64le-linux-gnu/libstdc++.so.6:
		ld64.so.2 (GLIBC_2.22) => /lib64/ld64.so.2
		libm.so.6 (GLIBC_2.17) => /lib/powerpc64le-linux-gnu/libm.so.6
		libgcc_s.so.1 (GCC_4.2.0) => /lib/powerpc64le-linux-gnu/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.3) => /lib/powerpc64le-linux-gnu/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.4.4) => /lib/powerpc64le-linux-gnu/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.0) => /lib/powerpc64le-linux-gnu/libgcc_s.so.1
		libc.so.6 (GLIBC_2.18) => /lib/powerpc64le-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.17) => /lib/powerpc64le-linux-gnu/libc.so.6
	/lib/powerpc64le-linux-gnu/libgcc_s.so.1:
		libc.so.6 (GLIBC_2.17) => /lib/powerpc64le-linux-gnu/libc.so.6
	/lib/powerpc64le-linux-gnu/libpthread.so.0:
		ld64.so.2 (GLIBC_2.17) => /lib64/ld64.so.2
		ld64.so.2 (GLIBC_PRIVATE) => /lib64/ld64.so.2
		libc.so.6 (GLIBC_PRIVATE) => /lib/powerpc64le-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.17) => /lib/powerpc64le-linux-gnu/libc.so.6
	/lib/powerpc64le-linux-gnu/libc.so.6:
		ld64.so.2 (GLIBC_2.23) => /lib64/ld64.so.2
		ld64.so.2 (GLIBC_PRIVATE) => /lib64/ld64.so.2
		ld64.so.2 (GLIBC_2.22) => /lib64/ld64.so.2
	/lib/powerpc64le-linux-gnu/libm.so.6:
		ld64.so.2 (GLIBC_2.23) => /lib64/ld64.so.2
		ld64.so.2 (GLIBC_PRIVATE) => /lib64/ld64.so.2
		libc.so.6 (GLIBC_PRIVATE) => /lib/powerpc64le-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.17) => /lib/powerpc64le-linux-gnu/libc.so.6
```

**Comment by kkraus14** [comment]
Thanks for sharing that @mikej3737, it looks like this a bug introduced from https://github.com/rapidsai/cudf/pull/6134

I think what's happening is that in the Python `setup.py` we only link against `libcudf.so` which is a library without symbols which links against a number of other libraries like `libcudf_base.so`, `libcudf_io.so`, etc. We've seen other problems with the linker pruning the dependency, but hadn't seen it happen before related to linking to the Cython produced libraries.

Could you try changing this line: https://github.com/rapidsai/cudf/blob/branch-0.18/python/cudf/setup.py#L114

Where instead of `["cudf"]`, we'd want `["cudf", "cudf_base", "cudf_ast", "cudf_comms", "cudf_hash", "cudf_interop", "cudf_io", "cudf_join", "cudf_merge", "cudf_partitioning", "cudf_reductions", "cudf_replace", "cudf_reshape", "cudf_rolling", "cudf_transpose"]`

**Comment by mikej3737** [comment]
@kkraus14 Thank you for your suggestions.
I installed again with your instruction and this time I got the following error.
Do you have any idea?

```
>>> import cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/cudf-0.17.0a0+383.g00ca24625e.dirty-py3.7-linux-ppc64le.egg/cudf/__init__.py", line 11, in <module>
    from cudf import core, datasets, testing
  File "/usr/local/lib/python3.7/dist-packages/cudf-0.17.0a0+383.g00ca24625e.dirty-py3.7-linux-ppc64le.egg/cudf/core/__init__.py", line 3, in <module>
    from cudf.core import buffer, column, common
  File "/usr/local/lib/python3.7/dist-packages/cudf-0.17.0a0+383.g00ca24625e.dirty-py3.7-linux-ppc64le.egg/cudf/core/column/__init__.py", line 3, in <module>
    from cudf.core.column.categorical import CategoricalColumn
  File "/usr/local/lib/python3.7/dist-packages/cudf-0.17.0a0+383.g00ca24625e.dirty-py3.7-linux-ppc64le.egg/cudf/core/column/categorical.py", line 8, in <module>
    from cudf import _lib as libcudf
  File "/usr/local/lib/python3.7/dist-packages/cudf-0.17.0a0+383.g00ca24625e.dirty-py3.7-linux-ppc64le.egg/cudf/_lib/__init__.py", line 4, in <module>
    from . import (
  File "cudf/_lib/gpuarrow.pyx", line 1, in init cudf._lib.gpuarrow
ModuleNotFoundError: No module named 'pyarrow._cuda'
```

**Comment by kkraus14** [comment]
Seems like pyarrow was installed without cuda support. Unfortunately, `pip` packages of pyarrow do not include cuda support, so you'd need to build and install the arrow cpp libs and pyarrow yourself.

**Comment by mikej3737** [comment]
@kkraus14 I really appreciate your support. I installed pyarrow successfully which include cuda support. And now there is a problem related nvtx, but I think this thread is not appropriate to discuss the problem. I will continue the investigation. Thanks.

**Comment by kkraus14** [comment]
Great. We are working to resolve this issue so that the changes in `setup.py` are not necessary. Going to close this issue as its now resolved for you.
