### ISSUE TITLE
Installation instructions incomplete: libcudf.so: undefined symbol

### ISSUE THREAD

**Issue by jangorecki** [rapidsai/cudf#736]
I am trying to install cudf but getting stuck.
Installed gcc-7 and g++-7 and set as defaults - required to install cuda toolkit 9.2.
Installed 9.2 toolkit
Set paths:
```sh
export LD_LIBRARY_PATH=/usr/local/cuda-9.2/bin:/usr/local/cuda-9.2/lib64:$LD_LIBRARY_PATH
export PATH=/usr/local/cuda-9.2/bin:$PATH
```

Create clean conda env for cudf and install to that env.

```sh
conda create --name cudf
conda install --name cudf -c nvidia -c rapidsai -c numba -c conda-forge -c defaults cudf=0.4.0
#...
#Preparing transaction: done
#Verifying transaction: done
#Executing transaction: done
conda activate cudf
python -c 'import cudf'
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jan/anaconda3/envs/cudf/lib/python3.6/site-packages/cudf/__init__.py", line 2, in <module>
    from cudf import dataframe             # noqa: F401
  File "/home/jan/anaconda3/envs/cudf/lib/python3.6/site-packages/cudf/dataframe/__init__.py", line 1, in <module>
    from cudf.dataframe import (buffer, dataframe, series,  # noqa: F401
  File "/home/jan/anaconda3/envs/cudf/lib/python3.6/site-packages/cudf/dataframe/dataframe.py", line 18, in <module>
    from cudf import formatting, _gdf
  File "/home/jan/anaconda3/envs/cudf/lib/python3.6/site-packages/cudf/_gdf.py", line 13, in <module>
    from libgdf_cffi import ffi, libgdf
  File "/home/jan/anaconda3/envs/cudf/lib/python3.6/site-packages/libgdf_cffi/__init__.py", line 30, in <module>
    libgdf_api = ffi.dlopen(_get_lib_name())
OSError: cannot load library 'libcudf.so': /home/jan/anaconda3/envs/cudf/lib/python3.6/site-packages/../../libcudf.so: undefined symbol: _ZN9NVStrings17create_from_indexEPSt4pairIPKcmEjb
```
```sh
nvcc --version
#nvcc: NVIDIA (R) Cuda compiler driver
#Copyright (c) 2005-2018 NVIDIA Corporation
#Built on Tue_Jun_12_23:07:04_CDT_2018
#Cuda compilation tools, release 9.2, V9.2.148
```

I was initially using CUDA toolkit 10.0 but I was getting error related to 9.2 `cannot load library 'librmm.so': libcudart.so.9.2` so installed toolkit 9.2 and trying on it.

**Comment by datametrician** [comment]
@kkraus14 can someone from your team look into this?

**Comment by dantegd** [comment]
@kkraus14 this seems like its pulling no strings from conda with the wrong abi compatibility version?

**Comment by niviksha** [comment]
Anyone? I’m stuck trying to use this to build a demo

**Comment by dantegd** [comment]
@niviksha Installing nvstring 0.1.0 solves the issue for cuDF 0.4:

```
conda install -c nvidia nvstrings==0.1.0
conda install -c rapidsai -c numba -c conda-forge -c defaults cudf=0.4.0
```

**Comment by kkraus14** [comment]
This will be resolved by 0.5 release.

**Comment by jangorecki** [comment]
Thanks, looking forward for 0.5 release. If you would be willing to use milestones tags for issues it would be useful for users to see how much of work is left till release.

**Comment by goravkaul** [comment]
@kkraus14 any update on this? We are unable to use visualization because of this error. Thanks.
