### ISSUE TITLE
[BUG] Cuda Error: device-side assert triggered

### ISSUE THREAD

**Issue by jperez999** [rapidsai/cudf#7421]
On cudf 0.18 nightly ('0.18.0a+253.g53ed28e91c') I am experiencing some problems with pytorch and cudf when using dlpack.

The following code hangs for an extremely long time... then hits a RuntimeError: CUDA error: device-side assert triggered
```
import torch
import cudf
from torch.utils.dlpack import from_dlpack
df = cudf.datasets.randomdata(10000, dtypes={"label": bool})
for x in range(5):
    df.label = df.label.astype(int)
    tensor = from_dlpack(df["label"].to_dlpack()).type(torch.float32)
    print(tensor)
``` 

But with cupy it works as intended... full example takes less than 1 second.
```
import cudf
import cupy
df = cudf.datasets.randomdata(10000, dtypes={"label": bool})
for x in range(5):
    df.label = df.label.astype(int)
    tensor = cupy.fromDlpack(df["label"].to_dlpack())
    print(tensor)
```

**Comment by jrhemstad** [comment]
Was there an error message with the device-side assert?

**Comment by jperez999** [comment]
```
Traceback (most recent call last):
  File "bs.py", line 9, in <module>
    print(tensor)
  File "/opt/conda/lib/python3.8/site-packages/torch/tensor.py", line 179, in __repr__
    return torch._tensor_str._str(self)
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor_str.py", line 372, in _str
    return _str_intern(self)
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor_str.py", line 352, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor_str.py", line 241, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/opt/conda/lib/python3.8/site-packages/torch/_tensor_str.py", line 101, in __init__
    if value != torch.ceil(value):
   ```

**Comment by jperez999** [comment]
We are also seeing some thrust related invalid global reads
```========= Invalid __global__ read of size 8
=========     at 0x00000088 in void thrust::cuda_cub::core::_kernel_agent<thrust::cuda_cub::__merge_sort::BlockSortAgent<thrust::device_ptr<long>, thrust::device_ptr<long>, long, ThrustLTOp<long, bool=0>, thrust::detail::integral_constant<bool, bool=1>, thrust::detail::integral_constant<bool, bool=0>>, bool, thrust::device_ptr<long>, thrust::device_ptr<long>, long, long*, long*, ThrustLTOp<long, bool=0>>(thrust::device_ptr<long>, thrust::device_ptr<long>, long, long, bool=0, ThrustLTOp<long, bool=0>, bool)
```
And invalid shared writes
```
========= Invalid __shared__ write of size 8
=========     at 0x00007378 in void thrust::cuda_cub::core::_kernel_agent<thrust::cuda_cub::__merge_sort::BlockSortAgent<thrust::device_ptr<long>, thrust::device_ptr<long>, long, ThrustLTOp<long, bool=0>, thrust::detail::integral_constant<bool, bool=1>, thrust::detail::integral_constant<bool, bool=0>>, bool, thrust::device_ptr<long>, thrust::device_ptr<long>, long, long*, long*, ThrustLTOp<long, bool=0>>(thrust::device_ptr<long>, thrust::device_ptr<long>, long, long, bool=0, ThrustLTOp<long, bool=0>, bool)
```
with from_dlpack out of torch

**Comment by kkraus14** [comment]
The `dlpack` and `randomdata` functions haven't been touched in a couple of releases where I'd guess this is a PyTorch issue.

**Comment by jperez999** [comment]
Perfect that is exactly what I needed to verify. It seems like an issue with pytorch but wanted to be safe. Thanks.

**Comment by kkraus14** [comment]
Will keep this open for now, but please let us know if there's pushback pointed towards cuDF.

**Comment by harrism** [comment]
@jperez999 Was a PyTorch issue filed or is this still an issue?

**Comment by jrhemstad** [comment]
Closing this. @jperez999 please reopen if this is still an issue.
