### ISSUE TITLE
[BUG] AttributeError: module 'pyarrow.lib' has no attribute '_CRecordBatchReader'

### ISSUE THREAD

**Issue by Pokiharena** [rapidsai/cudf#7860]
Hi,
I'm using cuml and cudf for a school project and I came across the following error (describe after) the error looks similar to #7224 but in my case pyarrow 1.0.1 is installed.
**Describe the bug**
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/python3.8/site-packages/cudf/__init__.py", line 11, in <module>
    from cudf import core, datasets, testing
  File "/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/python3.8/site-packages/cudf/core/__init__.py", line 3, in <module>
    from cudf.core import buffer, column, column_accessor, common
  File "/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/python3.8/site-packages/cudf/core/column/__init__.py", line 3, in <module>
    from cudf.core.column.categorical import CategoricalColumn
  File "/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/python3.8/site-packages/cudf/core/column/categorical.py", line 22, in <module>
    from cudf import _lib as libcudf
  File "/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/python3.8/site-packages/cudf/_lib/__init__.py", line 4, in <module>
    from . import (
  File "cudf/_lib/gpuarrow.pyx", line 1, in init cudf._lib.gpuarrow
AttributeError: module 'pyarrow.lib' has no attribute '_CRecordBatchReader'
```
**Steps/Code to reproduce bug**
I installed cudf using:
```bash
conda create -n rapids-0.18 -c rapidsai -c nvidia -c conda-forge \
    -c defaults rapids=0.18 python=3.8 cudatoolkit=11.0
```
and open python using `python` and try to `import cudf` inside.

**Expected behavior**
I expect cudf to be imported.

**Environment overview**
 - Environment location: [Bare-metal]
 - Method of cuDF install: [conda]

**Environment details**
Sorry for the Cpu's description in French
```bash
  **git***
     Not inside a git repository
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
     NAME="Ubuntu"
     VERSION="18.04.5 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.5 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux john6 4.15.0-140-generic #144-Ubuntu SMP Fri Mar 19 14:12:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Mon Apr  5 22:12:49 2021
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  GeForce RTX 3090    On   | 00000000:65:00.0 Off |                  N/A |
     |  0%   49C    P8    31W / 370W |     23MiB / 24268MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |    0   N/A  N/A      2438      G   /usr/lib/xorg/Xorg                  9MiB |
     |    0   N/A  N/A      2471      G   /usr/bin/gnome-shell               12MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture :                          x86_64
     Mode(s) opératoire(s) des processeurs : 32-bit, 64-bit
     Boutisme :                              Little Endian
     Processeur(s) :                         4
     Liste de processeur(s) en ligne :       0-3
     Thread(s) par cœur :                    1
     Cœur(s) par socket :                    4
     Socket(s) :                             1
     Nœud(s) NUMA :                          1
     Identifiant constructeur :              GenuineIntel
     Famille de processeur :                 6
     Modèle :                                85
     Nom de modèle :                         Intel(R) Xeon(R) W-2104 CPU @ 3.20GHz
     Révision :                              4
     Vitesse du processeur en MHz :          1567.079
     Vitesse maximale du processeur en MHz : 3200,0000
     Vitesse minimale du processeur en MHz : 1200,0000
     BogoMIPS :                              6399.96
     Virtualisation :                        VT-x
     Cache L1d :                             32K
     Cache L1i :                             32K
     Cache L2 :                              1024K
     Cache L3 :                              8448K
     Nœud NUMA 0 de processeur(s) :          0-3
     Drapaux :                               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req md_clear flush_l1d
     
     ***CMake***
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     
     ***Python***
     /usr/users/intercell/projrapids20/.conda/envs/pfe/bin/python
     Python 3.8.8
     
     ***Environment Variables***
     PATH                            : /usr/users/intercell/projrapids20/.conda/envs/pfe/bin:/opt/miniconda3/bin:/opt/miniconda3/condabin:.:/opt/miniconda3/bin:/opt/anaconda3/bin:.:/opt/anaconda3/bin:/opt/anaconda3/bin:.:/opt/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /usr/users/intercell/projrapids20/.conda/envs/pfe
     PYTHON_PATH                     :
     
     ***conda packages***
     /opt/miniconda3/bin/conda
     # packages in environment at /usr/users/intercell/projrapids20/.conda/envs/pfe:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       1_gnu    conda-forge
     abseil-cpp                20200923.3           h9c3ff4c_0    conda-forge
     aiohttp                   3.7.4            py38h497a2fe_0    conda-forge
     anyio                     2.2.0            py38h578d9bd_0    conda-forge
     appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
     argon2-cffi               20.1.0           py38h497a2fe_2    conda-forge
     arrow-cpp                 1.0.1           py38h5d4dd6c_35_cuda    conda-forge
     arrow-cpp-proc            3.0.0                      cuda    conda-forge
     async-timeout             3.0.1                   py_1000    conda-forge
     async_generator           1.10                       py_0    conda-forge
     attrs                     20.3.0             pyhd3deb0d_0    conda-forge
     aws-c-cal                 0.4.5                h76129ab_8    conda-forge
     aws-c-common              0.5.2                h7f98852_0    conda-forge
     aws-c-event-stream        0.2.7                h6bac3ce_1    conda-forge
     aws-c-io                  0.9.1                ha5b09cb_1    conda-forge
     aws-checksums             0.1.11               h99e32c3_3    conda-forge
     aws-sdk-cpp               1.8.151              hceb1b1e_1    conda-forge
     backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
     backports                 1.0                        py_2    conda-forge
     backports.functools_lru_cache 1.6.3              pyhd8ed1ab_0    conda-forge
     bleach                    3.3.0              pyh44b312d_0    conda-forge
     bokeh                     2.2.3            py38h578d9bd_0    conda-forge
     boost                     1.72.0           py38h1e42940_1    conda-forge
     boost-cpp                 1.72.0               h9d3c048_4    conda-forge
     brotli                    1.0.9                h9c3ff4c_4    conda-forge
     brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
     bzip2                     1.0.8                h7f98852_4    conda-forge
     c-ares                    1.17.1               h7f98852_1    conda-forge
     ca-certificates           2020.12.5            ha878542_0    conda-forge
     cairo                     1.16.0            h6cf1ce9_1008    conda-forge
     certifi                   2020.12.5        py38h578d9bd_1    conda-forge
     cffi                      1.14.5           py38ha65f79e_0    conda-forge
     cfitsio                   3.470                hb418390_7    conda-forge
     chardet                   4.0.0            py38h578d9bd_1    conda-forge
     click                     7.1.2              pyh9f0ad1d_0    conda-forge
     click-plugins             1.1.1                      py_0    conda-forge
     cligj                     0.7.1              pyhd8ed1ab_0    conda-forge
     cloudpickle               1.6.0                      py_0    conda-forge
     colorcet                  2.0.6              pyhd8ed1ab_0    conda-forge
     cryptography              3.4.7            py38ha5dfef3_0    conda-forge
     cudatoolkit               11.0.221             h6bb024c_0    nvidia
     cudf                      0.18.1          cuda_11.0_py38_g999be56c80_0    rapidsai
     cudf_kafka                0.18.1          py38_g999be56c80_0    rapidsai
     cudnn                     8.0.0                cuda11.0_0    nvidia
     cugraph                   0.18.0          py38_g65ec965f_0    rapidsai
     cuml                      0.18.0          cuda11.0_py38_gb5f59e005_0    rapidsai
     cupy                      8.0.0            py38hb7c6141_0    rapidsai
     curl                      7.76.0               h979ede3_0    conda-forge
     cusignal                  0.18.0          py38_g42899d2_0    rapidsai
     cuspatial                 0.18.0          py38_gf4da460_0    rapidsai
     custreamz                 0.18.1          py38_g999be56c80_0    rapidsai
     cuxfilter                 0.18.0          py38_gac6f488_0    rapidsai
     cyrus-sasl                2.1.27               h3274739_1    conda-forge
     cytoolz                   0.11.0           py38h497a2fe_3    conda-forge
     dask                      2021.4.0           pyhd8ed1ab_0    conda-forge
     dask-core                 2021.4.0           pyhd8ed1ab_0    conda-forge
     dask-cuda                 0.18.0                   py38_0    rapidsai
     dask-cudf                 0.18.1          py38_g999be56c80_0    rapidsai
     datashader                0.11.1             pyh9f0ad1d_0    conda-forge
     datashape                 0.5.4                      py_1    conda-forge
     decorator                 5.0.5              pyhd8ed1ab_0    conda-forge
     defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
     distributed               2021.4.0         py38h578d9bd_0    conda-forge
     dlpack                    0.3                  he1b5a44_1    conda-forge
     entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
     expat                     2.3.0                h9c3ff4c_0    conda-forge
     faiss-proc                1.0.0                      cuda    conda-forge
     fastavro                  1.3.5            py38h497a2fe_0    conda-forge
     fastrlock                 0.6              py38h709712a_0    conda-forge
     fiona                     1.8.18           py38h37fbd03_0    conda-forge
     fontconfig                2.13.1            hba837de_1004    conda-forge
     freetype                  2.10.4               h0708190_1    conda-forge
     freexl                    1.0.6                h7f98852_0    conda-forge
     fsspec                    0.8.7              pyhd8ed1ab_0    conda-forge
     gdal                      3.1.4            py38h25844d8_3    conda-forge
     geopandas                 0.8.1                      py_0    conda-forge
     geos                      3.8.1                he1b5a44_0    conda-forge
     geotiff                   1.6.0                h5d11630_3    conda-forge
     gettext                   0.19.8.1          h0b5b191_1005    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     giflib                    5.2.1                h36c2ea0_2    conda-forge
     glog                      0.4.0                h49b9bf7_3    conda-forge
     grpc-cpp                  1.36.4               hf89561c_1    conda-forge
     hdf4                      4.2.13            h10796ff_1004    conda-forge
     hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     icu                       68.1                 h58526e2_0    conda-forge
     idna                      2.10               pyh9f0ad1d_0    conda-forge
     importlib-metadata        3.10.0           py38h578d9bd_0    conda-forge
     ipykernel                 5.5.3            py38hd0cf306_0    conda-forge
     ipython                   7.22.0           py38hd0cf306_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
     jedi                      0.18.0           py38h578d9bd_2    conda-forge
     jinja2                    2.11.3             pyh44b312d_0    conda-forge
     joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
     jpeg                      9d                   h36c2ea0_0    conda-forge
     json-c                    0.13.1            hbfbb72e_1002    conda-forge
     jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
     jupyter-server-proxy      3.0.2              pyhd8ed1ab_0    conda-forge
     jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
     jupyter_core              4.7.1            py38h578d9bd_0    conda-forge
     jupyter_server            1.5.1            py38h578d9bd_0    conda-forge
     jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
     jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
     kealib                    1.4.14               hcc255d8_2    conda-forge
     krb5                      1.17.2               h926e7f8_0    conda-forge
     lcms2                     2.12                 hddcbb42_0    conda-forge
     ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
     libblas                   3.9.0                8_openblas    conda-forge
     libcblas                  3.9.0                8_openblas    conda-forge
     libcudf                   0.18.1          cuda11.0_g999be56c80_0    rapidsai
     libcudf_kafka             0.18.1            g999be56c80_0    rapidsai
     libcugraph                0.18.0          cuda11.0_g65ec965f_0    rapidsai
     libcuml                   0.18.0          cuda11.0_gb5f59e005_0    rapidsai
     libcumlprims              0.18.0          cuda11.0_g5939d3e_0    nvidia
     libcurl                   7.76.0               hc4aaa36_0    conda-forge
     libcuspatial              0.18.0          cuda11.0_gf4da460_0    rapidsai
     libdap4                   3.20.6               hd7c4107_2    conda-forge
     libedit                   3.1.20191231         he28a2e2_2    conda-forge
     libev                     4.33                 h516909a_1    conda-forge
     libevent                  2.1.10               hcdb4288_3    conda-forge
     libfaiss                  1.6.3           h328c4c8_3_cuda    conda-forge
     libffi                    3.3                  h58526e2_2    conda-forge
     libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
     libgcrypt                 1.9.2                h7f98852_0    conda-forge
     libgdal                   3.1.4                h96b6e7a_3    conda-forge
     libgfortran-ng            9.3.0               hff62375_18    conda-forge
     libgfortran5              9.3.0               hff62375_18    conda-forge
     libglib                   2.68.0               h3e27bee_2    conda-forge
     libgomp                   9.3.0               h2828fa1_18    conda-forge
     libgpg-error              1.42                 h9c3ff4c_0    conda-forge
     libgsasl                  1.8.0                         2    conda-forge
     libhwloc                  2.3.0                h5e5b7d1_1    conda-forge
     libiconv                  1.16                 h516909a_0    conda-forge
     libkml                    1.3.0             hd79254b_1012    conda-forge
     liblapack                 3.9.0                8_openblas    conda-forge
     libllvm10                 10.0.1               he513fc3_3    conda-forge
     libnetcdf                 4.7.4           nompi_h56d31a8_107    conda-forge
     libnghttp2                1.43.0               h812cca2_0    conda-forge
     libntlm                   1.4               h7f98852_1002    conda-forge
     libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
     libpng                    1.6.37               h21135ba_2    conda-forge
     libpq                     12.3                 h255efa7_3    conda-forge
     libprotobuf               3.15.7               h780b84a_0    conda-forge
     librdkafka                1.5.3                hc49e61c_1    conda-forge
     librmm                    0.18.0          cuda11.0_ga4ee6b7_0    rapidsai
     librttopo                 1.1.0                hb271727_4    conda-forge
     libsodium                 1.0.18               h36c2ea0_1    conda-forge
     libspatialindex           1.9.3                h9c3ff4c_3    conda-forge
     libspatialite             5.0.1                h6ec7341_0    conda-forge
     libssh2                   1.9.0                ha56f1ee_6    conda-forge
     libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
     libthrift                 0.14.1               he6d91bd_1    conda-forge
     libtiff                   4.2.0                hdc55705_0    conda-forge
     libutf8proc               2.6.1                h7f98852_0    conda-forge
     libuuid                   2.32.1            h7f98852_1000    conda-forge
     libuv                     1.41.0               h7f98852_0    conda-forge
     libwebp                   1.2.0                h3452ae3_0    conda-forge
     libwebp-base              1.2.0                h7f98852_2    conda-forge
     libxcb                    1.13              h7f98852_1003    conda-forge
     libxgboost                1.3.3dev.rapidsai0.18      cuda11.0_0    rapidsai
     libxml2                   2.9.10               h72842e0_3    conda-forge
     llvmlite                  0.36.0           py38h4630a5e_0    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
     markdown                  3.3.4              pyhd8ed1ab_0    conda-forge
     markupsafe                1.1.1            py38h497a2fe_3    conda-forge
     mistune                   0.8.4           py38h497a2fe_1003    conda-forge
     msgpack-python            1.0.2            py38h1fd1430_1    conda-forge
     multidict                 5.1.0            py38h497a2fe_1    conda-forge
     multipledispatch          0.6.0                      py_0    conda-forge
     munch                     2.5.0                      py_0    conda-forge
     nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
     nbconvert                 6.0.7            py38h578d9bd_3    conda-forge
     nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
     nccl                      2.7.8.1            h4962215_100    nvidia
     ncurses                   6.2                  h58526e2_4    conda-forge
     nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
     networkx                  2.5                        py_0    conda-forge
     nodejs                    14.15.4              h92b4a50_1    conda-forge
     notebook                  6.3.0            py38h578d9bd_0    conda-forge
     numba                     0.53.1           py38h0e12cce_0    conda-forge
     numpy                     1.20.2           py38h9894fe3_0    conda-forge
     nvtx                      0.2.3            py38h497a2fe_0    conda-forge
     olefile                   0.46               pyh9f0ad1d_1    conda-forge
     openjpeg                  2.4.0                hf7af979_0    conda-forge
     openssl                   1.1.1k               h7f98852_0    conda-forge
     orc                       1.6.7                heec2584_1    conda-forge
     packaging                 20.9               pyh44b312d_0    conda-forge
     pandas                    1.1.5            py38h51da96c_0    conda-forge
     pandoc                    2.12                 h7f98852_0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     panel                     0.10.3             pyhd8ed1ab_0    conda-forge
     param                     1.10.1             pyhd3deb0d_0    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.8.2              pyhd8ed1ab_0    conda-forge
     partd                     1.1.0                      py_0    conda-forge
     pcre                      8.44                 he1b5a44_0    conda-forge
     pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
     pickleshare               0.7.5                   py_1003    conda-forge
     pillow                    8.1.2            py38ha0e1e83_0    conda-forge
     pip                       21.0.1             pyhd8ed1ab_0    conda-forge
     pixman                    0.40.0               h36c2ea0_0    conda-forge
     poppler                   0.89.0               h2de54a5_5    conda-forge
     poppler-data              0.4.10                        0    conda-forge
     postgresql                12.3                 hc2f5b80_3    conda-forge
     proj                      7.1.1                h966b41f_3    conda-forge
     prometheus_client         0.10.0             pyhd8ed1ab_0    conda-forge
     prompt-toolkit            3.0.18             pyha770c72_0    conda-forge
     protobuf                  3.15.7           py38h709712a_0    conda-forge
     psutil                    5.8.0            py38h497a2fe_1    conda-forge
     pthread-stubs             0.4               h36c2ea0_1001    conda-forge
     ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
     py-xgboost                1.3.3dev.rapidsai0.18  cuda11.0py38_0    rapidsai
     pyarrow                   1.0.1           py38hb53058b_35_cuda    conda-forge
     pycparser                 2.20               pyh9f0ad1d_2    conda-forge
     pyct                      0.4.6                      py_0    conda-forge
     pyct-core                 0.4.6                      py_0    conda-forge
     pydeck                    0.5.0              pyh9f0ad1d_0    conda-forge
     pyee                      7.0.4              pyh9f0ad1d_0    conda-forge
     pygments                  2.8.1              pyhd8ed1ab_0    conda-forge
     pynvml                    8.0.4                      py_1    conda-forge
     pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
     pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
     pyppeteer                 0.2.2                      py_1    conda-forge
     pyproj                    2.6.1.post1      py38h56787f0_3    conda-forge
     pyrsistent                0.17.3           py38h497a2fe_2    conda-forge
     pysocks                   1.7.1            py38h578d9bd_3    conda-forge
     python                    3.8.8           hffdb5ce_0_cpython    conda-forge
     python-confluent-kafka    1.5.0            py38h1e0a361_0    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     python_abi                3.8                      1_cp38    conda-forge
     pytz                      2021.1             pyhd8ed1ab_0    conda-forge
     pyviz_comms               2.0.1              pyhd3deb0d_0    conda-forge
     pyyaml                    5.4.1            py38h497a2fe_0    conda-forge
     pyzmq                     22.0.3           py38h2035c66_1    conda-forge
     rapids                    0.18.0          cuda11.0_py38_g334c31e_223    rapidsai
     rapids-xgboost            0.18.0          cuda11.0_py38_g334c31e_223    rapidsai
     re2                       2021.04.01           h9c3ff4c_0    conda-forge
     readline                  8.0                  he28a2e2_2    conda-forge
     requests                  2.25.1             pyhd3deb0d_0    conda-forge
     rmm                       0.18.0          cuda_11.0_py38_ga4ee6b7_0    rapidsai
     rtree                     0.9.7            py38h02d302b_1    conda-forge
     s2n                       1.0.0                h9b69904_0    conda-forge
     scikit-learn              0.24.1           py38h658cfdd_0    conda-forge
     scipy                     1.6.2            py38h7b17777_0    conda-forge
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                49.6.0           py38h578d9bd_3    conda-forge
     shapely                   1.7.1            py38ha11d057_1    conda-forge
     simpervisor               0.4                pyhd8ed1ab_0    conda-forge
     six                       1.15.0             pyh9f0ad1d_0    conda-forge
     snappy                    1.1.8                he1b5a44_3    conda-forge
     sniffio                   1.2.0            py38h578d9bd_1    conda-forge
     sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
     spdlog                    1.7.0                hc9558a2_2    conda-forge
     sqlite                    3.35.4               h74cdb3f_0    conda-forge
     streamz                   0.6.2              pyh44b312d_0    conda-forge
     tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
     terminado                 0.9.4            py38h578d9bd_0    conda-forge
     testpath                  0.4.4                      py_0    conda-forge
     threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
     tiledb                    2.2.7                h91fcb0e_0    conda-forge
     tk                        8.6.10               h21135ba_1    conda-forge
     toolz                     0.11.1                     py_0    conda-forge
     tornado                   6.1              py38h497a2fe_1    conda-forge
     tqdm                      4.59.0             pyhd8ed1ab_0    conda-forge
     traitlets                 5.0.5                      py_0    conda-forge
     treelite                  1.0.0            py38hd08a91b_0    conda-forge
     treelite-runtime          1.0.0                    pypi_0    pypi
     typing-extensions         3.7.4.3                       0    conda-forge
     typing_extensions         3.7.4.3                    py_0    conda-forge
     tzcode                    2021a                h7f98852_1    conda-forge
     ucx                       1.9.0+gcd9efd3       cuda11.0_0    rapidsai
     ucx-proc                  1.0.0                       gpu    rapidsai
     ucx-py                    0.18.0          py38_gcd9efd3_0    rapidsai
     urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
     wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     websockets                8.1              py38h497a2fe_3    conda-forge
     wheel                     0.36.2             pyhd3deb0d_0    conda-forge
     widgetsnbextension        3.5.1            py38h578d9bd_4    conda-forge
     xarray                    0.17.0             pyhd8ed1ab_0    conda-forge
     xerces-c                  3.2.3                h9d8b166_2    conda-forge
     xgboost                   1.3.3dev.rapidsai0.18  cuda11.0py38_0    rapidsai
     xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
     xorg-libice               1.0.10               h7f98852_0    conda-forge
     xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
     xorg-libx11               1.7.0                h7f98852_0    conda-forge
     xorg-libxau               1.0.9                h7f98852_0    conda-forge
     xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
     xorg-libxext              1.3.4                h7f98852_1    conda-forge
     xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
     xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
     xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
     xorg-xproto               7.0.31            h7f98852_1007    conda-forge
     xz                        5.2.5                h516909a_1    conda-forge
     yaml                      0.2.5                h516909a_0    conda-forge
     yarl                      1.6.3            py38h497a2fe_1    conda-forge
     zeromq                    4.3.4                h9c3ff4c_0    conda-forge
     zict                      2.0.0                      py_0    conda-forge
     zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
     zlib                      1.2.11            h516909a_1010    conda-forge
     zstd                      1.4.9                ha95c52a_0    conda-forge
```

I think I'm missing something obvious but I'm unable to find what.
Please let me know if you need details more about our environments.
I hope my issue isn't flooding the git

Thanks a lot!

**Comment by galipremsagar** [comment]
It appears to be that you have `arrow-cpp-proc` installed, which comes with `3.0.0`, can remove it and get it a try:

```
conda remove arrow-cpp-proc --force
```

**Comment by Pokiharena** [comment]
Thanks for your answer.
I did the following
```bash
conda remove arrow-cpp-proc --force
```
And got the same AttributeError as previously.

**Comment by galipremsagar** [comment]
Looks like you might be having a pyarrow 3.0.0 `.so` file somewhere that is being linked, can you share the following output in python shell:

```python
import pyarrow as pa
print(pa.__version__)
```
and the following bash command output:

```
find /usr/users/intercell/projrapids20/.conda/envs/pfe/ -print | grep -i libarrow
```

**Comment by Pokiharena** [comment]
Indeed the pyarrow return:
```bash
>>> import pyarrow as pa
>>> print(pa.__version__)
3.0.0
```
and the bash command return:
```bash
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/libarrow_cuda.so.100
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/libarrow_cuda.so
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/libarrow.so.100
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/libarrow_dataset.so.100.1.0
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/libarrow_flight.so.100
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/libarrow.so
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/libarrow_python.so.100
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/libarrow_dataset.so
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/libarrow_dataset.so.100
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/libarrow_flight.so.100.1.0
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/python3.8/site-packages/pyarrow/includes/libarrow_flight.pxd
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/python3.8/site-packages/pyarrow/includes/libarrow_fs.pxd
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/python3.8/site-packages/pyarrow/includes/libarrow.pxd
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/python3.8/site-packages/pyarrow/includes/libarrow_dataset.pxd
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/python3.8/site-packages/pyarrow/includes/libarrow_cuda.pxd
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/libarrow_python_flight.so.100.1.0
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/libarrow_flight.so
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/libarrow_python.so.100.1.0
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/libarrow_python.so
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/libarrow_cuda.so.100.1.0
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/libarrow_python_flight.so.100
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/libarrow.so.100.1.0
/usr/users/intercell/projrapids20/.conda/envs/pfe/lib/libarrow_python_flight.so
```
Is it of any help?
Do you think the `3.0.0` was installed during the env creation or by something I installed before because during my trial and error to fix my issue I deleted the `/usr/users/intercell/projrapids20/.conda/envs/pfe/` folder?

**Comment by Pokiharena** [comment]
Hi,
I found the issue. I had the `3.0.0` pyarrow version install via pip on my machine outside conda. I uninstalled it with `pip uninstall pyarrow` outside conda env, and it worked. Maybe I don't understand conda, but why is my environment package installation overriding by an outside installation? 
Thanks for leading to the solution.

**Comment by galipremsagar** [comment]
This to me looks like a conda issue similar to this one: https://github.com/conda/conda/issues/7230

Maybe try upgrading conda to the latest ? and if this issue of global package interfering with a local install raising an issue with conda would be the way forward. Closing this issue, for now, please feel free to reopen/comment if you need more help on this one.
