### ISSUE TITLE
[BUG] Problems appending/concatting with empty dask_cudf dataframe

### ISSUE THREAD

**Issue by lastephey** [rapidsai/cudf#8014]
Hi cuDF developers,

**Describe the bug**

I think we've encountered a bug using dask_cudf. When trying to append one dataframe to an empty dataframe, the function fails. Likewise it fails when we try to concatenate two dataframes when one is empty. 

**Steps/Code to reproduce bug**

```
data1 = [[0,1], [1,2], [3,4]]

pdf1 = pd.DataFrame(data1, columns=['a', 'b'], dtype=int)
pdf2 = pd.DataFrame()

cdf1 = cudf.from_pandas(pdf1)
cdf2 = cudf.from_pandas(pdf2)

ddf1 = dask_cudf.from_cudf(cdf1, npartitions=2)
ddf2 = dask_cudf.from_cudf(cdf2, npartitions=2)
```

Try to append:
```
ddf3 = ddf2.append(ddf1)
```
Part of traceback:
```
/app/miniconda3/lib/python3.8/site-packages/cudf/core/dataframe.py in _reverse_op(fn)
     67 
     68 def _reverse_op(fn):
---> 69     return {
     70         "add": "radd",
     71         "radd": "add",

KeyError: '__eq__'
```

Try to concat:

```
ddf3 = dask_cudf.concat([ddf1, ddf2], axis=1)
```

Part of traceback:
```
ValueError: Unable to concatenate DataFrame with unknown division specifying axis=1
```

For completeness, if we try to concat along axis=0:
```
KeyError: '__eq__'
```

**Expected behavior**

I would expect the dask.dataframe, pandas or cuDF behavior where the function returns the non-empty dataframe. 

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: conda
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
   - You can find the dockerfile we're using here: https://hub.docker.com/layers/139510534/stephey/dask-gpu/2.0/images/sha256-c91de9cd744054678159afdb22c2fb60d5aff0800659c1e6f8330aff07a1cd39?context=explore 
   - Based on an nvidia cuda container with rapids installed via miniconda on top

**Environment details**

```
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     Not inside a git repository
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
     NAME="Ubuntu"
     VERSION="18.04.5 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.5 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux cgpu20 4.12.14-lp150.12.82-default #1 SMP Tue Nov 12 16:32:38 UTC 2019 (c939e24) x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Wed Apr 21 01:02:11 2021
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 11.0     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  A100-SXM4-40GB      Off  | 00000000:07:00.0 Off |                    0 |
     | N/A   28C    P0    59W / 400W |      0MiB / 40537MiB |      0%      Default |
     |                               |                      |             Disabled |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              256
     On-line CPU(s) list: 0-255
     Thread(s) per core:  2
     Core(s) per socket:  64
     Socket(s):           2
     NUMA node(s):        8
     Vendor ID:           AuthenticAMD
     CPU family:          23
     Model:               49
     Model name:          AMD EPYC 7742 64-Core Processor
     Stepping:            0
     CPU MHz:             1500.000
     CPU max MHz:         2250.0000
     CPU min MHz:         1500.0000
     BogoMIPS:            4491.65
     Virtualization:      AMD-V
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            512K
     L3 cache:            16384K
     NUMA node0 CPU(s):   0-15,128-143
     NUMA node1 CPU(s):   16-31,144-159
     NUMA node2 CPU(s):   32-47,160-175
     NUMA node3 CPU(s):   48-63,176-191
     NUMA node4 CPU(s):   64-79,192-207
     NUMA node5 CPU(s):   80-95,208-223
     NUMA node6 CPU(s):   96-111,224-239
     NUMA node7 CPU(s):   112-127,240-255
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd sev ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca
     
     ***CMake***
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2020 NVIDIA Corporation
     Built on Wed_Jul_22_19:09:09_PDT_2020
     Cuda compilation tools, release 11.0, V11.0.221
     Build cuda_11.0_bu.TC445_37.28845127_0
     
     ***Python***
     /app/miniconda3/bin/python
     Python 3.8.5
     
     ***Environment Variables***
     PATH                            : /opt/udiImage/modules/gpu/bin:/app/miniconda3/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/udiImage/bin
     LD_LIBRARY_PATH                 : /opt/udiImage/modules/gpu/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    :
     PYTHON_PATH                     :
     
     ***conda packages***
     /app/miniconda3/bin/conda
     # packages in environment at /app/miniconda3:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     abseil-cpp                20200225.2           he1b5a44_2    conda-forge
     arrow-cpp                 1.0.1           py38h9444e92_16_cuda    conda-forge
     arrow-cpp-proc            3.0.0                      cuda    conda-forge
     astropy                   4.1              py38h0b5ebd8_2    conda-forge
     aws-c-common              0.4.59               h36c2ea0_1    conda-forge
     aws-c-event-stream        0.1.6                had2084c_6    conda-forge
     aws-checksums             0.1.10               h4e93380_0    conda-forge
     aws-sdk-cpp               1.8.70               h57dc084_1    conda-forge
     backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
     backports                 1.0                        py_2    conda-forge
     backports.functools_lru_cache 1.6.1                      py_0    conda-forge
     blosc                     1.20.1               he1b5a44_0    conda-forge
     bokeh                     1.4.0            py38h32f6830_1    conda-forge
     boost-cpp                 1.72.0               h9d3c048_4    conda-forge
     brotli                    1.0.9                he1b5a44_3    conda-forge
     brotlipy                  0.7.0           py38h27cfd23_1003
     bzip2                     1.0.8                h516909a_3    conda-forge
     c-ares                    1.17.1               h36c2ea0_0    conda-forge
     ca-certificates           2020.12.5            ha878542_0    conda-forge
     certifi                   2020.12.5        py38h578d9bd_1    conda-forge
     cffi                      1.14.3           py38h261ae71_2
     chardet                   3.0.4           py38h06a4308_1003
     click                     7.1.2              pyh9f0ad1d_0    conda-forge
     cloudpickle               1.6.0                      py_0    conda-forge
     conda                     4.9.2            py38h578d9bd_0    conda-forge
     conda-package-handling    1.7.2            py38h03888b9_0
     cryptography              3.2.1            py38h3c74f83_1
     cudatoolkit               11.0.221             h6bb024c_0    nvidia
     cudf                      0.18.0a210226   cuda_11.0_py38_g1544474166_254    rapidsai-nightly
     cudnn                     8.0.0                cuda11.0_0    nvidia
     cupy                      8.0.0            py38hb7c6141_0    rapidsai-nightly
     cycler                    0.10.0                     py_2    conda-forge
     cytoolz                   0.11.0           py38h25fe258_1    conda-forge
     dask                      2021.2.0           pyhd8ed1ab_0    conda-forge
     dask-core                 2021.2.0           pyhd8ed1ab_0    conda-forge
     dask-cuda                 0.19.0a210301           py38_34    rapidsai-nightly
     dask-cudf                 0.18.0a210226   py38_g1544474166_254    rapidsai-nightly
     decorator                 4.4.2                      py_0    conda-forge
     distributed               2021.2.0         py38h578d9bd_0    conda-forge
     dlpack                    0.3                  he1b5a44_1    conda-forge
     fastavro                  1.2.0            py38h25fe258_0    conda-forge
     fastrlock                 0.5              py38h950e882_1    conda-forge
     freetype                  2.10.4               h7ca028e_0    conda-forge
     fsspec                    0.8.7              pyhd8ed1ab_0    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     glog                      0.4.0                h49b9bf7_3    conda-forge
     grpc-cpp                  1.33.2               h1870a98_1    conda-forge
     hdf5                      1.10.6          nompi_h7c3c948_1111    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     icu                       68.1                 h58526e2_0    conda-forge
     idna                      2.10                       py_0
     ipykernel                 5.5.0            py38h81c977d_1    conda-forge
     ipython                   7.21.0           py38h81c977d_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     jedi                      0.18.0           py38h578d9bd_2    conda-forge
     jinja2                    2.11.3             pyh44b312d_0    conda-forge
     jpeg                      9d                   h36c2ea0_0    conda-forge
     jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
     jupyter_core              4.7.1            py38h578d9bd_0    conda-forge
     kiwisolver                1.3.1            py38h82cb98a_0    conda-forge
     krb5                      1.17.2               h926e7f8_0    conda-forge
     lcms2                     2.11                 hcbb858e_1    conda-forge
     ld_impl_linux-64          2.33.1               h53a641e_7
     libblas                   3.9.0                8_openblas    conda-forge
     libcblas                  3.9.0                8_openblas    conda-forge
     libcudf                   0.18.0a210226   cuda11.0_g1544474166_254    rapidsai-nightly
     libcurl                   7.71.1               hcdd3856_3    conda-forge
     libedit                   3.1.20191231         h14c3975_1
     libevent                  2.1.10               hcdb4288_3    conda-forge
     libffi                    3.3                  he6710b0_2
     libgcc-ng                 9.1.0                hdf63c60_0
     libgfortran-ng            7.5.0               h14aa051_18    conda-forge
     libgfortran4              7.5.0               h14aa051_18    conda-forge
     liblapack                 3.9.0                8_openblas    conda-forge
     libllvm10                 10.0.1               he513fc3_3    conda-forge
     libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
     libpng                    1.6.37               h21135ba_2    conda-forge
     libprotobuf               3.13.0.1             h8b12597_0    conda-forge
     librmm                    0.18.0a210226   cuda11.0_gb9e0cd3_37    rapidsai-nightly
     libsodium                 1.0.18               h36c2ea0_1    conda-forge
     libssh2                   1.9.0                hab1572f_5    conda-forge
     libstdcxx-ng              9.1.0                hdf63c60_0
     libthrift                 0.13.0               h5aa387f_6    conda-forge
     libtiff                   4.1.0                hc3755c2_3    conda-forge
     libutf8proc               2.6.0                h36c2ea0_0    conda-forge
     llvmlite                  0.34.0           py38h4f45e52_2    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.9.2                he1b5a44_3    conda-forge
     lzo                       2.10              h516909a_1000    conda-forge
     markupsafe                1.1.1            py38h8df0ef7_2    conda-forge
     matplotlib                3.3.2                         0    conda-forge
     matplotlib-base           3.3.2            py38h5c7f4ab_1    conda-forge
     mock                      4.0.3            py38h578d9bd_1    conda-forge
     msgpack-python            1.0.0            py38h82cb98a_2    conda-forge
     nccl                      2.7.8.1            h4962215_100    nvidia
     ncurses                   6.2                  he6710b0_1
     numba                     0.51.2           py38hc5bc63f_0    conda-forge
     numexpr                   2.7.1            py38hc5bc63f_3    conda-forge
     numpy                     1.19.4           py38hf0fd68c_1    conda-forge
     nvtx                      0.2.1            py38h1e0a361_2    conda-forge
     olefile                   0.46               pyh9f0ad1d_1    conda-forge
     openssl                   1.1.1h               h516909a_0    conda-forge
     orc                       1.6.5                hd3605a7_0    conda-forge
     packaging                 20.9               pyh44b312d_0    conda-forge
     pandas                    1.1.4            py38h0ef3d22_0    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.8.1              pyhd8ed1ab_0    conda-forge
     partd                     1.1.0                      py_0    conda-forge
     patsy                     0.5.1                      py_0    conda-forge
     pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
     pickleshare               0.7.5                   py_1003    conda-forge
     pillow                    8.0.1            py38h70fbd49_0    conda-forge
     pip                       20.2.4           py38h06a4308_0
     prompt-toolkit            3.0.16             pyha770c72_0    conda-forge
     protobuf                  3.13.0.1         py38hadf7658_1    conda-forge
     psutil                    5.7.3            py38h8df0ef7_0    conda-forge
     ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
     pyarrow                   1.0.1           py38h3e2403a_16_cuda    conda-forge
     pycosat                   0.6.3            py38h7b6447c_1
     pycparser                 2.20                       py_2
     pygments                  2.8.0              pyhd8ed1ab_0    conda-forge
     pynvml                    8.0.4                      py_1    conda-forge
     pyopenssl                 19.1.0             pyhd3eb1b0_1
     pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
     pysocks                   1.7.1            py38h06a4308_0
     pytables                  3.6.1            py38hf9f05d5_3    conda-forge
     python                    3.8.5                h7579374_1
     python-dateutil           2.8.1                      py_0    conda-forge
     python_abi                3.8                      1_cp38    conda-forge
     pytz                      2021.1             pyhd8ed1ab_0    conda-forge
     pyyaml                    5.3.1            py38h8df0ef7_1    conda-forge
     pyzmq                     20.0.0           py38h1d1b12f_1    conda-forge
     re2                       2020.11.01           h58526e2_0    conda-forge
     readline                  8.0                  h7b6447c_0
     requests                  2.24.0                     py_0
     rmm                       0.18.0a210226   cuda_11.0_py38_gb9e0cd3_37    rapidsai-nightly
     ruamel_yaml               0.15.87          py38h7b6447c_1
     scipy                     1.5.3            py38h828c644_0    conda-forge
     seaborn                   0.11.1               hd8ed1ab_1    conda-forge
     seaborn-base              0.11.1             pyhd8ed1ab_1    conda-forge
     setuptools                50.3.1           py38h06a4308_1
     six                       1.15.0           py38h06a4308_0
     snappy                    1.1.8                he1b5a44_3    conda-forge
     sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
     spdlog                    1.7.0                hc9558a2_2    conda-forge
     sqlite                    3.33.0               h62c20be_0
     statsmodels               0.12.1           py38h0b5ebd8_1    conda-forge
     tblib                     1.6.0                      py_0    conda-forge
     tk                        8.6.10               hbc83047_0
     toolz                     0.11.1                     py_0    conda-forge
     tornado                   6.1              py38h25fe258_0    conda-forge
     tqdm                      4.51.0             pyhd3eb1b0_0
     traitlets                 5.0.5                      py_0    conda-forge
     typing_extensions         3.7.4.3                    py_0    conda-forge
     urllib3                   1.25.11                    py_0
     wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
     wheel                     0.35.1             pyhd3eb1b0_0
     xz                        5.2.5                h7b6447c_0
     yaml                      0.2.5                h7b6447c_0
     zeromq                    4.3.3                h58526e2_3    conda-forge
     zict                      2.0.0                      py_0    conda-forge
     zlib                      1.2.11               h7b6447c_3
     zstd                      1.4.5                h6597ccf_2    conda-forge
     
</pre></details>
```

**Additional context**

Thank you for your help,
Laurie

**Comment by beckernick** [comment]
Looks like we may not be properly handling some edge cases when the dtype is None and/or there are no column names.

It might be possible to temporarily work around this by specifying the column names and dtypes of the empty dataframe.

**Comment by galipremsagar** [comment]
> Looks like we may not be properly handling some edge cases when there are **no column names.**

Here is a minimal repro of the above issue: 

```python
>>> import cudf
>>> df = cudf.DataFrame({'a':[], 'b':[]})
>>> df1 = cudf.DataFrame()
>>> df1 == df
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.8/site-packages/cudf/core/dataframe.py", line 2461, in __eq__
    return self._apply_op("__eq__", other)
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.8/site-packages/cudf/core/dataframe.py", line 1498, in _apply_op
    result[col] = fallback(rhs[col], _reverse_op(fn))
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.8/site-packages/cudf/core/dataframe.py", line 70, in _reverse_op
    return {
KeyError: '__eq__'
>>> df1.to_pandas() == df.to_pandas()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.8/site-packages/pandas/core/ops/common.py", line 65, in new_method
    return method(self, other)
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.8/site-packages/pandas/core/arraylike.py", line 29, in __eq__
    return self._cmp_method(other, operator.eq)
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.8/site-packages/pandas/core/frame.py", line 5968, in _cmp_method
    self, other = ops.align_method_FRAME(self, other, axis, flex=False, level=None)
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.8/site-packages/pandas/core/ops/__init__.py", line 269, in align_method_FRAME
    raise ValueError(
ValueError: Can only compare identically-labeled DataFrame objects
```

dask upstream handles `ValueError` but not `KeyError`, ideally we should be raising a similar error type and message from cudf too. Fix incoming.

**Comment by lastephey** [comment]
Thank you very much for the quick fix!
