### ISSUE TITLE
[BUG] Bug related to recent change in the Distributed module

### ISSUE THREAD

**Issue by viclafargue** [rapidsai/cudf#8016]
**Describe the bug**
The `initialize` function from `dask_cudf` cannot be imported. The problem seems to be related to a recent change in the Distributed module. Indeed, the `weight` function [was recently removed](https://github.com/dask/distributed/commit/d5fc324bdef22f19d77c3d36e63a3778ceaac0b0#diff-0c7375c95aaa92986f8ed5460bae4e98720a14fca13556e01fd44ab6b927c24d).

**Steps/Code to reproduce bug**
```
>>> from dask_cuda import initialize
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/fs1/viclafargue/miniconda3/envs/cuml_dev/lib/python3.7/site-packages/dask_cuda/__init__.py", line 5, in <module>
    from .cuda_worker import CUDAWorker
  File "/gpfs/fs1/viclafargue/miniconda3/envs/cuml_dev/lib/python3.7/site-packages/dask_cuda/cuda_worker.py", line 21, in <module>
    from .device_host_file import DeviceHostFile
  File "/gpfs/fs1/viclafargue/miniconda3/envs/cuml_dev/lib/python3.7/site-packages/dask_cuda/device_host_file.py", line 19, in <module>
    from distributed.worker import weight
ImportError: cannot import name 'weight' from 'distributed.worker' (/gpfs/fs1/viclafargue/miniconda3/envs/cuml_dev/lib/python3.7/site-packages/distributed/worker.py)
```

**Expected behavior**
```
dask-cudf                 0.19.0a210420             py37_gcdf77047c6_363    rapidsai-nightly
distributed               2021.4.0+21.ge4b534af     pypi_0                  pypi
```

**Comment by beckernick** [comment]
This looks like a dask-cuda issue. Recommend transferring this issue to rapidsai/dask-cuda

**Comment by viclafargue** [comment]
Yes, you're right, my bad. People are already working on the issue anyway. I'll close this issue.
