### ISSUE TITLE
[FEA] Add support for writing dataframes containing decimal columns to orc writer

### ISSUE THREAD

**Issue by ChrisJar** [rapidsai/cudf#8159]
**Is your feature request related to a problem? Please describe.**
I'd would like to take a dataframe containing columns with type decimal and write it as an orc file. Currently when I try this:
```
s = cudf.Series(["2.1", "4.9", "3.4", "0.2"]).astype(Decimal64Dtype(7,2))
df = cudf.DataFrame({"val":s})
df.to_orc("test.orc")
```
I get:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-37-607d097fdab5> in <module>
----> 1 df.to_orc("test.orc")

~/anaconda3/envs/cudf_dev/lib/python3.8/site-packages/cudf/core/dataframe.py in to_orc(self, fname, compression, *args, **kwargs)
   7414         from cudf.io import orc as orc
   7415 
-> 7416         orc.to_orc(self, fname, compression, *args, **kwargs)
   7417 
   7418     def stack(self, level=-1, dropna=True):

~/anaconda3/envs/cudf_dev/lib/python3.8/site-packages/cudf/io/orc.py in to_orc(df, fname, compression, enable_statistics, **kwargs)
    325             liborc.write_orc(df, file_obj, compression, enable_statistics)
    326     else:
--> 327         liborc.write_orc(df, path_or_buf, compression, enable_statistics)
    328 
    329 

cudf/_lib/orc.pyx in cudf._lib.orc.write_orc()

cudf/_lib/orc.pyx in cudf._lib.orc.write_orc()

RuntimeError: cuDF failure at: /home/nfs/cjarrett/cudf/cpp/src/io/orc/writer_impl.cu:472: Unsupported ORC type kind
```

**Comment by randerzander** [comment]
@vuule if you try the snippet in this feature request, you get a failure:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rgelhausen/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/dataframe.py", line 7403, in to_orc
    orc.to_orc(self, fname, compression, *args, **kwargs)
  File "/home/rgelhausen/conda/envs/rapids/lib/python3.8/site-packages/cudf/io/orc.py", line 327, in to_orc
    liborc.write_orc(df, path_or_buf, compression, enable_statistics)
  File "cudf/_lib/orc.pyx", line 119, in cudf._lib.orc.write_orc
  File "cudf/_lib/orc.pyx", line 149, in cudf._lib.orc.write_orc
RuntimeError: cuDF failure at: ../src/io/orc/writer_impl.cu:472: Unsupported ORC type kind
```
