### ISSUE TITLE
AttributeError("'DataFrame' object has no attribute 'apply'")

### ISSUE THREAD

**Issue by aclifton314** [rapidsai/cudf#8242]
System: Red Hat Enterprise Linux Server release 7.7 (Maipo)
CUDA: 10.2
dask-cuda: 0.19.0
python: 3.7.10
GPU: 4 NVIDIA Titan V-100

I'm trying to use `dask_cudf.apply` on a dataframe but am getting the following error:
```
Traceback (most recent call last):
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask/dataframe/utils.py", line 175, in raise_on_meta_error
    yield
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask/dataframe/core.py", line 5510, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask/utils.py", line 900, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/cudf/core/dataframe.py", line 668, in __getattr__
    raise AttributeError("'DataFrame' object has no attribute %r" % key)
AttributeError: 'DataFrame' object has no attribute 'apply'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lcs_dask.py", line 99, in <module>
    new_strs = data_series.apply(process_text, axis=1, args=(run_type,))
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask/dataframe/core.py", line 4679, in apply
    M.apply, self._meta_nonempty, func, args=args, udf=True, **kwds
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask/dataframe/core.py", line 5510, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask/dataframe/utils.py", line 196, in raise_on_meta_error
    raise ValueError(msg) from e
ValueError: Metadata inference failed in `apply`.

You have supplied a custom function and Dask is unable to
determine the type of output that that function returns.

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
AttributeError("'DataFrame' object has no attribute 'apply'")

Traceback:
---------
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask/dataframe/utils.py", line 175, in raise_on_meta_error
    yield
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask/dataframe/core.py", line 5510, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask/utils.py", line 900, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/cudf/core/dataframe.py", line 668, in __getattr__
    raise AttributeError("'DataFrame' object has no attribute %r" % key)
```
Apologies for the newbie question, but am I going about this correctly? Here is a code example:
```python
import subprocess # we will use this to obtain our local IP using the following command
from dask_cuda import LocalCUDACluster
from dask.distributed import Client, progress
import dask_cudf
import spacy

if __name__ == "__main__":
    print('loading spacy model...')
    nlp = spacy.load('en_core_web_sm')
	
    def process_text(text: str, process_method: str):
        if 'no_punct_lower' in process_method:
            doc = nlp(text)
            new_strs_list = []
            proc_list = []
            for token in doc:
                if token.pos_ != 'PUNCT' and token.pos_ != 'SPACE':
                    proc_list.append(token.text.lower())
                new_strs_list.append(' '.join(proc_list))
            return dask_cudf.Series(new_strs_list)
        else:
            return text


    def setup_dask():
        cmd = "hostname --all-ip-addresses"
        process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
        output, error = process.communicate()
        IPADDR = str(output.decode()).split()[0]

        cluster = LocalCUDACluster(ip=IPADDR)
        client = Client(cluster)
        return cluster, client

    data_path = '/path/to/data.csv'

    print('reading data...')
    data_df = dask_cudf.read_csv(data_path, encoding='ISO-8859-1')

    print('setting up gpu_cluster and dask_client...')
    gpu_cluster, dask_client = setup_dask()

    run_types = ['raw', 'raw_no_punct_lower', 'lemma', 'lemma_no_punct_lower']

    for run_type in run_types:
	if 'raw' in run_type:
             data_series = data_df['raw'].to_frame()
        else:
             data_series = data_df['lemmatized'].to_frame()

        new_strs = data_series.apply(process_text, axis=1, args=(run_type,))
        new_strs.compute()
```

**Comment by jakirkham** [comment]
As this doesn't appear to be Dask-CUDA specific and appears to relate to cuDF or Dask-cuDF, have transferred to the cuDF repo.

**Comment by aclifton314** [comment]
@jakirkham Thank you for transferring this!

**Comment by aclifton314** [comment]
Does anyone have an idea about how to correct this error? I'm happy to provide more information if needed. Thanks in advance!

**Comment by vyasr** [comment]
Unfortunately I think this is just an issue of what you're trying not yet being supported. `cudf` supports some cases of applying user-defined functions (UDFs) using the `apply_rows` or `apply_chunks` methods for `DataFrame` or `applymap` for `Series`, but at the moment as far as I know that's restricted to numeric types (see [the docs here](https://docs.rapids.ai/api/cudf/stable/guide-to-udfs.html?highlight=udf#Series-UDFs)). There is work being done to support the `apply` method that you're trying more generally, but I don't know if that will support strings yet either (@brandon-b-miller would know better).

**Comment by brandon-b-miller** [comment]
`apply` won't initially support strings unfortunately. I think the bigger issue here is that the function is loading what looks like it might be a prebuilt model and then calling it on each row of the input data. Unfortunately we're probably a ways off from supporting that kind of functionality natively, and if we do at some point we'll probably need to do it through some kind of purposive API.

**Comment by beckernick** [comment]
If you change your function input to be a Series or the dataframe and a column name rather than an individual row, you can combine GPU spaCy with cuDF/Dask via `map_partitions`.

Something like:

```python
def ner_parser(df, col, batch_size=256):
    spacy.require_gpu()
    nlp = spacy.load("en_core_web_sm")
    docs = nlp.pipe(df[col], batch_size=batch_size)
    out = []
    for doc in docs:
        # do the per record processing and append to out
    df["out"] = out
    return df

ddf.map_partitions(ner_parser)
```

**Comment by aclifton314** [comment]
@beckernick Thank you for your reply! Does the setup below look correct?
```python
import subprocess
from dask_cuda import LocalCUDACluster
from dask.distributed import Client, progress
import dask_cudf
import spacy

if __name__ == "__main__":
    print('loading spacy model...')
    nlp = spacy.load('en_core_web_sm')
    spacy.require_gpu()

    def process_text(text_series, process_method: str, batch_size=256):
        if 'no_punct_lower' in process_method:
            docs = nlp.pipe(text_series, batch_size=batch_size)
            new_strs_list = []
            for doc in docs:
                proc_list = []
                for token in doc:
                    if token.pos_ != 'PUNCT' and token.pos_ != 'SPACE':
                        proc_list.append(token.text.lower())
                new_strs_list.append(' '.join(proc_list))
            return dask_cudf.Series(new_strs_list)
        else:
            return text_series

    def setup_dask():
        cmd = "hostname --all-ip-addresses"
        process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
        output, error = process.communicate()
        IPADDR = str(output.decode()).split()[0]

        cluster = LocalCUDACluster(ip=IPADDR)
        client = Client(cluster)
        return cluster, client

    data_path = '/path/to/data.csv'

    print('reading data...')
    data_df = dask_cudf.read_csv(data_path, encoding='ISO-8859-1')

    print('setting up gpu_cluster and dask_client...')
    gpu_cluster, dask_client = setup_dask()

    run_types = ['raw', 'raw_no_punct_lower', 'lemma', 'lemma_no_punct_lower']
    for run_type in run_types:
        if 'raw' in run_type:
            data_series = data_df['raw']
        else:
            data_series = data_df['lemmatized']
        
        data_df.map_partitions(process_text, data_series, run_type)

```

**Comment by beckernick** [comment]
`map_partitions` is generally designed to operate on data in the dataframe or series. I.e., the first argument to the function should be the dataframe or series itself. It will map the function to each partition (a cudf dataframe), so you should return a cudf.dataframe or series rather than a dask_cudf object.

You also may want to disable functionality in spacy you aren't using (such as NER)

**Comment by aclifton314** [comment]
@beckernick I'm a bit confused. In the previous example the only argument passed to `map_partitions` was the function `parser` which has 3 arguments passed to it, one of which appears to need to be specified (`col`). I've simplified my working code example a bit. Have I missed anything?
```python
import subprocess
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
import dask_cudf
import spacy
import cudf

if __name__ == "__main__":
    print('loading spacy model...')
    nlp = spacy.load('en_core_web_sm')
    spacy.require_gpu()

    def process_text(text_series, process_method: str, batch_size=256):
        if 'no_punct_lower' in process_method:
            docs = nlp.pipe(text_series, batch_size=batch_size, disable=['parser', 'ner'])
            new_strs_list = []
            for doc in docs:
                proc_list = []
                for token in doc:
                    if token.pos_ != 'PUNCT' and token.pos_ != 'SPACE':
                        proc_list.append(token.text.lower())
                new_strs_list.append(' '.join(proc_list))
            return cudf.Series(new_strs_list)
        else:
            return cudf.from_pandas(text_series.to_pandas())

    def setup_dask():
        cmd = "hostname --all-ip-addresses"
        process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
        output, error = process.communicate()
        IPADDR = str(output.decode()).split()[0]

        cluster = LocalCUDACluster(ip=IPADDR)
        client = Client(cluster)
        return cluster, client

    data_path = '/path/to/data.csv'
    print('reading data...')
    data_df = dask_cudf.read_csv(data_path, encoding='ISO-8859-1')

    print('setting up gpu_cluster and dask_client...')
    gpu_cluster, dask_client = setup_dask()

    data_series = data_df['lemmatized']
    data_series.map_partitions(process_text, data_series, 'lemma')
```

**Comment by aclifton314** [comment]
@beckernick Thank you for the clarification. As far as setting up the cluster, I have 4 GPUs. Here is some info:
```
System: Red Hat Enterprise Linux Server release 7.7 (Maipo)
CUDA: 10.2
dask-cuda: 0.19.0
python: 3.7.10
GPU: 4 NVIDIA Titan V-100
```
Is there anything further that needs to be setup for the cluster via this function?
```python
    def setup_dask():
        cmd = "hostname --all-ip-addresses"
        process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
        output, error = process.communicate()
        IPADDR = str(output.decode()).split()[0]

        cluster = LocalCUDACluster(ip=IPADDR)
        client = Client(cluster)
        return cluster, client
gpu_cluster, dask_client = setup_dask()
```
Also, it looks like something is being changed when I call `map_partitions()`:
```python
(Pdb) text_series
0    cat
1    dog
Name: raw, dtype: object
(Pdb) type(text_series)
<class 'cudf.core.series.Series'>

(Pdb) data_series
<dask_cudf.Series | 2 tasks | 1 npartitions>
```

Calling `data_series.head()` shows my actual data, which is a description of automobile parts and not cat or dog.

**Comment by beckernick** [comment]
I've edited my comment above. Let me know if that example helps clear things up!

Assuming the IP address / port are accessible, 

```python
cluster = LocalCUDACluster...)
client = Client(cluster)
```

should create a cluster with your 4 GPUs

**Comment by aclifton314** [comment]
@beckernick Ok, I think I have incorporated everything:
```python
import dask_cudf
import cudf
import spacy
import subprocess
from dask_cuda import LocalCUDACluster
from dask.distributed import Client

if __name__ == "__main__":
    print('loading spacy model...')
    nlp = spacy.load('en_core_web_sm')
    spacy.require_gpu()

    def process_text(text_series, process_method: str, batch_size=256):
        if 'no_punct_lower' in process_method:
            docs = nlp.pipe(text_series.to_pandas(), batch_size=batch_size, disable=['parser', 'ner'])
            new_strs_list = []
            for doc in docs:
                proc_list = []
                for token in doc:
                    if token.pos_ != 'PUNCT' and token.pos_ != 'SPACE':
                        proc_list.append(token.text.lower())
                new_strs_list.append(' '.join(proc_list))
            return cudf.Series(new_strs_list)
        else:
            return text_series

    def setup_dask():
        cmd = "hostname --all-ip-addresses"
        process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
        output, error = process.communicate()
        IPADDR = str(output.decode()).split()[0]

        cluster = LocalCUDACluster(ip=IPADDR)
        client = Client(cluster)
        return cluster, client

    print('setting up gpu_cluster and dask_client...')
    gpu_cluster, dask_client = setup_dask()

    print('reading data...')
    data_path = '/path/to/data.csv'
    #data_df = dask_cudf.read_csv(data_path, encoding='ISO-8859-1')
    data_cudf = cudf.read_csv(data_path, encoding='ISO-8859-1')
    data_dask_df = dask_cudf.from_cudf(data_cudf, 1)

    run_type = 'lemma_no_punct_lower'
    data_series = data_dask_df['lemma']
    data_series.map_partitions(process_text, run_type).compute()
```
However, the data is still being changed somehow:
```
(Pdb) type(text_series)
<class 'cudf.core.series.Series'>
(Pdb) text_series
0    cat
1    dog
Name: raw, dtype: object

(Pdb) type(data_series)
<class 'dask_cudf.core.Series'>
(Pdb) data_series
<dask_cudf.Series | 2 tasks | 1 npartitions>
(Pdb)
```
calling `data_series.head()` does show the first few rows of the dataset I have (which are car part descriptions and not cat or dog). Any thoughts about what might be happening?

**Comment by beckernick** [comment]
The types looks right to me, with the caveat that I'm not sure what scope `text_series` is coming from. Inside your function, you're operating in "cudf land", so the individual data structures should be cudf series, numpy/cupy arrays, lists, etc. `data_series` is a dask cudf Series. 

Also regarding the following:
```
#data_df = dask_cudf.read_csv(data_path, encoding='ISO-8859-1')
data_cudf = cudf.read_csv(data_path, encoding='ISO-8859-1')
data_dask_df = dask_cudf.from_cudf(data_cudf, 1)
```

We recommend reading directly with dask_cudf. My example above used `from_cudf` as I created a dataframe in memory

**Comment by aclifton314** [comment]
@beckernick Thanks very much for your help. The code below:
```python
import dask_cudf
import cudf
import spacy
import subprocess
from dask_cuda import LocalCUDACluster
from dask.distributed import Client

if __name__ == "__main__":
    print('loading spacy model...')
    nlp = spacy.load('en_core_web_sm')
    spacy.require_gpu()

    def process_text(text_series, process_method: str, batch_size=256):
        if 'no_punct_lower' in process_method:
            print('In process_text(). Printing the input text_series.head()')
            print(text_series.head())
            docs = nlp.pipe(text_series.to_pandas(), batch_size=batch_size, disable=['parser', 'ner'])
            new_strs_list = []
            for doc in docs:
                proc_list = []
                for token in doc:
                    if token.pos_ != 'PUNCT' and token.pos_ != 'SPACE':
                        proc_list.append(token.text.lower())
                new_strs_list.append(' '.join(proc_list))
            return cudf.Series(new_strs_list)
        else:
            return text_series

    def setup_dask():
        cmd = "hostname --all-ip-addresses"
        process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
        output, error = process.communicate()
        IPADDR = str(output.decode()).split()[0]

        cluster = LocalCUDACluster(ip=IPADDR)
        client = Client(cluster)
        return cluster, client

    print('setting up gpu_cluster and dask_client...')
    gpu_cluster, dask_client = setup_dask()

    print('reading data...')
    #data_path = '/mnt/isilon/jca-ai-data-and-models/data/dataframes/JCAproto_test_0split.csv'
    data_path = '/path/to/data.csv'
    #data_df = dask_cudf.read_csv(data_path, encoding='ISO-8859-1')
    #data_cudf = cudf.read_csv(data_path, encoding='ISO-8859-1')
    #data_dask_df = dask_cudf.from_cudf(data_cudf, 1)
    data_dask_df = dask_cudf.read_csv(data_path, encoding='ISO-8859-1')
    
    run_type = 'lemma_no_punct_lower'
    data_series = data_dask_df['raw']
    print('Created data_series variable. Calling data_series.head()...')
    print(data_series.head())
    tmp = data_series.map_partitions(process_text, run_type).compute()
    print('Ran data_series.map_partitions(). Printing first few rows')
    print(tmp.head())
```

prints the following information:
```python

$ python lcs_dask.py
loading spacy model...
setting up gpu_cluster and dask_client...
reading data...
Created data_series variable. Calling data_series.head()...
0    SCREW, FLAT-100...
1    STRAIGHT PLUG, GROUNDED ...
2    CONNECTOR,FUEL...
3    CONNECTOR, ELECTRICAL, FUSE...
4    CONNECTOR 1 1 Material -...
Name: raw, dtype: object

In process_text(). Printing the input text_series
0    cat
1    dog
Name: raw, dtype: object

In process_text(). Printing the input text_series
0    SCREW, FLAT-100...
1    STRAIGHT PLUG, GROUNDED ...
2    CONNECTOR,FUEL...
3    CONNECTOR, ELECTRICAL, FUSE...
4    CONNECTOR 1 1 Material -...
Name: raw, dtype: object

Ran data_series.map_partitions(). Printing first few rows
0    screw flat-100 cr...
1    straight plug grounded ...
2    connector fuel...
3    connector electrical fuse...
4    connector 1 1 material ...
dtype: object
```

So it appears that it's working, despite the first call to `data_series.map_partitions(process_text, run_type).compute()` producing: 
```python
0    cat
1    dog
Name: raw, dtype: object
```

**Comment by beckernick** [comment]
Great! I misunderstood what you were asking earlier. The reason you see "cat" and "dog" is that Dask needs to "infer" the correct metadata for the custom function executed via map_partitions. So the library is created a two row Series of strings (in this case) to use as a test run. If you explicitly tell Dask what the output metadata should be, this won't happen.

For example, using the metadata of the original series. `data_series.map_partitions(process_text, run_type).compute()` vs. `data_series.map_partitions(process_text, run_type, meta=data_series._meta).compute()`

Also note that `compute` brings the results to a single GPU in the client process. Unless this is the goal, you should use `persist` and store the result in memory or write the results somewhere

**Comment by aclifton314** [comment]
@beckernick Thank you very much for all your help. It is very useful. I'll include the meta data explicitly to avoid that first inference. Is the `persist` command the same? In other words, will the following work:
```
data_series.map_partitions(process_text, run_type, meta=data_series._meta).persist()
``
I've got about two more transformations that I need to perform on the data to complete my application. I haven't coded those up yet, as I wanted to get a feel for cudf and dask-cudf. 

I'll close this issue but essentially what I want to do is utilize all 4 GPUs to perform the remaining transformations. I'm calculating the longest common subsequence between pairs of these part descriptions and it takes forever on my CPU (> 3 days). My dataset can fit into memory just fine but the calculation is too lengthy. Having these GPUs at my dispense, I want to decrease the calculation time. If I run into more hiccups while finishing out the code, I'll be sure to post them here.
