### ISSUE TITLE
[BUG] Implement custom dtype handling utilities

### ISSUE THREAD

**Issue by vyasr** [rapidsai/cudf#8250]
**Describe the bug**
We currently make use of certain numpy and pandas utilities for dtype checking in various parts of our code base. These utilities are not reliable for us because they do not necessarily work on our extension dtypes, but currently these issues are being handled on a case-by-case basis, leaving us open to various bugs. We should instead write our own utilities that handle our own dtypes in addition to the common dtypes from other projects.

**Steps/Code to reproduce bug**
Here's one example for `np.issubdtype`.
```
>>> np.issubdtype(cudf.Decimal64Dtype(10, 2), np.int32)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nfs/vyasr/local/rapids/compose/etc/conda/cuda_11.2.0/envs/rapids/lib/python3.7/site-packages/numpy/core/numerictypes.py", line 419, in issubdtype
    arg1 = dtype(arg1).type
TypeError: Cannot interpret 'Decimal64Dtype(precision=10, scale=2)' as a data type
```

**Expected behavior**
Returns True or False

**Additional context**
Here's a not necessarily exhaustive list of functions that may need to be replaced (some have equivalents that simply aren't used everywhere):
- [ ] `np.issubdtype`
- [ ] `np.can_cast`
- [ ] Anything from `pd.api.types`
- [ ] `np.find_common_type`

**Comment by galipremsagar** [comment]
@vyasr Can we move this to `21.12`?

**Comment by vyasr** [comment]
Yup, moved.

**Comment by vyasr** [comment]
@mroeschke this issue is also relevant for a lot of your ongoing work.
