### ISSUE TITLE
[QST] Creating dataframe columns and indices from seris.

### ISSUE THREAD

**Issue by aclifton314** [rapidsai/cudf#8286]
System: Red Hat Enterprise Linux Server release 7.7 (Maipo)
CUDA: 10.2
dask-cuda: 0.19.0
python: 3.7.10
GPU: 4 NVIDIA Titan V-100

I've got a cudf series that gets returned from running `map_partitions`:
```python
    def setup_dask():
        cmd = "hostname --all-ip-addresses"
        process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
        output, error = process.communicate()
        IPADDR = str(output.decode()).split()[0]

        cluster = LocalCUDACluster(ip=IPADDR)
        client = Client(cluster)
        return cluster, client

    print('setting up gpu_cluster and dask_client...')
    gpu_cluster, dask_client = setup_dask()

    print('reading data...')
    data_path = '/path/to/data.csv'
    data_dask_df = dask_cudf.read_csv(data_path, encoding='ISO-8859-1')

    run_type = 'lemma_no_punct_lower'
    data_series = data_dask_df['lemmatized']
    tmp_series = data_series.map_partitions(process_text, run_type, meta=data_series._meta).persist()
```
I'm wanting to use that series to create an empty `dask_cudf ` dataframe where the columns and indices are the contents contained in the series but I'm not sure how to exactly. Here is how I would do it just using pandas (non-cudf):
```python
run_type = 'lemma_no_punct_lower'
tmp_series_pd = process_text_pd(data_series_pd, run_type)
df_pd = pd.DataFrame(columns=tmp_series_pd, index=tmp_series_pd)
```
Is there a way to do this in `dask_cudf`? Ultimately, I'm setting up this dataframe for some calculations that would benefit from being distributed on GPUs, but I wanted to get the creation issue resolved before posting about the calculations.

Thanks in advance!

**Comment by aclifton314** [comment]
Any thoughts on this issue?

**Comment by beckernick** [comment]
Dask doesn't have a global index. Does calling `to_frame()` and then `set_index()` accomplish what you're trying to do? `dask_series.to_frame().set_index("mycolumn")` should give you an empty dask dataframe with `mycolumn` as the index

**Comment by aclifton314** [comment]
@beckernick Here is what I have:
```python
def setup_dask():
    cmd = "hostname --all-ip-addresses"
    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
    output, error = process.communicate()
    IPADDR = str(output.decode()).split()[0]

    cluster = LocalCUDACluster(ip=IPADDR)
    client = Client(cluster)
    return cluster, client

print('setting up gpu_cluster and dask_client...')
gpu_cluster, dask_client = setup_dask()

print('reading data...')
data_path = '/path/to/data.csv'
data_dask_df = dask_cudf.read_csv(data_path, encoding='ISO-8859-1')

run_type = 'lemma_no_punct_lower'
data_series = data_dask_df['lemmatized']

tmp_series = data_series.map_partitions(process_text, run_type, meta=data_series._meta).persist()
setup_df = tmp_series.to_frame().set_index(tmp_series)
```
and here is the error I am getting:
```python
Traceback (most recent call last):
  File "test_lcs.py", line 98, in <module>
    setup_df = tmp_series.to_frame().set_index(tmp_series)
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask_cudf/core.py", line 235, in set_index
    **kwargs,
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask/dataframe/core.py", line 4101, in set_index
    **kwargs,
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask/dataframe/shuffle.py", line 163, in set_index
    df, index2, repartition, npartitions, upsample, partition_size
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask/dataframe/shuffle.py", line 35, in _calculate_divisions
    divisions, sizes, mins, maxes = base.compute(divisions, sizes, mins, maxes)
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask/base.py", line 566, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/distributed/client.py", line 2666, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/distributed/client.py", line 1981, in gather
    asynchronous=asynchronous,
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/distributed/client.py", line 844, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/distributed/utils.py", line 353, in sync
    raise exc.with_traceback(tb)
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/distributed/utils.py", line 336, in f
    result[0] = yield future
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/distributed/client.py", line 1840, in _gather
    raise exception.with_traceback(traceback)
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask/dataframe/partitionquantiles.py", line 411, inpercentiles_summary
    data = df.values
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/cudf/core/series.py", line 365, in values
    return self._column.values
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/cudf/core/column/string.py", line 4912, in values
    "String Arrays is not yet implemented in cudf"
NotImplementedError: String Arrays is not yet implemented in cudf
```

**Comment by aclifton314** [comment]
I'm going to close this issue in favor of https://github.com/rapidsai/dask-cuda/issues/633#issue-904155292 as it includes the question asked here.
