### ISSUE TITLE
[FEA] Support conversion of list columns to strings

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#8351]
In Pandas, if I want to get a string representation of a column of lists, I can cast the column as strings. In cuDF, I cannot:
```
>>> import pandas as pd
>>> import cudf

>>> df = pd.DataFrame({'id': [[0, 0], [1, 1]]})
>>> df.id.astype('str')
0    [0, 0]
1    [1, 1]
Name: id, dtype: object
>>> cudf.from_pandas(df).id.astype('str')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rgelhausen/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/series.py", line 3089, in astype
    raise e
  File "/home/rgelhausen/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/series.py", line 3081, in astype
    data = self._column.astype(dtype)
  File "/home/rgelhausen/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/column.py", line 904, in astype
    return self.as_string_column(dtype, **kwargs)
  File "/home/rgelhausen/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/column.py", line 988, in as_string_column
    raise NotImplementedError
NotImplementedError
```

**Comment by davidwendt** [comment]
I think this can be done inside cudf without `libcudf` by just converting the child column to strings and also copying the offsets column.
```
>>> sl = cudf.Series([[0,0],[1,1]])
>>> sl._column.children[1].astype('str')
<cudf.core.column.string.StringColumn object at 0x7fb52c35b200>
[
  "0",
  "0",
  "1",
  "1"
]
dtype: object

>>> sl._column.offsets
<cudf.core.column.numerical.NumericalColumn object at 0x7fb52c35b290>
[
  0,
  2,
  4
]
dtype: int32
```

Then create the output lists column by using the this result along with the offsets from the original lists column. Something like:
```
>>> c1 = sl._column.children[1].astype('str')
>>> c0 = sl._column.offsets
>>> lc = cudf.core.column.ListColumn( size=len(sl._column), dtype=cudf.ListDtype(c1.dtype), mask=sl._column.mask, offset=0, null_count=sl._column.null_count, children=(c0,c1))
>>> lc
<cudf.core.column.lists.ListColumn object at 0x7fb52c35b050>
[
  [
    "0",
    "0"
  ],
  [
    "1",
    "1"
  ]
]
dtype: list
```

**Comment by shwina** [comment]
I think the problem isn't so much converting the leaves to strings, but rather the entire list column to a string representation, i.e., `[0, 1]` -> `"[0, 1]"`. I believe this request is motivated by the need to work around the fact that we can't currently join on list columns.

**Comment by davidwendt** [comment]
I'm not following the `"[0, 1]"` example. Each list element is converted to a string element including the braces, comma, and space characters?

**Comment by shwina** [comment]
Correct, I realize that C++/Python/Spark/XYZ each could have different string representations of lists, where maybe it would make sense to have configurable brackets and separators?
