### ISSUE TITLE
[BUG] Can't import dask_cudf in latest cudf nightlies

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#8457]
```
(rapids) rgelhausen@rl-dgx-r11-u36-rapids-dgx101:~$ conda list | grep rapids
# packages in environment at /home/rgelhausen/conda/envs/rapids:
cudf                      21.08.00a210607 cuda_11.2_py38_gae8ee8a060_118    rapidsai-nightly
dask-cuda                 21.08.00a210608         py38_20    rapidsai-nightly
dask-cudf                 21.08.00a210607 py38_gae8ee8a060_118    rapidsai-nightly
libcudf                   21.08.00a210608 cuda11.2_gaa82646248_120    rapidsai-nightly
librmm                    21.08.00a210608 cuda11.2_gaa2a2f3_18    rapidsai-nightly
rmm                       21.08.00a210608 cuda_11.2_py38_gaa2a2f3_18    rapidsai-nightly
ucx                       1.9.0+gcd9efd3       cuda11.2_0    rapidsai-nightly
ucx-proc                  1.0.0                       gpu    rapidsai-nightly
ucx-py                    0.21.0a210608   py38_gcd9efd3_14    rapidsai-nightly

conda list | grep dask
dask                      2021.5.1           pyhd8ed1ab_0    conda-forge
dask-core                 2021.5.1           pyhd8ed1ab_0    conda-forge
dask-cuda                 21.08.00a210608         py38_20    rapidsai-nightly
dask-cudf                 21.08.00a210607 py38_gae8ee8a060_118    rapidsai-nightly
```

```
iPython 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dask_cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rgelhausen/conda/envs/rapids/lib/python3.8/site-packages/dask_cudf/__init__.py", line 6, in <module>
    from . import backends
  File "/home/rgelhausen/conda/envs/rapids/lib/python3.8/site-packages/dask_cudf/backends.py", line 38, in <module>
    from .core import DataFrame, Index, Series
  File "/home/rgelhausen/conda/envs/rapids/lib/python3.8/site-packages/dask_cudf/core.py", line 17, in <module>
    from dask.dataframe.core import (
ImportError: cannot import name 'make_meta' from 'dask.dataframe.core' (/home/rgelhausen/conda/envs/rapids/lib/python3.8/site-packages/dask/dataframe/core.py)
```

**Comment by pentschev** [comment]
cuDF is pinning to 2021.5.1 and we need 2021.6.0 here. I'll submit a PR to fix that shortly.
