### ISSUE TITLE
[BUG] cudf::strings::replace_with_backrefs produces incorrect result

### ISSUE THREAD

**Issue by sperlingxx** [rapidsai/cudf#8569]
**Describe the bug**
Cudf Java test against `cudf::strings::replace_with_backrefs` suddenly went wrong in these days, which looks related to #8460 

For more details: https://github.com/NVIDIA/spark-rapids/issues/2750

**Comment by abellina** [comment]
Here's the exception we saw in CUDF. I mistakenly filed it under spark-rapids.

```
08:25:40  [ERROR] testStringReplaceWithBackrefs  Time elapsed: 0.005 s  <<< FAILURE!
08:25:40  org.opentest4j.AssertionFailedError: Column unnamed Row 0 ==> array lengths differ, expected: <14> but was: <19>
08:25:40  	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
08:25:40  	at org.junit.jupiter.api.AssertArrayEquals.assertArraysHaveSameLength(AssertArrayEquals.java:423)
08:25:40  	at org.junit.jupiter.api.AssertArrayEquals.assertArrayEquals(AssertArrayEquals.java:208)
08:25:40  	at org.junit.jupiter.api.AssertArrayEquals.assertArrayEquals(AssertArrayEquals.java:66)
08:25:40  	at org.junit.jupiter.api.Assertions.assertArrayEquals(Assertions.java:1217)
08:25:40  	at ai.rapids.cudf.TableTest.assertPartialColumnsAreEqual(TableTest.java:224)
08:25:40  	at ai.rapids.cudf.TableTest.assertPartialColumnsAreEqual(TableTest.java:152)
08:25:40  	at ai.rapids.cudf.TableTest.assertColumnsAreEqual(TableTest.java:102)
08:25:40  	at ai.rapids.cudf.TableTest.assertColumnsAreEqual(TableTest.java:92)
08:25:40  	at ai.rapids.cudf.ColumnVectorTest.testStringReplaceWithBackrefs(ColumnVectorTest.java:4266)
08:25:40  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
08:25:40  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
08:25:40  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
08:25:40  	at java.lang.reflect.Method.invoke(Method.java:498)
08:25:40  	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
08:25:40  	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
08:25:40  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:184)
08:25:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
08:25:40  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:180)
08:25:40  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127)
08:25:40  	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
08:25:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
08:25:40  	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
08:25:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
08:25:40  	at java.util.ArrayList.forEach(ArrayList.java:1259)
08:25:40  	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
08:25:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
08:25:40  	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
08:25:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
08:25:40  	at java.util.ArrayList.forEach(ArrayList.java:1259)
08:25:40  	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
08:25:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
08:25:40  	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
08:25:40  	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
08:25:40  	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
08:25:40  	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
08:25:40  	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
08:25:40  	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
08:25:40  	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
08:25:40  	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
08:25:40  	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
08:25:40  	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:132)
08:25:40  	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:111)
08:25:40  	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
08:25:40  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
08:25:40  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
08:25:40  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
```

**Comment by davidwendt** [comment]
Looks like the error occurs on the first set of test data there.
```
  cudf::test::strings_column_wrapper input1({"<h1>title</h1>", "<h1>another title</h1>", ""}, {1, 1, 0});
  std::string pattern     = "<h1>(.*)</h1>";
  std::string replacement = "<h2>\\1</h2>";
  auto view               = cudf::strings_column_view(input1);
  auto results            = cudf::strings::replace_with_backrefs(view, pattern, replacement);
  cudf::test::print(results->view());
```
Produces the incorrect result:
```
<h2>title</h1></h2>,<h2>another title</h1></h2>,NULL
```
I will look into this today.
