### ISSUE TITLE
[FEA] Replace `infer_dtype_from_object` with `infer_dtype`

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cudf#8623]
Currently we depend on `infer_dtype_from_object` in `utils/dtype.py`:
https://github.com/rapidsai/cudf/blob/9510ef6a97102782906423ff5fd132c0e4bb08fd/python/cudf/cudf/utils/dtypes.py#L11

Since `infer_dtype_from_object` is not publicly documented in pandas, it is arguably better to switch to the [public documented](https://pandas.pydata.org/docs/reference/api/pandas.api.types.infer_dtype.html) version of `infer_dtype`.

The switch is not trivial. As two functions does not always have the same behavior:
```python
>>> infer_dtype("timedelta64")
'string'
>>> infer_dtype_from_object("timedelta64")
<class 'numpy.timedelta64'>
```
```python
>>> infer_dtype(np.datetime64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandas/_libs/lib.pyx", line 1350, in pandas._libs.lib.infer_dtype
  File "pandas/_libs/lib.pyx", line 1229, in pandas._libs.lib._try_infer_map
AttributeError: 'getset_descriptor' object has no attribute 'name'
>>> infer_dtype_from_object(np.datetime64)
<class 'numpy.datetime64'>
```

**Comment by vyasr** [comment]
@mroeschke it looks like we have [exactly one use of this right now](https://github.com/rapidsai/cudf/blob/2c25b05a2ee9e115190fc43166972c956d5a800d/python/cudf/cudf/core/dataframe.py#L6972). I believe it is the same code that Michael linked above, but now moved to only exist in one place. Do you think replacing it is viable?

**Comment by mroeschke** [comment]
Without vendoring that method, I am not confident that we can replace it with a public API and still capture all the flexibility of `select_dtypes`. Do you think we should go as far as vendoring this method to avoid the private import?

**Comment by vyasr** [comment]
Probably not, at least for now. Should we close this issue as a wontfix? We can reopen it if a time comes where we observe issues where use of this pandas API breaks us.

**Comment by mroeschke** [comment]
Yes let's close for now then.
