### ISSUE TITLE
[BUG] ORC reader crashes using a very recent version of cudf

### ISSUE THREAD

**Issue by Christian8491** [rapidsai/cudf#8665]
**Describe the bug**
when reading a specific ORC file (tpch benchmarking, lineitem table) it crashes. (I can't upload the .orc file here but I could send an email with this orc file in order to provide facilities to reproduce, this file is about 11.8 MB). 

**Steps/Code to reproduce bug**
```py
import cudf

table = cudf.read_orc("/.../tpch/lineitem_0_0.orc")   # crash
#table = cudf.read_parquet("/...tpch/lineitem_0_0.parquet")  # ok
print(table.head())
```

which produces

```
Traceback (most recent call last):
  File "/home/christian/Desktop/issue_cudf.py", line 3, in <module>
    table = cudf.read_orc("/.../tpch/lineitem_0_0.orc")
  File "/home/christian/miniconda3/envs/bsql_public/lib/python3.8/site-packages/cudf/io/orc.py", line 294, in read_orc
    liborc.read_orc(
  File "cudf/_lib/orc.pyx", line 68, in cudf._lib.orc.read_orc
  File "cudf/_lib/orc.pyx", line 105, in cudf._lib.orc.read_orc
RuntimeError: CUDA error at: /home/christian/miniconda3/envs/bsql_public/include/rmm/cuda_stream_view.hpp:95: cudaErrorIllegalAddress an illegal memory access was encountered
```

**Expected behavior**
It should not crash.

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal]
 - Method of cuDF install: [conda]

**Environment details**
```
$ conda list | grep rapids 
cudf                      21.08.00a210706 cuda_11.2_py38_gc54346e717_245    rapidsai-nightly
dask-cuda                 21.08.00a210706         py38_32    rapidsai-nightly
dask-cudf                 21.08.00a210706 py38_gc54346e717_245    rapidsai-nightly
libcudf                   21.08.00a210706 cuda11.2_ge855eb9ea0_246    rapidsai-nightly
librmm                    21.08.00a210706 cuda11.2_g3c86211_32    rapidsai-nightly
rmm                       21.08.00a210706 cuda_11.2_py38_g3c86211_32    rapidsai-nightly
ucx                       1.9.0+gcd9efd3       cuda11.2_0    rapidsai-nightly
ucx-proc                  1.0.0                       gpu    rapidsai-nightly
ucx-py                    0.21.0a210706   py38_gcd9efd3_28    rapidsai-nightly
```

**Comment by harrism** [comment]
Setting to P0 since this is a crash.  @Christian8491 is it possible to create a smaller .orc file that reproduces so it can be attached here?

**Comment by Christian8491** [comment]
This is a smaller version from the original lineitem file. It contains only 100 rows. 
[lineitem_100rows.zip](https://github.com/rapidsai/cudf/files/6778384/lineitem_100rows.zip)

**Comment by harrism** [comment]
Thanks!

**Comment by rgsl888prabhu** [comment]
@Christian8491 Does it fail with the 100 rows file ?

**Comment by Christian8491** [comment]
@rgsl888prabhu yes, it still fails whit just 100 rows. I hope this file can help to debug.

**Comment by rgsl888prabhu** [comment]
I tried latest nightly, and it worked

```
cudf                      21.08.00a210707 cuda_11.2_py37_gf0f2170972_251    rapidsai-nightly
libcudf                   21.08.00a210707 cuda11.2_gf0f2170972_251    rapidsai-nightly
librmm                    21.08.00a210707 cuda11.2_geb2b991_34    rapidsai-nightly
rmm                       21.08.00a210707 cuda_11.2_py37_geb2b991_34    rapidsai-nightly
(pyspark_env) rgsl888@onepiece:~/Projects/backup/cudf$ python
Python 3.7.10 (default, Jun  4 2021, 14:48:32) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf;df = cudf.read_orc("lineitem_100rows.orc")
>>> df
    l_orderkey  l_partkey  l_suppkey  l_linenumber  l_quantity  l_extendedprice  l_discount  ...  l_linestatus l_shipdate l_commitdate l_receiptdate     l_shipinstruct l_shipmode                                  l_comment
0            1      15519        785             1        17.0         24386.67        0.04  ...             O 1996-03-13   1996-02-12    1996-03-22  DELIVER IN PERSON      TRUCK                    egular courts above the
1            1       6731        732             2        36.0         58958.28        0.09  ...             O 1996-04-12   1996-02-28    1996-04-20   TAKE BACK RETURN       MAIL         ly final dependencies: slyly bold 
2            1       6370        371             3         8.0         10210.96        0.10  ...             O 1996-01-29   1996-03-05    1996-01-31   TAKE BACK RETURN    REG AIR              riously. regular, express dep
3            1        214        465             4        28.0         31197.88        0.09  ...             O 1996-04-21   1996-03-30    1996-05-16               NONE        AIR                    lites. fluffily even de
4            1       2403        160             5        24.0         31329.60        0.10  ...             O 1996-03-30   1996-03-14    1996-04-01               NONE        FOB                    pending foxes. slyly re
..         ...        ...        ...           ...         ...              ...         ...  ...           ...        ...          ...           ...                ...        ...                                        ...
95          97       4957        212             2        37.0         68892.15        0.02  ...             F 1993-04-13   1993-03-30    1993-04-14  DELIVER IN PERSON       SHIP           ic requests boost carefully quic
96          97       7770        542             3        19.0         31877.63        0.06  ...             F 1993-05-14   1993-03-05    1993-05-25   TAKE BACK RETURN       RAIL  gifts. furiously ironic packages cajole. 
97          98       4022         23             1        28.0         25928.56        0.06  ...             F 1994-12-24   1994-10-25    1995-01-16        COLLECT COD    REG AIR                pending, regular accounts s
98          98      10975        756             2         1.0          1885.97        0.00  ...             F 1994-12-01   1994-12-12    1994-12-15  DELIVER IN PERSON      TRUCK             . unusual instructions against
99          98       4471        472             3        14.0         19256.58        0.05  ...             F 1994-12-30   1994-11-22    1995-01-27        COLLECT COD        AIR   cajole furiously. blithely ironic ideas 

[100 rows x 16 columns]

```

**Comment by rgsl888prabhu** [comment]
@Christian8491 I have also pulled cudf branch and tested on it, and it also worked,

1) Can you please try on the latest nightly and let me know if you have the issue (Try with this 100 row file as well).
2) Please provide information on the GPU you are using.

**Comment by Christian8491** [comment]
@rgsl888prabhu  I just updated to `21.08.00a210707` and the issue go away only for this small file, but not with the original one.  Some useful info about my GPU. 


```
$ nvidia-smi
Wed Jul  7 22:09:35 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.27.04    Driver Version: 460.27.04    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   36C    P8    N/A /  N/A |      0MiB /  4042MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

```

This time I am attaching the original file. 

[lineitem_0_0.zip](https://github.com/rapidsai/cudf/files/6781206/lineitem_0_0.zip)

**Comment by rgsl888prabhu** [comment]
@Christian8491 I was able to reproduce the issue with the whole file and here is the smaller repro.

```
>>> import cudf;df = cudf.read_orc("lineitem_0_0.orc", columns=["l_commitdate"], num_rows=20343)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rgsl888/anaconda3/envs/rapids_dev/lib/python3.8/site-packages/cudf/io/orc.py", line 294, in read_orc
    liborc.read_orc(
  File "cudf/_lib/orc.pyx", line 77, in cudf._lib.orc.read_orc
  File "cudf/_lib/orc.pyx", line 114, in cudf._lib.orc.read_orc
RuntimeError: CUDA error at: /home/rgsl888/anaconda3/envs/rapids_dev/include/rmm/cuda_stream_view.hpp:95: cudaErrorIllegalAddress an illegal memory access was encountered

```

Thank you for the repro file.

**Comment by rgsl888prabhu** [comment]
@Christian8491 can you please try the PR #8700 and let me know if it fixes your issue.

**Comment by Christian8491** [comment]
@rgsl888prabhu I not builded from scratch. I only installed (and updated). I think if you cant reproduce anymore this issue locally is a great point. If you still prefer i build that PR let me know (will take me a while), but I think this is ready for merge.
