### ISSUE TITLE
[FEA] Support nested column pruning in ORC reader when reading a struct column.

### ISSUE THREAD

**Issue by firestarman** [rapidsai/cudf#8848]
Assuming there is an orc files contains one struct column "_c0" as below.
```bash
>>> pandas.read_orc("/data/tmp/test.log")
                                                  _c0
0                                                None
1   {'child0': -21.0, 'child1': 770290356.0, 'chil...
2   {'child0': 112.0, 'child1': 741485586.0, 'chil...
3   {'child0': -50.0, 'child1': -2094070070.0, 'ch...
4   {'child0': -49.0, 'child1': -228841867.0, 'chi...
5   {'child0': -55.0, 'child1': -2116626173.0, 'ch...
6   {'child0': None, 'child1': 2117211837.0, 'chil...
7   {'child0': -61.0, 'child1': -456120487.0, 'chi...
8                                                None
9   {'child0': 126.0, 'child1': -850819620.0, 'chi...
10  {'child0': 88.0, 'child1': 2143646677.0, 'chil...
11  {'child0': -18.0, 'child1': -1698102546.0, 'ch...
12  {'child0': -121.0, 'child1': 1460680657.0, 'ch...
>>> 
```

We can read only one nested column by Pandas orc reader, e.g
```bash
>>> pandas.read_orc("/data/tmp/test.log", columns=['_c0.child0'])
                   _c0
0                 None
1    {'child0': -21.0}
2    {'child0': 112.0}
3    {'child0': -50.0}
4    {'child0': -49.0}
5    {'child0': -55.0}
6     {'child0': None}
7    {'child0': -61.0}
8                 None
9    {'child0': 126.0}
10    {'child0': 88.0}
11   {'child0': -18.0}
12  {'child0': -121.0}
>>> 
```
or two of the nested columns,
```bash
>>> pandas.read_orc("/data/tmp/test.log", columns=['_c0.child1', '_c0.child0'])
                                           _c0
0                                         None
1     {'child0': -21.0, 'child1': 770290356.0}
2     {'child0': 112.0, 'child1': 741485586.0}
3   {'child0': -50.0, 'child1': -2094070070.0}
4    {'child0': -49.0, 'child1': -228841867.0}
5   {'child0': -55.0, 'child1': -2116626173.0}
6     {'child0': None, 'child1': 2117211837.0}
7    {'child0': -61.0, 'child1': -456120487.0}
8                                         None
9    {'child0': 126.0, 'child1': -850819620.0}
10    {'child0': 88.0, 'child1': 2143646677.0}
11  {'child0': -18.0, 'child1': -1698102546.0}
12  {'child0': -121.0, 'child1': 1460680657.0}
```

cudf will complain an error for the cases above.
```bash
>>> cudf.read_orc("/data/tmp/test.log", columns=['_c0.child0'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/liangcail/miniconda3/envs/cudf-python-rt/lib/python3.7/site-packages/cudf/io/orc.py", line 302, in read_orc
    timestamp_type,
  File "cudf/_lib/orc.pyx", line 73, in cudf._lib.orc.read_orc
  File "cudf/_lib/orc.pyx", line 110, in cudf._lib.orc.read_orc
RuntimeError: cuDF failure at: ../src/io/orc/reader_impl.cu:540: Unknown column name : _c0.child0
```

**Comment by firestarman** [comment]
You can get the test file in issue https://github.com/rapidsai/cudf/issues/8704.

**Comment by devavret** [comment]
CC: @rgsl888prabhu 

@vuule I think we also need to support this for parquet reader to address this https://github.com/rapidsai/cudf/pull/7248#issuecomment-769463408.

**Comment by firestarman** [comment]
One more thing.
The column order in the output of Pandas aligns with the file schema (`'child0', 'child1'`), even `['_c0.child1', '_c0.child0']` is specified.

I hope the output columns have the same order with the column names in parameter `columns`, meaing (`'child1', 'child0'`). Or at least having an addition parameter to control this behavior.

**Comment by devavret** [comment]
> I hope cuDF can support the output columns having the same order with the column names in parameter `columns`, meaning (`'child1', 'child0'`). Or at least having an addition parameter to control this behavior.

Actually that's easier to support. It's what we do for non-nested column selection.
