### ISSUE TITLE
[BUG] Many Dask cuDF operations fail with list or struct columns present in dataframe

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#8913]
Dask cuDF cannot write parquet files with list or struct columns. The underlying error may be caused by a failure to run `reset_index()` on a frame containing a list/struct column.

```python
import cudf
import dask_cudf
​
df = cudf.DataFrame({
    "a":[[0,1],[1,2]]
})
ddf = dask_cudf.from_cudf(df, 1)
df.to_parquet("test")
ddf.to_parquet("dask_test")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    175     try:
--> 176         yield
    177     except Exception as e:

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   5675     with raise_on_meta_error(funcname(func), udf=kwargs.pop("udf", False)):
-> 5676         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   5677 

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py in _extract_meta(x, nonempty)
   5655     elif isinstance(x, tuple):
-> 5656         return tuple([_extract_meta(_x, nonempty) for _x in x])
   5657     elif isinstance(x, dict):

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py in <listcomp>(.0)
   5655     elif isinstance(x, tuple):
-> 5656         return tuple([_extract_meta(_x, nonempty) for _x in x])
   5657     elif isinstance(x, dict):

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py in _extract_meta(x, nonempty)
   5651     if isinstance(x, (Scalar, _Frame)):
-> 5652         return x._meta_nonempty if nonempty else x._meta
   5653     elif isinstance(x, list):

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py in _meta_nonempty(self)
    395         """A non-empty version of `_meta` with fake data."""
--> 396         return meta_nonempty(self._meta)
    397 

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/utils.py in __call__(self, arg, *args, **kwargs)
    574         meth = self.dispatch(type(arg))
--> 575         return meth(arg, *args, **kwargs)
    576 

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask_cudf/backends.py in meta_nonempty_cudf(x)
    123             columns_with_dtype[dtype] = cudf.core.column.as_column(
--> 124                 _get_non_empty_data(x[col])
    125             )

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask_cudf/backends.py in _get_non_empty_data(s)
     94     else:
---> 95         if pd.api.types.is_numeric_dtype(s.dtype):
     96             data = cudf.core.column.as_column(

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/pandas/core/dtypes/common.py in is_numeric_dtype(arr_or_dtype)
   1270     """
-> 1271     return _is_dtype_type(
   1272         arr_or_dtype, classes_and_not_datetimelike(np.number, np.bool_)

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/pandas/core/dtypes/common.py in _is_dtype_type(arr_or_dtype, condition)
   1650 
-> 1651     return condition(tipo)
   1652 

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/pandas/core/dtypes/common.py in <lambda>(tipo)
    195     return lambda tipo: (
--> 196         issubclass(tipo, klasses)
    197         and not issubclass(tipo, (np.datetime64, np.timedelta64))

TypeError: issubclass() arg 1 must be a class

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
/tmp/ipykernel_42970/3677375296.py in <module>
      7 ddf = dask_cudf.from_cudf(df, 1)
      8 df.to_parquet("test")
----> 9 ddf.to_parquet("dask_test")

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask_cudf/core.py in to_parquet(self, path, *args, **kwargs)
    261         from dask_cudf.io import to_parquet
    262 
--> 263         return to_parquet(self, path, *args, **kwargs)
    264 
    265     def to_orc(self, path, **kwargs):

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/io/parquet/core.py in to_parquet(df, path, engine, compression, write_index, append, overwrite, ignore_divisions, partition_on, storage_options, custom_metadata, write_metadata_file, compute, compute_kwargs, schema, **kwargs)
    613         real_cols = set(df.columns)
    614         none_index = list(df._meta.index.names) == [None]
--> 615         df = df.reset_index()
    616         if none_index:
    617             df.columns = [

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py in reset_index(self, drop)
    520             Do not try to insert index into dataframe columns.
    521         """
--> 522         return self.map_partitions(
    523             M.reset_index, drop=drop, enforce_metadata=False
    524         ).clear_divisions()

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py in map_partitions(self, func, *args, **kwargs)
    706         None as the division.
    707         """
--> 708         return map_partitions(func, self, *args, **kwargs)
    709 
    710     @insert_meta_param_description(pad=12)

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py in map_partitions(func, meta, enforce_metadata, transform_divisions, *args, **kwargs)
   5730         # Use non-normalized kwargs here, as we want the real values (not
   5731         # delayed values)
-> 5732         meta = _emulate(func, *args, udf=True, **kwargs)
   5733     else:
   5734         meta = make_meta(meta, index=meta_index, parent_meta=parent_meta)

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   5674     """
   5675     with raise_on_meta_error(funcname(func), udf=kwargs.pop("udf", False)):
-> 5676         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   5677 
   5678 

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/contextlib.py in __exit__(self, type, value, traceback)
    129                 value = type()
    130             try:
--> 131                 self.gen.throw(type, value, traceback)
    132             except StopIteration as exc:
    133                 # Suppress StopIteration *unless* it's the same exception that

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    195         )
    196         msg = msg.format(" in `{0}`".format(funcname) if funcname else "", repr(e), tb)
--> 197         raise ValueError(msg) from e
    198 
    199 

ValueError: Metadata inference failed in `reset_index`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
TypeError('issubclass() arg 1 must be a class')

Traceback:
---------
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/utils.py", line 176, in raise_on_meta_error
    yield
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py", line 5676, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py", line 5656, in _extract_meta
    return tuple([_extract_meta(_x, nonempty) for _x in x])
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py", line 5656, in <listcomp>
    return tuple([_extract_meta(_x, nonempty) for _x in x])
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py", line 5652, in _extract_meta
    return x._meta_nonempty if nonempty else x._meta
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py", line 396, in _meta_nonempty
    return meta_nonempty(self._meta)
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/utils.py", line 575, in __call__
    return meth(arg, *args, **kwargs)
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask_cudf/backends.py", line 124, in meta_nonempty_cudf
    _get_non_empty_data(x[col])
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask_cudf/backends.py", line 95, in _get_non_empty_data
    if pd.api.types.is_numeric_dtype(s.dtype):
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/pandas/core/dtypes/common.py", line 1271, in is_numeric_dtype
    return _is_dtype_type(
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/pandas/core/dtypes/common.py", line 1651, in _is_dtype_type
    return condition(tipo)
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/pandas/core/dtypes/common.py", line 196, in <lambda>
    issubclass(tipo, klasses)
```
```python
ddf.reset_index()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    175     try:
--> 176         yield
    177     except Exception as e:

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   5675     with raise_on_meta_error(funcname(func), udf=kwargs.pop("udf", False)):
-> 5676         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   5677 

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py in _extract_meta(x, nonempty)
   5655     elif isinstance(x, tuple):
-> 5656         return tuple([_extract_meta(_x, nonempty) for _x in x])
   5657     elif isinstance(x, dict):

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py in <listcomp>(.0)
   5655     elif isinstance(x, tuple):
-> 5656         return tuple([_extract_meta(_x, nonempty) for _x in x])
   5657     elif isinstance(x, dict):

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py in _extract_meta(x, nonempty)
   5651     if isinstance(x, (Scalar, _Frame)):
-> 5652         return x._meta_nonempty if nonempty else x._meta
   5653     elif isinstance(x, list):

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py in _meta_nonempty(self)
    395         """A non-empty version of `_meta` with fake data."""
--> 396         return meta_nonempty(self._meta)
    397 

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/utils.py in __call__(self, arg, *args, **kwargs)
    574         meth = self.dispatch(type(arg))
--> 575         return meth(arg, *args, **kwargs)
    576 

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask_cudf/backends.py in meta_nonempty_cudf(x)
    123             columns_with_dtype[dtype] = cudf.core.column.as_column(
--> 124                 _get_non_empty_data(x[col])
    125             )

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask_cudf/backends.py in _get_non_empty_data(s)
     94     else:
---> 95         if pd.api.types.is_numeric_dtype(s.dtype):
     96             data = cudf.core.column.as_column(

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/pandas/core/dtypes/common.py in is_numeric_dtype(arr_or_dtype)
   1270     """
-> 1271     return _is_dtype_type(
   1272         arr_or_dtype, classes_and_not_datetimelike(np.number, np.bool_)

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/pandas/core/dtypes/common.py in _is_dtype_type(arr_or_dtype, condition)
   1650 
-> 1651     return condition(tipo)
   1652 

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/pandas/core/dtypes/common.py in <lambda>(tipo)
    195     return lambda tipo: (
--> 196         issubclass(tipo, klasses)
    197         and not issubclass(tipo, (np.datetime64, np.timedelta64))

TypeError: issubclass() arg 1 must be a class

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
/tmp/ipykernel_42970/1345017498.py in <module>
----> 1 ddf.reset_index()

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py in reset_index(self, drop)
    520             Do not try to insert index into dataframe columns.
    521         """
--> 522         return self.map_partitions(
    523             M.reset_index, drop=drop, enforce_metadata=False
    524         ).clear_divisions()

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py in map_partitions(self, func, *args, **kwargs)
    706         None as the division.
    707         """
--> 708         return map_partitions(func, self, *args, **kwargs)
    709 
    710     @insert_meta_param_description(pad=12)

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py in map_partitions(func, meta, enforce_metadata, transform_divisions, *args, **kwargs)
   5730         # Use non-normalized kwargs here, as we want the real values (not
   5731         # delayed values)
-> 5732         meta = _emulate(func, *args, udf=True, **kwargs)
   5733     else:
   5734         meta = make_meta(meta, index=meta_index, parent_meta=parent_meta)

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   5674     """
   5675     with raise_on_meta_error(funcname(func), udf=kwargs.pop("udf", False)):
-> 5676         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   5677 
   5678 

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/contextlib.py in __exit__(self, type, value, traceback)
    129                 value = type()
    130             try:
--> 131                 self.gen.throw(type, value, traceback)
    132             except StopIteration as exc:
    133                 # Suppress StopIteration *unless* it's the same exception that

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    195         )
    196         msg = msg.format(" in `{0}`".format(funcname) if funcname else "", repr(e), tb)
--> 197         raise ValueError(msg) from e
    198 
    199 

ValueError: Metadata inference failed in `reset_index`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
TypeError('issubclass() arg 1 must be a class')

Traceback:
---------
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/utils.py", line 176, in raise_on_meta_error
    yield
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py", line 5676, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py", line 5656, in _extract_meta
    return tuple([_extract_meta(_x, nonempty) for _x in x])
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py", line 5656, in <listcomp>
    return tuple([_extract_meta(_x, nonempty) for _x in x])
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py", line 5652, in _extract_meta
    return x._meta_nonempty if nonempty else x._meta
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py", line 396, in _meta_nonempty
    return meta_nonempty(self._meta)
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/utils.py", line 575, in __call__
    return meth(arg, *args, **kwargs)
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask_cudf/backends.py", line 124, in meta_nonempty_cudf
    _get_non_empty_data(x[col])
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask_cudf/backends.py", line 95, in _get_non_empty_data
    if pd.api.types.is_numeric_dtype(s.dtype):
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/pandas/core/dtypes/common.py", line 1271, in is_numeric_dtype
    return _is_dtype_type(
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/pandas/core/dtypes/common.py", line 1651, in _is_dtype_type
    return condition(tipo)
  File "/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/pandas/core/dtypes/common.py", line 196, in <lambda>
    issubclass(tipo, klasses)
```

EDIT: This also presents with ORC files.

**Comment by beckernick** [comment]
I believe the root cause may be the metadata handling for List and Struct Dtypes.

```python
import cudf
import dask_cudf
​
df = cudf.DataFrame({
    "a":[[0,1],[1,2]],
})
ddf = dask_cudf.from_cudf(df, 1)
ddf._meta_nonempty
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_72838/825033467.py in <module>
      6 })
      7 ddf = dask_cudf.from_cudf(df, 1)
----> 8 ddf._meta_nonempty

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/dataframe/core.py in _meta_nonempty(self)
    394     def _meta_nonempty(self):
    395         """A non-empty version of `_meta` with fake data."""
--> 396         return meta_nonempty(self._meta)
    397 
    398     @property

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask/utils.py in __call__(self, arg, *args, **kwargs)
    573         """
    574         meth = self.dispatch(type(arg))
--> 575         return meth(arg, *args, **kwargs)
    576 
    577     @property

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask_cudf/backends.py in meta_nonempty_cudf(x)
    122         if dtype not in columns_with_dtype:
    123             columns_with_dtype[dtype] = cudf.core.column.as_column(
--> 124                 _get_non_empty_data(x[col])
    125             )
    126         res._data[col] = columns_with_dtype[dtype]

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/dask_cudf/backends.py in _get_non_empty_data(s)
     93         data = pa.array(["cat", "dog"])
     94     else:
---> 95         if pd.api.types.is_numeric_dtype(s.dtype):
     96             data = cudf.core.column.as_column(
     97                 cp.arange(start=0, stop=2, dtype=s.dtype)

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/pandas/core/dtypes/common.py in is_numeric_dtype(arr_or_dtype)
   1269     False
   1270     """
-> 1271     return _is_dtype_type(
   1272         arr_or_dtype, classes_and_not_datetimelike(np.number, np.bool_)
   1273     )

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/pandas/core/dtypes/common.py in _is_dtype_type(arr_or_dtype, condition)
   1649         return False
   1650 
-> 1651     return condition(tipo)
   1652 
   1653 

/raid/nicholasb/miniconda3/envs/cudf-21.10/lib/python3.8/site-packages/pandas/core/dtypes/common.py in <lambda>(tipo)
    194     """
    195     return lambda tipo: (
--> 196         issubclass(tipo, klasses)
    197         and not issubclass(tipo, (np.datetime64, np.timedelta64))
    198     )

TypeError: issubclass() arg 1 must be a class
```

**Comment by beckernick** [comment]
This is probably due to our type handling in the dask-cudf backend. If it's not a categorical or string type, the first thing that happens is a type check of whether it's a numeric type via `pd.api.types.is_numeric_dtype`. 

Interestingly, this only errors for List dtypes (as opposed to struct/decimal).

https://github.com/rapidsai/cudf/blob/0ad36ff30fd693e9778ec7af206d5e5460d2bfa5/python/dask_cudf/dask_cudf/backends.py#L96-L104


```python
import pandas as pd
import cudf
​
s = cudf.Series([0.0, 1.0])
print(pd.api.types.is_numeric_dtype(s.dtype)) # True
​
s = cudf.Series([0.0, 1.0]).astype(cudf.core.dtypes.Decimal64Dtype(8,1))
print(pd.api.types.is_numeric_dtype(s.dtype)) # False
​
s = cudf.Series([{"a":1}, {"a":2}])
print(pd.api.types.is_numeric_dtype(s.dtype)) # False
​
s = cudf.Series([[0.0], [1.0]])
pd.api.types.is_numeric_dtype(s.dtype) # Error
True
False
False
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_44811/3642469118.py in <module>
     12 
     13 s = cudf.Series([[0.0], [1.0]])
---> 14 pd.api.types.is_numeric_dtype(s.dtype) # Error

/raid/nicholasb/miniconda3/envs/rapids-21.10/lib/python3.8/site-packages/pandas/core/dtypes/common.py in is_numeric_dtype(arr_or_dtype)
   1269     False
   1270     """
-> 1271     return _is_dtype_type(
   1272         arr_or_dtype, classes_and_not_datetimelike(np.number, np.bool_)
   1273     )

/raid/nicholasb/miniconda3/envs/rapids-21.10/lib/python3.8/site-packages/pandas/core/dtypes/common.py in _is_dtype_type(arr_or_dtype, condition)
   1649         return False
   1650 
-> 1651     return condition(tipo)
   1652 
   1653 

/raid/nicholasb/miniconda3/envs/rapids-21.10/lib/python3.8/site-packages/pandas/core/dtypes/common.py in <lambda>(tipo)
    194     """
    195     return lambda tipo: (
--> 196         issubclass(tipo, klasses)
    197         and not issubclass(tipo, (np.datetime64, np.timedelta64))
    198     )

TypeError: issubclass() arg 1 must be a class
```

**Comment by beckernick** [comment]
Separately, struct columns likely cause failures due to typecasting in the same function:

https://github.com/rapidsai/cudf/blob/0ad36ff30fd693e9778ec7af206d5e5460d2bfa5/python/dask_cudf/dask_cudf/backends.py#L101-L104

We cannot typecast like this for a structcolumn, so we throw a NotImplementedError
