### ISSUE TITLE
[BUG] getMapValue on empty column asserts with "num_blocks must be > 0"

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#9253]
**Describe the bug**
Calling `getMapValue` on an empty Java map type column throws the following exception:
```
ai.rapids.cudf.CudfException: cuDF failure at: /home/jenkins/agent/workspace/jenkins-cudf_nightly-dev-github-467-cuda11/java/src/main/native/../../../../cpp/include/cudf/detail/utilities/cuda.cuh:65: num_blocks must be > 0
  at ai.rapids.cudf.ColumnView.mapLookup(Native Method)
  at ai.rapids.cudf.ColumnView.getMapValue(ColumnView.java:2972)
```

**Steps/Code to reproduce bug**
Here's a repro step from the Spark Scala REPL that constructs an empty map column and attempts to call getMapValue on it:
```
scala> import ai.rapids.cudf._
import ai.rapids.cudf._

scala> val p: java.util.List[ai.rapids.cudf.HostColumnVector.DataType] = Arrays.asList(new HostColumnVector.BasicType(true, DType.STRING), new HostColumnVector.BasicType(true, DType.STRING))
p: java.util.List[ai.rapids.cudf.HostColumnVector.DataType] = [ai.rapids.cudf.HostColumnVector$BasicType@10312f0a, ai.rapids.cudf.HostColumnVector$BasicType@227f3bb7]

scala> val s = new HostColumnVector.StructType(true, p)
s: ai.rapids.cudf.HostColumnVector.StructType = ai.rapids.cudf.HostColumnVector$StructType@5a1d9416

scala> val c = ColumnVector.fromLists(new HostColumnVector.ListType(true, s))
c: ai.rapids.cudf.ColumnVector = ColumnVector{rows=0, type=LIST, nullCount=Optional.empty, offHeap=(ID: 16 7f88c99c7300)}

scala> c.getMapValue(Scalar.fromString("a"))
ai.rapids.cudf.CudfException: cuDF failure at: /home/jenkins/agent/workspace/jenkins-cudf_nightly-dev-github-467-cuda11/java/src/main/native/../../../../cpp/include/cudf/detail/utilities/cuda.cuh:65: num_blocks must be > 0
  at ai.rapids.cudf.ColumnView.mapLookup(Native Method)
  at ai.rapids.cudf.ColumnView.getMapValue(ColumnView.java:2972)
  ... 51 elided
```

**Expected behavior**
`getMapValue` should return an empty string column when the input map column is empty.

**Comment by hyperbolic2346** [comment]
I have not verified this fix inside a scala shell. I need to rebuild with a cuda version change to match my spark setup.
