### ISSUE TITLE
[BUG] HostColumnVectorCore requires native libs to be loaded

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#9329]
**Describe the bug**
Java's `HostColumnVectorCore` should deal solely with host memory buffers and thus not require libcudf.so to be loaded.  However it touches `ColumnVector.closeBuffers` which in turn forces `ColumnVector` to load and that requires libcudf.so.  In the RAPIDS Accelerator plugin for Spark, the driver should not require CUDA to be installed.  This bug causes the driver to try to load libcudf.so which fails on environments where the driver is not on a CUDA-capable node.  It fails with an exception like the following:
```
2021-09-28 21:31:14,062 ERROR cudf.NativeDepsLoader: Could not load cudf jni library...
java.io.IOException: Error loading dependencies
	at ai.rapids.cudf.NativeDepsLoader.loadNativeDeps(NativeDepsLoader.java:168)
	at ai.rapids.cudf.NativeDepsLoader.loadNativeDeps(NativeDepsLoader.java:74)
	at ai.rapids.cudf.ColumnVector.<clinit>(ColumnVector.java:44)
	at ai.rapids.cudf.HostColumnVectorCore$OffHeapState.cleanImpl(HostColumnVectorCore.java:560)
	at ai.rapids.cudf.MemoryCleaner$Cleaner.clean(MemoryCleaner.java:111)
	at ai.rapids.cudf.HostColumnVector.close(HostColumnVector.java:114)
```

**Steps/Code to reproduce bug**
On a system without CUDA installed, load the cudf.jar in `spark-shell` and create a `HostColumnVectorCore` instance from host buffers and the close the instance.  The `close()` will trigger a load of libcudf.so through `ColumnVector` and result in an exception similar to the following:

**Expected behavior**
`HostColumnVectorCore` should not try to load native dependencies like libcudf.so and therefore should not require CUDA to be installed.

**Comment by beckernick** [comment]
Closing, as I believe this was closed by #9332 . @jlowe please feel free to reopen if I'm mistaken.
