### ISSUE TITLE
[BUG] Java CI is failing with partition and nvcomp test failures

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#9375]
**Describe the bug**
Recent CI builds in both 21.10 and 21.12 have been failing with Java test errors like the following:
```
06:32:52 [ERROR] Tests run: 226, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.386 s <<< FAILURE! - in ai.rapids.cudf.TableTest
06:32:56 [ERROR] testPartition  Time elapsed: 0.003 s  <<< FAILURE!
06:32:56 org.opentest4j.AssertionFailedError: Column 0 Row 2 ==> expected: <5> but was: <9>
06:32:56 	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
06:32:56 	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:195)
06:32:56 	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:152)
06:32:56 	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:542)
06:32:56 	at ai.rapids.cudf.TableTest.assertPartialColumnsAreEqual(TableTest.java:210)
06:32:56 	at ai.rapids.cudf.TableTest.assertPartialColumnsAreEqual(TableTest.java:161)
06:32:56 	at ai.rapids.cudf.TableTest.assertPartialTablesAreEqual(TableTest.java:312)
06:32:56 	at ai.rapids.cudf.TableTest.assertTablesAreEqual(TableTest.java:322)
06:32:56 	at ai.rapids.cudf.TableTest.testPartition(TableTest.java:2927)
[...]
04:56:06 [ERROR] testBatchedLZ4CompressRoundTrip  Time elapsed: 0.131 s  <<< FAILURE!
04:56:06 org.opentest4j.AssertionFailedError: mismatch in batch buffer 0 ==> array contents differ at index [2049], expected: <1> but was: <0>
04:56:06 	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
04:56:06 	at org.junit.jupiter.api.AssertArrayEquals.failArraysNotEqual(AssertArrayEquals.java:432)
04:56:06 	at org.junit.jupiter.api.AssertArrayEquals.assertArrayEquals(AssertArrayEquals.java:212)
04:56:06 	at org.junit.jupiter.api.AssertArrayEquals.assertArrayEquals(AssertArrayEquals.java:66)
04:56:06 	at org.junit.jupiter.api.Assertions.assertArrayEquals(Assertions.java:1217)
04:56:06 	at ai.rapids.cudf.nvcomp.NvcompTest.testBatchedLZ4CompressRoundTrip(NvcompTest.java:183)
[..]
04:56:06 [ERROR] testBatchedLZ4RoundTripAsync  Time elapsed: 0.129 s  <<< FAILURE!
04:56:06 org.opentest4j.AssertionFailedError: mismatch in batch buffer 0 ==> array contents differ at index [2049], expected: <1> but was: <0>
04:56:06 	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
04:56:06 	at org.junit.jupiter.api.AssertArrayEquals.failArraysNotEqual(AssertArrayEquals.java:432)
04:56:06 	at org.junit.jupiter.api.AssertArrayEquals.assertArrayEquals(AssertArrayEquals.java:212)
04:56:06 	at org.junit.jupiter.api.AssertArrayEquals.assertArrayEquals(AssertArrayEquals.java:66)
04:56:06 	at org.junit.jupiter.api.Assertions.assertArrayEquals(Assertions.java:1217)
04:56:06 	at ai.rapids.cudf.nvcomp.NvcompTest.testBatchedLZ4RoundTripAsync(NvcompTest.java:120)
[...]
04:56:06 [ERROR] testLZ4RoundTripAsync  Time elapsed: 0.295 s  <<< FAILURE!
04:56:06 org.opentest4j.AssertionFailedError: Expected 256 at 256 found 0
04:56:06 	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
04:56:06 	at org.junit.jupiter.api.Assertions.fail(Assertions.java:109)
04:56:06 	at ai.rapids.cudf.nvcomp.NvcompTest.lz4RoundTrip(NvcompTest.java:316)
04:56:06 	at ai.rapids.cudf.nvcomp.NvcompTest.testLZ4RoundTripAsync(NvcompTest.java:38)
[...]
04:56:06 [ERROR] testLZ4RoundTripSync  Time elapsed: 0.667 s  <<< FAILURE!
04:56:06 org.opentest4j.AssertionFailedError: Expected 256 at 256 found 0
04:56:06 	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
04:56:06 	at org.junit.jupiter.api.Assertions.fail(Assertions.java:109)
04:56:06 	at ai.rapids.cudf.nvcomp.NvcompTest.lz4RoundTrip(NvcompTest.java:316)
04:56:06 	at ai.rapids.cudf.nvcomp.NvcompTest.testLZ4RoundTripSync(NvcompTest.java:33)

```

**Steps/Code to reproduce bug**
Create a PR and run CI.  Example failure logs in the past can be found for the CI runs for #9320 and #9368

**Expected behavior**
Java CI should pass

**Environment overview (please complete the following information)**
Java CI environment

**Comment by jlowe** [comment]
I have not been able to reproduce this locally, and the Java nightly builds for 21.10 and 21.12 have not been failing.  This seems to be something specific to the cudf Java CI environment.

**Comment by jlowe** [comment]
This appears to be specific to P100 GPUs.  It looks like the recent CI failures all ran on P100 GPUs but pass on other GPUs.  I tried running the Java unit tests on a P100 instance and verified that the same set indeed fails there.

**Comment by jlowe** [comment]
Appears to be fixed by moving to the new nvcomp 2.x APIs in #9384
