### ISSUE TITLE
[BUG] Address out of bounds when using the async allocator

### ISSUE THREAD

**Issue by rongou** [rapidsai/cudf#9504]
**Describe the bug**
When using the rapids-spark plugin with the `cuda_async_memory_resource`, getting an address out of bounds errors reported by `compute-sanitizer`.

**Steps/Code to reproduce bug**
Haven't been able to reproduce this more simply, but seems to be getting it pretty consistently running TPC-DS `q64` on my desktop (and on DGX-2s). Just run the TPC-DS query as usual, but with `--conf spark.rapids.memory.gpu.pool=ASYNC`.

**Expected behavior**
Should not produce this error.

**Environment overview (please complete the following information)**
 - Environment location: Spark standalone on local desktop
 - Method of cuDF install: from source

**Environment details**
Built from `branch-21.12`, commit `72694d22cff81e629f24dd64d7f9993dc5cc27fc`.

**Additional context**
This is the output from `compute-sanitizer`:
```console
========= Invalid __global__ read of size 4 bytes
=========     at 0x9f0 in /home/rou/src/cudf/cpp/src/copying/contiguous_split.cu:198:void tmpxft_0001ee52_00000000_7_contiguous_split_cpp1_ii::cudf::<unnamed>::copy_buffer<(int)256>(unsigned char *, const unsigned char *, int, unsigned long, unsigned long, unsigned long, unsigned int, int, int, unsigned long, int *)
=========     by thread (0,0,0) in block (1198,0,0)
=========     Address 0x6ae248200 is out of bounds
=========     Device Frame:/home/rou/src/cudf/cpp/src/copying/contiguous_split.cu:268:void cudf::<unnamed>::copy_partition<(int)256>(int, const unsigned char **, unsigned char **, cudf::<unnamed>::dst_buf_info *) [0x7d0]
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x22da7a]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame: [0x111cb]
=========                in /home/rou/.miniconda3/envs/cudf_dev/lib/libcudart.so.11.0
=========     Host Frame:cudaLaunchKernel_ptsz [0x42870]
=========                in /home/rou/.miniconda3/envs/cudf_dev/lib/libcudart.so.11.0
=========     Host Frame:cudf::detail::contiguous_split(cudf::table_view const &, std::vector<int, std::allocator<int>> const &, rmm::cuda_stream_view, rmm::mr::device_memory_resource*) [0xfdfcba]
=========                in /tmp/cudf7202212859460743434.so
=========     Host Frame:cudf::contiguous_split(cudf::table_view const &, std::vector<int, std::allocator<int>> const &, rmm::mr::device_memory_resource*) [0xfe0736]
=========                in /tmp/cudf7202212859460743434.so
=========     Host Frame:Java_ai_rapids_cudf_Table_contiguousSplit [0x1bbe6b]
=========                in /tmp/cudfjni4206561694907818921.so
=========     Host Frame: [0x7fce9d017da7]
=========                in 
```

@nvdbaranec @davidwendt

**Comment by jbrennan333** [comment]
@rongou do you have the spark output log for one of these queries?   Would be good to see any exceptions in the log.

**Comment by rongou** [comment]
Here is one using the latest nightly jars:
```console
21/11/12 17:49:19 WARN TaskSetManager: Lost task 46.0 in stage 43.0 (TID 12181) (127.0.0.1 executor 0): ai.rapids.cudf.CudfException: CUDA error encountered at: /home/jenkins/agent/workspace/jenkins-cudf_nightly-dev-github-521-cuda11/cpp/src/copying/contiguous_split.cu:1054: 719 cudaErrorLaunchFailure unspecified launch failure
	at ai.rapids.cudf.Table.contiguousSplit(Native Method)
	at ai.rapids.cudf.Table.contiguousSplit(Table.java:1833)
	at com.nvidia.spark.rapids.GpuPartitioning.$anonfun$sliceInternalOnGpu$3(GpuPartitioning.scala:57)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
	at com.nvidia.spark.rapids.GpuPartitioning.$anonfun$sliceInternalOnGpu$1(GpuPartitioning.scala:57)
	at com.nvidia.spark.rapids.Arm.closeOnExcept(Arm.scala:120)
	at com.nvidia.spark.rapids.Arm.closeOnExcept$(Arm.scala:118)
	at com.nvidia.spark.rapids.GpuHashPartitioning.closeOnExcept(GpuHashPartitioning.scala:28)
	at com.nvidia.spark.rapids.GpuPartitioning.sliceInternalOnGpu(GpuPartitioning.scala:55)
	at com.nvidia.spark.rapids.GpuPartitioning.sliceInternalOnGpu$(GpuPartitioning.scala:50)
	at com.nvidia.spark.rapids.GpuHashPartitioning.sliceInternalOnGpu(GpuHashPartitioning.scala:28)
	at com.nvidia.spark.rapids.GpuPartitioning.sliceInternalGpuOrCpu(GpuPartitioning.scala:115)
	at com.nvidia.spark.rapids.GpuPartitioning.sliceInternalGpuOrCpu$(GpuPartitioning.scala:102)
	at com.nvidia.spark.rapids.GpuHashPartitioning.sliceInternalGpuOrCpu(GpuHashPartitioning.scala:28)
	at com.nvidia.spark.rapids.GpuHashPartitioning.$anonfun$columnarEval$3(GpuHashPartitioning.scala:86)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:55)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:53)
	at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
	at com.nvidia.spark.rapids.GpuHashPartitioning.$anonfun$columnarEval$1(GpuHashPartitioning.scala:85)
	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
	at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
	at com.nvidia.spark.rapids.GpuHashPartitioning.columnarEval(GpuHashPartitioning.scala:78)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$.$anonfun$prepareBatchShuffleDependency$3(GpuShuffleExchangeExecBase.scala:272)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.partNextBatch(GpuShuffleExchangeExecBase.scala:293)
	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.hasNext(GpuShuffleExchangeExecBase.scala:304)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at org.apache.spark.sql.rapids.RapidsCachingWriter.write(RapidsShuffleInternalManagerBase.scala:98)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jbrennan333** [comment]
I have been able to reliably reproduce this running q64 on my local machine with a 100GB dataset by setting `spark.rapids.memory.gpu.allocFraction=0.40`
My GPU is an RTX A4000 with 16GB memory.

This is the relevant portion of the log:

```
21/11/22 14:02:00 INFO Executor: Finished task 16.0 in stage 41.0 (TID 217). 7830 bytes result sent to driver
21/11/22 14:02:00 INFO TaskSetManager: Starting task 40.0 in stage 41.0 (TID 241) (192.168.1.128, executor driver, partition 40, NODE_LOCAL, 4724 bytes) taskResourceAssignments Map()
21/11/22 14:02:00 INFO Executor: Running task 40.0 in stage 41.0 (TID 241)
21/11/22 14:02:00 INFO TaskSetManager: Finished task 16.0 in stage 41.0 (TID 217) in 25956 ms on 192.168.1.128 (executor driver) (17/200)
21/11/22 14:02:00 INFO RapidsShuffleInternalManager: Registering shuffle 5
21/11/22 14:02:00 INFO RapidsShuffleInternalManager: Asking map output tracker for dependency GPU Shuffle Dependency, map output sizes for: 0, parts=40-41
21/11/22 14:02:00 INFO RapidsCachingReader: Will read 26 cached blocks, 0 remote blocks from the RapidsShuffleTransport.
21/11/22 14:02:00 INFO RapidsShuffleInternalManager: Asking map output tracker for dependency GPU Shuffle Dependency, map output sizes for: 1, parts=40-41
21/11/22 14:02:00 INFO RapidsCachingReader: Will read 26 cached blocks, 0 remote blocks from the RapidsShuffleTransport.
========= Invalid __global__ read of size 4 bytes
=========     at 0x13b0 in /home/jimb/dev/rapids/cudf/cpp/src/copying/contiguous_split.cu:197:_ZN50_INTERNAL_6bd54e56_19_contiguous_split_cu_26302e214cudf52_GLOBAL__N__6bd54e56_19_contiguous_split_cu_26302e2111copy_bufferILi256EEEvPhPKhimmmjiimPi
=========     by thread (0,0,0) in block (2796,0,0)
=========     Address 0x8ccff4800 is out of bounds
=========     and is 1 bytes after the nearest allocation at 0x8ccff0800 of size 16384 bytes
=========     Device Frame:/home/jimb/dev/rapids/cudf/cpp/src/copying/contiguous_split.cu:268:void cudf::<unnamed>::copy_partition<(int)256>(int, const unsigned char **, unsigned char **, cudf::<unnamed>::dst_buf_info *) [0x740]
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x22da7a]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame: [0x141cc]
=========                in /usr/local/cuda-11.5/lib64/libcudart.so.11.0
=========     Host Frame:cudaLaunchKernel_ptsz [0x4c348]
=========                in /usr/local/cuda-11.5/lib64/libcudart.so.11.0
=========     Host Frame:cudf::detail::contiguous_split(cudf::table_view const &, std::vector<int, std::allocator<int>> const &, rmm::cuda_stream_view, rmm::mr::device_memory_resource*) [0x10130ea]
=========                in /tmp/cudf117294534664750114.so
=========     Host Frame:cudf::contiguous_split(cudf::table_view const &, std::vector<int, std::allocator<int>> const &, rmm::mr::device_memory_resource*) [0x1013af6]
=========                in /tmp/cudf117294534664750114.so
=========     Host Frame:Java_ai_rapids_cudf_Table_contiguousSplit [0x169a8b]
=========                in /tmp/cudfjni2770144042182094202.so
=========     Host Frame: [0x49be5d847]
=========                in
=========
========= Invalid __global__ read of size 4 bytes
=========     at 0x13b0 in /home/jimb/dev/rapids/cudf/cpp/src/copying/contiguous_split.cu:197:_ZN50_INTERNAL_6bd54e56_19_contiguous_split_cu_26302e214cudf52_GLOBAL__N__6bd54e56_19_contiguous_split_cu_26302e2111copy_bufferILi256EEEvPhPKhimmmjiimPi
=========     by thread (0,0,0) in block (2798,0,0)
=========     Address 0x8388cc800 is out of bounds
=========     and is 1 bytes after the nearest allocation at 0x8388c8800 of size 16384 bytes
=========     Device Frame:/home/jimb/dev/rapids/cudf/cpp/src/copying/contiguous_split.cu:268:void cudf::<unnamed>::copy_partition<(int)256>(int, const unsigned char **, unsigned char **, cudf::<unnamed>::dst_buf_info *) [0x740]
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x22da7a]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame: [0x141cc]
=========                in /usr/local/cuda-11.5/lib64/libcudart.so.11.0
=========     Host Frame:cudaLaunchKernel_ptsz [0x4c348]
=========                in /usr/local/cuda-11.5/lib64/libcudart.so.11.0
=========     Host Frame:cudf::detail::contiguous_split(cudf::table_view const &, std::vector<int, std::allocator<int>> const &, rmm::cuda_stream_view, rmm::mr::device_memory_resource*) [0x10130ea]
=========                in /tmp/cudf117294534664750114.so
=========     Host Frame:cudf::contiguous_split(cudf::table_view const &, std::vector<int, std::allocator<int>> const &, rmm::mr::device_memory_resource*) [0x1013af6]
=========                in /tmp/cudf117294534664750114.so
=========     Host Frame:Java_ai_rapids_cudf_Table_contiguousSplit [0x169a8b]
=========                in /tmp/cudfjni2770144042182094202.so
=========     Host Frame: [0x49be5d847]
=========                in
=========
========= Invalid __global__ read of size 4 bytes
=========     at 0x13b0 in /home/jimb/dev/rapids/cudf/cpp/src/copying/contiguous_split.cu:197:_ZN50_INTERNAL_6bd54e56_19_contiguous_split_cu_26302e214cudf52_GLOBAL__N__6bd54e56_19_contiguous_split_cu_26302e2111copy_bufferILi256EEEvPhPKhimmmjiimPi
=========     by thread (0,0,0) in block (2794,0,0)
=========     Address 0x824f96600 is out of bounds
=========     and is 1 bytes after the nearest allocation at 0x824f92600 of size 16384 bytes
=========     Device Frame:/home/jimb/dev/rapids/cudf/cpp/src/copying/contiguous_split.cu:268:void cudf::<unnamed>::copy_partition<(int)256>(int, const unsigned char **, unsigned char **, cudf::<unnamed>::dst_buf_info *) [0x740]
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x22da7a]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame: [0x141cc]
=========                in /usr/local/cuda-11.5/lib64/libcudart.so.11.0
=========     Host Frame:cudaLaunchKernel_ptsz [0x4c348]
=========                in /usr/local/cuda-11.5/lib64/libcudart.so.11.0
=========     Host Frame:cudf::detail::contiguous_split(cudf::table_view const &, std::vector<int, std::allocator<int>> const &, rmm::cuda_stream_view, rmm::mr::device_memory_resource*) [0x10130ea]
=========                in /tmp/cudf117294534664750114.so
=========     Host Frame:cudf::contiguous_split(cudf::table_view const &, std::vector<int, std::allocator<int>> const &, rmm::mr::device_memory_resource*) [0x1013af6]
=========                in /tmp/cudf117294534664750114.so
=========     Host Frame:Java_ai_rapids_cudf_Table_contiguousSplit [0x169a8b]
=========                in /tmp/cudfjni2770144042182094202.so
=========     Host Frame: [0x49be5d847]
=========                in
=========
========= Program hit cudaErrorLaunchFailure (error 719) due to "unspecified launch failure" on CUDA API call to cudaMemcpyAsync_ptsz.
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame: [0x3495c3]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame:cudaMemcpyAsync_ptsz [0x51e44]
=========                in /usr/local/cuda-11.5/lib64/libcudart.so.11.0
=========     Host Frame:cudf::detail::contiguous_split(cudf::table_view const &, std::vector<int, std::allocator<int>> const &, rmm::cuda_stream_view, rmm::mr::device_memory_resource*) [0x1013123]
=========                in /tmp/cudf117294534664750114.so
=========     Host Frame:cudf::contiguous_split(cudf::table_view const &, std::vector<int, std::allocator<int>> const &, rmm::mr::device_memory_resource*) [0x1013af6]
=========                in /tmp/cudf117294534664750114.so
=========     Host Frame:Java_ai_rapids_cudf_Table_contiguousSplit [0x169a8b]
=========                in /tmp/cudfjni2770144042182094202.so
=========     Host Frame: [0xffffffffe85dfd16]
=========                in
=========


```

**Comment by jbrennan333** [comment]
I added some additional debug logging.  Two runs failed at the same place:

```
21/11/24 15:35:30 INFO Table: CONTIG-SPLIT: rows: 131056 columns: 11 indices: [623, 1222, 1911, 2573, 3263, 3949, 4616, 5189, 5814, 
6470, 7141, 7736, 8412, 9057, 9699, 10356, 11011, 11710, 12412, 13042, 13726, 14359, 14948, 15529, 16272, 16928, 17571, 18258, 1885
6, 19541, 20231, 20876, 21578, 22223, 22871, 23537, 24163, 24850, 25502, 26173, 26820, 27449, 28088, 28719, 29366, 30003, 30632, 31
307, 31922, 32572, 33277, 33942, 34608, 35292, 35920, 36643, 37304, 38006, 38632, 39311, 39977, 40587, 41253, 41916, 42534, 43223, 
43855, 44542, 45221, 45886, 46587, 47226, 47897, 48549, 49178, 49834, 50472, 51156, 51857, 52511, 53202, 53851, 54486, 55154, 55842
, 56493, 57097, 57748, 58474, 59090, 59783, 60435, 61116, 61676, 62359, 63071, 63732, 64348, 65013, 65663, 66319, 66997, 67651, 683
36, 68996, 69675, 70326, 71007, 71630, 72288, 72965, 73644, 74257, 74905, 75544, 76210, 76917, 77543, 78188, 78850, 79514, 80172, 8
0847, 81495, 82154, 82797, 83450, 84069, 84780, 85456, 86106, 86793, 87404, 88051, 88667, 89328, 89999, 90626, 91323, 91997, 92654,
 93308, 93960, 94631, 95254, 95943, 96646, 97273, 97945, 98579, 99220, 99804, 100445, 101084, 101751, 102443, 103105, 103733, 10439
9, 105013, 105639, 106298, 106937, 107597, 108262, 108973, 109642, 110279, 110962, 111542, 112225, 112908, 113590, 114240, 114872, 
115499, 116087, 116706, 117352, 118034, 118732, 119368, 120014, 120642, 121314, 121998, 122639, 123246, 123920, 124557, 125167, 125
780, 126483, 127093, 127756, 128370, 129028, 129642, 130344]
========= Invalid __global__ read of size 4 bytes

```

**Comment by jbrennan333** [comment]
I dumped a stack trace just before the call to contiguousSplit that fails:
```
21/11/29 11:26:17 INFO Executor: Running task 40.0 in stage 41.0 (TID 241)
21/11/29 11:26:17 INFO TaskSetManager: Finished task 16.0 in stage 41.0 (TID 217) in 25162 ms on 192.168.1.128 (executor driver) (17/200)
21/11/29 11:26:17 INFO RapidsShuffleInternalManager: Registering shuffle 5
21/11/29 11:26:17 INFO RapidsShuffleInternalManager: Asking map output tracker for dependency GPU Shuffle Dependency, map output sizes for: 0, parts=40-41
21/11/29 11:26:17 INFO RapidsCachingReader: Will read 26 cached blocks, 0 remote blocks from the RapidsShuffleTransport. 
21/11/29 11:26:17 INFO RapidsShuffleInternalManager: Asking map output tracker for dependency GPU Shuffle Dependency, map output sizes for: 1, parts=40-41
21/11/29 11:26:17 INFO RapidsCachingReader: Will read 26 cached blocks, 0 remote blocks from the RapidsShuffleTransport. 
21/11/29 11:26:19 INFO Table: Stack Trace: 
21/11/29 11:26:19 INFO Table: 	at java.lang.Thread.getStackTrace(Thread.java:1559)
21/11/29 11:26:19 INFO Table: 	at ai.rapids.cudf.Table.contiguousSplit(Table.java:1846)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.GpuPartitioning.$anonfun$sliceInternalOnGpu$3(GpuPartitioning.scala:61)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.GpuPartitioning.$anonfun$sliceInternalOnGpu$1(GpuPartitioning.scala:61)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.Arm.closeOnExcept(Arm.scala:120)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.Arm.closeOnExcept$(Arm.scala:118)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.GpuHashPartitioning.closeOnExcept(GpuHashPartitioning.scala:28)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.GpuPartitioning.sliceInternalOnGpu(GpuPartitioning.scala:55)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.GpuPartitioning.sliceInternalOnGpu$(GpuPartitioning.scala:50)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.GpuHashPartitioning.sliceInternalOnGpu(GpuHashPartitioning.scala:28)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.GpuPartitioning.sliceInternalGpuOrCpu(GpuPartitioning.scala:119)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.GpuPartitioning.sliceInternalGpuOrCpu$(GpuPartitioning.scala:106)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.GpuHashPartitioning.sliceInternalGpuOrCpu(GpuHashPartitioning.scala:28)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.GpuHashPartitioning.$anonfun$columnarEval$3(GpuHashPartitioning.scala:86)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:55)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:53)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.GpuHashPartitioning.$anonfun$columnarEval$1(GpuHashPartitioning.scala:85)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.GpuHashPartitioning.withResource(GpuHashPartitioning.scala:28)
21/11/29 11:26:19 INFO Table: 	at com.nvidia.spark.rapids.GpuHashPartitioning.columnarEval(GpuHashPartitioning.scala:78)
21/11/29 11:26:19 INFO Table: 	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$.$anonfun$prepareBatchShuffleDependency$3(GpuShuffleExchangeExecBase.scala:272)
21/11/29 11:26:19 INFO Table: 	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.partNextBatch(GpuShuffleExchangeExecBase.scala:293)
21/11/29 11:26:19 INFO Table: 	at org.apache.spark.sql.rapids.execution.GpuShuffleExchangeExecBase$$anon$1.hasNext(GpuShuffleExchangeExecBase.scala:304)
21/11/29 11:26:19 INFO Table: 	at scala.collection.Iterator.foreach(Iterator.scala:941)
21/11/29 11:26:19 INFO Table: 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
21/11/29 11:26:19 INFO Table: 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
21/11/29 11:26:19 INFO Table: 	at org.apache.spark.sql.rapids.RapidsCachingWriter.write(RapidsShuffleInternalManagerBase.scala:98)
21/11/29 11:26:19 INFO Table: 	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
21/11/29 11:26:19 INFO Table: 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
21/11/29 11:26:19 INFO Table: 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
21/11/29 11:26:19 INFO Table: 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
21/11/29 11:26:19 INFO Table: 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
21/11/29 11:26:19 INFO Table: 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
21/11/29 11:26:19 INFO Table: 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
21/11/29 11:26:19 INFO Table: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21/11/29 11:26:19 INFO Table: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21/11/29 11:26:19 INFO Table: 	at java.lang.Thread.run(Thread.java:748)
21/11/29 11:26:19 INFO Table: CONTIG-SPLIT: rows: 131056 columns: 11indices: [623, 1222, 1911, 2573, 3263, 3949, 4616, 5189, 5814, 6470, 7141, 7736, 8412, 9057, 9699, 10356, 11011, 11710, 12412, 13042, 13726, 14359, 14948, 15529, 16272, 16928, 17571, 18258, 18856, 19541, 20231, 20876, 21578, 22223, 22871, 23537, 24163, 24850, 25502, 26173, 26820, 27449, 28088, 28719, 29366, 30003, 30632, 31307, 31922, 32572, 33277, 33942, 34608, 35292, 35920, 36643, 37304, 38006, 38632, 39311, 39977, 40587, 41253, 41916, 42534, 43223, 43855, 44542, 45221, 45886, 46587, 47226, 47897, 48549, 49178, 49834, 50472, 51156, 51857, 52511, 53202, 53851, 54486, 55154, 55842, 56493, 57097, 57748, 58474, 59090, 59783, 60435, 61116, 61676, 62359, 63071, 63732, 64348, 65013, 65663, 66319, 66997, 67651, 68336, 68996, 69675, 70326, 71007, 71630, 72288, 72965, 73644, 74257, 74905, 75544, 76210, 76917, 77543, 78188, 78850, 79514, 80172, 80847, 81495, 82154, 82797, 83450, 84069, 84780, 85456, 86106, 86793, 87404, 88051, 88667, 89328, 89999, 90626, 91323, 91997, 92654, 93308, 93960, 94631, 95254, 95943, 96646, 97273, 97945, 98579, 99220, 99804, 100445, 101084, 101751, 102443, 103105, 103733, 104399, 105013, 105639, 106298, 106937, 107597, 108262, 108973, 109642, 110279, 110962, 111542, 112225, 112908, 113590, 114240, 114872, 115499, 116087, 116706, 117352, 118034, 118732, 119368, 120014, 120642, 121314, 121998, 122639, 123246, 123920, 124557, 125167, 125780, 126483, 127093, 127756, 128370, 129028, 129642, 130344]
========= Invalid __global__ read of size 4 bytes
=========     at 0x13d0 in void cudf::<unnamed>::copy_partition<(int)256>(int, const unsigned char **, unsigned char **, cudf::<unnamed>::dst_buf_info *)
=========     by thread (0,0,0) in block (2794,0,0)
=========     Address 0x9a44ce800 is out of bounds
=========     and is 1 bytes after the nearest allocation at 0x9a44ca800 of size 16384 bytes

```

**Comment by harrism** [comment]
Clearly this is in contiguous_split. There are even line numbers above.  @nvdbaranec
