### ISSUE TITLE
[BUG] Error "Operation <function make_upper> not supported for dtype object" for text columns

### ISSUE THREAD

**Issue by chopeen** [rapidsai/cudf#9646]
`applymap` fails for text columns (`dtype('O')`). Why? Is this not supported?

### Code snippet

```
import cudf

def add_ten(num):
    return num + 10

def make_upper(text: str) -> str:
    return text.upper()

df = cudf.DataFrame({
    'numbers': [1, 2],
    'text': ['Aaaa', 'Bbbb']
})

df['numbers'] = df['numbers'].applymap(add_ten)
print(df)
df['text'] = df['text'].applymap(make_upper)
```

### Output

```
   numbers  text
0       11  Aaaa
1       12  Bbbb
>>> df['text'] = df['text'].applymap(make_upper)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[snip]/miniconda3/envs/parallel_cudf_env/lib/python3.8/site-packages/cudf/core/series.py", line 3792, in applymap
    return self._from_data({self.name: self._unaryop(udf)}, self._index)
  File "[snip]/miniconda3/envs/parallel_cudf_env/lib/python3.8/site-packages/cudf/core/frame.py", line 3309, in _unaryop
    return self.__class__._from_data(
  File "[snip]/miniconda3/envs/parallel_cudf_env/lib/python3.8/site-packages/cudf/core/series.py", line 285, in _from_data
    out: Series = super()._from_data(data, index, name)
  File "[snip]/miniconda3/envs/parallel_cudf_env/lib/python3.8/site-packages/cudf/core/frame.py", line 4784, in _from_data
    out = super()._from_data(data, index)
  File "[snip]/miniconda3/envs/parallel_cudf_env/lib/python3.8/site-packages/cudf/core/frame.py", line 74, in _from_data
    libcudf.table.Table.__init__(obj, data, index)
  File "cudf/_lib/table.pyx", line 37, in cudf._lib.table.Table.__init__
  File "[snip]/miniconda3/envs/parallel_cudf_env/lib/python3.8/site-packages/cudf/core/column_accessor.py", line 121, in __init__
    data = dict(data)
  File "[snip]/miniconda3/envs/parallel_cudf_env/lib/python3.8/site-packages/cudf/core/frame.py", line 3308, in <genexpr>
    data_columns = (col.unary_operator(op) for col in self._columns)
  File "[snip]/miniconda3/envs/parallel_cudf_env/lib/python3.8/site-packages/cudf/core/column/column.py", line 1158, in unary_operator
    raise TypeError(
TypeError: Operation <function make_upper at 0x7f2aad7fb550> not supported for dtype object.
```

### Expected behavior

Either text columns should be processed **or** the error should clearly state that text columns are not supported.

### Environment overview
 - Environment location: laptop
 - Method of cuDF install: conda (`rapids-blazing=21.10`)

**Comment by davidwendt** [comment]
`applymap` is not supported for strings columns: #3802

**Comment by beckernick** [comment]
Closing as a duplicate of the linked issue.

Please note that this specific example can be executed with `Series.str.upper()`, as `upper` is a supported string method.
