### ISSUE TITLE
[FEA] Improved error message when calling `query()` on expresions involving columns of string values

### ISSUE THREAD

**Issue by rlratzel** [rapidsai/cudf#9894]
`DataFrame.query()` calls using expressions that involve columns of string values are not supported in cuDF. Adding support for this would be ideal, but given that strings are not fully supported for a variety of reasons, a better error message would be the next best improvement.  
As an example, in `pandas` the following works as expected:
```
>>> DF4.query("type_name=='merchants' and merchant_size>80 and merchant_location==44145") # pandas version
   vertex  type_name  merchant_location  merchant_size  distro_size  user_location  vertical
2      21  merchants            44145.0           83.0          NaN            NaN       NaN
```
However, the same code using `cudf` produces the following:
```
>>> DF4.query("type_name=='merchants' and merchant_size>80 and merchant_location==44145") # cudf version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/dataframe.py", line 3915, in query
    boolmask = queryutils.query_execute(self, expr, callenv)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/utils/queryutils.py", line 220, in query_execute
    colarrays = [
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/utils/queryutils.py", line 221, in <listcomp>
    cudf.core.dataframe.extract_col(df, col).data_array_view
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/string.py", line 5179, in data_array_view
    raise ValueError("Cannot get an array view of a StringColumn")
ValueError: Cannot get an array view of a StringColumn
```

Perhaps raising `TypeError(f"query expression including string column {col} is not supported")` or something similar might be better.

NOTE: for those interested, the proposed workaround for the above example is:
```
DF4[DF4["type_name"]=='merchants'].query(merchant_size>80 and merchant_location==44145")
```

cc @vyasr @brandon-b-miller

**Comment by vyasr** [comment]
For context, supporting the query itself requires addressing #9639.
